### ISSUE TITLE
Missing translation strings from crowdin. Many kivy strings are not picked up by gettext.

### ISSUE THREAD

**Issue by Kimbatt** [spesmilo/electrum#5012] opened 2019-01-18 19:55 UTC
I noticed that a few strings are missing from crowdin (so they cannot be translated) :

https://github.com/spesmilo/electrum/blob/master/electrum/gui/kivy/uix/dialogs/settings.py :
Electrum Settings (line 20)
PIN code (line 40)
Change your PIN code. (line 41)
Base unit for Bitcoin amounts. (line 47)
Display amounts in fiat currency. (line 53)
Labels Sync (line 58)
Save and synchronize your labels. (line 59)
Replace-by-fee (line 64)
Create replaceable transactions. (line 65)

------- this should be "pay higher fees" at the end, since there is already a string for that (and also that is grammatically correct):
and you will have the possibility, while they are unconfirmed, to replace them with transactions that pays higher fees. (line 68)

Spend unconfirmed (line 74)
Use unconfirmed coins in transactions. (line 75)
Spend unconfirmed coins (line 76)
Use unconfirmed (line 77)
Send your change to separate addresses. (line 82)
Send excess coins to change addresses (line 83)

https://github.com/spesmilo/electrum/blob/master/electrum/gui/kivy/uix/ui_screens/about.kv :
Developers (line 35)

[gui/qt/main_window.py](https://github.com/spesmilo/electrum/blob/master/electrum/gui/qt/main_window.py)
Electrum's focus is speed, with low resource usage and simplifying Bitcoin. (line 600)
Startup times are instant because it operates in conjunction with high-performance that handle the most complicated parts of the Bitcoin system. (line 603-604)

---

Edit: I also found some hardcoded english strings in [plugins/trustedcoin/qt.py](https://github.com/spesmilo/electrum/blob/master/electrum/plugins/trustedcoin/qt.py):
Pay every %d transactions: (line 185)
Please scan the following QR code in Google Authenticator. You may as well use the following key: %s (line 270)
This wallet is already registered with TrustedCoin. To finalize wallet creation, please enter your Google Authenticator Code. (line 278-279)

[plugins/trustedcoin/trustedcoin.py](https://github.com/spesmilo/electrum/blob/master/electrum/plugins/trustedcoin/trustedcoin.py)
Disclaimer (line 497)

[base_wizard.py](https://github.com/spesmilo/electrum/blob/master/electrum/base_wizard.py)
 (%d of %d) (line 163)

[gui/qt/qrtextedit.py](https://github.com/spesmilo/electrum/blob/master/electrum/gui/qt/qrtextedit.py)
select file (line 47)

**Comment by bauerj** [comment] 2019-01-19 17:10
Gettext doesn't parse the Kivy code inside Python strings.

This could probably be solved by changing the calls to `Builder.load_string` to `Builder.load_file` and moving the strings to .kv files accordingly.

**Comment by andronoob** [comment] 2019-01-22 15:08
@bauerj #2032 is still unfixed. If kivy cannot load fonts provided by local Android system, could we pack some another fonts (like wenquanyi/sourcehan etc) instead?

**Comment by dalijolijo** [comment] 2019-06-20 16:44
Any update about this translation strings for Kivy?

**Comment by dalijolijo** [comment] 2019-06-21 21:56
> Gettext doesn't parse the Kivy code inside Python strings.
> 
> This could probably be solved by changing the calls to `Builder.load_string` to `Builder.load_file` and moving the strings to .kv files accordingly.

I try to follow your idea to fix the Missing translation strings in electrum/gui/kivy/uix/dialogs/settings.py
https://github.com/dalijolijo/electrum-btx/commit/808c8c08ed0d2bba7dda75d0b0e50f302d66153a

After execution of script ./contrib/make_locate only the template file electrum/locale/messages.pot list all additional entries of settings.kv, but all language files like electrum/locale/da_DK/electrum.po are not updated with additional entries.

What is missing?

**Comment by myxmaster** [comment] 2022-12-29 14:56
This seems to be fixed and can be closed (?)

**Comment by SomberNight** [comment] 2022-12-30 01:04
No, I don't think it is fixed.
E.g. this line:
https://github.com/spesmilo/electrum/blob/90d64a004b15e4809138c4968e36d2ebb6b21ba6/electrum/gui/kivy/uix/dialogs/settings.py#L76
is not picked up by gettext, see:
```
$ rm -rf electrum/locale/
$ ./contrib/push_locale 
Found 329 files to translate
Generating template...
Missing crowdin_api_key. Cannot push.
$ ls electrum/locale
messages.pot
$ cat electrum/locale/messages.pot | grep "Use unconfirmed coins in transactions"
$
```
However, we are planning on deprecating the kivy GUI, so it is less important, I will remove the "pull-request wanted" label.

**Comment by myxmaster** [comment] 2023-01-03 14:02
You are right, there are still some strings that are not translated. Unfortunately I don't fully understand how this works, but for example:
Receive Tab, the items in the "Expire after" ComboBox are not translated. The strings seem to be referred correctly in the locale file (e.g. locale/de_DE/electrum.po lines 209-219, 225-227, 3758-3760 pointing to correct source: electrum/invoices.py lines 57-61), so I don't understand why it doesn't work.

Settings -> Transactions
"Use Replace-By-Fee" and "Batch RBF transactions" are not translated. The latter seems to be redundant for string 'Batch unconfirmed transactions' in electrum/gui/qt/settings_dialog.py line 121, which is existing in the locale file (line 700-702), but I'm not sure, it's confusing.

**Comment by accumulator** [comment] 2023-09-22 09:21
Kivy client has been removed, closing.

**Closed by accumulator** 2023-09-22 09:21 UTC
Labels: bug 🐞, toolchain 🛠, localization 🌍, gui-kivy
