### ISSUE TITLE
Electrum close after complete new transaction

### ISSUE THREAD

**Issue by Jazb** [spesmilo/electrum#1144] opened 2015-04-13 15:09 UTC
After completing each transaction program closes suddenly , I'm using version 2.0.4 on Archlinux installed from AU

**Comment by ecdsa** [comment] 2015-04-13 16:19
are you using a hardware wallet?

**Comment by ecdsa** [comment] 2015-04-13 16:22
can you run it from a terminal and see if there is a traceback?

**Comment by ecdsa** [comment] 2015-04-19 08:49
closing: cannot reproduce, no info provided

**Closed by ecdsa** 2015-04-19 08:49 UTC
