### ISSUE TITLE
unverified transactions in electrum 2.3.2

### ISSUE THREAD

**Issue by Shimoli** [spesmilo/electrum#1390] opened 2015-08-10 17:35 UTC
I make two transactions last 12 hours but none of the are verified, I deposited and send the bitcoins but up to now no any help. I have googled and followed the tricks seemed to work but nothing happened still the same problems.

**Comment by kyuupichan** [comment] 2015-08-25 05:46
This may be a duplicate of #1379 which is now fixed I believe

**Comment by ecdsa** [comment] 2015-08-27 14:49
closing this as well, no?

**Closed by ecdsa** 2015-08-27 14:49 UTC
