### ISSUE TITLE
hangup on key sweep

### ISSUE THREAD

**Issue by Ernie-FR** [spesmilo/electrum#3498] opened 2017-12-11 12:11 UTC
Today I downloaded Electrum 3.0.2 on Win7 64bit Dell laptop. Started it, choose a wallet name "EvD_wallet" and added my old bitcoin address from my previous Multibit wallet. No problem view-only wallet is there, transaction history visible in no time. Great. Then I wanted fully control it again by adding the old private key of multibit that I saved in a file. Opened 'wallet-privatekeys-sweep' and clicked on file icon to point to privatekey file, which is then shown in the box. 
Here is where things go wrong. If I click on address button, with or without my current bitcoinaddress in the field next to it, the program hangs up on me. I need to right-hand-click on it to force it to stop.
The first time after the crash I expected a shortcut icon would have been added to the desktop, or the startmenu, or an installation directory created in the c:\program files directrory. Nothing of all that. There is no installation, only a folder under userdata added with the wallet data. This is very confusing cause all other programs do work like this. I don't care that this one does not, only it should be documented or stated during first run or on the download page. Could help avoid a lot of confusion. 
Well I know now to displace (and not throw away) after download the electrum file to somewhere normal executables are stored and make a shortcut myself...
Neverthe less the question remains; how do I make my old Multibit address fully operational with Electrum? Hope anybody can help, cheers, Ernie.

**Comment by SomberNight** [comment] 2017-12-11 13:31
> The first time after the crash I expected a shortcut icon would have been added to the desktop, or the startmenu, or an installation directory created in the c:\program files directrory. Nothing of all that. There is no installation, only a folder under userdata added with the wallet data. This is very confusing cause all other programs do work like this. I don't care that this one does not, only it should be documented or stated during first run or on the download page. Could help avoid a lot of confusion.

Have you used the "Windows Installer" (`setup`) binary? That should give you a shortcut. The `standalone` and the `portable` binaries won't.

> Here is where things go wrong. If I click on address button, with or without my current bitcoinaddress in the field next to it, the program hangs up on me. I need to right-hand-click on it to force it to stop.

Sounds similar to https://github.com/spesmilo/electrum/issues/3486
Does the app fill in that field by itself when the dialog opens? If it does, have you changed the address there before clicking the `Address` button?

> Neverthe less the question remains; how do I make my old Multibit address fully operational with Electrum?

I suggest one of two things:
- If you want to have seeded wallet, create a new seed (in Electrum). In the wizard, just choose `Standard wallet`>`Create a new seed`, and then sweep the private keys into that, using the option you described -- it should work.
- Alternatively, you can just import the private keys you have, and leave the coins there. In the wizard, choose `Import Bitcoin addresses or private keys`.

**Comment by SomberNight** [comment] 2017-12-19 00:59
Closing; only actual bug is probably dupe of https://github.com/spesmilo/electrum/issues/3486

**Closed by SomberNight** 2017-12-19 00:59 UTC
