### ISSUE TITLE
My balance does not correspond to my real BTC in electrum 4.0.4

### ISSUE THREAD

**Issue by giuannibabbera** [spesmilo/electrum#6713] opened 2020-11-05 17:06 UTC
i had to pay and my wallet said i had 0.00223 btc in the left-down corner, then i got to the "send" fragment and tried to put my max BTC and then i saw i had 0.00195 btc, what does it means?

p.s. 
in the balance there is nothing else than my balance

**Comment by ecdsa** [comment] 2020-11-05 19:49
this is because of the fees.
note: this issue is caused by the new workflow, where the fee is displayed later

**Comment by atenea19** [comment] 2020-11-17 12:49
Buenos dias, hoy he entrado en mi cuenta de Electrum, me a pedido que la pasara a 4.0 y al hacerlo me ha desaparecido todo el saldo que habia a una transaccion que yo no he hecho, aun se esta ejecutando

**Comment by giuannibabbera** [comment] 2020-11-20 03:33
oh i see, thanks

Il giorno mar 17 nov 2020 alle ore 13:49 atenea19 <notifications@github.com>
ha scritto:

**Comment by ecdsa** [comment] 2020-11-25 18:11
it should be fixed by 9fced6d

**Closed by ecdsa** 2020-11-25 18:11 UTC
Labels: topic-fees, user-interface
