### ISSUE TITLE
"Cannot load wallet file" When starting electrum a second time

### ISSUE THREAD

**Issue by tvl83** [spesmilo/electrum#1085] opened 2015-03-14 21:44 UTC
I backed up my `AppData\roaming\Electrum` folder then opened **Electrum 2.0.2**  and used my seed to load up my addresses. That part works fine. 

When I close the wallet then launch it again it gives me an error `Cannot load wallet file` and closes.

**Comment by ecdsa** [comment] 2015-03-14 22:41
was it a large file?
the wallet file might be empty as in #960

**Comment by ecdsa** [comment] 2015-03-14 22:42
also, is it reproducible?

**Comment by tvl83** [comment] 2015-03-14 23:03
It has happened 3-4 times. I've done it by leaving the electrum folder there from the 1.9.8 client and then moving that folder so 2.0.2 will create a new folder and everything. 

It happens every time on the second start of the program. This is the stand alone version on windows 8.1 pro.

**Comment by ecdsa** [comment] 2015-03-15 05:32
are you sure you are opening with 2.0.2 the second time, not with the old version?

**Comment by tvl83** [comment] 2015-03-15 05:35
Yes, I am positive but, I can try it again if you would like me to.

**Comment by ecdsa** [comment] 2015-03-15 06:04
what is the size of the wallet file after the error?

**Comment by tvl83** [comment] 2015-03-15 06:08
I put in the comment above that it is about 9 megs, in comparison, the `Electrum 1.9.8` wallet file that I am using right now is 24mb. 

I have tried it 3-4 times before submitting the original issue.

**Comment by ecdsa** [comment] 2015-03-15 06:11
do you mind sending me the non-working file?
(remove all coins that are in the wallet before, using 1.9.8)

**Comment by tvl83** [comment] 2015-03-15 07:04
I can do that, but I have some auto deposits going to some of my addresses. You wouldn't be able to withdraw them anyway since it is encrypted, right ? (not to say you would)

to bypass this whole issue (although i know you probably want to figure it out for others) could I just export my keys, create a new wallet/seed and import the addresses i use regularly for my mining stuff?

**Comment by ecdsa** [comment] 2015-03-15 07:17
Exporting some keys might work around the issue, but that's not what I want.
I am doing this to fix the issue, not just your individual case..

if you have some technical knowledge, can you at least check that the wallet file is json, and that it can be parsed?

**Comment by tvl83** [comment] 2015-03-15 07:28
Yes, I know what JSON is and took a look at the file, it is invalid, the `transactions` object is cut off, it doesn't end properly it just stops without the end quote or } 

There are only 190 lines to the object but as pointed out previously, in comparison, my 1.9.8 wallet is 24MB.

I cannot tell how many transactions are in the 1.9.8 object because that wallet file is not formatted with line breaks and such, it's a single line. 

I was having network issues the past few days, but I was able to download everything fine (over and over again when reverting back) with the 1.9.8 wallet. 

I will try again with 2.0.2 now that I have a more stable connection.

**Comment by ecdsa** [comment] 2015-03-15 07:37
2.0.3 will be released probably tomorrow. it might fix it, because it seems to be related to #960

**Comment by tvl83** [comment] 2015-03-15 08:22
I'll check that one out and see. I just backed up my 1.9.8 folder then opened 2.0.2. I am watching the size of the `default_wallet` file and it's at 24.2MB. That is about the size of my 1.9.8 wallet file.

I will wait until the synchronize message is gone and the addresses appear and then open electrum again. I have a feeling it's modifying the file when it's reading it and deleting a bunch of data or something.

I let it sync for a good 10 minutes. It didn't grow in size from 24,822KB for several minutes so I copied that file and then quit electrum. The default wallet file promptly dropped down to 3,500KB.

I renamed the copied file back to default_wallet and it opens without error but I am waiting almost 15 minutes for it to open up and let me see anything.

**Comment by ecdsa** [comment] 2015-03-16 11:24
new binaries are ready, please try with 2.0.3

**Comment by ecdsa** [comment] 2015-03-17 06:46
any news?

**Comment by tvl83** [comment] 2015-03-17 07:05
yes, It seems to be working just fine now. I backed up the electrum folder and had it create it from scratch and it no longer corrupts the wallet file. I reported a second issue about the label sync. 

Thanks!

**Closed** 2015-03-17 07:07 UTC
