### ISSUE TITLE
wallet file encryption is slow on osx

### ISSUE THREAD

**Issue by jtoomim** [spesmilo/electrum#2470] opened 2017-05-31 00:42 UTC
I have a wallet file comprised of a few hundred imported private keys, some of which have transactions going back to 2015. Many wallet operations take a few hours to complete. These operations appear to include:

1. Generating an unsigned transaction (e.g. via Preview)
2. Signing a generated transaction
3. Adding or editing a label for an address

Because sending a transaction requires both 1 and 2, it usually takes about 8-12 hours total to send a transaction.

I can understand a python program being slow with this many private keys, but taking multiple hours suggests to me that there is an O(n^2) issue somewhere. In particular, adding a label shouldn't be slow. (I haven't checked to see how long that actually takes. I just tried it once, noticed that it caused the UI to hang, and force-quitted it.)

The wallet has very few UTXOs left, but it has a total of around 1000 (or maybe more) spent TXOs. I have not determined whether this performance issue is related to the number of addresses, the number of TXOs, or something else.

Test results are from OS X 10.11.3 with Electrum 2.8.1 on a 2013 Macbook Pro Retina 13 (2.4 GHz Core I5, 8 GB).

**Comment by dabura667** [comment] 2017-05-31 03:43
The wallet file is accessed when creating unsigned transactions and the wallet file always contains a list of all transactions in the history... so it could very well just be that every time the code tries to access the wallet object python is loading a huge list of 1000s of transactions every time.

That seems like it would cause O(n^2) calculations.

**Comment by ecdsa** [comment] 2017-07-04 10:02
Signing a bitcoin transaction is by nature quadratic, because each input has to sign an unsigned transaction of size O(n).

However, that does not explain such a long time; I regularly sign transactions with 100 inputs and they require only a few minutes. there must be something else.

**Comment by ecdsa** [comment] 2017-07-04 10:17
@jtoomim your labels issue could be caused by an old bug, that was duplicating labels in the wallet file. That bug was caused by the labels sync plugin. It has been fixed a long time ago, but extra wallets were not removed from the affected wallets. I suggest you export your labels and check if the file has a reasonable size

**Comment by jtoomim** [comment] 2017-07-04 11:03
ecdsa, this is not related to the size of the transaction being signed. I have signed 1-input 2-output transactions with this wallet and had that take multiple hours.

dabura667's explanation makes more sense. This issue is not just related to signing transactions; it also occurs when just changing the labels for addresses in the Addresses tab. The symptoms appear to be the same when signing transactions as when changing the labels, suggesting that the bottleneck is in code common to both actions. Parsing the wallet file would make sense as such a process.

It also takes a substantial amount of time (30 minutes?) to simply load the wallet file.

**Comment by jtoomim** [comment] 2017-07-04 14:00
@ecdsa Exported labels json file is 103 bytes, with only one entry.

I'm going to see if I can hack the Electrum.app package to use cProfile. That might give us a better idea of what's going on than talking.

**Comment by ecdsa** [comment] 2017-07-04 15:24
try to sign a message with one of your bitcoin addresses, and see if it takes as much time

**Comment by ecdsa** [comment] 2017-07-04 15:25
btw, how many addresses do you have in your wallet? how many transactions?

**Comment by ecdsa** [comment] 2017-07-04 15:32
does it improve if you disable wallet file encryption? (leaving the password protection)
what is the wallet file size?
file encryption could explain why it affects both labels and wallet loading/closing

**Comment by jtoomim** [comment] 2017-07-04 15:36
I have a few different wallets that have this problem. One of them has about 600 private keys, and another has about 100 private keys. The second wallet is a subset of the first wallet, comprised of the keys that we've more actively used.

The number of transactions is a few thousand. I haven't counted the exact number. One address in particular has over 1500 transactions, many of which are mining reward payout transactions (5 to 20 kB each).

One of the wallet files with this problem is 4.3 MB, and another is 32 MB.

I'm still waiting for the wallet to close, so I won't be able to do any more tests for several hours.

**Comment by ecdsa** [comment] 2017-07-04 15:39
also, are you using the OSX binary, or running rom source?
if you are running from sources, you should install pycryptodome: 
https://pypi.python.org/pypi/pycryptodome

**Comment by jtoomim** [comment] 2017-07-04 15:40
Binary app. If there's a guide for installing the dependencies needed to run from source, I can do that and add some profiling. (p2app stripped the profile and cProfile modules from the distribution, and I haven't yet been able to add them back in.)

**Comment by ecdsa** [comment] 2017-07-04 16:25
what's the size of the wallet file?

**Comment by jtoomim** [comment] 2017-07-04 17:24
One of the wallet files with this problem is 4.3 MB, and another is 32 MB.

**Comment by ecdsa** [comment] 2017-07-04 17:28
I still believe the wallet encryption is causing this.
try to disable it, and see if it improves.

**Comment by jtoomim** [comment] 2017-07-07 06:50
Yes, disabling encryption seems to have resolved the issue. Thanks.

**Comment by ecdsa** [comment] 2017-07-07 08:37
ok, can you try "import Cryptodome" in the wallet console?
maybe it is not available in your binary

**Comment by jtoomim** [comment] 2017-07-07 09:48
It is correctly available.

**Comment by ecdsa** [comment] 2017-07-07 09:54
thanks. I will try with my mac. 
can you tell me how much time does it take to open/close the 4.3MB and 32MB, respectively?
(with encryption enabled)

**Comment by jtoomim** [comment] 2017-07-07 14:32
The 32 M files are now 56 MB with encryption disabled. They take around 3.5 hours for most operations.

I don't use the smaller wallet very often and can't say for certain how long it takes to load or do things, but I think it's around 30 minutes.

**Comment by jtoomim** [comment] 2017-07-07 14:39
I have been able to reproduce this problem with a watching-only wallet as well.

**Comment by TheButterZone** [comment] 2017-12-22 03:31
Hangs on opening an encrypted 4.8 MB wallet composed entirely of imported keys with 83 TXs & only 6 unspent coins between them.

**Comment by SomberNight** [comment] 2018-01-31 01:41
Can you try on master? It should be somewhat faster now.

- make sure you have Cryptodome, as said earlier in the thread https://github.com/spesmilo/electrum/issues/3778
- you should have these commits https://github.com/spesmilo/electrum/pull/3782

**Comment by SomberNight** [comment] 2020-09-11 18:05
Many-many improvements have been made over the years, so this issue is now obsolete.

**Closed by SomberNight** 2020-09-11 18:05 UTC
Labels: awaiting-response, enhancement
