### ISSUE TITLE
History: no right click, 0 amount, 0 balance, empty transaction

### ISSUE THREAD

**Issue by alpengeist** [spesmilo/electrum#2587] opened 2017-07-09 22:47 UTC
Hi,

I'm using Windows10 & Electrum 2.8.3 (installer version)

I've just started using electrum. A friend has sent me 0.0000666BTC. The transaction shows up in the  History with the green check icon. However, there is no amount (0) and no balance (0), no matter how many decimal digits I configure. Even in mBTC there is nothing.

Also, I thought a right click on the trans should open a menu to give me infos about the trans. Not happening. I was able to get the trans key via Wallet/History/Export. There, all numbers are also 0.

In blockexplorer everything looks normal: 796dd575a1b363e5d36661da197bcfa72575fb1c64aa1757de3e8c46fe40b872

Something is not right here and I have no clue where to look.

Hermann

**Comment by ecdsa** [comment] 2017-07-10 05:30
screenshot please

**Comment by alpengeist** [comment] 2017-07-10 09:23
I also noticed that in the status bar, the "Synchronizing..." never goes away. Is that normal?

![electrum_screen](https://user-images.githubusercontent.com/84187/28011254-04491e16-6562-11e7-9e47-e0cae98b84fa.PNG)

**Comment by bauerj** [comment] 2017-07-10 10:31
I can confirm the issue:

![electrum-2 8 3_2017-07-10_12-27-59](https://user-images.githubusercontent.com/598790/28013973-3ad01dc8-656b-11e7-9056-8e39796dc2b2.png)

Interestingly, it doesn't occur when running the 2.8.3 tag (d062792) from source:

![python_2017-07-10_12-29-23](https://user-images.githubusercontent.com/598790/28014031-6bc4a7aa-656b-11e7-8b1c-99a60c17fdaf.png)

**Comment by bauerj** [comment] 2017-07-10 11:36
Nevermind, it only works in the second screenshot because I opened the wallet with current `HEAD` before.

**Comment by bauerj** [comment] 2017-07-10 11:40
This seems to be the same issue as #2356 and will be fixed with the next release.

**Comment by ecdsa** [comment] 2017-07-10 11:49
@bauerj did you create the wallet from his xpub or from his btc address?

**Comment by bauerj** [comment] 2017-07-10 11:50
From the BTC address.

**Comment by ecdsa** [comment] 2017-07-10 11:53
I cannot reproduce it with address 16szvqozG6MeQ9jKUtSEZG5obrSfr5yShm, neither from HEAD nor 2.8.3

**Comment by bauerj** [comment] 2017-07-10 11:55
Try 1LSxaUm9kspevxhQaXwX67pd7NAq1Hdi14 😉

**Comment by ecdsa** [comment] 2017-07-10 11:55
indeed, same as #2356

**Closed by ecdsa** 2017-07-10 11:55 UTC
