### ISSUE TITLE
DL-Link for OSX executable outdated

### ISSUE THREAD

**Issue by hfr-hfr** [spesmilo/electrum#2958] opened 2017-10-02 12:11 UTC
On https://electrum.org/#download the OSX executable points to https://download.electrum.org/2.9.2/electrum-2.9.2.dmg
Should point to https://download.electrum.org/2.9.3/electrum-2.9.3.dmg

**Comment by SomberNight** [comment] 2017-10-02 13:39
This is by design. There is a problem with 2.9.3 on Mac. See #2728.
Also, issue is duplicate of #2847.

**Closed** 2017-10-03 12:21 UTC
