### ISSUE TITLE
password error popup hidden out of focus

### ISSUE THREAD

**Issue by jlopp** [spesmilo/electrum#6557] opened 2020-09-05 20:29 UTC
Ran into an issue where I was having issues opening a password protected wallet and couldn't figure out why for a bit.

1. Open up a wallet that has one or more hardware devices linked to it but don't have the devices plugged in
2. Quickly go to File -> Recently Open and choose password protected wallet, thus creating second window like so

![Screenshot from 2020-09-05 11-18-05](https://user-images.githubusercontent.com/288011/92313010-7f68e300-ef94-11ea-955d-ada9477f852c.png)

3. Input wrong password into new wallet and click next
4. Nothing happens. Keep clicking next to no avail
5. Eventually click back on the other wallet window through the hardware devices popups and then notice an error popup come into focus on the password protected wallet
![Screenshot from 2020-09-05 11-18-17](https://user-images.githubusercontent.com/288011/92313047-d373c780-ef94-11ea-8320-aaf6a5f7d762.png)

6. Click "OK" on the password dialog, enter correct password and the wallet will open

**Comment by SomberNight** [comment] 2020-09-07 15:43
Thank you for the report. I am going to close this as duplicate of https://github.com/spesmilo/electrum/issues/3286.

**Closed by SomberNight** 2020-09-07 15:43 UTC
Labels: Qt, bug, user-interface
