### ISSUE TITLE
Electrum freezes when selecting Pay -> Advanced

### ISSUE THREAD

**Issue by Liongrass** [spesmilo/electrum#6921] opened 2021-01-08 05:42 UTC
I am able to reliably produce this bug in Electrum 4.0.9 on MacOS

REPRO:
- Recover BIP39 wallet from seed
- Fill out 'Pay to' and 'Amount' fields
- Select 'Pay'
- Select Advanced

EXPECTED:
- The advanced payment dialogue comes up

ACTUAL:
- Electrum becomes unresponsible, the cursor keeps spinning

**Comment by ecdsa** [comment] 2021-01-08 09:30
please be accurate: "crash" and "freeze" have different meanings. also, it is unlikely to be related to BIP39.
might be related to #6914

**Comment by Liongrass** [comment] 2021-01-08 09:34
You're right, 'freezes' is the correct terminology.
What made me think that it's related to BIP39 is that on the same computer the issue did not appear in a separate wallet (created natively in Electrum).

**Comment by ecdsa** [comment] 2021-01-08 09:50
please check if there are common aspects with #6914.
namely, does the issue arise with any transaction, or does it depend on the amount you are trying to pay?
does it arise specifically if you select particular coins in your list?

**Comment by SomberNight** [comment] 2021-01-08 15:15
What version of macOS are you using?
Is this with the official .dmg binary from the website? (as opposed to running from source or building your own binary)

**Comment by Liongrass** [comment] 2021-01-08 15:41
Yes, installed from the dmg image. I'll check back when I get access to that machine again, it's not mine and I can't reproduce this on Linux.

**Comment by amm-ljmu** [comment] 2021-01-20 14:49
I have this issue on Linux (downloaded from electrum.org and gpg verified files) for v4.0.2 and v4.0.9.
Same result irrespective of value trying to transact. 
Flow used: Open -> Click "Send" -> Add pay address, desc, value -> Click "Pay" -> Click "Advanced" -> Dialog box appears: "Sorry! Something went wrong while executing Electrum..."
Bug Report:
Traceback (most recent call last):
  File "/home/USERNAME/.local/lib/python3.8/site-packages/electrum/gui/qt/main_window.py", line 1613, in do_pay
    self.do_pay_invoice(self.pending_invoice)
  File "/home/USERNAME/.local/lib/python3.8/site-packages/electrum/gui/qt/main_window.py", line 1627, in do_pay_invoice
    self.pay_onchain_dialog(self.get_coins(), invoice.outputs)
  File "/home/USERNAME/.local/lib/python3.8/site-packages/electrum/gui/qt/main_window.py", line 1689, in pay_onchain_dialog
    self.preview_tx_dialog(make_tx=make_tx,
  File "/home/USERNAME/.local/lib/python3.8/site-packages/electrum/gui/qt/main_window.py", line 1693, in preview_tx_dialog
    d = PreviewTxDialog(make_tx=make_tx, external_keypairs=external_keypairs,
  File "/home/USERNAME/.local/lib/python3.8/site-packages/electrum/gui/qt/transaction_dialog.py", line 693, in __init__
    self.update()
  File "/home/USERNAME/.local/lib/python3.8/site-packages/electrum/gui/qt/transaction_dialog.py", line 391, in update
    self.update_fee_fields()
  File "/home/USERNAME/.local/lib/python3.8/site-packages/electrum/gui/qt/transaction_dialog.py", line 819, in update_fee_fields
    size = self.tx.estimated_size()
AttributeError: 'NoneType' object has no attribute 'estimated_size'
 
Additional information
Electrum version: 4.0.9 
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0] 
Operating system: Linux-5.4.0-58-generic-x86_64-with-glibc2.29 
Wallet type: standard,imported 
Locale: en_GB

**Comment by SomberNight** [comment] 2021-01-20 14:53
@amm-ljmu I suspect that's a different issue. Yours seem to be a duplicate of https://github.com/spesmilo/electrum/issues/6424.

**Comment by SomberNight** [comment] 2021-01-30 17:08
duplicate of https://github.com/spesmilo/electrum/issues/6914

**Closed by SomberNight** 2021-01-30 17:08 UTC
Labels: OS-mac, Qt ✨, bug 🐞
