### ISSUE TITLE
ERROR: zbar processor in zbar_processor_init():

### ISSUE THREAD

**Issue by petrkr** [spesmilo/electrum#1452] opened 2015-09-15 21:01 UTC
I just got this error message when I click on "qr" icon in send tab

ERROR: zbar processor in zbar_processor_init():
    unsupported request: no compatible image format

in log
WARNING: no compatible input to output format
...trying again with output disabled

nothing more

Electrum version is 2.4.4

zbar is installed from packages tree in version zbar-0.10-5

[root@petrkr-dell petrkr]# pip2 install zbar
Collecting zbar
  Using cached zbar-0.10.tar.bz2
Installing collected packages: zbar
  Running setup.py install for zbar
Successfully installed zbar-0.10

**Comment by ecdsa** [comment] 2016-10-11 15:29
closing, cannot reproduce that.

**Closed by ecdsa** 2016-10-11 15:29 UTC
