### ISSUE TITLE
ValueError('Exceeds the limit (4300 digits

### ISSUE THREAD

**Issue by xeverse** [spesmilo/electrum#8411] opened 2023-05-08 19:30 UTC
```
E/P | lnpeer.Peer.[LNGossip, 0359ba82d7-f41bd277] | Exception in main_loop: ValueError('Exceeds the limit (4300 digits) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit')
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/electrum/util.py", line 1239, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/electrum/lnpeer.py", line 415, in wrapper_func
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/electrum/lnpeer.py", line 429, in main_loop
    async with self.taskgroup as group:
  File "/usr/lib/python3.11/site-packages/aiorpcx/curio.py", line 304, in __aexit__
    self.secs = secs
  File "/usr/lib/python3.11/site-packages/electrum/util.py", line 1335, in join
    task.result()
  File "/usr/lib/python3.11/site-packages/electrum/lnpeer.py", line 456, in process_gossip
    await self.network.lngossip.process_gossip(chan_anns, node_anns, chan_upds)
  File "/usr/lib/python3.11/site-packages/electrum/lnworker.py", line 603, in process_gossip
    await run_in_thread(process_node_anns)
  File "/usr/lib/python3.11/site-packages/aiorpcx/curio.py", line 57, in run_in_thread
    return await get_event_loop().run_in_executor(None, func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/electrum/lnworker.py", line 602, in process_node_anns
    self.channel_db.add_node_announcements(node_anns)
  File "/usr/lib/python3.11/site-packages/electrum/channel_db.py", line 611, in add_node_announcements
    node_info, node_addresses = NodeInfo.from_msg(msg_payload)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/electrum/channel_db.py", line 166, in from_msg
    validate_features(features)
  File "/usr/lib/python3.11/site-packages/electrum/lnutil.py", line 1323, in validate_features
    features = LnFeatures(features)
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 714, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 1128, in __new__
    ve_exc = ValueError("%r is not a valid %s" % (value, cls.__qualname__))
```

**Comment by SomberNight** [comment] 2023-05-08 19:35
duplicate of https://github.com/spesmilo/electrum/issues/8403

**Closed by SomberNight** 2023-05-08 19:35 UTC

**Comment by SomberNight** [comment] 2023-05-08 21:41
No, I don't think so.
Note that "can send" values can be lower than the local balance in a channel (by a significant margin), as onchain fees are very high right now.

**Comment by xeverse** [comment] 2023-05-09 04:52
? how come on earth currently crazy onchain feez have 
anything to do with CanSend << localBL+Res+Dust..
https://share.riseup.net/#rw8feHi4fykab3mfmipQqg

**Comment by ecdsa** [comment] 2023-05-09 08:07
There is something called "fee spike buffer" that needs to be added to the channel reserves, and it is not displayed in the GUI.
This fee spike buffer is very high at the moment, because of the mempool situation.
I think the buffer amount should be displayed in the GUI, because users do not have any way to know about it.

**Comment by xeverse** [comment] 2023-05-09 08:39
feeSpikeBuff for chan closing? which 
fee we have no control over whatsoever..
does it need to be added to localRes at all?
while channels can be reqForceClose on the other side..
& who incurrs teh closingTxFees? who opened the chan or
can it be somehow split/ with other party in case of coop/force/req?
