### ISSUE TITLE
Issues with high DPI in Windows

### ISSUE THREAD

**Issue by ctyar** [spesmilo/electrum#6654] opened 2020-10-16 16:06 UTC
Wallet window:

![Capture1](https://user-images.githubusercontent.com/1432648/96281531-52254100-0fe6-11eb-9b9f-8a6819533da8.PNG)

Main window in default size:

![Capture2](https://user-images.githubusercontent.com/1432648/96281602-6bc68880-0fe6-11eb-9b44-16b5f177ef63.PNG)

This might seem fine but relative to the whole screen it is very small

Main window full screen:
![Capture3](https://user-images.githubusercontent.com/1432648/96281653-7c76fe80-0fe6-11eb-8eba-8ad94bb27338.PNG)

The status bar especially is hard to read

**Comment by Transisto** [comment] 2020-10-16 17:17
https://github.com/spesmilo/electrum/issues/6432 https://github.com/spesmilo/electrum/issues/6433

**Comment by SomberNight** [comment] 2020-10-16 17:44
right, seems to be duplicate of https://github.com/spesmilo/electrum/issues/6432
thanks for the report nevertheless

**Closed by SomberNight** 2020-10-16 17:44 UTC
Labels: Qt
