### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Daswaa** [spesmilo/electrum#8014] opened 2022-10-12 16:51 UTC
Hello, I have updated my computer and downloaded the wallet. I restored the wallet, but my investments were not on it. Is it possible to solve this problem somehow. I was transferred bitcoins, but there is no such thing in history
[https://www.blockchain.com/btc/address/bc1q6xgjannrr4wtmeesdhrusphefrmjhwr2c7l465](https://vk.com/away.php?to=https%3A%2F%2Fwww.blockchain.com%2Fbtc%2Faddress%2Fbc1q6xgjannrr4wtmeesdhrusphefrmjhwr2c7l465&cc_key=)
![image](https://user-images.githubusercontent.com/115648966/195402334-1bfa3bea-8bda-43a7-9b2a-78dba50906ac.png)

**Comment by ecdsa** [comment] 2022-10-12 19:36
not sure what the issue is...

**Comment by Daswaa** [comment] 2022-10-13 04:54
![Screenshot_20221012-081749_Electrum](https://user-images.githubusercontent.com/115648966/195504949-9e9e47c9-2f6c-4d5c-b4dd-ee35eda27224.jpg)

**Comment by ecdsa** [comment] 2022-10-13 09:20
not enough information, closing

**Closed by ecdsa** 2022-10-13 09:20 UTC
