### ISSUE TITLE
Bug: Can't go "Back" or forward ("Next") when pop up window in another wallet is open

### ISSUE THREAD

**Issue by fresheneesz** [spesmilo/electrum#5861] opened 2019-12-23 20:20 UTC
Repro steps:

1. Open one wallet
2. Go to File -> New/Restore
3. Open Wallet -> Information in the original wallet

Expected results:

Continuing the wallet creation process while that Wallet Information window is open should be possible.

Actual Results:

The Back and Next button are unresponsive (until the Wallet Information window is closed, at which point it seems to respond to a previous button click if you did that). 

One use case this is annoying in is trying to create a multisig wallet using the master public key, where I put in the master public key (while the wallet information window was still open) and was confused why I couldn't advance to the next screen.

**Comment by SomberNight** [comment] 2019-12-24 01:54
this is a duplicate of https://github.com/spesmilo/electrum/issues/3286

**Closed by SomberNight** 2019-12-24 01:54 UTC
