### ISSUE TITLE
Ledger Nano S still can't sign transactions 3.0.2

### ISSUE THREAD

**Issue by bustacapptv** [spesmilo/electrum#3313] opened 2017-11-16 09:03 UTC
When I click send, the Ledger never acknowledges any event has occured. No error message from my segwit Electrum wallet.

**Comment by jesusangelm** [comment] 2017-11-17 12:46
Same here, i'm trying to configure Electrum with my Ledger Nano S with Firmware 1.3.1 and i get this message:

`Firmware version too old for Segwit support. Please update at https://www.ledgerwallet.com`

i,m using m/49'/0'/0' derivation path

**Comment by SomberNight** [comment] 2017-11-17 14:23
@jesusangelm that's not the "same". That is a different error. Actually not even an error, though perhaps the text could be changed. Please make **both** the **firmware** AND the **bitcoin app** on the Ledger are updated.

**Comment by jesusangelm** [comment] 2017-11-17 14:40
@SomberNight you are right!, i updated Bitcoin app on Ledger from 1.1.5 to 1.1.10 and now this working good Electrum with Ledger.

sorry for that

**Comment by SomberNight** [comment] 2017-11-17 14:40
@bustacapptv 
Can you share more details? I have now tested signing and sending a bunch of transactions (on testnet though) with a p2sh-segwit wallet (bip49 derivation), and encountered no problems.
I used Electrum master (almost same as 3.0.2), on Debian 9.

What is the version of the Bitcoin app on the Ledger Nano S for you?
What OS are you using? If Linux, could you try running Electrum with `-v` and share the log?

**Comment by bustacapptv** [comment] 2017-11-17 15:01
Sorry, I'm running Win 10 (up to date), Ledger has latest firmware and bitcoin v1.1.10. When I try sending bitcoin, the window pops up telling me to sign the transaction but the ledger never acknowledges any event is occurring. With Electrum 3.0.1, the wallet would crash at this point.

**Comment by SomberNight** [comment] 2017-11-17 15:48
I guess this might be a duplicate of #3264... unless you think it isn't, let's move the discussion to that issue.

**Comment by bustacapptv** [comment] 2017-11-17 15:50
It may be

**Closed** 2017-11-18 10:42 UTC
