### ISSUE TITLE
Electrum websocket can't establish a connection to the server port 9999

### ISSUE THREAD

**Issue by aneesh2usman** [spesmilo/electrum#5701] opened 2019-10-15 08:17 UTC
Electrum merchant payment show in browser  WebSocket connection to 'wss://ip:9999/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by ecdsa** [comment] 2019-10-16 09:15
wrong commit comment: it should fix #5707, not #5701

**Comment by ecdsa** [comment] 2019-10-16 16:26
closing, duplicate of #5423

**Closed by ecdsa** 2019-10-16 16:26 UTC
