### ISSUE TITLE
Segmentation error ( core dumped)

### ISSUE THREAD

**Issue by Wargof** [spesmilo/electrum#4479] opened 2018-07-01 13:20 UTC
Hi, since recently I can no longer use Electrum because it cuts itself after a few seconds, when I launch it in terminal I have its 2 errors :
- ecc] warning: libsecp256k1 library not available, falling back to python-ecdsa
- Segmentation error ( core dumped)

Whether Electrum is installed or I run it from the zip file I have these errors.
I am running Linux Mint 18.3 and I use Electrum with a Nano Ledger.

**Comment by SomberNight** [comment] 2018-07-01 15:08
Hi. Does this only happen with 3.2.x?
Possibly related https://github.com/spesmilo/electrum/issues/4024
The warning about libsecp256k1 can be safely ignored.

**Comment by Wargof** [comment] 2018-07-01 16:29
I tested several versions after 3.0.3 and on all versions I have this problem.

**Comment by SomberNight** [comment] 2018-07-01 16:33
ok, then I would say this is a duplicate of https://github.com/spesmilo/electrum/issues/4024
(which is I guess a duplicate of https://github.com/spesmilo/electrum/issues/3660 ...)
try to describe your config in #4024, and I will try to reproduce

**Closed by SomberNight** 2018-07-01 16:33 UTC
