### ISSUE TITLE
[Android] can't send

### ISSUE THREAD

**Issue by romerun** [spesmilo/electrum#1729] opened 2016-03-22 13:29 UTC
when I clicked Pay on the Send tab, it's saying "unpack requires a string argument of length 4" . It used to work, then it stopped working.

My setting is 2-3 multisig wallets, 2 wallets on Android phones, 1 on Desktop. If I use electrum on desktop to create multisig transaction and use an android to sign it, it works just fine, but I now can no longer use an android to create a transaction.

**Comment by ecdsa** [comment] 2016-03-23 06:26
is your 'coin selection' setting 'privacy'?
can you check if that setting has an effect on it?

**Comment by ecdsa** [comment] 2016-03-23 06:47
ok, so it is probably the same bug as #1703
can you check if enabling/disabling dynamic fees has an effect on it?

**Comment by romerun** [comment] 2016-03-23 07:18
No, on/off dynamic fee has no effect on this. It could be the combination of "Privacy" + multisig wallet.

**Comment by kyuupichan** [comment] 2016-03-26 04:45
As I asked in the other PR, it would be nice if someone with this issue could put a print statement at the line in question to reveal what is going on.  I cannot reproduce this, and looking at the code it seems impossible, though clearly it's not.

**Comment by kyuupichan** [comment] 2016-03-26 04:48
Is this perhaps something specific to Python on Android?

**Comment by ecdsa** [comment] 2016-03-26 06:17
the traceback posted by @EagleTM  is with QT, not with Android

**Comment by ecdsa** [comment] 2016-04-08 08:38
duplicate of #1703

**Closed by ecdsa** 2016-04-08 08:38 UTC
