### ISSUE TITLE
Is Virtual Keyboard Plugin working ? Or am I wrong about it's use ?

### ISSUE THREAD

**Issue by sasatefa2009** [spesmilo/electrum#3229] opened 2017-11-06 20:30 UTC
![1](https://user-images.githubusercontent.com/22708418/32462432-f8e1cf76-c341-11e7-957e-a5d7f324cbce.jpg)
![2](https://user-images.githubusercontent.com/22708418/32462433-f90a44e2-c341-11e7-98f2-26c29ead4c3d.jpg)

**Comment by ecdsa** [comment] 2017-11-06 20:41
duplicate of #2538

**Closed by ecdsa** 2017-11-06 20:41 UTC

**Comment by sasatefa2009** [comment] 2017-11-06 20:48
@ecdsa  so you just added a feature that doesn't exist ??!!

**Comment by ecdsa** [comment] 2017-11-06 20:50
no, you opened a new issue for a bug that has already been reported.
this creates noise and wastes people's time.
next time, please check existing issues before you create a new one.

**Comment by sasatefa2009** [comment] 2017-11-06 20:54
@ecdsa wise answer.
next time i have to check the 175 opened issue.

Great.

**Comment by ecdsa** [comment] 2017-11-06 21:00
yes you should. do you think things get better when we have 176 instead of 175?

**Comment by sasatefa2009** [comment] 2017-11-06 21:44
@ecdsa 
Sir, with all the due respect.
the issue you are referring to is from June, which means 5 months ago.
if this function is not working, then it would be better to be removed until fixed.
