### ISSUE TITLE
Cannot sweep coins from command line, "mandatory-script-verify-flag-failed"

### ISSUE THREAD

**Issue by qirtaiba** [spesmilo/electrum#3002] opened 2017-10-05 22:10 UTC
This is related to #2988 which was fixed by upgrading. I'm now on the latest master, which should make this bug report more useful than the last one.

After the upgrade, Electrum seems to generate a valid transaction to sweep coins from a private key into my wallet. The transaction validates (eg. on coinb.in) with the correct amount and the correct destination wallet, and signed. However, it won't broadcast. (By the way, I've tried both an ordinary wallet and a multisig wallet as the destination wallet, it makes no difference.) The error I get when trying to broadcast (no matter whether I do this using Electrum or using coinb.in) is:

`16: mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation)`

The command line that I'm using is:

`electrum sweep [privkey-to-sweep] [destination-wallet-address] | electrum broadcast -`

Also the wallet that I'm sweeping from checks out when I look at it on blockchain.info, with the expected balance.

**Comment by ecdsa** [comment] 2017-10-06 02:48
is it a p2pk output? maybe a duplicate of #2857

**Comment by ecdsa** [comment] 2017-10-06 05:48
closing as duplicate of #2857

**Closed by ecdsa** 2017-10-06 05:48 UTC

**Comment by SomberNight** [comment] 2017-10-09 08:16
In the other issue, @qirtaiba shared a raw tx.
```
0100000001550206d45a254ce039d51b23db2e1e9a890b9548575bf8e24600ec51ce2a1864000000006b4830450221009ad83ae43d5b93fde14ebefc1278de3ff9359d8b82391bca23bae19d22f85e1f0220181e9774632a657a22e2e69d839ee8e70d6fa6342a9d5047154d6e43b2383c220121023c68bea0b6135bc42d6d65f89efecc49f36cc8bb5a99a2e7df9d7b108d9beac5feffffff0195230000000000001976a914952bf590dc7e0eb1f1b7b89e67d9ef5c12aeeab188ac00000000
```

I can confirm that creating and signing a raw tx from a private key with **uncompressed** public keys does NOT work.
