### ISSUE TITLE
Electrum wallet with wallet type 2 of 3 signs. Trezor and Ledger

### ISSUE THREAD

**Issue by Chewdone** [spesmilo/electrum#4662] opened 2018-08-27 14:24 UTC
Wallet on Electrum with wallet type: 2 of 3 signs. 
Script type: p2sh
It was created on 3.2.0 or newer version
After confirming on the hardware, he gives a message: "Electrum can not pair with your TREZOR.
Before you request bitcoins to get sent to addresses in this wallet, to ensure you can pair with your device, or that you have its seed (and passphrase, if any). Otherwise all bitcoins you receive will be unspendable"

Earlier it was enough to have one confirmation on the hardware and password from the electrum to send the transaction.

Why if I create transaction, make 2 signs but he ask for a third sign and transaction cannot be submit?

**Comment by ohenrik** [comment] 2019-06-29 16:27
I have the same issue, however i was able to sign with multiple Hardware devices by exporting the partially signed transaction, disconnecting the previous devices, restarting Electrum and then connecting the next device i want to sign with. However i get the error message multiple times, both at start up and after each signature i make. This happens for all Hardware Wallet types I have tested.

**Comment by SomberNight** [comment] 2019-06-29 16:29
Could you explain what the issue is? I don't follow.

**Comment by ohenrik** [comment] 2019-06-30 10:25
1. I receive this error multiple times on startup: 
> Electrum can not pair with your TREZOR.
>Before you request bitcoins to get sent to addresses in this wallet, to ensure you can pair with your device, or that you have its seed (and passphrase, if any). Otherwise all bitcoins you receive will be unspendable

2. When i sign transactions, i also get the error above after i sign. I then cannot sign using multiple devices without exporting the partially signed transaction, restarting the Electrum app and then importing it again before signing with another device (for every additional signature).

I got this error on both Ubuntu 18 and macOS. I also tried downloading an earlier version of Electrum (3.4 i believe) and i still get all these errors.

I have checked the checksum before using all of these Electrum installations.

**Comment by ohenrik** [comment] 2019-06-30 10:37
I see now that the original poster was asking about having to use all 3 Hardware wallets. I can successfully sign with only 2 of 3, or 3 of 5, but i get the errors as explained above. So to summarize, The multi-signature wallet works, but this error is confusing, annoying and makes it seem like the wallet is not really working.

Do I have to configure the Ledger/Trezors through Electrum to be able to use them without these errors? I have set up these devices using the normal setup procedure. Then created the multi-sig wallets through Electrum signing every step with a hardware wallet.

**Comment by SomberNight** [comment] 2019-07-02 15:41
@ohenrik I cannot reproduce.
Can you give a specific example that you have tried? (e.g. 2of3 with ledger nano s, trezor one, trezor one)
Do you have all the hardware wallets connected when you try to sign?
Do you use the `Send` button or the `Preview` button in the `Send` tab?
After you get this error and the transaction is partially signed, is the `Sign` button in the tx dialog clickable?

**Comment by ohenrik** [comment] 2019-07-03 09:08
One example: 
I created a 3 of 5 multisig using 3 Trezor one and 2 Trezor T. I did not have all models connected at once when i created the multisig wallet. And i did not have all trezors connected at the same time when trying to sign. The main reason for this is that when i attach more than 1 Trezor model one, only one of these decives are usable at a time (only one of then gets asked for a pin code etc).

The send button did not seem to work, it only produced the error message i wrote above without giving me any further actions. 

I managed to use the preview button and then sign as i described above.

Could you please share the exact process you used when setting up the multisign wallet? Maybe i did something wrong. All my trezors where already set up using the trezor command line tool + the web interface to set the pin etc. Maybe i should reset them and set them up using electrum?

**Comment by SomberNight** [comment] 2019-07-03 09:19
> All my trezors where already set up using the trezor command line tool + the web interface to set the pin etc. Maybe i should reset them and set them up using electrum?

No, this is fine.

> I did not have all models connected at once when i created the multisig wallet.

Then this is part of the reason for the behaviour you describe. You will not be able to sign with the devices that you did not add during wallet creation; i.e. the ones for which you only added an xpub. However you should not see an error message for these either.

You would usually add all the hardware wallets during wallet creation that you have; and use xpubs for cosigners that are intentionally at a physically separate location, or are controlled by other people.

> Could you please share the exact process you used when setting up the multisign wallet? 

I added all the hardware wallets during wallet creation.

> The main reason for this is that when i attach more than 1 Trezor model one, only one of these decives are usable at a time (only one of then gets asked for a pin code etc).

They should all be asked for PIN/passphrase/button presses; but sequentially, one after the other. Is this not the case?
I don't usually test with many hw devices of the same manifacturer at the same time; and I suspect based on what you write that there might be a bug there.

**Comment by ohenrik** [comment] 2019-07-03 12:17
I will try to create a new multisig wallet in a few hours and keep all my devices connected at the same time during wallet creation. However is it documented somewhere that i need to have all devices plugged in during the entire wallet creation process? That would mean that in order to be able to create a 5 of 8 wallet i need to have 8 usb ports on my machine? (or use a large usb hub).

I feel like it would be natural to connect the devices to add them to the list of devices needed for the multisig wallet, then disconnect it in order to be able to connect a new device. 

I can see that it might be necessary if electrum needs some information from all the devices at the end of the process at the same time, but if this is the case, it needs to be written somewhere. Or a message should appear once i unplug one of the devices during multisig wallet creation.

**Comment by SomberNight** [comment] 2019-07-03 13:22
Sorry I meant that all devices should be added using the "hardware device" option during wallet creation and not with the "master key"/"enter cosigner key" option; not that all devices must be connected throughout the whole creation process. The former just means that every device must be connected at some point during the creation.

**Comment by ohenrik** [comment] 2019-07-04 16:12
Then i have done exactly as you explained above. 

I have now tried to create several wallets and have tried to restore my wallet using the same hardware wallets. It does seem to work however:

1. During creation and restoring wallets. It seems like Electrum displays the same device label when i connect a new device using the same usb port. Signing does however seem to work, but when the wallet is opened in electrum, the Trezor icons on the bottom right corner all have the same label, making it impossible to distinguish the devices.
2. When open my wallet with only one device connected, Electrum seems to ask me about an arbitrary number of other devices telling me it is unable to connect to it and asks if i want to retry. 
3. It seems like it is impossible to connect a Trezor model T after connecting a Trezor model One. I also have to try multiple times and switch USB ports to be able to connect Trezor One after connecting a Trezor T.

It might be something wrong with how Electrum uses Trezor Bridge. I have followed the guide provided by Electrum on how to use Trezor Hardware wallet on Linux.

**Comment by SomberNight** [comment] 2019-12-20 01:03
Is this a duplicate of https://github.com/spesmilo/electrum/issues/5759 ?
Do the Trezor devices in question have identical labels?

**Comment by craigraw** [comment] 2020-01-24 09:37
I think this is a duplicate of #5789

**Comment by SomberNight** [comment] 2020-04-10 19:21
https://github.com/spesmilo/electrum/issues/5759 and https://github.com/spesmilo/electrum/issues/5789 are now solved so I believe this is fixed.

**Closed by SomberNight** 2020-04-10 19:21 UTC
Labels: hw-generic
