### ISSUE TITLE
UI in testnet mode is poor in feedback

### ISSUE THREAD

**Issue by stefanocudini** [spesmilo/electrum#6809] opened 2020-12-04 15:01 UTC
I have read numerous articles that tell about scams against newbie users who have been deceived only for trivial interface problems.

I believe it is important to avoid scams involving electrum to improve the visual feedback in the testnet mode

in the current version this is the only feedback in the interface to understand which network the wallet is connected to
![testnet](https://user-images.githubusercontent.com/47107/101178765-ae512c80-3649-11eb-83e7-63807aef861c.png)

instead this is what I would expect to see:
![testnet2](https://user-images.githubusercontent.com/47107/101178785-b27d4a00-3649-11eb-8c07-68a3bca0b433.png)

**Comment by ecdsa** [comment] 2020-12-05 19:34
closing as duplicate of #3728

**Closed by ecdsa** 2020-12-05 19:34 UTC
