### ISSUE TITLE
macOS build: codesigned Electrum.app fails to load

### ISSUE THREAD

**Issue by vertiond** [spesmilo/electrum#7652] opened 2022-02-04 18:00 UTC
I explicitly followed directions in `contrib/osx/README.md` to create a macOS 10.14.6 build environment using full Xcode 11.3.1.  I have my own codesigning certificate as well.  Every build I make that is codesigned and notarized successfully fails to load.

```
verts-iMac:dist vert$ open Electrum.app/

LSOpenURLsWithRole() failed with error -10810 for the file /Users/vagrant/electrum/dist/Electrum.app.
```
Upon running `run_electrum`, I see that the error has to do with libsecp256k1.

```
verts-iMac:dist vert$ ./Electrum.app/Contents/MacOS/run_electrum

Error: Failed to load libsecp256k1.

E | ecc_fast | libsecp256k1 library failed to load. exceptions: [PyInstallerImportError("Failed to load dynlib/dll '/Users/vagrant/electrum/dist/Electrum.app/Contents/MacOS/libsecp256k1.0.dylib'. Most probably this dynlib/dll was not found when the application was frozen."), PyInstallerImportError("Failed to load dynlib/dll '/Users/vagrant/electrum/dist/Electrum.app/Contents/MacOS/libsecp256k1.0.dylib'. Most probably this dynlib/dll was not found when the application was frozen.")]
```

Is there an extra step or something about the build environment that is not documented in the README?

**Comment by gruve-p** [comment] 2022-03-06 19:04
Duplicate of https://github.com/spesmilo/electrum/issues/7607

**Comment by SomberNight** [comment] 2022-03-16 17:49
closing this in favour of the other issue

**Closed by SomberNight** 2022-03-16 17:49 UTC
Labels: OS-mac
