### ISSUE TITLE
Can't run Electrum by comman line

### ISSUE THREAD

**Issue by bar-boss** [spesmilo/electrum#7876] opened 2022-07-02 11:38 UTC
Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-121-generic x86_64)

My installation process:
`apt-get  update`
`sudo apt install python3-pip python3-setuptools python3-pyqt5 libsecp256k1-dev`
`sudo -H pip3 install https://download.electrum.org/4.2.2/Electrum-4.2.2.tar.gz#egg=electrum[fast]`

And then I try to execute command:
`# /usr/local/bin/electrum help`

Output:
```
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 87, in <module>
    from electrum.logging import get_logger, configure_logging  # import logging submodule first
  File "/usr/local/lib/python3.8/dist-packages/electrum/__init__.py", line 16, in <module>
    from .wallet import Wallet
  File "/usr/local/lib/python3.8/dist-packages/electrum/wallet.py", line 68, in <module>
    from .storage import StorageEncryptionVersion, WalletStorage
  File "/usr/local/lib/python3.8/dist-packages/electrum/storage.py", line 37, in <module>
    from .wallet_db import WalletDB
  File "/usr/local/lib/python3.8/dist-packages/electrum/wallet_db.py", line 45, in <module>
    from .paymentrequest import PaymentRequest
  File "/usr/local/lib/python3.8/dist-packages/electrum/paymentrequest.py", line 37, in <module>
    from . import paymentrequest_pb2 as pb2
  File "/usr/local/lib/python3.8/dist-packages/electrum/paymentrequest_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by SomberNight** [comment] 2022-07-02 14:01
Duplicate of https://github.com/spesmilo/electrum/issues/7833.

Try running `python3 -m pip install --user "protobuf>=3.12,<4"` before installing electrum.
Will be fixed in the next version.

**Comment by bar-boss** [comment] 2022-07-02 18:34
Thank you.
I execute command after installing electrum and is worked.
`pip install protobuf==3.20.*`

**Closed** 2022-07-02 21:40 UTC
