### ISSUE TITLE
Edit online block explorer

### ISSUE THREAD

**Issue by Yoshi-dot** [spesmilo/electrum#6727] opened 2020-11-12 13:04 UTC
When using btc-rpc-explorer people have different ip-addresses and port-numbers.
It would be a good idea to make it possible to manually add a online block explorer.

**Comment by petrhejna** [comment] 2021-01-23 22:57
Maybe duplicate of https://github.com/spesmilo/electrum/issues/4831 ?

**Comment by SomberNight** [comment] 2021-01-23 23:41
yes, you are correct

**Closed by SomberNight** 2021-01-23 23:41 UTC
Labels: block-explorer 🧭
