### ISSUE TITLE
add support for XDG_DATA_HOME for os.name == 'posix'

### ISSUE THREAD

**Issue by toxeus** [spesmilo/electrum#4123] opened 2018-03-14 09:53 UTC
Currenlty, electrum does not follow the XDG specification for its data directory but [hard codes](https://github.com/spesmilo/electrum/blob/7e6fba0513b6a8db0a0546e8184f7d7a66008585/lib/util.py#L391-L392) it to `$HOME/.electrum`. 

Besides reducing the clutter inside `$HOME` the XDG specification enables the user to selectively backup all of his or her application's data. 

I'm opening this issue to ask if the project is interested in implementing the [XDG specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), i.e. to use `XDG_DATA_HOME` to store the appliaction's data. If so then I'm happy to contribute patches that maintain backwards compatiblity.

**Comment by SomberNight** [comment] 2018-03-14 10:43
related: https://github.com/spesmilo/electrum/pull/1636

**Comment by toxeus** [comment] 2018-03-14 11:43
I see. So the last attempt to implement this failed because people couldn't agree on how to split the `.electrum` folder into the various XDG folders. I tackle such things in a problem driven approach:

 Nobody so far complained about different application artifacts such as configs, data, and `blockchain_headers` living in the same folder. Therefore, I don't see the need to split them - even if XDG would propose a structure for it.

On the other hand, having a un-cluttered `$HOME` and a desire to easily backup `$XDG_DATA_HOME` seems to be a real-world feature request by some users. Therefore, migrating from `$HOME/.electrum` to `$XDG_DATA_HOME/electrum` would make sense because we're solving a real-world problem and not just complying with some (possibly over-engineered) spec.

If in future someone is not happy about having the `blockchain_headers` in `$XDG_DATA_HOME` then it's still possible to implement `$XDG_CACHE_HOME` for them. But I wouldn't do it before a real-world user request/need exists.

**Comment by ecdsa** [comment] 2018-03-14 12:55
closing, duplicate of #1636. no need to fragment the discussion.

**Closed by ecdsa** 2018-03-14 12:55 UTC

**Comment by toxeus** [comment] 2018-03-14 13:08
I'd prefered you'd closed the PR which was inactive for almost 6 months. Before opening this issue I used Github's search to check if this was discussed already. Needles to say, I didn't find the discussion in the PR because Github doesn't search in PRs by default. Also, this is aligned to how people use Github: issues for discussions and PRs for review.
