### ISSUE TITLE
Icons (Copy to clipboard, Read QR code, Read file) within Send & Receive tabs incorrectly sized / scaled

### ISSUE THREAD

**Issue by eeik** [spesmilo/electrum#5167] opened 2019-02-28 18:54 UTC
I'm not sure if this is a scaling issue or experienced by all users, but the copy to clipboard icon within 3.3.4 doesn't fit within the receiving address bar.

Windows 10, 3440 x 1440, with native display 100% text/apps scaling.

![electrum clipboard icon](https://user-images.githubusercontent.com/5521252/53590638-7b623680-3b4f-11e9-8d54-b41521b63003.png)

Read QR code & Read file icons within "Send" are also exhibiting this same behavior for me.

**Comment by SomberNight** [comment] 2019-02-28 19:44
Thank you for the report. This is a duplicate of https://github.com/spesmilo/electrum/issues/5047

**Closed by SomberNight** 2019-02-28 19:44 UTC
