### ISSUE TITLE
ledger nano s showing "Warning !" and freezing when trying to sign transaction using electrum / unusual BIP32 change path 49'/0'/0'/0/0 should be 49'/0'/0'/1/0

### ISSUE THREAD

**Issue by onpars** [spesmilo/electrum#5271] opened 2019-04-18 06:58 UTC
Electrum is using "unusual BIP32 change path" `49'/0'/0'/0/0` but should be using `49'/0'/0'/1/0` according to jean-ledger `Ledger Engineer`.

* `49'/0'/0'/0/0`
* `49'/0'/0'/1/0`

This results in ledger showing `Warning !` which is then non-obvious to proceed (press both ledger buttons). Without asking ledger support, I wouldn't have known if it is safe to proceed.

This is a summary. The full bug report was originally posted ledger's reddit, you can find it here:
https://www.reddit.com/r/ledgerwallet/comments/b8vf3z/ledger_nano_s_showing_warning_and_freezing_when/

I am just a user so I don't know if this should be fixed in ledger and/or electrum. Please consider joining the technical discussion on reddit or perhaps the ledger engineer can join the discussion here so this can be sorted among the two involved projects.

**Comment by jhoenicke** [comment] 2019-04-18 11:06
Most likely you have unset the "use change addresses" option. Open the preferences dialog (Tools -> Preferences) and enable "use change addresses" on the Transactions tab.

It may make sense to change the ledger plugin to not mark these as change outputs, but change them to normal send to address outputs.

**Comment by SomberNight** [comment] 2019-04-19 22:36
@onpars As @jhoenicke says, could you please check whether you have "use change addresses" enabled. If you do not, that would explain this.

Otherwise, I am inclined to close this.

**Closed** 2019-05-16 16:46 UTC
Labels: awaiting-response, hw-ledger

**Comment by onpars** [comment] 2019-06-13 12:21
Did not use "use change address".

**Comment by SomberNight** [comment] 2019-09-06 17:05
Another report on Reddit today: https://www.reddit.com/r/ledgerwallet/comments/d0fcnz/ledger_nano_s_and_electrum_warning/

> Secure Element 1.5.5
MCU 1.7
Bitcoin App 1.3.8
Electrum 3.3.8

> Warning
Press both buttons - The Change of path is unusual
Press both buttons - Change Path 49'/0'/0'/0/6
Press both buttons - Reject if you are unsure Y or N

> Hi
I am using Electrum 3.3.8 to send BTC and it has been fine for several months.
I just tried to send some BTC from there and insted of the usual CONFIRM on Ledger Nano S i get a message 'Warning!'
Then [... above happened ...]
This has NEVER happened before, what is happening, is it safe to accept, i have not altered/updated anything on Ledger/Electrum?

To reiterate, this happens if you manually disabled the `Use change addresses` option.
(`Tools`>`Preferences`>`Transactions`>`Use change addresses`)

**Comment by craig5999** [comment] 2020-01-27 02:05
I've set up a multi-sig using OSX (Catalina 10.15.2) Electrum 3.3.8 with a Trezor and Ledger (both up-to-date firmware), using the default m/48'/0'/0'/2' path. Both public keys are available when I check the wallet information via the Electrum menu.

I get the message "The change path is unusual" 48'/0'/0'/2'/1/3 on my Ledger when attempting to sign a tx. Accepting the change path allows me to complete the tx successfully. The change comes back to my multi-sig wallet as expected. I checked the option "Use change addresses". It is checked. Above it was stated that the issue should be fixed if the option is checked. But this does not fix it for me.

I tried unchecking "Use change addresses" and restarting Electrum. I still got the warning, but this time with change path 48'/0'/0'/2'/1/2. I considered this unusual - why is it asking this if I disabled change addresses? Because it still needs to use a change path to send back to the same wallet?

Would it be safe for me to manually select any other derivation path supported by Ledger?

Anyway, it would be great if you could give me some clarity on this. My guess is that Ledger does not yet recognize this multi-sig derivation path, so a warning is thrown. I read the reddit threads and saw that it is safe to continue, so I guess it's not a big issue. I've contacted Ledger support and will update when I receive an answer.

Thank you!

**Comment by craig5999** [comment] 2020-01-27 02:38
UPDATE!

On the Ledger I'm using, there is also some BTC stored in m/49'/0'/0'. So I thought, how about trying from scratch with a different set of addresses? I set a temp passphrase and set up a new multi-sig wallet with everything kept the same except the ledger passphrase.

Transactions went through without any change address warning.

Could it be that the use of the m/49'/0'/0' path in the original Ledger is somehow conflicting with the multi-sig setup, and giving me a warning when I try to use 48'/0'/0'/2'/1/3? It seems the case to me.

Thoughts?

**Comment by jhoenicke** [comment] 2020-01-28 18:21
If the "use change address" box is unchecked, the change is send to the first input address (address reuse).  This part is expected behavior.  The change output is used in any case; if you would remove this output, it would be a donation to the miner.

Now in your first case the change address 48'/0'/0'/2'/1/3 uses the right path.  The "/1/" indicates it uses a change address.  I guess the algorithm that Ledger uses to determine whether a change address is fine is too restrictive in this case. They probably erred on the side of giving too many warnings.  Maybe they don't accept derivation paths with unusual length (6 instead of 5).

Handling of change addresses in multisig setup is always a bit tricky.  You don't want that the change goes to a different wallet or even is under the control of different signers.  For a hardware wallet it is better to err on the side of too many warnings, than to silently send the change to a 1 of 2 multisig where the second key is owned by someone else (some very early firmware of Trezor had this bug).

If you sign it on the Trezor, does it work there, or does it explicitly ask you to confirm the change output?  I think it should work as the path matches what the Trezor is expecting.

**Comment by craig5999** [comment] 2020-01-29 05:31
Thank you for your reply. Signing on the Trezor does not produce any warning. Why do you say the path matches what the Trezor is expecting? Shouldn't both wallets be expecting the path? Or does the Trezor firmware allow more paths?

The thing that confuses me most is in the update to my post above. There is no change path warning after setting up a new multisig wallet using the same Trezor, and the same Ledger but with a temp passphrase entered for the Ledger...

**Comment by craig5999** [comment] 2020-01-29 23:14
Response from Ledger:

`Thank you for reaching Ledger Support. My name is Hao and I will be gladly assisting you from now.

We sincerely suggest you contact Electrum BTC wallet support regarding your question here.

Let us know if you have any other issues.`

**Comment by SomberNight** [comment] 2020-02-05 13:45
> Shouldn't both wallets be expecting the path? Or does the Trezor firmware allow more paths?

The Trezor behaves according to its own firmware code, and the Ledger behaves according to its own firmware code. There is no guarantee that the behaviour is identical.

> There is no change path warning after setting up a new multisig wallet using the same Trezor, and the same Ledger but with a temp passphrase entered for the Ledger...

Have you changed the derivation path for the Ledger signer in the new multisig wallet you created, or only the passphrase (I assume you mean passphrase in the BIP39 hmac salt sense)?

**Comment by craig5999** [comment] 2020-02-05 23:40
> Have you changed the derivation path for the Ledger signer in the new multisig wallet you created
No, I used the same (m/48'/0'/0'/2'). 

> or only the passphrase (I assume you mean passphrase in the BIP39 hmac salt sense)?
I'm not quite sure what this means... but probably yes. Adding the extra passphrase. Ledger gives the option to tie it to a PIN or set it temporarily.
