### ISSUE TITLE
v3.3.2 Trezor Model T "String value expected" - macOS High Sierra

### ISSUE THREAD

**Issue by jonathancross** [spesmilo/electrum#5006] opened 2019-01-15 01:21 UTC
Electrum `v3.3.2`
System: macOS High Sierra
Trezor Model T firmware `2.0.10`

Steps:

1. Select "File > New/Restore"
2. Select "standard wallet"
3. Select "Use a hardware device"
4. Select either of 2 options shown (`webusb:020:1` or `bridge:lib01`)
5. Model T prompts to enter password on "Device" or "Host".  Select "Device".

Result:

Model T screen goes blank.
Electrum reports "String value expected"

```
[Plugin][trezor] connecting to device at webusb:020:1
[Plugin][trezor] connected to device at webusb:020:1
[DeviceMgr] Registering My-Model-T/8**********************5
[Plugin][trezor] connecting to device at bridge:lib01
[Plugin][trezor] connected to device at bridge:lib01
[DeviceMgr] Registering My-Model-T/8**********************5
[DeviceMgr] scanning devices...
Traceback (most recent call last):
  File "electrum/base_wizard.py", line 296, in on_device
  File "/var/folders/r6/52hwfppd54gcp282htjvwwcw0000gn/T/_MEI1DeE1y/electrum/plugins/trezor/trezor.py", line 273, in setup_device
    client.get_xpub('m', 'standard', creating=is_creating_wallet)
  File "/var/folders/r6/52hwfppd54gcp282htjvwwcw0000gn/T/_MEI1DeE1y/electrum/plugins/trezor/clientbase.py", line 122, in get_xpub
    node = trezorlib.btc.get_public_node(self.client, address_n).node
  File "trezorlib/tools.py", line 208, in wrapped_f
  File "trezorlib/btc.py", line 36, in get_public_node
  File "trezorlib/tools.py", line 229, in wrapped_f
  File "trezorlib/client.py", line 171, in call
  File "trezorlib/client.py", line 144, in _callback_passphrase
  File "mnemonic/mnemonic.py", line 70, in normalize_string
TypeError: String value expected
[DeviceMgr] scanning devices...
```

**Comment by SomberNight** [comment] 2019-01-16 18:30
the issue is in python-trezor, and was fixed in https://github.com/trezor/python-trezor/commit/cf9106ff5d7be28cc3b75dccef7bef6ba37fbe1e
we need to pull in at least 0.11.1

**Closed** 2019-01-25 01:06 UTC
Labels: bug, hw-trezor
