### ISSUE TITLE
Can't send transaction on multiple signature wallet

### ISSUE THREAD

**Issue by djnocide** [spesmilo/electrum#2024] opened 2016-11-07 22:40 UTC
When i try to broadcast a transaction i've received, an error message pop up saying: 

> error: The transaction was rejected by network rules. (16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with false/empty top stack element)

What do i need to do to resolve this error?

**Comment by ecdsa** [comment] 2016-11-08 04:36
please explain how you created the transaction, and paste it here

**Comment by djnocide** [comment] 2016-11-08 11:17
My friend sent me a transaction to sign which i opened in the electrum wallet: tools -> load transaction -> from file. When the file opened, i entered my password to sign the transaction. When i try to broadcast the transaction i receive that error 
![error 16](https://cloud.githubusercontent.com/assets/8508331/20097089/b7c372aa-a57a-11e6-8e74-0fcd5d4fe19c.png)

We try the other way around, i create the transaction (Send -> filling Pay to and amount -> Send), i sent him the unsigned transaction but he received the same message.

I try with the dynamic fees on and off but had the same result.

**Comment by dabura667** [comment] 2016-11-08 12:06
It looks like the signature is invalid. How did your friend make the unsigned transaction?

**Comment by ecdsa** [comment] 2016-11-08 16:28
can you publish the unsigned transaction please?

**Comment by djnocide** [comment] 2016-11-08 23:04
@ecdsa 
![unsigned tx](https://cloud.githubusercontent.com/assets/8508331/20121113/ba3916c6-a5dd-11e6-9812-3114e368db9a.png)

@dabura667 i asked my friend to come answer your question himself

**Comment by djnocide** [comment] 2016-11-08 23:58
@ecdsa @dabura667 the transaction went through when using the 2.6.4 wallet

**Comment by ecdsa** [comment] 2016-11-09 05:55
can you publish the unsigned transaction please?

**Comment by djnocide** [comment] 2016-11-09 10:57
how do i get that (hexadecimal string)?
I thought the picture above was what you wanted.

**Comment by ecdsa** [comment] 2016-11-09 11:04
save it to a text file

**Comment by djnocide** [comment] 2016-11-09 11:14
0100000001082f265c42e64d741ca20e1f07b42bf0c9b5f6f874632ac35a042bf698a781fe01000000c800483045022100ad56f04d42bb605725387dd290f81d76fbe4dae486c8a6ec3afdddb23b8fe669022015f448be24d8f1235cce7bde231cce6c0177b757cd60c348cdb25520caa72b7e0101ff4c7a522103a703c611b20fc32ab31517b381fa0b87d08689f3cbdd60a62dbf8ac75c758d5d4c53ff0488b21e000000000000000000baa31d7c59409082da3029776ea5f5e3bd05c59fbe88a6e0e1f6262e9fa186a903f2534f07bc6471bf425e8b95b6af1ffe69dcbb8d45e0678253639625c55e9a820100010052aeffffffff02c832f5050000000017a914f928a995e7f2ae31797a72732ae6f60ab18d3da28700e1f505000000001976a9143858c9857ea19da4857dc1b5e74b08df82fc4c1588ac00000000

Is it what you were looking for?

**Comment by ecdsa** [comment] 2016-11-09 11:26
yes thanks

**Comment by dabura667** [comment] 2016-11-09 12:18
Did Electrum switch to some sort of special partially signed tx format?

Trying to by-hand parse this tx threw me for a loop, as immediately after pushing the sig to the stack it pushes a 1 byte of data 0xff to the stack, then the rest makes no sense.

**Comment by g17hu84cc7** [comment] 2016-11-11 22:58
Did you find a solution for this? I've encountered the same problem. Regardless of which wallet the transaction is initiated from, I'm getting the same error when trying to broadcast it. Signing seems to work for both (it is a 2 of 2 multisig wallet). But on attempting to broadcast, I get the following: 

error: The transaction was rejected by network rules.(16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element))

Both wallets are updated to the latest version: 2.7.12, but the issue was first encountered running 2.6.4. I updated to the latest release specifically in an attempt to resolve the trouble broadcasting, but no joy.

This was not an issue previously, and multisig transactions were working fine until now.

**Comment by djnocide** [comment] 2016-11-11 23:10
@g17hu84cc7 the way it worked for us was, tx created on wallet 2.6.4 and signed/broadcast on 2.7.11
I don't know why but it worked for us. We'll see if it works next time.

**Comment by g17hu84cc7** [comment] 2016-11-11 23:20
@djnocide

Thanks! I'll give that a shot and see if it works for me too. If I have any luck, I'll update here with what got it to broadcast.

**Comment by g17hu84cc7** [comment] 2016-11-12 01:42
I wanted to post an update in the event others faced this issue. I tried changing lots of settings and tried all different options for fees, uninstalling/reinstalling electrum, and a number of other things without success. I also tried the suggestion of using 2.6.4 to create the tx and 2.7.12 to sign/broadcast, but no luck as the program/wallet would no longer load when I rolled back to 2.6.4 after having already updated to 2.7.12. In any event, I doubt it would have mattered because I started out on 2.6.4 and encountered the issue on that version earlier as stated above, which was the very thing that prompted the version update in the first place. Anyway, I ran out of time to try new things and the transaction needed to get sent, so I settled for a workaround:

On a separate OS without Electrum installed yet, I installed it and selected the "Restore a wallet or import keys" and "Multi-signature wallet" options and entered the seed for both wallets and then sent the transaction from that restored wallet which no longer needed 2 signatures after the restore. This doesn't seem like a good solution for regular multisig wallet function, and would make me hesitant to use this feature in the future with others. I'm also unsure how that restore impacted the current function of the other existing wallets, and if they will still require multisignature to send. I did not test yet.

**Comment by stiell** [comment] 2016-11-29 15:31
Same problem here with a 2-of-3 multisig wallet between three Electrum 2.7.12 instances. I've tried:

- unsigned on desktop 1 -> partially signed on desktop 2 -> fully signed on Android,
- unsigned on desktop 1 -> partially signed on Android -> fully signed on desktop 2,
- partially signed on desktop 2 -> fully signed on Android.

They all resulted in exactly the same invalid TX.

**Comment by ecdsa** [comment] 2016-12-05 14:18
@djnocide @stiell can you please publish the invalid TX ? (fully signed)

**Comment by ecdsa** [comment] 2016-12-05 14:19
@dabura667 yes electrum has a custom format for partially signed TX. this is not new, it has been around since 2.0.

**Comment by djnocide** [comment] 2016-12-05 20:58
@ecdsa we we're able to solve the problem by using 2.6.4. We've made multiple transaction and it worked. We don't know why but it was the solution for us.

**Comment by ecdsa** [comment] 2016-12-06 05:56
@djnocide I am not trying to solve your problem. I am trying to understand and fix bugs in the software. if you want to help me, please provide the signed tx that caused this.

**Comment by djnocide** [comment] 2016-12-06 10:57
@ecdsa 
58de1b1959d6aa60e1eb14f86c914de8c984c550c247f21977e9e43fb16ba79f

**Comment by ecdsa** [comment] 2016-12-06 11:26
@djnocide that's not what I need. could you please paste the raw transaction that causes the error message? (created in 2.7.12)

**Comment by djnocide** [comment] 2016-12-06 11:31
@ecdsa is it what you want? if not tell me how to get the raw transaction.
0100000001082f265c42e64d741ca20e1f07b42bf0c9b5f6f874632ac35a042bf698a781fe01000000db00483045022100bd159c6585498e747c4f0c5d9bd82788635e39460fb0761ae198dafd0be5ece002200b31ec96603b1ca5e64dfb6ada59ed7be2746dad4c5f00eaba9ecef52c35c1a601483045022100c9793d7742d54b3bd5520a3ce4a4e7cb8ca46e564e72154b23cd97784c2dcc2902200e1022a8a195c4b6976adcda6c922818f28237d8c68dcf100282225665728ec20147522103a703c611b20fc32ab31517b381fa0b87d08689f3cbdd60a62dbf8ac75c758d5d210269f6d9762c9ad3e3d9dde319713fdf06d810d2ac906c3fe6cd2e39501bdab3f952aeffffffff02e457f5050000000017a914f928a995e7f2ae31797a72732ae6f60ab18d3da28700e1f505000000001976a9143858c9857ea19da4857dc1b5e74b08df82fc4c1588ac00000000

**Comment by ecdsa** [comment] 2016-12-06 11:34
yes, that's what I need, except that this transaction is old and the coins have been spent already, so it does not produce the same error message. would be great if you could create a new one, with unspent inputs, that causes this error.

**Comment by djnocide** [comment] 2016-12-06 11:46
we don't have any more coins in the wallet. We had to use them.

**Comment by fauno** [comment] 2016-12-06 13:57
we were affected by this too, i'll post a transaction later :)

**Comment by fauno** [comment] 2016-12-06 23:31
is there any way to remove metadata from it?

**Comment by ecdsa** [comment] 2016-12-07 04:45
there's no metadata in raw transactions.

**Comment by neocogent** [comment] 2016-12-09 14:49
I've just had this error msg today. It was for a tx created with Ledger HW1 wallet. It was a test tx while trying to see how the new HW1 worked. I successfully entered 2nd factor codes and appeared to be signed fine. Then I clicked broadcast and got this error. The full content of eror window is below and I think this includes raw tx hex.

I thought was error with HW1 but then googled and found this issue. Hope this helps.

```
error: The transaction was rejected by network rules.(16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element))
[010000000178e5a0fc3f69108df5fa3704aa8ac53b4b02d2e493f3e2e164442ad6fd4dacbb000000006b483045022100d7705495b45065f39ee6a5915671e32b8e6af0b93a6f469061d6ca33444d9dbd02203116f2f8ba672e341df2e08b873db084b0a69c3e53936a361c56bc455cf9d754012103448deaeae083cd89f2b0941cd9fb841f44945a36d5b258b567177fe9cceb5180ffffffff02a0860100000000001976a914bfffa5354e1a3dcb68e7a32404e54d9104db65a988acd0c30200000000001976a914053914841199faa72bb1da2586072187d726b78b88ac00000000]
```

**Comment by ecdsa** [comment] 2016-12-09 18:55
@neocogent @btchip  could that be caused by an old HW1 firmware?

**Comment by btchip** [comment] 2016-12-09 23:24
if it worked the second time no

**Comment by neocogent** [comment] 2016-12-10 07:34
Brand new HW1 and I used getFirmwareVersion to confirm LW 1.0.1

I've sent  a couple more txs, one regular and one multisig, after that and both went ok. I suspect maybe something different in data flow between "Send" and "Preview", "Sign", "Broadcast". Just guessing though as both ways have now worked.

**Comment by ecdsa** [comment] 2016-12-10 12:58
@btchip IIRC the old hw1 signing process used to be non-deterministic, no?

**Comment by stiell** [comment] 2016-12-30 04:12
Looking at @djnocide's tx and some of my own, the problem seems to be that the public keys are not correctly sorted when generating the redeemScript (should be lexicographically sorted according to BIP45/BIP67), causing a mismatch between the hash of the generated redeemScript and the hash given in the corresponding scriptPubKey.

I managed to work around the issue by restoring the wallet from the master public keys and using the restored wallet to make an unsigned tx. Not sure if that worked just by chance (master public keys ordered differently causing a different ordering in the redeemScript?) or if there is something wrong in the old wallet file (bug in converting from 2.6.x format?).

Here is @djnocide's tx broken up into segments and indented for easier parsing. Notice how the redeemScript (the last, 0x47-byte push in the 0xdb-byte scriptSig) pushes the pubkey 03a703... before pushing 0269f6..., meaning the keys are not lexicographically sorted.
```
01000000
01 082f265c42e64d741ca20e1f07b42bf0c9b5f6f874632ac3
     5a042bf698a781fe
   01000000
   db 00
      48 3045022100bd159c6585498e747c4f0c5d9bd82788635e39
           460fb0761ae198dafd0be5ece002200b31ec96603b1ca5e6
           4dfb6ada59ed7be2746dad4c5f00eaba9ecef52c35c1a601
      48 3045022100c9793d7742d54b3bd5520a3ce4a4e7cb8ca46e
           564e72154b23cd97784c2dcc2902200e1022a8a195c4b697
           6adcda6c922818f28237d8c68dcf100282225665728ec201
      47 52
         21 03a703c611b20fc32ab31517b381fa0b87d08689f3cbdd60
              a62dbf8ac75c758d5d
         21 0269f6d9762c9ad3e3d9dde319713fdf06d810d2ac906c3f
              e6cd2e39501bdab3f9
         52
         ae
   ffffffff
02 e457f50500000000
   17 a914f928a995e7f2ae31797a72732ae6f60ab18d3da287
   00e1f50500000000
   19 76a9143858c9857ea19da4857dc1b5e74b08df82fc4c1588ac
   00000000
```

**Comment by ecdsa** [comment] 2016-12-30 06:41
thanks, I had not noticed that

**Comment by ecdsa** [comment] 2016-12-30 07:17
this could be a duplicate of bug #1975 (fixed in version 2.7.9)
@stiell does the problem persist if you regenerate your wallet?

**Comment by stiell** [comment] 2016-12-30 17:46
The wallet regenerated from the master public keys seems to consistently create valid transactions. The main difference between the original and regenerated wallet file is that the pubkeys have been reordered (apparently according to some specific xpub ordering). Removing the pubkey entries from the original wallet file also results in a wallet with presumably correct pubkey ordering.

96016a9 apparently didn't catch the wrong pubkey ordering in this wallet.

**Comment by ecdsa** [comment] 2016-12-30 17:49
@stiell thanks for the info. any idea why 96016a9ee8d6e5198659e682d823fbe44e140f98 failed to get activated?

**Comment by stiell** [comment] 2016-12-30 18:57
I just regenerated the wallet in 2.6.4 and imported it in 2.7.12. The resulting pubkey ordering in the updated wallet file is different from the wallet regenerated in 2.7.12. It keeps the pubkey ordering from 2.6.4, apparently causing a mismatch between pubkey ordering and xpub ordering.

**Comment by ecdsa** [comment] 2016-12-31 09:37
ok, anyone else having this issue, please regenerate your wallet and report here.

**Comment by fauno** [comment] 2016-12-31 14:19
with which version?  i regenerated my wallet with 2.7.12 back when i
came here :)

(sorry for not posting the tx, i got busy)

-- 
P)

**Comment by ecdsa** [comment] 2017-01-01 11:01
@fauno try to make sure you regenerate all the cosigners

**Comment by madshell** [comment] 2017-01-03 09:49
we got the same problem upgrading from 2.6.4 to 2.7.12 with a 2-of-5 multisig wallet
wallets are upgraded without notice in the new format that is not backward compatible

wallet is readable / decryptable in 2.7.12 so with the seed + master public keys we managed to restore the wallet and the problem is gone.

**Closed** 2017-02-26 07:37 UTC
