### ISSUE TITLE
Electrum error - 'message': 'the transaction was rejected by network rules.

### ISSUE THREAD

**Issue by guaji61** [spesmilo/electrum#4462] opened 2018-06-25 19:00 UTC
Below is the error - this error made me to LOSE the funds - need help - I have the seed but because of the error I can't save the private keys!

This is not correct because the seed need to open my funds - the same electrum-3.1.2-portable program receives payments - but ONLY the wallet with the funds - DISAPPEARED!

error: {'message': 'the transaction was rejected by network rules.\n\n16: mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation)\n[01000000011b3d1c0cce91507fa7003f5d3c24e2fef200e303eb2de10bcff22f50cd665759000000006a473044022030fc5f836e7fc31f004850e5cfbaa59d5b48e182ad743b826f7814c4583ffe54022060d82df810f3aa09d86974d251f378b88ec83533685775fd8c6718c05d4d34e4012103a0328a951557897d0782945a7ca0e027c218e0387f478e07c2bd603d5280bfa6fdffffff02d0470000000000001976a91450aed898bf35087ea331cfabc3f03ed2dd1a797888ac66792b02000000001976a9149f321cac8e09435ca7856e26f6023966acd1c3a788ac1f000800]', 'code': -1}

**Comment by SomberNight** [comment] 2018-06-25 19:15
Hi. It's hard to understand the situation from your description.
What do you mean you can't save the private keys?
What do you mean by
> ONLY the wallet with the funds - DISAPPEARED

Have you tried restoring the wallet from seed words? Or is that what you are describing? Do you recognise the addresses in the restored wallet?

**Comment by guaji61** [comment] 2018-06-25 19:37
I already restored the wallet using the seed words - but as I said - only the wallet with the funds - DISAPPEARED!

Its hard to understand also this situation - but its exactly as I described. I received the funds - then I tried to send the funds to another wallet.

I got the error:

error: {'message': 'the transaction was rejected by network rules.\n\n16: mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation)\n[01000000011b3d1c0cce91507fa7003f5d3c24e2fef200e303eb2de10bcff22f50cd665759000000006a473044022030fc5f836e7fc31f004850e5cfbaa59d5b48e182ad743b826f7814c4583ffe54022060d82df810f3aa09d86974d251f378b88ec83533685775fd8c6718c05d4d34e4012103a0328a951557897d0782945a7ca0e027c218e0387f478e07c2bd603d5280bfa6fdffffff02d0470000000000001976a91450aed898bf35087ea331cfabc3f03ed2dd1a797888ac66792b02000000001976a9149f321cac8e09435ca7856e26f6023966acd1c3a788ac1f000800]', 'code': -1}

I tried many times to send the funds - but I this error rejection was every time. After a few hours simply - the funds DISAPPEARED!

The funds are still there in the wallet because I test it and the wallet still receives funds - but this wallet DISAPPEARED from my electrum-3.1.2-portable!!!

**Comment by guaji61** [comment] 2018-06-25 19:38
So, the wallet with the funds DISAPPEARED !

**Comment by guaji61** [comment] 2018-06-25 19:42
Do you recognise the addresses in the restored wallet? - NO - this is what I am trying to say - after restoring - the wallet DISAPPEARED !

**Comment by AbdussamadA** [comment] 2018-06-25 19:48
>Do you recognise the addresses in the restored wallet?

This is from my site I'm guessing. So did you try the other things listed [there](https://bitcoinelectrum.com/frequently-asked-questions/#why-does-restoring-my-wallet-from-seed-lead-to-a-different-wallet)? What version of electrum are you using? What is the wallet type under wallet menu > information?

**Comment by guaji61** [comment] 2018-06-25 19:50
electrum-3.1.2-portable and tried to restore in the same version and also to electrum-3.1.3

**Comment by AbdussamadA** [comment] 2018-06-25 19:51
try the things listed in that link i posted above

**Comment by guaji61** [comment] 2018-06-25 19:53
Wallet type: standard

**Comment by guaji61** [comment] 2018-06-25 20:02
Thanks! Got the link - I will read it and try to follow the information's.

**Comment by guaji61** [comment] 2018-06-25 20:15
I switched the servers and waited until the servers synchronized - no success !

**Comment by SomberNight** [comment] 2018-06-25 21:53
> I already restored the wallet using the seed words - but as I said - only the wallet with the funds - DISAPPEARED!

By "wallet" do you mean "address"?
So just to clarify, is it the case that when you restore from seed words all your addresses and transaction history is found; except for a single address?

**Comment by guaji61** [comment] 2018-06-25 21:58
Yes - correct. Its about the "address" and when restore from seed words all my addresses and transaction history is found; except for a single address - the one with the funds!

**Comment by AbdussamadA** [comment] 2018-06-26 04:19
did you import private keys into your wallet in the past? that would explain the missing address (assuming you already tried increasing the gap limit)

**Comment by SomberNight** [comment] 2018-06-26 13:57
Could you make a screenshot of the "Addresses" tab with the weird address visible in your original wallet file; and the same screenshot of the "Addresses" tab in the restored wallet file?

**Comment by guaji61** [comment] 2018-06-26 21:34
I never imported private keys - this was a new wallet - it was first transaction. I have attched the photo - initial electrum and restored.

![photo electrum](https://user-images.githubusercontent.com/40578311/41940575-1c27a5bc-7924-11e8-89a2-47cb35bbdc6f.jpg)

**Comment by SomberNight** [comment] 2018-06-26 23:38
You said that there is an address that is present in the original wallet but not in the restored wallet. I can't see it. There is nothing out of ordinary in your picture.

**Comment by guaji61** [comment] 2018-06-27 15:52
I will explain again:

1. I created new seed and new wallet - first photo ( the photo was made after the error).

2. I received a payment at that time was $2700 value.

3. After I received - I tried to send the $2700 to another person.

4. When I clicked send I got this error:

error: {'message': 'the transaction was rejected by network rules.\n\n16: mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation)\n[01000000011b3d1c0cce91507fa7003f5d3c24e2fef200e303eb2de10bcff22f50cd665759000000006a473044022030fc5f836e7fc31f004850e5cfbaa59d5b48e182ad743b826f7814c4583ffe54022060d82df810f3aa09d86974d251f378b88ec83533685775fd8c6718c05d4d34e4012103a0328a951557897d0782945a7ca0e027c218e0387f478e07c2bd603d5280bfa6fdffffff02d0470000000000001976a91450aed898bf35087ea331cfabc3f03ed2dd1a797888ac66792b02000000001976a9149f321cac8e09435ca7856e26f6023966acd1c3a788ac1f000800]', 'code': -1}

5. I tried to send again and still got the error.
6. After a few hours the money $2700 and the "BTC address" when it was the money received $2700 - just DISAPPEARED.

7. I restored the wallet using the seed words saved. The money still not don't showed and also the "BTC address" - DISAPPEARED from the list.

Also I already changed servers host - no success.

I hope you understand my explications. 

Someone knows how I can contact people from electrum team? 

Thanks

**Comment by fr3aker** [comment] 2018-06-27 19:20
for reference, this is the transaction used as an input in the failed tx: https://blockchain.info/tx/595766cd502ff2cf0be12deb03e300f2fee2243c5d3f00a77f5091ce0c1c3d1b

address "1A3rvBfd48efYgrgXeXmvLgTmZiSQjyKPE" indeed does not seem to belong to the wallet. Two possiblitilies:
1. you downloaded an infected version of electrum. Where did you download it from?
2. you copied the wrong address

**Comment by guaji61** [comment] 2018-06-27 19:44
Yes this is the address who received the funds - 1A3rvBfd48efYgrgXeXmvLgTmZiSQjyKPE

It was downloaded from https://electrum.org at that time. Strange things is that I copied the address 1A3rvBfd48efYgrgXeXmvLgTmZiSQjyKPE from Receiving and received the funds - so it was a correct address!

Only when tried to send the funds I got this error!

**Comment by guaji61** [comment] 2018-06-27 19:47
When I created the new wallet and new seed words - I just put the click on the Receive and copied the address - 1A3rvBfd48efYgrgXeXmvLgTmZiSQjyKPE. 

I received the money from the person - https://blockchain.info/address/1A3rvBfd48efYgrgXeXmvLgTmZiSQjyKPE

Everything was normal as every time - then tried to sent the money to another address and just got the error!

**Comment by guaji61** [comment] 2018-06-27 19:49
After I tried a few times - I changed the servers - the address 1A3rvBfd48efYgrgXeXmvLgTmZiSQjyKPE just DISAPPEARED - I send after that $1 and the address receives payments!

**Comment by fr3aker** [comment] 2018-06-27 20:14
When exactly did you download electrum? Please check your browser history for the download link.

**Comment by guaji61** [comment] 2018-06-27 20:17
April 18, 2018

**Comment by guaji61** [comment] 2018-06-28 14:55
For sure the address was copied from the Receive! 

So, please someone let me know what can I do in this case? because people can have a lot money in their electrum  programs and with a simple click and error - they can lose a lot of money. 

Where is the electrum team ? someone knows something about a contact from electrum?

**Comment by guaji61** [comment] 2018-06-28 14:55
Until now I lost $2,700.

**Comment by fr3aker** [comment] 2018-06-28 15:09
Since you insist you downloaded electrum from the official website I can only blame your lost funds on user error. If, after careful re-consideration, you deem it possible to have downloaded an infected version from a different place you should file a report with the police.

Electrum is open source software. It has a project maintainer and some very active contributors but nothing you could call a "electrum team", not in the sense of support or liability. Everything you do with this software you do so at your own risk.

Regardless of what exactly happened in your specific case, there is nothing anyone here can do to help you. The address that received your bitcoins is not part of your wallet/seed and that really makes a dead end.

If you have any specific suggestions on how to improve the software you can open a feature request here on github.

**Comment by guaji61** [comment] 2018-06-28 15:16
So, its my fault that I downloaded the electrum version infected from their official website?

**Comment by fr3aker** [comment] 2018-06-28 15:21
Let me re-phase what I wrote above. If you have strong indications of having been used an infected electrum version you should file a police report. However, while not impossible, it seems very unlikely to me that you downloaded an infected version from the official website.

**Comment by guaji61** [comment] 2018-06-28 15:48
I am 100% sure it was downloaded from https://electrum.org - I use electrum from about 2 years. I understand the idea that its an open source software -  but no one has the guarantee that the program downloaded from their official website will not have the same problem. So, at any moment we can lose the funds.

**Comment by AbdussamadA** [comment] 2018-07-01 05:04
You said above that you created a new wallet and then received funds into it. When creating the new wallet did you set a password and did you choose to encrypt the whole wallet file? If you don't remember open that original wallet file using electrum and go to file > save copy to save it somewhere you can find it. Then open it in a plain text editor like notepad and tell us if you see random characters or JSON code? JSON code looks like this btw: http://termbin.com/j02n

**Comment by guaji61** [comment] 2018-07-01 19:10
Here the address: 

{
    "1H4cnH5GQAAavofvmekVeezZjetYrMCN18": "p2pkh:L5dooQCmABKAHGJVZbhx5bxMy3yTMsz6ks1rvKBWH3LPmqx4MvG9",
    "1JJL5ya1fmgv2WsHDE3MnvTwxQT1ejJYnY": "p2pkh:L134UJgz9wR9VNWGZKjb43vLacr5QUPfvJiEniKU3jZ7jcMAmLGv",
    "1AQ6rMCJm1YPMVkyiHcYBiAr3P4KZCTSVQ": "p2pkh:KyZFEUZAQsd3Qtk3XhirnU4iTDsrpd9SzYfbq8dZ7pGRq5YwSfi6",
    "1FoxzkRZmNhcGKQjp2vKcpQevC7EnW9nkA": "p2pkh:L3sq7ZEguEqgZAxbjPm2X37WbRDgR1BhySi1xkUcLz5uTzN62MFn",
    "1PqjBc9wnLPZXF7KyjtABqx5Px2JFfWULA": "p2pkh:L1XVkLB5JQXkw5cjBbiX2TRYSRjirXX7f6McqsEXB9g6YjJ53tS8",
    "13U58PgZ5myqSi7PmEGwYWA8TrX9ay3dpN": "p2pkh:L1GzgyD1nsn3AQkPA8T8znSgCZ76c7gLWrwuqJSCpqwx9VYVpaYw",
    "1AMFub1N4zPNgLHmXLWD2Cd1p7NjXrHSHt": "p2pkh:L4PGJs5edQZ7QoTxAqizdgYBMh2ssFXKTWfceMBdYN5zh6pF6YLt",
    "1ELnRaVF5Sg2xRgwhZfnnpGR6LJqeUxVuP": "p2pkh:Kx8ZadQpevWM7VUwHdV4MwunVWBdWBvdf7uUBZWeNq1q3MKGuvvc",
    "1CANpx4bHHfvgCnqeWYEHLjjkG63d9BzrV": "p2pkh:L1epjTzizpbsZfYYxFkcuDVt5Ynskqh5TnssDRCRpAzpobqbE8XS",
    "132uCLdoPZF54m9p9V8EvmbnjWWioXZDoT": "p2pkh:KwEwDCCjwbSdEi1mtjHV8atkE1MyaqfZZkxRj6idphbd1aqJSeva",
    "1BXc2XDkr9Ga7Ap82VJb3Ndfr7UfNqBJTK": "p2pkh:L5G3YY5SfpSp5dgUnWVxDFyXxDyAADmi3f2gVQdS14RR9yPNmMGe",
    "1BzuPUNfUN7zLQJQ1xgtE454WUa71h4M4W": "p2pkh:KxUEeTYuJwDiyk8UAp5yovDdPjLXYtU7kdWGdTpADDADowomJ5PK",
    "18kJkvKzjNaviKgEEJSXtCU88sXvCZkV5H": "p2pkh:KykRk5DcMLqSMaYDgxueZjhDqv9FVkWwbap1gwg2DUWuRMTHpLyz",
    "1DHrWo5oszSQTU4Wwn3tjeRf9ZiapUB7f8": "p2pkh:KxajVV4HbEQLYRe4RfeLxEw6HeBn8Qqnr6ZgMW9FRCD1Zm2tMwh4",
    "19xbMkoZqR3cSAhHq6rrzCa1Z6Kmku1c9y": "p2pkh:L2LLdQ8JKeivuq5GyETutKPSrnaKoB4MZ48DPi1nfopYanyy5roz",
    "16JdanaqYPwKp2w6KzdSRKzV1Gn84eKvmC": "p2pkh:L3fch8HB2F8XVMx86ApuuXb4cdtBmmdUa6VsM1tTyfhuYN6Xx4XM",
    "1KhgmFS7yaGJ2hGE5n5uxg4ArAQsG27S87": "p2pkh:KzPVnR8QZuvyS3wZN3ebsF3ZFzJPSNAAv3gbWvQR21ZVJSAwFDLi",
    "19Hk2JtMZHQr357xNNPBM7r2XBLyYEEbJ9": "p2pkh:KxGMZxuK5qeZYd4XQdp6BDvpZCtUhgMEErqRPa28YR2SVSYMVQMk",
    "1EKSW3z9xxrDUWkrHq9L8mCTnFXBWR6sEq": "p2pkh:L2uw8R57zSkh6U4LbhKZD98LnkkPVTzSNU6R2CJpRXby3mYuSobn",
    "17unjMF8vv751z7vGcvGEhRphvCkqzU21B": "p2pkh:KzC1Q368uvU4HgaH6pbzpfT8GZMQmaVrVV9h8LPWrKX1FfjN4YhW",
    "1FunuXmVqgLi9fVyNWfuQRZ9TUKqENxQwb": "p2pkh:KySqzpFnCTyHS5rWRahmxhcEfhFVfAC7XqSuVLdQXUhJEaqrSHX1",
    "15M4mNU5dtoEfDfUWcn6JxNYAotReXAvcz": "p2pkh:L51mspaHrW84LywqVnrXgMq6sYFDA877mvLQb9rKG6GX1FhYJNcj",
    "1H9YRnR72baQhz75Qk5eWMQoCS4m1FRitK": "p2pkh:Kznj6RfxLY3EPWDpV11X56tnhtDi5gLtkGFFnU5gyDHK4RCdcj5J",
    "15GkJRgHT6bzs1Gnn4E9rmMsCUdhwFAgqA": "p2pkh:Kx7S6zXa2awXSjdMhHHFiK2Tj67qHcQWZv3J4N9CZvmR5Msuj5oS",
    "1BmYdC5tbERXgKvrgzeDGYTWzSR9gDdWPv": "p2pkh:L2G6cYor9mfGAGUCbGLve2TgzBAUfhwqbKB3dDSAQCmhhHcPmW4H",
    "12MVYvhoowyNa9bdRNVHh1fj8Yr6xfVke9": "p2pkh:KyKDRkzjRvmMKMa7WVZX93cF42roYmngjis18sHrsVtKL3n5HYiH",
    "1DWbLThG57SSg5Kc9b99gwN1aqjP3oCMzE": "p2pkh:L4WTNt7AeNRQutGy92yd5tdkpkZJyiQgYMfsDrFS7cfBiUzbDs6L",
    "1AwCPZszo6z4didtMGnyomE2beUVPmpwwz": "p2pkh:L4XDWDVGGZ1PtLe3ndNXi2er7z8CKYwTGD41f859rj6h4Ry6RxF4"
}

But the one who received the funds is not here: 1A3rvBfd48efYgrgXeXmvLgTmZiSQjyKPE

**Comment by fr3aker** [comment] 2018-07-01 19:15
You just posted the private keys for your wallet. Consider all funds therein compromised. Do not ever use this wallet again. If you have any addresses with funds immediately transfer them to a new wallet.

**Comment by guaji61** [comment] 2018-07-01 19:34
Don't worry - I never used this wallet again ! I just want to clarify my situations. Also, the address 1A3rvBfd48efYgrgXeXmvLgTmZiSQjyKPE is not here ... so!

**Comment by AbdussamadA** [comment] 2018-07-02 11:39
I just wanted to know whether the wallet file was encrypted or not. I didn't want a private key export. 

The reason i asked if the wallet was encrypted or not is because if it wasn't then it's quite trivial for malware to inject it's own address in your wallet file if it manages to get write access to it. It'll appear as if that address is a part of your wallet but your wallet won't have the private key for that address so it won't be able to sign spending transactions. As example I created a wallet like that which i'm attaching to this message. You can open it via file > open. Try spending from it!

[standard_wallet.txt](https://github.com/spesmilo/electrum/files/2155025/standard_wallet.txt)

**Comment by SomberNight** [comment] 2019-02-06 19:33
Please take a look at potential explanation in #5082
Does that seem feasible?

Note: OP was using portable version of Electrum so it seems likely the file was stored on a USB flash drive.

**Comment by ecdsa** [comment] 2019-02-08 08:47
closing this, because the issue is explained.  please follow-up in #5082

**Closed by ecdsa** 2019-02-08 08:47 UTC
Labels: maybe-malware, question
