### ISSUE TITLE
Big chunk of JsonRPC commands not working! v2.6.3

### ISSUE THREAD

**Issue by RealBugReporter** [spesmilo/electrum#1756] opened 2016-04-09 23:53 UTC
#Hello,

[http://docs.electrum.org/en/latest/merchant.html#jsonrpc-interface](http://docs.electrum.org/en/latest/merchant.html#jsonrpc-interface)

Tried all 3 of your tutorials curl commands and it is not working (here is output):
`
root@post2:~# curl --data-binary '{"id":"curltext","method":"getbalance","params":[]}' http://127.0.0.1:7777
{"error": {"message": "Server error:   File \"/usr/local/lib/python2.7/dist-packages/electrum/commands.py\", line 288, in getbalance | AttributeError: 'NoneType' object has no attribute 'get_balance'", "code": -32603}, "jsonrpc": "2.0", "id": "curltext"}
`

`
root@post2:~# curl --data-binary '{"id":"curltext","method":"listaddresses","params":{"funded":true}}' http://127.0.0.1:7777
{"error": {"message": "Server error:   File \"/usr/local/lib/python2.7/dist-packages/electrum/commands.py\", line 482, in listaddresses | AttributeError: 'NoneType' object has no attribute 'addresses'", "code": -32603}, "jsonrpc": "2.0", "id": "curltext"}r
`

`
root@post2:~# curl --data-binary '{"id":"curltext","method":"addrequest","params":{"amount":"3.14","memo":"test"}}' http://127.0.0.1:7777
{"error": {"message": "Server error:   File \"/usr/local/lib/python2.7/dist-packages/electrum/commands.py\", line 566, in addrequest | AttributeError: 'NoneType' object has no attribute 'get_unused_address'", "code": -32603}, "jsonrpc": "2.0", "id": "curltext"}
`

Hey, but atleast this one works for me:
`
root@post2:~# curl --data-binary '{"id":"curltext","method":"version","params":[]}' http://127.0.0.1:7777
{"jsonrpc": "2.0", "result": "2.6.3", "id": "curltext"}
`

**Comment by ecdsa** [comment] 2016-04-10 06:59
duplicate of #1731, aleady fixed

**Closed by ecdsa** 2016-04-10 06:59 UTC
