### ISSUE TITLE
Single instance instead of new windows?

### ISSUE THREAD

**Issue by HerHde** [spesmilo/electrum#1147] opened 2015-04-18 23:38 UTC
Ahoj,
is it possible to set the client to a "single instance only"-mode? Always when I click on a `bitcoin:`address, it opens up a new window, so I get some trouble when I've added new contacts etc and close another window without this contact later.

I run v 2.0.4 on Linux (Mint Cinnamon, so the GUI GTK I guess)

**Comment by ecdsa** [comment] 2015-04-19 05:59
this is a duplicate of #971
please check existing issues before submiting yours

**Closed by ecdsa** 2015-04-19 05:59 UTC
