### ISSUE TITLE
Electrum 4.0.4 not starting on macOS 11 beta

### ISSUE THREAD

**Issue by 634-5789** [spesmilo/electrum#6706] opened 2020-11-02 11:54 UTC
Hi all

Installed by replacing the old version (3.x), the app does not start. It shows the icon but nothing happens. How can I troubleshoot this?

Thanks for any help.

**Comment by SomberNight** [comment] 2020-11-02 13:37
Did the old version of Electrum start on macOS 11?

anyway, duplicate of https://github.com/spesmilo/electrum/issues/6461
see comments there; current workaround is to run from source

**Closed by SomberNight** 2020-11-02 13:37 UTC
