### ISSUE TITLE
Feature request: add confirm receive address on a hardware device

### ISSUE THREAD

**Issue by Raulo** [spesmilo/electrum#3974] opened 2018-02-26 07:58 UTC
Currently, Electrum requests the hardware confirmation while sending. Recently, due to the threat of receive address spoofing, Ledger (and I guess also Trezor) has added receive address confirmation. It would be great if Electrum could also do the same.

**Comment by ecdsa** [comment] 2018-02-26 10:17
closing, duplicate of #3364

**Closed by ecdsa** 2018-02-26 10:17 UTC
