### ISSUE TITLE
Bad error message using ledger without supporting libraries

### ISSUE THREAD

**Issue by keis** [spesmilo/electrum#3204] opened 2017-11-03 15:14 UTC
When trying to sign (tx and message) with my ledger I was presented with this mysterious message, root cause turns out to be missing `hid` and `btchip-python` packages. But it would be good if electrum could guide me to that solution.

```
Traceback (most recent call last):             
  File "/usr/lib/python3.6/site-packages/electrum_gui/qt/util.py", line 581, in run            
    result = task.task()                       
  File "/usr/lib/python3.6/site-packages/electrum/wallet.py", line 1344, in sign_message       
    return self.keystore.sign_message(index, message, password)                                
  File "/usr/lib/python3.6/site-packages/electrum_plugins/ledger/ledger.py", line 226, in sign_message
    client = self.get_client()                 
  File "/usr/lib/python3.6/site-packages/electrum_plugins/ledger/ledger.py", line 198, in get_client
    return self.plugin.get_client(self).dongleObject                                           
  File "/usr/lib/python3.6/site-packages/electrum_plugins/ledger/ledger.py", line 510, in get_client
    client = devmgr.client_for_keystore(self, handler, keystore, force_pair)                   
  File "/usr/lib/python3.6/site-packages/electrum/plugins.py", line 395, in client_for_keystore
    handler.update_status(False)               
AttributeError: 'NoneType' object has no attribute 'update_status'
```

installed from 3.0.0 tar.gz

**Comment by ecdsa** [comment] 2017-11-03 15:20
indeed. I suppose you created the wallet with version 2, which had the ledger library?

**Comment by keis** [comment] 2017-11-03 15:22
yes, the wallet was created with an older version running on python2

**Comment by neocogent** [comment] 2017-11-03 17:20
I was doing testing on 3.0.0 today with ledger plugin. Looks like needed command is,

sudo pip3 install btchip-python websocket-client

After that I could use my Nano and pair with mobile phone again. However, in my case I have not been able to complete an authentication for a few months since recent segwit ledger firmware update. I think that may be specific to my Android version being old as in Electrum it behaves normally but my phone doesn't respond to auth request. I haven't been able to test further yet.

As for what to do when the packages aren't present - it used to prompt the user but maybe that isn't being caught for sign_message and only for txs?

**Comment by ecdsa** [comment] 2017-11-05 10:41
note: this is a duplicate of #2562

**Closed** 2017-11-05 11:50 UTC
