### ISSUE TITLE
failing to build android apk for x86_64 arch

### ISSUE THREAD

**Issue by shuaiLiWang** [spesmilo/electrum#5508] opened 2019-07-13 01:24 UTC
![x86](https://user-images.githubusercontent.com/9347690/61165210-ef760780-a54f-11e9-8337-a2ae98b135dc.png)

**Comment by shuaiLiWang** [comment] 2019-07-13 01:36
i just change "android.arch = x86_64" in electrum/gui/kivy/tools/buildozer.spec
when android.arch = armeabi-v7a ,it ok.i get apk sucessuffly

**Comment by SomberNight** [comment] 2019-07-13 02:06
I'm afraid we've never tested building for other architectures before.

Is it only the libsecp256k1 recipe that fails to build? Try removing it from requirements here:
https://github.com/spesmilo/electrum/blob/16f56ccbf008cdb48d3391c732c55b43db6706e9/electrum/gui/kivy/tools/buildozer.spec#L45

**Comment by shuaiLiWang** [comment] 2019-07-13 06:55
> I'm afraid we've never tested building for other architectures before.
> 
> Is it only the libsecp256k1 recipe that fails to build? Try removing it from requirements here:
> https://github.com/spesmilo/electrum/blob/16f56ccbf008cdb48d3391c732c55b43db6706e9/electrum/gui/kivy/tools/buildozer.spec#L45

it ok, no have other issue.i got the apk for x86_64 arch.thanks

**Comment by shuaiLiWang** [comment] 2019-07-13 07:01
> I'm afraid we've never tested building for other architectures before.
> 
> Is it only the libsecp256k1 recipe that fails to build? Try removing it from requirements here:
> https://github.com/spesmilo/electrum/blob/16f56ccbf008cdb48d3391c732c55b43db6706e9/electrum/gui/kivy/tools/buildozer.spec#L45

Will this lead to other problems？ libsecp256k1 be used in many places

**Comment by SomberNight** [comment] 2019-07-13 18:57
> no have other issue.i got the apk for x86_64 arch

Ok, good to know the issue is only with libsecp256k1.

libsecp256k1 is currently an optional dependency; I was mostly suggesting you try without it as part of troubleshooting. All EC signing and verifying operations are a lot slower without.

**Comment by shuaiLiWang** [comment] 2019-07-26 05:49
please see https://github.com/spesmilo/electrum/issues/5508#issuecomment-511145845 
thks！！！

**Comment by shuaiLiWang** [comment] 2019-07-26 05:49
> > no have other issue.i got the apk for x86_64 arch
> 
> Ok, good to know the issue is only with libsecp256k1.
> 
> libsecp256k1 is currently an optional dependency; I was mostly suggesting you try without it as part of troubleshooting. All EC signing and verifying operations are a lot slower without it.

please see #5508 (comment)
thks！！！

**Comment by ecdsa** [comment] 2019-09-10 07:11
closing; we do not have official apk bulds for x86_64

**Closed by ecdsa** 2019-09-10 07:11 UTC
Labels: OS-android, build/packaging
