### ISSUE TITLE
Low fee - why?

### ISSUE THREAD

**Issue by szymon1051** [spesmilo/electrum#2211] opened 2017-02-28 15:21 UTC
I set the slider with a fee of one to the left and so far it was all about. Just yesterday came out a transaction with a small fee. I do not know why the other went normally just set the slider.

Version 2.7.12 now updated to 7.2.18.

On 02/07/18 I had to turn off the "Use dynamic fees" after the program back on and turn on the "Use dynamic fees" and restart again. I did it after that charges accordingly because they have taken up the renovation were the charges which have written "low fees".

This transaction https://blockchain.info/tx/03da9e40567b1c5883d1657ff28c2cb7d4dea70375c4cf526aa5d053c2cdcbfe come out sometime? I can use it when "Enable Replace-To-Fee" if it was not previously included?

/translate google below orginal text

Ustawiłem suwak z opłatą o jedno w lewo i do tej pory było wszystko ok. Tylko wczoraj wyszła transakcja z małą opłatą. Nie wiem dlaczego jak inne poszły normalnie z tak samo ustawionym suwakiem. 

Wersja 2.7.12 teraz zaktualizowana do 2.7.18.

W 2.7.18 musiałem wyłączyć "Use dynamic fees" potem program, znów włączyć i włączyć "Use dynamic fees" i ponownie zrestartować. Zrobiłem to po żeby opłaty się odpowiednio pobrały bo po aktualizacji były opłaty przy których pisało "low fees".

Ta transakcja https://blockchain.info/tx/03da9e40567b1c5883d1657ff28c2cb7d4dea70375c4cf526aa5d053c2cdcbfe wyjdzie kiedyś? Moge przy niej użyć "Enable Replace-By-Fee" jeżeli nie było wczesniej włączone?

**Comment by bauerj** [comment] 2017-02-28 17:24
What does "zaczytały" mean?

I understand that you used Electrum to create that transaction. The fee looks like the dynamic fee feature was disabled at the time of the transaction. Is that correct?

The transaction you linked will be confirmed in a few hours.

**Comment by szymon1051** [comment] 2017-02-28 19:17
Generally, the point is that I set the slider and it does not budge charges and yesterday around midnight generated transactions me with a small fee and thus waited more than 12 hours to confirm.

On computer where transation was generation after upgrade fees load correct, but i do not know what happend yesturday when i send BTC.

On other computer where i have electrum i upgrade too and no want load correcty i see fees were wrote "fees low". I turn on electrum and left for few hours, but fees no change. Only turn off "Use dynamic fees" and electrum after that turn on electrum with "Use dynamic fees" and restart electrum, after that load fees correct.

"zaczytały" = load

**Comment by ecdsa** [comment] 2017-03-02 08:50
I think the issue is that dynamic fees are not active until the fee estimates have been received by the client. until then, the wallet silently uses static fees.

**Comment by ecdsa** [comment] 2017-03-02 10:11
fixed in 9dde9971da83f146e30f7685a70578cfb3351372

**Closed by ecdsa** 2017-03-02 10:11 UTC
