### ISSUE TITLE
Please provide build instructions that do as little as possible on the host machine

### ISSUE THREAD

**Issue by Giszmo** [spesmilo/electrum#7417] opened 2021-07-20 00:10 UTC
Reading the 4.1.5 build instructions for Android I'm supposed to run the 68 LOC `contrib/android/build.sh` which calls the 154 LOC `contrib/build_tools_util.sh` and it even requires `sudo` root access.

I compile a lot of APKs for WalletScrutiny.com and no other requires this. Can't that be encapsulated in the Docker scripts so I can run Docker (without root) and it does what it needs to do inside the container?

I'd like to automate reproducibility testing but am reluctant running those scripts as root or actually anything but inside docker containers without a careful review after any change.

**Comment by SomberNight** [comment] 2021-07-20 01:46
Most of `build.sh` is just about setting up docker: it is building the image, potentially doing a fresh clone, and instantiating and running a docker container.

Most of what `build.sh` is doing currently, was in the README previously, to be run by the user manually. We mostly turned the README into a bash script as we created a master script (`contrib/release.sh`) that can build all distributables for all target platforms. So there were two obvious choices: either leave the multi-step manual READMEs for each target platform and duplicate the steps in `release.sh`, or turn the READMEs into build scripts and just call those directly from the `release.sh`.

Some of the fluff in `build.sh` that is not directly invoking docker is due to limitations of docker itself.
- See e.g. (1)
    https://github.com/spesmilo/electrum/blob/d35a68d2d1b2220f25f63d7b1298b419ea76d318/contrib/android/build.sh#L25-L30
    The cp and rm are needed as we want the docker build context to contain `requirements-build-android.txt`. As the requirements files for the different architectures are outside the android folder, there is no easy way to access them from the Dockerfile.
- or see e.g. (2)
    https://github.com/spesmilo/electrum/blob/d35a68d2d1b2220f25f63d7b1298b419ea76d318/contrib/android/build.sh#L54-L62
    the `mkdir` is there as otherwise if the path does not exist, and we try to mount it with `-v` a few lines below, docker will create it with `root` as owner.

Anyway, I will try to do away with using sudo in `build.sh` for the rm and the cp.
We could maybe call docker without sudo if we required the current user to be member of the docker unix group; is that the kind of thing you have in mind?

**Comment by Giszmo** [comment] 2021-07-20 04:30
Thanks for quick reply. I made some progress and have it almost automated using my minimal setup:

```
test() {
  repo=https://github.com/spesmilo/electrum
  tag=$( echo "$versionName" | sed 's/\.0$//g' )
  builtApk="$workDir/app/dist/Electrum-$versionName-arm64-v8a-release-unsigned.apk"
  
  prepare

  # build
  cp contrib/deterministic-build/requirements-build-android.txt contrib/android/
  docker build -t electrum-android-builder-img contrib/android/
  mkdir --parents .buildozer/.gradle
  docker run -it --rm \
        --name electrum-android-builder-cont \
        --volume $PWD:/home/user/wspace/electrum \
        --volume $PWD/.buildozer/.gradle:/home/user/.gradle \
        --workdir /home/user/wspace/electrum electrum-android-builder-img \
        /bin/bash -c "./contrib/android/make_apk release-unsigned;
        $takeUserActionCommand"
      
  # collect results
  result
}
```

* For all other reproducible android apps I could switch to [podman](https://github.com/containers/podman) but Electrum resists as the `Dockerfile` defines both version and sha256 of the base Ubuntu image. That is not supported in podman yet. It's great that you guys pin the base image hash though!
* It's a minor nuisance that the APK versionName is longer than the tag in a non-obvious way. Is it always an extra ".0"? Other teams tag "release-$versionName", "v$versionName" or plain "$versionName".
* This is the first reproducible Android app to have more than one artifact - 32bit and 64bit.

**Comment by SomberNight** [comment] 2021-07-20 11:57
> It's a minor nuisance that the APK versionName is longer than the tag in a non-obvious way. Is it always an extra ".0"? Other teams tag "release-$versionName", "v$versionName" or plain "$versionName".

The apk `versionName` is `APK_VERSION` in `version.py`, at the given git tag you build:
https://github.com/spesmilo/electrum/blob/d8d2c180aafaec1ae9bc68c27a7d780df8de4348/electrum/version.py#L1-L2

It has an extra version number field for historical reasons. Several times in the past, especially when the android app was new, there were android-specific bugs or issues with the apk itself, which were fixed without a corresponding "official" release or even release notes (usually these were either builds from git master without a tag; or just a rebuild of the apk with a clean build environment). The motivation was not to have to re-release for every platform just because there is a bug on Android.

We haven't done this for several years though, and now with reproducible builds we cannot do it anyway.
So, most likely, going forwards, `git_tag+".0" == ELECTRUM_VERSION+".0" == APK_VERSION`; as it is easiest to keep it `.0`.
(It cannot easily be removed as the toolchain we use, python-for-android, calculates the apk `versionCode` from the `versionName`.)

**Comment by Giszmo** [comment] 2021-07-21 00:11
That's great. So my script should work just fine, stripping a final ".0" from the versionName.

My perspective is not "Is the build process deterministic", starting from git. My perspective is "There's an apk on Google Play. Can I reproduce it?", so I unpack the apk, figure out the `appId` and `versionName` and go from there.

> (It cannot easily be removed as the toolchain we use, python-for-android, calculates the apk `versionCode` from the `versionName`.)

You could  add a secondary tag that contains that `.0`. Maybe even make it `android-v4.1.5.0` but again, for my needs no changes are necessary. Stripping the `.0` is easy enough.

**Comment by SomberNight** [comment] 2021-07-21 18:41
> So for my purpose, this issue can be closed. I'm not sure if others have the same concerns when reproducing a binary.

Ok, especially if it's not that important, I don't actually have much time to look into removing the sudo usage...
However, if someone is interested, please have a look. I'll close this issue though.

**Closed by SomberNight** 2021-07-21 18:41 UTC
Labels: build/packaging 📦
