### ISSUE TITLE
Feature: Access settings on first time setup screen

### ISSUE THREAD

**Issue by relativisticelectron** [spesmilo/electrum#6144] opened 2020-05-06 10:36 UTC
Problem (Kivy and qt GUI): It is difficult to create a wallet and use one's own electrum server from the very start. (One has to create the wallet in airplane mode, and then set the server in the settings).

Possible solutions:
1. Have a checkbox "Auto-connect to electrum servers" (default checked) in the start of the wallet creation. If unchecked it does not connect to any server with the settings: (One-server = True, server = localhost:50002). Then the user can manually set these settings later.
2. Have a way to access the settings BEFORE creating the wallet,
3. show the network settings directly after the wallet creation process (before it started to sync)

**Comment by relativisticelectron** [comment] 2020-05-06 18:22
Do you think this would be a useful (privacy) feature?

**Comment by ecdsa** [comment] 2020-05-07 08:28
isn't it already possible with qt?

**Comment by relativisticelectron** [comment] 2020-05-07 09:33
> isn't it already possible with qt?

Yes it is in qt. (I didn't know.) I wish this would also be available in kivy.

**Comment by relativisticelectron** [comment] 2020-05-07 12:43
I need some help: The choice dialog is not showing up for some reason:  https://github.com/relativisticelectron/electrum/commit/0a789c12fd7a33ef0591adc827a948f1a315f76e#diff-d3ef59134ccb28b8db063f9f5926e58fR1135

Only if I call wizard.terminate() afterwards I can see the dialog (but this causes an exception).

**Comment by SomberNight** [comment] 2020-05-11 15:37
this is a duplicate of https://github.com/spesmilo/electrum/issues/5512

**Closed by SomberNight** 2020-05-11 15:37 UTC
Labels: OS-android

**Comment by SomberNight** [comment] 2020-05-11 15:38
Note that it is an implementation detail that in Qt the first-start network dialog appears as part of the InstallWizard
This does not have to be the case in kivy.

**Comment by relativisticelectron** [comment] 2020-05-12 15:00
> Note that it is an implementation detail that in Qt the first-start network dialog appears as part of the InstallWizard
> This does not have to be the case in kivy.

Why?  I would find that extremely useful in kivy.

**Comment by SomberNight** [comment] 2020-05-12 15:11
Yes I agree it would be useful for power users; I would use it myself.

I just meant that just because in the Qt GUI the first time network setup is tied to the "InstallWizard" object, this does not necessarily have to be the case for the kivy GUI, in terms of implementation. Not sure though. E.g. it might be easier to add a dialog before the wizard shows up, not as part of the wizard.

**Comment by relativisticelectron** [comment] 2020-05-12 16:32
> Yes I agree it would be useful for power users; I would use it myself.
> 
> I just meant that just because in the Qt GUI the first time network setup is tied to the "InstallWizard" object, this does not necessarily have to be the case for the kivy GUI, in terms of implementation. Not sure though. E.g. it might be easier to add a dialog before the wizard shows up, not as part of the wizard.

Yes of course, the implementation can differ in qt and kivy.  If I understand this qt code https://github.com/spesmilo/electrum/blob/master/electrum/gui/qt/__init__.py#L350 correctly, the init_network starts a seprate InstallWizard instance and kills it after the 1 dialog.
