### ISSUE TITLE
Cannot open LN channel from electrum to MyNode

### ISSUE THREAD

**Issue by jansocz** [spesmilo/electrum#7580] opened 2021-11-30 01:24 UTC
When I try to open lightning channel from electrum to MyNode, I get always following error:

Could not open channel: ConnStringFormatError('Hostname does not resolve (getaddrinfo failed)')

It would be better if it was possible to receive new channels opened from other nodes, but I dont know why I cant open from electrum at least, as it did worked with other nodes in the past..

version 4.1.5/windows

**Comment by jansocz** [comment] 2021-11-30 03:03
I was able to use tor proxy at port 9150, probable progress, now I am getting this error:
Could not open channel: Exception('RemoteConfig. dust limit too low: 354 sat')

**Comment by Alfreddo12** [comment] 2021-11-30 12:31
Duplicate of #`

**Comment by dolcalmi** [comment] 2021-12-10 03:33
@jansocz is you node? maybe is related to this config https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L371 in my node

**Comment by SomberNight** [comment] 2022-02-18 15:30
> Could not open channel: ConnStringFormatError('Hostname does not resolve (getaddrinfo failed)')

Sounds like DNS issues

> I was able to use tor proxy at port 9150, probable progress

When using a Tor proxy, DNS is resolved via the proxy. So if a proxy helped, then indeed there are DNS issues on your local system.

> Could not open channel: Exception('RemoteConfig. dust limit too low: 354 sat')

duplicate of https://github.com/spesmilo/electrum/issues/7541

**Closed by SomberNight** 2022-02-18 15:30 UTC
