### ISSUE TITLE
Check for updates reports older version as latest (Electrum hacked again?)

### ISSUE THREAD

**Issue by sallywoog** [spesmilo/electrum#6393] opened 2020-07-15 09:33 UTC
Check for updates reports older version as latest

Run AppImage for Linux for Electrum v4.0.2 and then Check for Updates

Reported latest version is v3.3.8

Has the site been hacked again and the versions changed? This is a concern, a big one

Did somebody balls this up? Don't you run checklists on release processes? Don't you have somebody else verify the checklist and release?

Is this version v4.0.2 legitimate or hacked?

**Comment by SomberNight** [comment] 2020-07-15 13:47
dupe of https://github.com/spesmilo/electrum/issues/6338

it was a conscious decision to delay triggering the update notification, to spread out users updating somewhat

**Comment by SomberNight** [comment] 2020-07-15 13:48
> Has the site been hacked again

please elaborate, as it was never hacked...

**Closed by SomberNight** 2020-07-15 13:47 UTC

**Comment by sallywoog** [comment] 2020-07-15 13:50
> > Has the site been hacked again
> 
> please elaborate, as it was never hacked...

Well when I install a version and the update check notifies me that an older version is the latest then that raises warning flags that the installed later version is not the official latest and potentially modified and distributed

**Comment by SomberNight** [comment] 2020-07-15 13:51
You should check the GPG signatures. You should consider that as the root of trust.

**Comment by sallywoog** [comment] 2020-07-15 13:52
> You should check the GPG signatures. You should consider that as the root of trust.

I could but they could publish those too along with the hacked version

**Comment by SomberNight** [comment] 2020-07-15 13:53
> I could but they could publish those too along with the hacked version so they match

If that was possible, then "they" could also fake the `version` file that you are talking about.

**Comment by sallywoog** [comment] 2020-07-15 13:53
> > I could but they could publish those too along with the hacked version so they match
> 
> If that was possible, then "they" could also fake the `version` file that you are talking about.

I will use the "latest" reported one that I have stored away

**Comment by SomberNight** [comment] 2020-07-15 13:54
you are free to do whatever you want, we are just wasting each other's time.
