### ISSUE TITLE
Cant connect ...

### ISSUE THREAD

**Issue by Bitcoinhuman** [spesmilo/electrum#5368] opened 2019-05-21 18:40 UTC
Hello. I can’t connect today. I was on version 3.3.3, before upgrading on 3.3.6 today, but the same problem remains.

In fact, I can’t connect to the servers, I can’t sync. Sometimes I can connect, but the servers only stay connected for 1 or 2 seconds in the list. This shows me something new "sync 0/256" I’ve never seen this. Then, if I ever get to the end, he tells me "server 190 blocks late" and then disconnects. I’ve never had this problem before. What should I do?

Windows 7 64bits/electrum 3.3.6
Thank you in advance

**Comment by SomberNight** [comment] 2019-05-21 18:44
Please try the following server: `fortress.qtornado.com` with either port `50002` or `443`.

**Comment by Bitcoinhuman** [comment] 2019-05-21 18:50
Hello. I just tried, but still nothing. Even if I select the server, nothing changes, it remains not connected. And some servers scroll through the list but only have one or two seconds left. I don’t understand anything.

**Comment by SomberNight** [comment] 2019-05-21 18:53
Try enabling logs.
`Tools`>`Preferences`>`General`>`Write logs to file`
After enabling it, restart the app.

Logs will be written to disk, check at path `%appdata%/electrum/logs`.
Please upload a logfile (or contents) to here

**Comment by AbdussamadA** [comment] 2019-05-23 05:41
you have to right click on a server in the server list and choose 'use server' to change servers.

**Comment by rchovan** [comment] 2019-09-13 07:36
Hi, 
I don't want to open new issue, when this one is not solved. I have same problem, can't connect to server. I have tried standalone version from 3.3.5 to 3.3.8. All of them show same message "Not Connected" and this I found in logs:
```
20190913T073024.547791Z |     INFO | logging | Electrum version: 3.3.8 - https://electrum.org - https://github.com/spesmilo/electrum
20190913T073024.548768Z |     INFO | logging | Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]. On platform: Windows-10-10.0.17763
20190913T073024.548768Z |     INFO | logging | Logging to file: C:\Users\elct\AppData\Roaming\Electrum\logs\electrum_log_20190913T073024Z_10556.log
20190913T073024.548768Z |     INFO | logging | Log filters: verbosity '', verbosity_shortcuts ''
20190913T073025.552601Z |     INFO | daemon | failed to connect to JSON-RPC server: [WinError 10061] No connection could be made because the target machine actively refused it
20190913T073025.562362Z |     INFO | plugin.Plugins | registering hardware coldcard: ('hardware', 'coldcard', 'Coldcard Wallet')
20190913T073025.563338Z |     INFO | plugin.Plugins | registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
20190913T073025.566299Z |     INFO | plugin.Plugins | registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
20190913T073025.700954Z |     INFO | gui.qt.history_list | could not import electrum.plot. This feature needs matplotlib to be installed.
20190913T073025.704858Z |     INFO | plugin.Plugins | loaded labels
20190913T073025.705834Z |     INFO | plugin.Plugins | registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
20190913T073025.706810Z |     INFO | plugin.Plugins | registering hardware safe_t: ('hardware', 'safe_t', 'Safe-T mini wallet')
20190913T073025.707786Z |     INFO | plugin.Plugins | registering hardware trezor: ('hardware', 'trezor', 'Trezor wallet')
20190913T073025.708762Z |     INFO | plugin.Plugins | registering wallet type ('2fa', 'trustedcoin')
20190913T073025.709738Z |    DEBUG | util.profiler | Plugins.__init__ 0.1493
20190913T073025.711725Z |     INFO | network | blockchains [0]
20190913T073025.711725Z |     INFO | exchange_rate.FxThread | using exchange CoinGecko
20190913T073025.712707Z |     INFO | network | starting network
20190913T073025.712707Z |     INFO | network | connecting to electrum-server.ninja:50002:s as new interface
20190913T073025.714648Z |     INFO | exchange_rate.CoinGecko | getting fx quotes for EUR
20190913T073025.715617Z |    DEBUG | util.profiler | Daemon.__init__ 0.0059
20190913T073026.372438Z |    DEBUG | util.profiler | ElectrumGui.__init__ 0.6559
20190913T073026.378295Z |     INFO | storage.WalletStorage | wallet path c:\users\radoslav.chovan\appdata\roaming\electrum\wallets\osx
20190913T073026.788214Z |     INFO | storage.WalletStorage | wallet path c:\users\radoslav.chovan\appdata\roaming\electrum\wallets\osx
20190913T073026.789189Z |     INFO | storage.WalletStorage | wallet path c:\users\radoslav.chovan\appdata\roaming\electrum\wallets\osx
20190913T073026.891670Z |     INFO | interface.[electrum-server.ninja:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20190913T073026.891670Z |     INFO | interface.[enode.duckdns.org:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20190913T073026.891670Z |     INFO | interface.[electrumx.erbium.eu:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20190913T073026.892645Z |     INFO | interface.[qtornadoklbgdyww.onion:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20190913T073026.892645Z |     INFO | interface.[electrum2.villocq.com:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20190913T073026.893623Z |     INFO | interface.[electrumx.ml:50002] | disconnecting due to: ConnectError(gaierror(11001, 'getaddrinfo failed'),)
20190913T073026.893623Z |     INFO | interface.[fedaykin.goip.de:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20190913T073026.894597Z |     INFO | interface.[btchub.fr:50002] | disconnecting due to: ConnectError(gaierror(11001, 'getaddrinfo failed'),)
20190913T073026.894597Z |     INFO | interface.[hsmiths4fyqlw5xw.onion:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20190913T073026.894597Z |     INFO | exchange_rate.CoinGecko | failed fx quotes: ClientConnectorError(11001, 'getaddrinfo failed')
20190913T073026.895572Z |     INFO | network | couldn't launch iface electrum-server.ninja:50002:s -- CancelledError()
20190913T073026.896550Z |     INFO | network | couldn't launch iface enode.duckdns.org:50002:s -- CancelledError()
20190913T073026.896550Z |     INFO | network | couldn't launch iface electrumx.erbium.eu:50002:s -- CancelledError()
20190913T073026.896550Z |     INFO | network | couldn't launch iface qtornadoklbgdyww.onion:50002:s -- CancelledError()
20190913T073026.896550Z |     INFO | network | couldn't launch iface electrum2.villocq.com:50002:s -- CancelledError()
20190913T073026.896550Z |     INFO | network | couldn't launch iface electrumx.ml:50002:s -- CancelledError()
20190913T073026.897535Z |     INFO | network | couldn't launch iface fedaykin.goip.de:50002:s -- CancelledError()
20190913T073026.897535Z |     INFO | network | couldn't launch iface btchub.fr:50002:s -- CancelledError()
20190913T073026.898508Z |     INFO | network | couldn't launch iface hsmiths4fyqlw5xw.onion:50002:s -- CancelledError()
20190913T073026.904359Z |     INFO | interface.[xray587.startdedicated.de:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20190913T073026.905333Z |     INFO | network | couldn't launch iface xray587.startdedicated.de:50002:s -- CancelledError()
20190913T073027.203395Z |     INFO | interface.[VPS.hsmiths.com:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20190913T073027.203395Z |     INFO | interface.[hsmiths5mjk6uijs.onion:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20190913T073027.203395Z |     INFO | interface.[bitcoins.sk:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20190913T073027.203395Z |     INFO | interface.[electrumx.bot.nu:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20190913T073027.203395Z |     INFO | interface.[bitcoin.corgi.party:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20190913T073027.203395Z |     INFO | interface.[electrum.eff.ro:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20190913T073027.203395Z |     INFO | interface.[vmd27610.contaboserver.net:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20190913T073027.204371Z |     INFO | interface.[bitcoin3nqy3db7c.onion:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20190913T073027.204371Z |     INFO | interface.[electrum2.eff.ro:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed'),),)
20190913T073027.204371Z |     INFO | network | couldn't launch iface VPS.hsmiths.com:50002:s -- CancelledError()
20190913T073027.204371Z |     INFO | network | couldn't launch iface hsmiths5mjk6uijs.onion:50002:s -- CancelledError()
20190913T073027.204371Z |     INFO | network | couldn't launch iface bitcoins.sk:50002:s -- CancelledError()
20190913T073027.204371Z |     INFO | network | couldn't launch iface electrumx.bot.nu:50002:s -- CancelledError()
20190913T073027.204371Z |     INFO | network | couldn't launch iface bitcoin.corgi.party:50002:s -- CancelledError()
20190913T073027.205388Z |     INFO | network | couldn't launch iface electrum.eff.ro:50002:s -- CancelledError()
20190913T073027.205388Z |     INFO | network | couldn't launch iface vmd27610.contaboserver.net:50002:s -- CancelledError()
20190913T073027.205388Z |     INFO | network | couldn't launch iface bitcoin3nqy3db7c.onion:50002:s -- CancelledError()
20190913T073027.205388Z |     INFO | network | couldn't launch iface electrum2.eff.ro:50002:s -- CancelledError()

```

Log  is repeating and equal for all versions.  I have tried to run electrum as admin user too. 

Windows 10/64bit

**Comment by SomberNight** [comment] 2019-09-13 13:18
@rchovan yours is a different issue. moved it to https://github.com/spesmilo/electrum/issues/5638

And in fact I am closing this one due to OP not answering. Without logs, it's very difficult to tell what the cause was.

**Closed by SomberNight** 2019-09-13 13:18 UTC
Labels: topic-network
