### ISSUE TITLE
electrum doesn´t start anymore at latest ubuntu

### ISSUE THREAD

**Issue by mischmar** [spesmilo/electrum#984] opened 2015-01-21 15:01 UTC
Hello,
I have a big problem. My electrum wallet doesn´t start anymore. Now all my transaction decription are lost. That is big problem for our accounting...
Can you help me to rebuild it? I live in berlin.

Thank you

**Comment by ecdsa** [comment] 2015-01-21 16:46
this is probably a duplicate of bug #849 
try with the code in github

**Comment by ecdsa** [comment] 2015-01-22 23:23
closing, because OP does not respond

**Closed by ecdsa** 2015-01-22 23:23 UTC
