### ISSUE TITLE
Error if the address has transactions where change go back to himself

### ISSUE THREAD

**Issue by osminogin** [spesmilo/electrum#1994] opened 2016-10-23 18:55 UTC
Don't find solution how to just send some part of coins from address with API or CLI, so I'm use same address as change address (because have a certain high-level logic that works with Electrum, and I don't need change addresses at all). 

This works okay with `payto` function, but after this address got errors on all operations (`getaddressbalance` for example):

```
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 361, in <module>
    result = server.run_cmdline(config_options)
  File "/usr/local/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 288, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 238, in _request
    check_for_errors(response)
  File "/usr/local/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 567, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/usr/local/lib/python2.7/site-packages/electrum/network.py", line 857, in synchronous_get | BaseException: \'Node\' object has no attribute \'__getitem__\'')
```

Example transaction that breaks Electrum: https://blockchain.info/tx/c9e6e72621ad14f73ca649d45e4a2826194a9489cfd18d79b4d2536f07bca22d

This tx looks tricky, but I don't see any crime - it is a normal operation for blockchain.

**Comment by gits7r** [comment] 2016-10-23 19:13
A don't use  a different change checkbox in the "Send" tab would be useful I agree for some use cases. But the checkbox should not appear by default, only if enabled previously in wallet settings by checking "Allow disabling change addresses for transactions [Not Recommended]" because it might confuse non experienced users and use it in a bad way that will affect their bitcoin usage -- we know re-using addresses is bad and it is not meant for bitcoin, but if some experts need this feature for some specific use cases I don't see a problem in having it.

**Comment by osminogin** [comment] 2016-10-23 19:23
@gits7r This bug is not about GUI and some checkboxes (at least that's what I'm writing). This about internal Electrum things, because I can manually make transaction for address which Electrum can't work. If you see any errors or suggestions for behavior is not related to this bug, please create a separate report.

**Comment by gits7r** [comment] 2016-10-23 19:27
Oh, sorry disregard my comment then. I thought you are missing the feature to make this happen easily. I will open a ticket for the feature request described by me if I see more users requesting it, not urgent.

**Comment by ecdsa** [comment] 2016-10-24 09:26
this looks like a server side error.
I cannot reproduce it (tried ```getaddressbalance 1QGJ6ZNjpsWernRwNvDEWv9j```)
do you remember which server you were connected to?

**Comment by osminogin** [comment] 2016-10-24 10:20
@ecdsa thanks for attention. After some additional debug, look like this specific to some problematic electrum server. I can get electrum server address from API or CLI (or any way to catch some example of problematic server)?

To reproduce:

- Make transaction where source address is equal to the change address and any destination:

```
electrum payto -f 0.0001 -F 1QGJ6ZNjpsWernRwNvDEWv9jzkTS2cwPas -c 1QGJ6ZNjpsWernRwNvDEWv9jzkTS2cwPas 1AH12y6vuvQSbtGSBhRDsx6LLTwmqEcHzN 0.01 | electrum broadcast - 
```

- Try `getaddressbalance` on source address:

```
electrum getaddressbalance 1QGJ6ZNjpsWernRwNvDEWv9jzkTS2cwPas
```

**Comment by ecdsa** [comment] 2016-10-24 10:25
run 'electrum daemon status' to see which server you are using

**Comment by ecdsa** [comment] 2016-10-24 13:51
yes, I can reproduce it on dragonzone, so it's a server issue.
I guess they are running old code.
use another server, it will be fixed.

**Closed by ecdsa** 2016-10-24 13:51 UTC

**Comment by osminogin** [comment] 2016-10-24 14:13
Ok, thanks.

But may be is good idea to get some workaround for this issue (may be some warning about incompatibility client and server versions). I think simple user don't want some mystic exceptions or finding and pin to concrete server that suit him. But thanks again, my deal is to report.
