### ISSUE TITLE
The server returned an error when broadcasting the transaction. Consider trying to connect to a different server, or updating Electrum.  insufficient fee

### ISSUE THREAD

**Issue by kuedsu** [spesmilo/electrum#5240] opened 2019-04-04 00:29 UTC
Hello!
I get an error!

"""The server returned an error when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.

insufficient fee"""

I already did it, but nothing helped me

""Switch to a different server. Tools > network > server tab, uncheck select automatically, right click on a different server and choose use server. Then try to send btc again.""

**Comment by AbdussamadA** [comment] 2019-04-04 00:55
what fee are you setting?

**Comment by kuedsu** [comment] 2019-04-04 01:05
Hi

ETA

чт, 4 апр. 2019 г. в 03:56, Abdussamad Abdurrazzaq <notifications@github.com

**Comment by DriftwoodPalace** [comment] 2019-04-04 07:44
Having the same issue. Using a hardware-wallet and Tor. Tried setting fees manually, with mempool and ETA. Nothing worked. 

Exported and broadcasted the transaction via a block explorer without issues.

**Comment by Strarters** [comment] 2019-04-05 06:21
Hello !
I have the same error, please explain what I need to do to send bits

**Comment by Strarters** [comment] 2019-04-05 06:31
I will be more accurate and write literally!
_____________
The server returned an error when broadcasting the transaction.
Consider trying to connect Electrum.

too-long-mempool-chain
_____________________________

**Comment by DriftwoodPalace** [comment] 2019-04-05 06:48
I don't know how to fix the issue. But you can do a work around if you need to send out a transaction. Go to the send tab and construct the transaction. Instead of clicking "Send", click "Preview".

In the new window click "Sign" and then "copy". Go here https://blockstream.info/tx/push paste and broadcast the transaction. It should show up in Electrum.

**Comment by SomberNight** [comment] 2019-04-11 03:04
It's quite possible that all of you have different issues.

@kuedsu might have been trying to RBF
@Strarters might have had, as the error says, a too long chain of unconfirmed txns

It's also possible that the servers you happened to connect to behaved weird.

I assume your issues have been resolved by now, especially as mempool shrunk.
Not much to do; closing until more reports.

**Closed by SomberNight** 2019-04-11 03:04 UTC

**Comment by gregongithub** [comment] 2020-02-05 21:04
Getting the same error
The server returned an error when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.
Unknown error

Screen here
https://gyazo.com/b953aa642bc945cac0648ba57b03780f

Electrum 3.3.8 - newes version
I change the servers (just picked one other) > same error
I chose automatic select servers  > same error
Fee: within 5 blocks
VPN: on with USD server

I am a newbee in BTC, but I am surprised that this fundamental things do not work to send BTC.

**DriftwoodPalace** Thanks a lot - workarroung worked.

**Comment by AbdussamadA** [comment] 2020-02-06 08:58
@gregongithub next time try using it without a VPN.

**Comment by gregongithub** [comment] 2020-02-06 09:15
AbdussamadA - thanks for the hint, I will : )

**Comment by kh3ldar** [comment] 2021-05-03 23:39
Hello guys, I'm having the same issue. I've tried everything written on this post. Still same error. I'm pretty certain I'm trying to send a valid amount because I've sent a lesser amount before and it worked. I tried preview mode and changing the servers nothing worked.

**Comment by fernando323960** [comment] 2023-08-31 08:54
Guys,contact me ,probably i can help all of you.Telegram:
@jeembo228123
