### ISSUE TITLE
object of type "nonetype" has no len

### ISSUE THREAD

**Issue by mattyzeepdsn** [spesmilo/electrum#3535] opened 2017-12-16 17:40 UTC
setup an electrum wallet yesterday, sent some coin to it, now want to send that coin to exchange site but everytime I click send or preview it comes up with (object of type nonetype has no len. am I doing something wrong? no idea. new to this. thanks

**Comment by SomberNight** [comment] 2017-12-16 17:41
What version of Electrum? If older than 3.0.3, please test with that.

**Comment by mattyzeepdsn** [comment] 2017-12-16 17:43
its 3.0.2, its the one off there website? do I have to delete wallet then download new one?

**Comment by SomberNight** [comment] 2017-12-16 17:51
> its 3.0.2

Ok, so that version is also fairly recent... but still in any case could you try with 3.0.3?
 https://electrum.org/#download

> do I have to delete wallet then download new one?

No, just install the newer version. As a precaution, make sure you have a copy of your seed words.

Btw, what operating system are you using?

**Comment by mattyzeepdsn** [comment] 2017-12-16 17:58
thankyou very much, just installed it and its now 3.0.3. will give this transaction a go. I think I have windows 10

**Comment by mattyzeepdsn** [comment] 2017-12-16 18:03
it sent, thanks very much for your help. just waiting on the nem funds to show up in my wallet now, could be a while....

**Comment by SomberNight** [comment] 2017-12-16 18:20
Note: the bug might have "gone away" just by chance, not necessarily because of trying with the newer version. In hindsight it could have been better to try to find out the cause before updating...

**Comment by SomberNight** [comment] 2017-12-25 17:41
Closing; will reopen if there is another report.

**Closed by SomberNight** 2017-12-25 17:41 UTC
