### ISSUE TITLE
BIP39 seed and custom word extensions on Android

### ISSUE THREAD

**Issue by gordonel** [spesmilo/electrum#5567] opened 2019-08-17 09:56 UTC
Although I agree that Electrum seed generation is somewhat better than BIP39, Electrum should allow for compatibility with other solutions and never deprecate BIP39 support. With that said, the BIP39 seed support is missing from the Android app. The only way for me to get a wallet generated by a BIP39 seed into Android was though my master private key, which is not the best and secure option.

**Comment by ecdsa** [comment] 2019-08-17 11:25
closing as duplicate of #3388. issue already fixed

**Closed by ecdsa** 2019-08-17 11:25 UTC

**Comment by SomberNight** [comment] 2019-08-17 13:21
Note that seed extensions have been available on Android for a long time.
You need to touch the text box that contains the seed words to have the corresponding dialog appear.
(This too was made more intuitive in the above and related commits).
