### ISSUE TITLE
cannot send all after deleting send-task

### ISSUE THREAD

**Issue by rubo77** [spesmilo/electrum#6755] opened 2020-11-21 08:20 UTC
1. try to send a very tiny amount of 0.000055BTC (which has to be **all BTC in that wallet**) to another address
2. select the "send" tab, enter the address,  press MAX and "Pay"
3. there I was not sure about the fee, so I canceled it.
4. Now it is in the list below, rightclick it and delete the task
5. Try to send it again

Now you get the error "Not enough funds" although the 0.00055BTC are still visible. There is no open task any more, and no way to try to send this again.

**Comment by ecdsa** [comment] 2020-11-21 11:06
duplicate of #6713 
it is a user interface issue

**Comment by SomberNight** [comment] 2020-11-21 17:51
Doesn't the ConfirmTxDialog appear even if the user does not have enough balance for mining fee?
https://github.com/spesmilo/electrum/blob/32ffc9e9a415f0709f8a2e4595c5de7c1ebbb52b/electrum/gui/qt/main_window.py#L1650-L1656

----

> try to send a very tiny amount of 0.000055BTC (which has to be all BTC in that wallet) to another address

Do you mean you are clicking "max"?

**Closed** 2020-11-21 18:35 UTC
Labels: bug, user-interface
