### ISSUE TITLE
Can't escape install wizard

### ISSUE THREAD

**Issue by H4NNE5** [spesmilo/electrum#1778] opened 2016-05-01 14:04 UTC
Hi, after installation I choose multi sig wallet but didn't know, that it meant that there is another wallet necessary.
I came to the window where i had to enter the "master public key of cosigner #1". So I hit cancel and the window closed. But anytime I start electrum again it just opens this window  and there is no way to get to the initial screen.

Please help me with that because I think it's a SW bug.
Thanks and best regards

Update: Doesn't even work after De- and Reinstallation...

**Comment by mrnitrate** [comment] 2016-05-07 00:38
I have the same issue !! Any solution yet?

**Comment by mrnitrate** [comment] 2016-05-07 00:48
Looks like you can remove the \AppData\Roaming\Electrum\wallets\default_wallet file to cancel this  multi sig wallet install

**Comment by kyuupichan** [comment] 2016-05-07 01:47
@ecdsa - how about asking the user if they want to remove the wallet when we catch the UserCancelled exception?  We should only do this if something has actually been saved.

**Comment by ecdsa** [comment] 2016-05-16 15:29
closing, duplicate of #1755

**Closed by ecdsa** 2016-05-16 15:29 UTC

**Comment by ecdsa** [comment] 2016-05-16 15:47
@kyuupichan yes that would work
