### ISSUE TITLE
[Feature Request] Support BIP-0137 for text message sign/verify

### ISSUE THREAD

**Issue by brianddk** [spesmilo/electrum#5644] opened 2019-09-16 23:52 UTC
The text message sign/verify functions in Electrum 3.3.8 do not seem to comply with [BIP-0137](https://github.com/bitcoin/bips/blob/master/bip-0137.mediawiki#conventions-with-signatures-used-in-bitcoin).  This BIP was accepted on [March 29, 2019](https://github.com/bitcoin/bips/pull/764#event-2240835661)

Are there plans to support this BIP in Electrum.  Possibly as an options setting if there is a need for backward compatibility.

**Comment by SomberNight** [comment] 2019-09-17 00:34
Thanks for pointing out that BIP.
Closing as duplicate of https://github.com/spesmilo/electrum/issues/3861

**Closed by SomberNight** 2019-09-17 00:34 UTC
