### ISSUE TITLE
Crash on launch - new instal

### ISSUE THREAD

**Issue by verynewb** [spesmilo/electrum#2753] opened 2017-08-15 03:16 UTC
Hi, I'm new to Electrum. Just downloaded it from https://electrum.org/#download. It's version 2.9.3.

The program is crashing on launch - when I open it I get the "Electrum quit unexpectedly" window popup. 

Mac osx 10.11.16
hardly any other apps/processes running

Hope someone can help. Cheers

**Comment by verynewb** [comment] 2017-08-15 03:17
Oh - Mac osx 10.11.16 
hardly any other apps/processes running

**Comment by ecdsa** [comment] 2017-08-15 05:32
duplicate of #2726

**Closed by ecdsa** 2017-08-15 05:32 UTC
