### ISSUE TITLE
Windows 11 - Failed type: 'Cross-thread'

### ISSUE THREAD

**Issue by izerow** [spesmilo/electrum#7972] opened 2022-09-09 23:58 UTC
**This occurs to me sometimes when closing the Electrum Wallet window.**

I simply click close button and the program freezes until I click "force close application".

Event Logs shows:

Source: Application Hang
Level: Error

 The electrum-4.3.1.exe program version 0.0.0.0 stopped interacting with Windows and closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
  Process ID: 2f10
  Start Time: 01d8c4a68084f877
  End time: 11
  Application Path: C:\Program Files (x86)\Electrum\electrum-4.3.1.exe
  Report ID: 86a4591f-3982-48fd-94f4-e54c52523f1c
  Failed package full name:
  Application ID relative to the failing package:
  Failed type: Cross-thread

I don't know if there is a way to fix it, my system is newly formatted.

**Comment by SomberNight** [comment] 2022-09-20 16:08
I think this is probably a duplicate of https://github.com/spesmilo/electrum/issues/6889.

**Comment by SomberNight** [comment] 2024-01-17 21:28
I'll close this in favour of the linked issue.

**Closed by SomberNight** 2024-01-17 21:28 UTC
Labels: OS-windows 🪟
