### ISSUE TITLE
Trezor Safe 5 not compatible

### ISSUE THREAD

**Issue by GitHubSeattle** [spesmilo/electrum#9171] opened 2024-08-22 20:18 UTC
Have Electrum running correctly with Trezor Model T.  (Electrum AppImage client 4.5.5).   (Ubuntu 22.xx)

When I try to connect my new Trezor Safe 5 to electrum, it says this version of trezor is not supported.
(This is similar post to when Safe 3 first came out #8722.  T5 was just released two months ago.)

Did attempt $ pip install --upgrade trezor.   No joy.

Can send factory new Trezor Safe 5 for testing purposes if needed (consider it a donation to a great product.  :-)

**Comment by swedishlars** [comment] 2024-08-28 20:50
Same issue, this model is not supported msg. 

I'm completely new to this and ordered a Trezor 5. I did not realise it is a brand new device that is not (yet?) supported by electrum.

Silly me and a bit of a bummer. I was hoping to use electrum sweep feature since Trezor Suite does not support it.

**Comment by SomberNight** [comment] 2024-09-02 13:55
I think this is already fixed on master with https://github.com/spesmilo/electrum/commit/bd845080b852ab19c54c2c4bd5ec8a36255b9e35 and https://github.com/spesmilo/electrum/pull/9141.

**Closed by SomberNight** 2024-09-02 13:55 UTC
Labels: hw-trezor

**Comment by jlopp** [comment] 2024-10-10 12:53
Has anyone confirmed that this is fixed?

I have a Safe 5 in hand and am running master branch commit fbca54db49dd52d4b60338d8244d7e10bae3ed52

I'm still receiving the "model not supported" error.

**Comment by SomberNight** [comment] 2024-10-10 14:19
@jlopp Thank you for testing! I don't have a device to test with.
You need both a recent commit from electrum master (which you have) and recent version of [python-trezor](https://pypi.org/project/trezor/) (0.13.9). Do you have both?

See if you satisfy the latter by running this in the Qt console in Electrum:
```py
>>> import trezorlib
>>> trezorlib.__version__
'0.13.9'
```

or you can also do something like:  `$ python3 -m pip show trezor`

**Comment by jlopp** [comment] 2024-10-10 15:03
Aha; upgraded my python-trezor library and now it's working.
