### ISSUE TITLE
Incorrect BTC Balance after a certain date.

### ISSUE THREAD

**Issue by tvl83** [spesmilo/electrum#1331] opened 2015-07-01 05:32 UTC
While I wish this was my true balance, it simply is not. 

I have used this one wallet file for all of my bitcoin addresses on my computer since October of last 2014. Maybe it is just too large ?

Electrum 2.0.4 doesnt have this problem but 2.1.1 did and now I noticed 2.3.2 so I upgraded and when I first run electrum it is fine. After a few hours, this happens. 

![http://i.imgur.com/G3gjEuf.png](http://i.imgur.com/G3gjEuf.png)

I am on this server if that makes any difference. I do not check the server regularly so I do not know if it is only this server or a certain couple of servers that cause this. I can keep my eye on it.
![http://i.imgur.com/sTl2pVF.png](http://i.imgur.com/sTl2pVF.png)

I plan on reverting back to 2.0.4 but I will stay on this one for a while longer if it helps resolve this. I can provide any necessary information to help fix it.

**Comment by ecdsa** [comment] 2015-07-01 06:17
is the final balance wrong, or are you worried by the 'unknown' lines displayed in the history?

**Comment by tvl83** [comment] 2015-07-01 06:35
The final balance is wrong. I do not have 51btc, more like 1.8btc

**Comment by ecdsa** [comment] 2015-07-01 06:48
ok, can you email me your master public key ?

**Comment by ecdsa** [comment] 2015-07-02 15:01
it might be caused by a bug in pruning
(transactions were removed from history while still referenced)
that is fixed by commit 65e7667eba75044255c2b476434b6a22cbad2e34

**Closed by ecdsa** 2015-07-02 15:01 UTC

**Comment by ecdsa** [comment] 2015-07-02 15:02
note: this fix will not correct the balance on a wallet that shows an incorrect balance; it only prevents it from happening again. to fix it, you need to clear the history: ```wallet.clear_history()```
