### ISSUE TITLE
Unable to send via Lightning

### ISSUE THREAD

**Issue by ChineseGeek** [spesmilo/electrum#6415] opened 2020-07-19 13:52 UTC
Hello, i have enable Lightning on Electrum, channel is Open, but i cant send using Lightning, i have tried sending to 3 different wallets (BLW, Phoenix and Wallet of  Satoshi) and all 3 give me the "Payment Failed. No path found" error. What could it be? How can I solve this issue?

**Comment by SomberNight** [comment] 2020-07-19 21:55
Are you using Electrum on desktop or on Android?

Is the graph synced? (check `Tools`>`Lightning Network`; what does it say there?)

**Comment by ChineseGeek** [comment] 2020-07-19 22:51
Using Electrum 4.0.2 on Ubuntu 20.04. Yes, it is synced, it says "Connected to 4 peers. 5885 nodes. 33148 channels." Im assumming that suggested nodes have enough liquidity to route my payment, or im i wrong?

**Comment by gits7r** [comment] 2020-07-26 00:39
This is a duplicate of #6430 - let us take the matter there. I confirm I get this behavior as well, and I cannot use lightning because of it.

**Comment by ecdsa** [comment] 2020-07-30 11:04
@ChineseGeek open more channels, and make sure you connect to well connected nodes

**Comment by ChineseGeek** [comment] 2020-08-08 12:51
> @ChineseGeek open more channels, and make sure you connect to well connected nodes

Sorry for the question, but how opening more channels can help finding a path? Right now i have one channel open with a citadel21.com node, that has 24 more channels... And still can not send funds on Lightning, same error "Path not found"

**Comment by ecdsa** [comment] 2020-12-20 08:06
closing, not enough information here

**Closed by ecdsa** 2020-12-20 08:06 UTC
Labels: lightning ⚡
