### ISSUE TITLE
Show the wallet name in the title bar

### ISSUE THREAD

**Issue by dandv** [spesmilo/electrum#2222] opened 2017-03-02 05:23 UTC
I use Electrum on Ubuntu, and have created two wallets. Since both wallets are empty right now, it's impossible to tell which wallet is which, because Electrum doesn't display the wallet's filename anywhere.

Please show which wallet is open in the current window, for example by listing the wallet's name in the title bar.

Even better, use a tabbed approach like MultiBit Classic, where all wallets are visible at once.

![image](https://cloud.githubusercontent.com/assets/33569/23494087/55357396-fec5-11e6-9dad-f574d1a39b73.png)

**Comment by ecdsa** [comment] 2017-03-02 07:05
are you kidding? Electrum does display the wallet name in the title bar.

**Comment by ecdsa** [comment] 2017-03-02 07:06
please submit a screenshot

**Comment by dandv** [comment] 2017-03-02 07:08
![image](https://cloud.githubusercontent.com/assets/33569/23496616/eda95c42-fed3-11e6-95dc-c76329953641.png)

**Comment by ecdsa** [comment] 2017-03-02 07:09
what is your OS and window manager?

**Comment by dandv** [comment] 2017-03-02 07:10
As I mentioned in the first comment, I use Ubuntu. Ubuntu comes by default with Unity.

**Comment by ecdsa** [comment] 2017-03-02 07:13
this looks like a bug in unity. does it work if you maximize the window?
http://unix.stackexchange.com/questions/296914/how-to-display-window-titles-on-non-maximized-windows-in-unity-7-4

**Comment by ecdsa** [comment] 2017-03-02 07:15
see also http://askubuntu.com/questions/795074/how-to-display-window-titles-on-not-maximized-windows
closing this, because the problem is not with Electrum

**Closed by ecdsa** 2017-03-02 07:15 UTC

**Comment by dandv** [comment] 2017-03-02 07:24
May I suggest displaying the wallet name in the status bar as well, in the lower-right corner?

**Comment by ecdsa** [comment] 2017-03-02 07:29
well, I don't like fixing things by adding new things next to them...
