### ISSUE TITLE
Account labels revert to default names after change

### ISSUE THREAD

**Issue by RustyNomad** [spesmilo/electrum#1380] opened 2015-07-29 16:33 UTC
The account labels when changed reverts back to the default value the moment another account's label is changed.

Example: Change first account from 'Main Account' to say 'Test'. That works. Change label of second account to 'Test2' and that also works BUT the label on the first account reverts back to 'Main Account. If you now edit the first account label again the label value of the second account reverts back to normal.

**Comment by ecdsa** [comment] 2015-07-29 20:09
duplicate of #1158

**Closed by ecdsa** 2015-07-29 20:09 UTC
