### ISSUE TITLE
There was a transaction that I did not do

### ISSUE THREAD

**Issue by Vitboo** [spesmilo/electrum#2434] opened 2017-05-22 11:18 UTC
A transaction appeared in my wallet, which I did not do. 
Please, help to understand - is it a hack or a mistake?
What should I report?

**Comment by bauerj** [comment] 2017-05-22 11:44
Well, did it send coins to you?

**Comment by Vitboo** [comment] 2017-05-22 11:46
All coins are transferred to another address

**Comment by Vitboo** [comment] 2017-05-22 11:58
Transaction is on the blockchain.info

**Comment by ecdsa** [comment] 2017-05-22 13:02
either you've been robbed, or you are misinterpreting change addresses.
closing, because there's not enough information in your report to say anything else.

**Closed by ecdsa** 2017-05-22 13:02 UTC

**Comment by Vitboo** [comment] 2017-05-22 13:14
I will add the necessary information. Tell me what to add?
Here is one transaction that I did not do. And the purse was closed.
https://blockchain.info/ru/tx/0ca4acf388b0710cf15a494ab40d66bc1a8c5c0845a069404ecfd6eafe1ab078

**Comment by ecdsa** [comment] 2017-05-22 16:16
well, it looks like your bitcoins have been stolen.

**Comment by Vitboo** [comment] 2017-05-22 21:54
Please tell me what I did wrong - the password from the wallet is unique, not used or where. In the password of 19 different characters and was stored only in the head.
The computer was used only by me, there are no viruses on the computer.
Prompt please, in what there can be an error
Thanks in advance

**Comment by ecdsa** [comment] 2017-05-23 06:47
either someone got access to your seed, or your computer was compromised.
the best way to prevent this is to use hardware wallets ot two-factor authentication

**Comment by Vitboo** [comment] 2017-05-23 07:16
Thank you very much for your help
Allow only one question - there were 35 addresses in the wallet. The receipt was always only for 4 of them.
After the withdrawal of money, these 4 addresses were lost from the address list.
One of my addresses- 1JauUnWnPZ34ZTW5t6FaLckRsc8xaEkr5J
And here on the screen in the list it is not
![adress](https://cloud.githubusercontent.com/assets/28862526/26342301/d031c000-3f97-11e7-8f00-79bfeefe45a9.jpg)
Please tell me why it happened, why did they disappear?
Sincerely, Vitalii

**Comment by ecdsa** [comment] 2017-05-23 08:23
addresses were probably moved to the "used" section
no, you cannot cancel an unconfirmed transaction.

you need to create a new wallet if you want two-factor authentication.
I strongly suggest that you wait for the 2.9 release, because we are bringing some improvements there 
(it will be this week)

**Comment by Vitboo** [comment] 2017-05-23 08:45
Exactly, I forgot for two-factor authentication.
Thank you very much for your help and your time.
