### ISSUE TITLE
How to import BIP39 mnemonics through the command line in Linux version?

### ISSUE THREAD

**Issue by makenong** [spesmilo/electrum#9060] opened 2024-05-21 03:33 UTC
How to import BIP39 mnemonics through the command line in Linux version?

**Comment by SomberNight** [comment] 2024-05-22 13:57
The relevant CLI/RPC commands are create/restore, however they do not support BIP39.
Duplicate of https://github.com/spesmilo/electrum/issues/6507

**Closed by SomberNight** 2024-05-22 13:57 UTC
Labels: CLI/RPC ▶
