### ISSUE TITLE
P2SH addresses on android

### ISSUE THREAD

**Issue by Coinomatron** [spesmilo/electrum#4930] opened 2018-12-13 10:21 UTC
Hi, I have a P2SH electrum electrum wallet on my desktop, is there any way to port this wallet to Android? The Electrum client on my phone doesn't seem to have the option to generate P2SH addresses. Thanks.

**Comment by ecdsa** [comment] 2018-12-13 11:18
what kind of p2sh wallet is that?

**Comment by Coinomatron** [comment] 2018-12-13 11:36
One generated on the desktop via 'options', 'BIP39 seed'.

**Comment by ecdsa** [comment] 2018-12-13 12:41
closing, duplicate of  #3388

**Closed by ecdsa** 2018-12-13 12:41 UTC
Labels: OS-android
