### ISSUE TITLE
electrum 2.9.3 not starting on OS X el capitan

### ISSUE THREAD

**Issue by ja-heller** [spesmilo/electrum#2737] opened 2017-08-12 12:32 UTC
When trying to start electrum 2.9.3 on OS X el capitan I get:

> Process:               Electrum [1393]
> Path:                  /Applications/Electrum.app/Contents/MacOS/Electrum
> Identifier:            org.pythonmac.unspecified.Electrum
> Version:               2.9.3 (2.9.3)
> Code Type:             X86-64 (Native)
> Parent Process:        ??? [1]
> Responsible:           Electrum [1393]
> User ID:               501
> 
> Date/Time:             2017-08-12 14:30:00.850 +0200
> OS Version:            Mac OS X 10.11.6 (15G1611)
> Report Version:        11
> Anonymous UUID:        52A6F259-9C6F-CC31-B306-459A9CF45793
> 
> 
> Time Awake Since Boot: 2500 seconds
> 
> System Integrity Protection: disabled
> 
> Crashed Thread:        0  Dispatch queue: com.apple.main-thread
> 
> Exception Type:        EXC_BREAKPOINT (SIGTRAP)
> Exception Codes:       0x0000000000000002, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Dyld Error Message:
>   Symbol not found: _getentropy
>   Referenced from: /Applications/Electrum.app/Contents/Frameworks/Python.framework/Versions/2.7/Python (which was built for Mac OS X 10.12)
>   Expected in: /usr/lib/libSystem.B.dylib

**Comment by ecdsa** [comment] 2017-08-12 13:24
duplicate of #2726

**Closed by ecdsa** 2017-08-12 13:24 UTC

**Comment by ja-heller** [comment] 2017-08-12 13:25
Any timeframe for new update to fix this?

**Comment by ecdsa** [comment] 2017-08-12 13:26
no timeframe.
you can revert to 2.9.2, or update to Sierra

**Comment by westonal** [comment] 2017-08-14 13:07
> you can revert to 2.9.2

So: El Capitan -> 2.9.2
Sierra or better -> 2.9.3

Please put this simple advice on the website. This must affect loads of people. Not may would dig out the github repo to find out problem.
