### ISSUE TITLE
Signing a message with SegWit address

### ISSUE THREAD

**Issue by xSkyer** [spesmilo/electrum#3341] opened 2017-11-20 17:00 UTC
Using Electrum ver. 3.0.2 and Ledger Nano S

Signing a message with a SegWit address is not possible. Electrum hangs itself after confirming signing on the Ledger device.

**Comment by SomberNight** [comment] 2017-11-20 17:03
What OS?
I suspect that this is a duplicate of #3264.
You might try https://github.com/spesmilo/electrum/issues/3264#issuecomment-345414501 for the time being.

**Comment by xSkyer** [comment] 2017-11-20 17:11
Windows 10
I was referring to this feature: https://bitcointalk.org/index.php?topic=990345.0
Pressing Ledger's buttons after closing Electrum's prompt box helped.

**Comment by SomberNight** [comment] 2017-11-20 17:14
I know what message signing is :)

> Pressing Ledger's buttons after closing Electrum's prompt box helped

Thanks, then it is a duplicate.

**Closed** 2017-11-20 17:21 UTC

**Comment by DanielBompart** [comment] 2017-11-21 03:08
please help me a little of mBTC my email daniel.bompartr@gmail.com
