### ISSUE TITLE
zcl electrum pending deposit

### ISSUE THREAD

**Issue by shotty11** [spesmilo/electrum#3809] opened 2018-01-31 04:48 UTC
i send about 1.45 zcl from cryptopia to my electrum wallet about 11 hours ago, and it still hasn't arrived into electrum. it says 'pending' on cryptopia. the wallet is connected to 1 node, and the receiving address is right. i did send it before setting up a 'description' and 'amount' on the 'receive' tab of the wallet, but the address i sent to is the same as the 'receiving address' on the receive tab. thanks

**Comment by SomberNight** [comment] 2018-01-31 04:52
dupe of https://github.com/spesmilo/electrum/issues/3808

**Closed by SomberNight** 2018-01-31 04:52 UTC
Labels: duplicate
