### ISSUE TITLE
Login through fingerprints

### ISSUE THREAD

**Issue by nicolasmaia** [spesmilo/electrum#7381] opened 2021-07-01 22:34 UTC
It would be great to have a system in which you can use biometrics like fingerprinting to log in, in lieu of your password.

**Comment by gruve-p** [comment] 2022-03-06 19:12
For Android or for the desktop versions?

**Comment by nicolasmaia** [comment] 2022-03-07 18:53
Android

**Comment by gruve-p** [comment] 2022-03-07 19:26
Duplicate of https://github.com/spesmilo/electrum/issues/7560

**Comment by ecdsa** [comment] 2022-03-08 16:36
indeed, closing as duplicate

**Closed by ecdsa** 2022-03-08 16:36 UTC
