### ISSUE TITLE
Signature must be zero for failed CHECK(MULTI)SIG operation

### ISSUE THREAD

**Issue by PRFinklemeister** [spesmilo/electrum#6621] opened 2020-09-28 18:53 UTC
- Electrum version 4.0.3
- 2 of 4 wallet 
- Signed with hardware device in wallet 1
- Exported transaction from wallet 1
- Imported transaction in Wallet 2
- Cosigned partially signed transaction with hardware device in Wallet 2
- Attempt to broadcast and always get this error...

```
The server returned an error when broadcasting the transaction. Consider trying to connect to a different server, or updating Electrum.

Signature must be zero for failed CHECK(MULTI)SIG operation
```

The same transaction will broadcast if cosigned with 2 hardware devices in the same wallet.

**Comment by SomberNight** [comment] 2020-10-05 12:08
In `Wallet`>`Information`, what is "Script type"?

What kind of keystores does wallet1 and wallet2 contain? (see `Wallet`>`Information` dialog again)
For example, is wallet1 comprised of one hw keystore and three xpubs? Same for wallet2?

What type of hardware devices do you use?

When did you originally create the wallet files? (approx with what version of Electrum?)

> `Signature must be zero for failed CHECK(MULTI)SIG operation`

Would you be willing to share an example tx that produces this error?

**Comment by SomberNight** [comment] 2020-10-14 15:42
bump. any chance at further info? I can't reproduce as-is.

**Comment by SomberNight** [comment] 2020-11-25 07:27
closing, no answer.
btw, https://github.com/spesmilo/electrum/issues/6743 might explain it

**Closed by SomberNight** 2020-11-25 07:27 UTC
Labels: awaiting-response, topic-transactions, topic-wallet
