### ISSUE TITLE
Cannot synchronize wallet with electrs (many transactions, status mismatch)

### ISSUE THREAD

**Issue by RR82** [spesmilo/electrum#7058] opened 2021-02-22 14:26 UTC
I have a legacy wallet with an address that contains a large number of transactions. When I try to open (or restore from seed) it gets stuck syncing and never completes. I am running electrum-4.0.9-x86_64.AppImage accessing only my own server (electrs 0.8.6). There are no errors reported in the logs for electrum or electrs.

While I can open this wallet with an older version of Electrum/electrs, that is not advised. The latest version of Electrum corrupts the wallet when I open it, such that neither old or new Electrum will open the wallet. Fortunately, I can recover the wallet from the seed, but only using an old version (electrum-3.3.8-x86_64.AppImage)

This is a continuation of issue 7040:
https://github.com/spesmilo/electrum/issues/7040

That issue was closed telling me to read the changelog, in answer to my question about risk. However I would like to be able to use the latest version of Electrum to access my wallet. Is there support for this?

**Comment by ecdsa** [comment] 2021-02-22 14:58
of course there is. but we cannot work with a vague statement like: "The latest version of Electrum corrupts the wallet when I open it". Please provide a traceback, or a better description.

**Comment by SomberNight** [comment] 2021-02-22 15:22
> it gets stuck syncing and never completes

Could you be more specific? For example, what does it show in the bottom left corner of the GUI?
Also, what is in the electrum (client) logs? Does the client keep reconnecting to the server?
Does the interface freeze (application not responding)?

How many addresses/txs are there in your wallet?

**Comment by RR82** [comment] 2021-02-22 16:26
Thanks for getting back to me. I'll try to describe my problem in more detail. 

In v3 it takes about two hours to sync the 900+ transactions located in the first address of the wallet, if I restore from seed. Once created, it opens/syncs in a few minutes (v3).

When I try to open this wallet on v4 I get:
Synchronizing...0/30, 10/30, 0/1, 0/2, 0/3, 0/30, 11/30 (etc., as the status messages, nothing logged to terminal and no errors in /var/log/electrs.log) and it never syncs or loads the addresses. The denominator doesn't get larger than 35 or so. Restoring from seed in v4 gives the exact same behavior.

Then, when I try to reopen this wallet in v3 (after it failing to sync/open in v4), I get the following error:
Cannot load wallet (1):
This version of Electrum is too old to open this wallet.
(highest supported storage version: 18, version of this file: 33)

I'm guessing the problem is the large number of transactions into a single address. If it's safe, I can just move the funds w/v3. Other (smaller) wallets I have work just fine in v4.

**Comment by ecdsa** [comment] 2021-02-22 17:25
well, there is no reason to write that your wallet file is corrupted. 
the log of the client is not in /var/log/electrs.log, (that is the log of your server).
try to locate the log of the client, it should be in your .electrum directory

**Comment by RR82** [comment] 2021-02-22 18:04
I enabled logging in the client, when trying to open the wallet in v4, I get:
```
INFO | network | fee_histogram [[194.1708526611328, 100029], ....lots of these entries, then:
20210222T175413.518529Z |     INFO | plugins.trezor.clientbase.TrezorClientBase | timed out
20210222T175413.518728Z |     INFO | plugins.trezor.clientbase.TrezorClientBase | clear session: [redacted]
20210222T175422.169558Z |     INFO | synchronizer.[wallet] | receiving history 1...[redacted] 960
20210222T175422.170876Z |     INFO | synchronizer.[wallet] | error: status mismatch: 1..[redacted - same address as above]
20210222T175422.250439Z |     INFO | wallet.Standard_Wallet.[wallet] | set_up_to_date: True
20210222T175422.257867Z |     INFO | storage.WalletStorage | saved /home[redacted]
20210222T175422.258010Z |    DEBUG | util.profiler | WalletStorage.write 0.0072
20210222T175422.709560Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20210222T175422.710096Z |    DEBUG | util.profiler | Abstract_Wallet.get_full_history 0.0001
20210222T175422.710232Z |    DEBUG | util.profiler | HistoryModel.refresh 0.0007
20210222T175422.710886Z |    DEBUG | util.profiler | AddressList.update 0.0000
```

I wrote 'corrupted' as I can no longer load the wallet file after v4 touches it. I have to either restore a backup file of the wallet or restore from seed.

**Comment by SomberNight** [comment] 2021-02-22 19:22
> I wrote 'corrupted' as I can no longer load the wallet file after v4 touches it. I have to either restore a backup file of the wallet or restore from seed.

This is expected. Downgrades are not supported. It's not nice but the alternative would be unmaintainable complexity.

> ```
> 20210222T175422.169558Z |     INFO | synchronizer.[wallet] | receiving history 1...[redacted] 960
> 20210222T175422.170876Z |     INFO | synchronizer.[wallet] | error: status mismatch: 1..[redacted - same address as above]
> ```

Hmm! Therein lies the problem. electrs is doing something weird.
The server sends a different history for that address than what it previously announced.

The protocol looks like this:
- client requests statushash for address. server sends statushash
- client calculates statushash locally and compares it to received statushash
- if they mismatch, client requests history for address. server sends history.
- client validates that received history corresponds to previously received statushash. --> this check fails for you.

@romanz

**Comment by ecdsa** [comment] 2021-02-22 19:59
> Hmm! Therein lies the problem. electrs is doing something weird.

you should install ElectrumX, it will probably fix this.
I guess we can close this issue?

**Comment by romanz** [comment] 2021-02-22 20:47
@SomberNight Thanks for the heads-up!

> I have a legacy wallet with an address that contains a large number of transactions.

@RR82 Could you please share the total number of transactions and the active addresses, so I could reproduce the issue locally?

**Comment by RR82** [comment] 2021-02-22 21:14
@SomberNight @ecdsa Thank you for your help!

@romanz Over 900 transactions in the first address of a legacy wallet (I'd rather not share the actual address). No issues syncing the wallet with electrum-3.3.8-x86_64.AppImage and electrs v0.7.0

**Comment by SomberNight** [comment] 2021-02-23 01:18
not sure if related but I've just realised the client has not been enforcing the sorted order of heights in get_history
(this could potentially result in a status mismatch)
(the order of heights for confirmed txs is [specified by the protocol spec](https://github.com/spesmilo/electrumx/blob/4ff6a9c4f022bcddad9c7f99d6f2f47360fb222d/docs/protocol-methods.rst#blockchainscripthashget_history))

added in https://github.com/spesmilo/electrum/commit/26d73cba0ee6ad8e07ba2262dc716a8658863899

**Comment by romanz** [comment] 2021-02-23 07:32
> No issues syncing the wallet with an older version (electrum-3.3.8-x86_64.AppImage and electrs v0.7.0).
> I only have issues with electrum-4.0.9-x86_64.AppImage and electrs 0.8.6

Could you please check whether electrum-3.3.8-x86_64.AppImage works with electrs 0.8.6?

**Comment by RR82** [comment] 2021-02-23 23:17
I tried that initially (running v3 with electrs v.0.8.6) and get a lot of errors logged to the console. I had to downgrade electrs to 0.7.0 to work with electrum v3 (which works flawlessly for me).

I just tried it again, and it loaded the wallet (previously created with 3.3.8/0.7.0) with no issues. When trying to restore from seed though, it fails to sync. The errors look to be network related (even though it's all on my LAN), so maybe something else is going on?

Error logged to the console:
```
E | asyncio | Task exception was never retrieved
future: <Task finished coro=<subscribe_to_address() done, defined at /tmp/.mount_electraXjey9/usr/lib/python3.6/site-packages/electrum/synchronizer.py:104> exception=RequestTimedOut("request timed out: ('blockchain.scripthash.subscribe', ['6...[redacted]']) (id: 14)",)>
Traceback (most recent call last):
  File "/tmp/.mount_electraXjey9/usr/lib/python3.6/site-packages/electrum/interface.py", line 115, in send_request
    timeout)
  File "/tmp/.mount_electraXjey9/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/tmp/.mount_electraXjey9/usr/lib/python3.6/site-packages/aiorpcx/session.py", line 525, in send_request
    return await self._send_concurrent(message, future, 1)
  File "/tmp/.mount_electraXjey9/usr/lib/python3.6/site-packages/aiorpcx/session.py", line 495, in _send_concurrent
    return await future
  File "/tmp/.mount_electraXjey9/usr/lib/python3.6/site-packages/aiorpcx/curio.py", line 324, in __aexit__
    raise TaskTimeout(self._secs) from None
aiorpcx.curio.TaskTimeout: task timed out after 180s

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/.mount_electraXjey9/usr/lib/python3.6/site-packages/electrum/synchronizer.py", line 109, in subscribe_to_address
    await self.session.subscribe('blockchain.scripthash.subscribe', [h], self.status_queue)
  File "/tmp/.mount_electraXjey9/usr/lib/python3.6/site-packages/electrum/interface.py", line 137, in subscribe
    result = await self.send_request(method, params)
  File "/tmp/.mount_electraXjey9/usr/lib/python3.6/site-packages/electrum/interface.py", line 117, in send_request
    raise RequestTimedOut(f'request timed out: {args} (id: {msg_id})') from e
electrum.interface.RequestTimedOut: Network request timed out.
```
It keeps retrying, but not succeeding...

**Comment by SomberNight** [comment] 2021-02-27 10:34
Are you able to test with the client from the master branch? Or with ElectrumX?

**Comment by RR82** [comment] 2021-03-07 19:50
I've done some additional testing after upgrading electrs to v0.8.8. Here are the results with various versions of Electrum and Electrs:

electrum ver with electrs ver
3.3.8 with 0.7.0
- new wallet - loads correctly
- from existing wallet - loads correctly

4.0.9 with 0.7.0:
	electrum error logged to terminal, a bunch, ends with:
```
electrum.interface.RequestCorrupted: fees must be in decreasing order
```

3.3.8 with 0.8.8
- new wallet - does not sync; correct addresses, but blank amount and 0 transactions
- from existing wallet - loads correctly
I still get the 'error status mismatch' in the logs with this combo, but everything looks OK

4.0.9 appimage with 0.8.8
- new wallet - does not sync; correct addresses, but blank amount and 0 transactions
- from existing wallet - loads correctly
I still get the 'error status mismatch' in the logs with this combo, but everything looks OK

latest 4.0.9 (pulled Mar 5) with 0.8.8
- new wallet - does not sync; correct addresses, but blank amount and 0 transactions
- from existing wallet - does not sync; correct addresses, but blank amount and 0 transactions

error logged to the terminal:
```
E/i | interface.[192.xx:50002] | Exception in run: SynchronizerFailure('timeout reached waiting for addr 15...: history still stale')
Traceback (most recent call last):
  File "/home/.../electrum/electrum/util.py", line 1095, in wrapper
    return await func(*args, **kwargs)
  File "/home/.../electrum/electrum/interface.py", line 487, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/home/.../electrum/electrum/interface.py", line 510, in run
    await self.open_session(ssl_context)
  File "/home/.../electrum/electrum/interface.py", line 657, in open_session
    await group.spawn(self.monitor_connection)
  File "/home/.../.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/home/.../.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/home/.../electrum/electrum/synchronizer.py", line 83, in _run_tasks
    await group.spawn(self.main())
  File "/home/.../.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/home/.../.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/home/.../electrum/electrum/synchronizer.py", line 196, in disconnect_if_still_stale
    raise SynchronizerFailure(f"timeout reached waiting for addr {addr}: history still stale")
electrum.synchronizer.SynchronizerFailure: timeout reached waiting for addr 15...: history still stale
```
I have not had the chance to try ElectrumX yet. Let me know if there's additional information I can provide. Thanks again for helping me with this issue!

**Comment by SomberNight** [comment] 2021-03-07 19:57
I assume your wallet has many addresses; presumably it is deterministic (e.g. xpub or seed).
Could you try testing with an imported wallet that only has this single `15...` address in it?
Also, if you can reproduce like that, while it violates your privacy, it might help if you privately shared that address with romanz.

**Comment by romanz** [comment] 2021-03-07 20:01
My PGP key can be found here: https://romanzey.de/pgp.txt

**Comment by RR82** [comment] 2021-03-07 22:16
Yes, same issues with creating a watch-only wallet with the single address. E-mail sent to @romanz

**Comment by romanz** [comment] 2021-03-08 17:51
Thanks @RR82, got it.
BTW, could you please share which hardware (CPU/RAM/disk) are you running bitcoind/electrs on?

**Comment by RR82** [comment] 2021-03-08 18:08
Most of my testing has been on a x86 VM (myNode) w/4GB allocated and a 1TB SSD for the blockchain and indexer data. I manually changed/upgraded the electrs version on myNode for testing.

I also did more limited testing with a RPi (Raspiblitz) 8GB and a RockPRO64 (myNode) 4GB (each with their own 1TB SSD) with similar results.

**Comment by romanz** [comment] 2021-04-09 14:02
Could you please try the [p2p branch](https://github.com/romanz/electrs/commits/p2p)?
It now uses the correct algorithm for computing the status hash - so no mismatches should happen.

It uses a [different DB schema](https://github.com/romanz/electrs/blob/5d3457b764778cffebe991ce5aab812b85a1e30e/doc/schema.md) - so it'll require re-indexing the blockchain.
It takes ~4 hours to sync using a HDD - hopefully less on an SSD :)
Querying a "popular" address (taken randomly from https://blockstream.info) with ~1.2k transactions should take <1 minute (with cold cache), and <1 second (with hot cache):
```
$ ./query.sh bitcoin 3Fzn4esuf5gNQEPE7ZBzWSyL4VqCiK3A2L
<snip>
[2021-04-09T13:57:47.906Z INFO  electrs::chain] loading 678451 headers, tip=00000000000000000002700c0f6a8507f21a65909b3a86cc5e8dbf977501fba7
[2021-04-09T13:57:49.079Z INFO  electrs::chain] chain updated: tip=00000000000000000002700c0f6a8507f21a65909b3a86cc5e8dbf977501fba7, height=678451
[2021-04-09T13:58:15.205Z INFO  query] 3Fzn4esuf5gNQEPE7ZBzWSyL4VqCiK3A2L has 0.09438393 BTC
[2021-04-09T13:58:15.205Z INFO  query] total: 0.09438393 BTC
[2021-04-09T13:58:25.527Z INFO  query] 3Fzn4esuf5gNQEPE7ZBzWSyL4VqCiK3A2L has 0.09438393 BTC
[2021-04-09T13:58:25.527Z INFO  query] total: 0.09438393 BTC
[2021-04-09T13:58:35.791Z INFO  query] 3Fzn4esuf5gNQEPE7ZBzWSyL4VqCiK3A2L has 0.09438393 BTC
[2021-04-09T13:58:35.791Z INFO  query] total: 0.09438393 BTC
[2021-04-09T13:58:46.049Z INFO  query] 3Fzn4esuf5gNQEPE7ZBzWSyL4VqCiK3A2L has 0.09438393 BTC
[2021-04-09T13:58:46.049Z INFO  query] total: 0.09438393 BTC
[2021-04-09T13:58:56.315Z INFO  query] 3Fzn4esuf5gNQEPE7ZBzWSyL4VqCiK3A2L has 0.09438393 BTC
[2021-04-09T13:58:56.315Z INFO  query] total: 0.09438393 BTC
```

**Comment by SomberNight** [comment] 2021-04-10 02:43
>  It now uses p2p-based sync (instead of JSON-RPC) and also uses the correct algorithm for computing the status hash - so no mismatches should happen.

Ah, so there was a bug in electrs, right?
Asking because in that case I would close this issue.

**Comment by romanz** [comment] 2021-04-10 07:53
Yes, unfortunately the current code (in `master` branch) doesn't order same-block transactions correctly:
https://github.com/romanz/electrs/issues/297#issuecomment-695040748
It uses only the block height - when it should also include the position within the block:
https://github.com/romanz/electrs/blob/f9cf5386d1b5de6769ee271df5eef324aa9491bc/src/query.rs#L101

**Closed** 2021-04-10 14:12 UTC
Labels: topic-network 🕸
