### ISSUE TITLE
Hackering Electrum

### ISSUE THREAD

**Issue by BrunoCrime** [spesmilo/electrum#3468] opened 2017-12-07 15:24 UTC
Is possible? Today are missing all my funds and i see just like attached, who is responsable?
![1e](https://user-images.githubusercontent.com/34344740/33722711-072116a0-db6b-11e7-9735-1ad1ca10eb9e.JPG)

**Comment by hachre** [comment] 2017-12-07 15:31
Duplicate of https://github.com/spesmilo/electrum/issues/3466

**Closed** 2017-12-07 15:35 UTC
