### ISSUE TITLE
problems with funds

### ISSUE THREAD

**Issue by rdianini** [spesmilo/electrum#4605] opened 2018-08-03 15:37 UTC
<!-- Note: This website is for bug reports, not general questions.
Do not post issues about non-bitcoin versions of Electrum. --good afternoon, I transferred my wallet blockchain to the electrum, but all my background was as watch-only. Since I'm new I do not know how to use my funds. In the wallet says that is to put the seed or private key..but which of the electrum or the blockchain, completely lost..thank you

**Comment by SomberNight** [comment] 2018-08-03 17:29
please don't open multiple issues for the same problem
duplicate of https://github.com/spesmilo/electrum/issues/4604

**Closed by SomberNight** 2018-08-03 17:29 UTC
