### ISSUE TITLE
Error mac os 10.9

### ISSUE THREAD

**Issue by eret1k** [spesmilo/electrum#3716] opened 2018-01-14 10:42 UTC
I downloaded latest packege from this link https://download.electrum.org/3.0.5/electrum-3.0.5.dmg
But i have error when i start it:

`Last login: Sun Jan 14 13:28:26 on ttys001
MacBook-Pro-eret1k:~ eret1k$ /Users/eret1k/Desktop/Electrum.app/Contents/MacOS/Electrum
[940] Error loading Python lib '/var/folders/8b/vx_pt1qj6fl4827jm0rfpz_40000gn/T/_MEISAKOrL/Python': dlopen: dlopen(/var/folders/8b/vx_pt1qj6fl4827jm0rfpz_40000gn/T/_MEISAKOrL/Python, 10): Symbol not found: _faccessat
  Referenced from: /var/folders/8b/vx_pt1qj6fl4827jm0rfpz_40000gn/T/_MEISAKOrL/Python
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/8b/vx_pt1qj6fl4827jm0rfpz_40000gn/T/_MEISAKOrL/Python

MacBook-Pro-eret1k:~ eret1k$ 
`
OS X version 10.9.5 13F1911

Can you fix it, or 10.9 now not supported?

**Comment by ecdsa** [comment] 2018-01-14 10:43
dupe of #3685

**Closed by ecdsa** 2018-01-14 10:43 UTC
