### ISSUE TITLE
Electrum crashes when confirming/denying transactions on the Ledger nano s

### ISSUE THREAD

**Issue by Highflyer108** [spesmilo/electrum#3332] opened 2017-11-19 13:02 UTC
On 3.0.2 and it always crashes.

**Comment by jeikoo** [comment] 2017-11-19 13:58
Confirm with 3.0.2. No crash but dialog becomes unresponsive and has to be killed.

Nano S firmware 1.3.1 and Bitcoin app 1.1.10. Windows 10/64. Electrum full install and standalone, no difference.

**Comment by Highflyer108** [comment] 2017-11-19 14:12
Yeah sorry it doesn’t CTD I meant it just becomes unresponsive.

**Comment by SomberNight** [comment] 2017-11-19 15:16
duplicate of https://github.com/spesmilo/electrum/issues/3264

**Comment by ecdsa** [comment] 2017-11-20 15:54
ok, closing

**Closed by ecdsa** 2017-11-20 15:54 UTC
