### ISSUE TITLE
Encrypt interface in command line

### ISSUE THREAD

**Issue by twhite00** [spesmilo/electrum#5521] opened 2019-07-21 16:04 UTC
I used Electrum-3.3.3 on Ubuntu16.04 PC,
I encrypt a message with this command:
“./run_electrum encrypt mypubkey hello”
and it return a error “assertion error”

**Comment by ecdsa** [comment] 2019-07-21 16:11
please try with the latest version.
if the error still occurs, post the traceback

**Comment by ecdsa** [comment] 2019-08-14 10:12
closing: no answer, and cannot reproduce the issue

**Closed by ecdsa** 2019-08-14 10:12 UTC
Labels: CLI/RPC, awaiting-response
