### ISSUE TITLE
Cannot create new segwit wallet, getting BEX (0xc0000409) in ucrtbase.dll / "TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by Eegee** [spesmilo/electrum#3651] opened 2018-01-05 00:24 UTC
I'm getting a crash with Electrum 3.0.3 on Windows 10 Pro (10.0.16299) when choosing to create a new segwit wallet via the wizard. Path: filename "segwit_wallet", Standard wallet, Create a new seed, Segwit, *crash*

I've tried Windows 10 safe mode, but that didn't make a difference.

Event log data for "Application error" (in Dutch):
````
Naam van toepassing met fout: electrum-3.0.3.exe, versie: 0.0.0.0, tijdstempel: 0x597f4ad5
Naam van module met fout: ucrtbase.dll, versie: 10.0.16299.125, tijdstempel: 0x9e3394c7
Uitzonderingscode: 0xc0000409
Foutmarge: 0x000933ab
Id van proces met fout: 0x8b4
Starttijd van toepassing met fout: 0x01d385b97340425b
Pad naar toepassing met fout: D:\Program Files (x86)\Electrum\electrum-3.0.3.exe
Pad naar module met fout: C:\WINDOWS\System32\ucrtbase.dll
Rapport-id: ***
Volledige pakketnaam met fout: 
Relatieve toepassings-id van pakket met fout: 
````
Event log data for "Windows error reporting":
````
Foutbucket 2261398494278761912, type 5
Naam van gebeurtenis: BEX
Antwoord: Niet beschikbaar
Id van CAB-bestand: 0

Handtekening van probleem:
P1: electrum-3.0.3.exe
P2: 0.0.0.0
P3: 597f4ad5
P4: ucrtbase.dll
P5: 10.0.16299.125
P6: 9e3394c7
P7: 000933ab
P8: c0000409
P9: 00000007
P10: 
````
I managed to run the Python3 version instead of the Windows binary and with that the console mentions the following:

````
D:\Electrum-3.0.3>c:\Python36\python.exe electrum
Traceback (most recent call last):
  File "D:\Electrum-3.0.3\gui\qt\main_window.py", line 444, in new_wallet
    self.gui_object.start_new_window(full_path, None)
  File "D:\Electrum-3.0.3\gui\qt\__init__.py", line 199, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "D:\Electrum-3.0.3\gui\qt\installwizard.py", line 274, in run_and_get_wallet
    self.run(action)
  File "D:\Electrum-3.0.3\lib\base_wizard.py", line 60, in run
    f(*args)
  File "D:\Electrum-3.0.3\lib\base_wizard.py", line 87, in new
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.on_wallet_type)
  File "D:\Electrum-3.0.3\gui\qt\installwizard.py", line 91, in func_wrapper
    run_next(*out)
  File "D:\Electrum-3.0.3\lib\base_wizard.py", line 105, in on_wallet_type
    self.run(action)
  File "D:\Electrum-3.0.3\lib\base_wizard.py", line 60, in run
    f(*args)
  File "D:\Electrum-3.0.3\lib\base_wizard.py", line 137, in choose_keystore
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.run)
  File "D:\Electrum-3.0.3\gui\qt\installwizard.py", line 91, in func_wrapper
    run_next(*out)
  File "D:\Electrum-3.0.3\lib\base_wizard.py", line 60, in run
    f(*args)
  File "D:\Electrum-3.0.3\lib\base_wizard.py", line 391, in choose_seed_type
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.run)
  File "D:\Electrum-3.0.3\gui\qt\installwizard.py", line 91, in func_wrapper
    run_next(*out)
  File "D:\Electrum-3.0.3\lib\base_wizard.py", line 60, in run
    f(*args)
  File "D:\Electrum-3.0.3\lib\base_wizard.py", line 393, in create_segwit_seed
    def create_segwit_seed(self): self.create_seed('segwit')
  File "D:\Electrum-3.0.3\lib\base_wizard.py", line 402, in create_seed
    self.show_seed_dialog(run_next=f, seed_text=seed)
  File "D:\Electrum-3.0.3\gui\qt\installwizard.py", line 81, in func_wrapper
    out = func(*args, **kwargs)
  File "D:\Electrum-3.0.3\gui\qt\installwizard.py", line 384, in show_seed_dialog
    slayout = SeedLayout(seed=seed_text, title=title, msg=True, options=['ext'])
  File "D:\Electrum-3.0.3\gui\qt\seed_dialog.py", line 132, in __init__
    self.seed_warning.setText(seed_warning_msg(seed))
  File "D:\Electrum-3.0.3\gui\qt\seed_dialog.py", line 48, in seed_warning_msg
    ]) % len(seed.split())
TypeError: not all arguments converted during string formatting
````
If more information is needed, I am happy to provide it.

**Comment by SomberNight** [comment] 2018-01-05 00:40
I think this is a duplicate of https://github.com/spesmilo/electrum/issues/3405
Should be fixed in the next release (it is fixed on master).

The crash is due to a faulty translation string. As a workaround, you can either
- run from source (latest git HEAD / master)
- change the locale/language to English or another lang

**Closed by SomberNight** 2018-01-05 00:40 UTC
