### ISSUE TITLE
getrequest improvment

### ISSUE THREAD

**Issue by klerms** [spesmilo/electrum#1887] opened 2016-08-07 00:17 UTC
Hi,

firstly, thank you for your excellent work on this project.

I use old merchant.py script, which isn't supported anymore (I have to fix it almost every time a new relase of Electrum is published). The reason for that is, that I want to accept payments to my website with 3 confirmations only.

My modified merchant.py sends the following information to my website when an address status changes: (address, amount, number_of_confirmations). This is very important, because I can inform my clients about the payment status (BROADCASTED, WAITING_FOR_LAST_CONFIRMATION, CONFIRMED)

I suppose that there is no efficient way how can this be achieved via Electrun API. Could you please change the API to contain this functionality?

For example adding lower number of confirmations of all incoming transactions (verified by SPV) and sum of incoming transactions to the getrequest result?

... or adding list of incoming txids to getrequest result (SPV verified)
... or implementing a no-network-request version of getaddresshistory (SPV verified)

Regards

**Comment by ecdsa** [comment] 2016-09-30 08:39
I agree we will have to improve that.

**Comment by ecdsa** [comment] 2016-10-05 09:05
would it work if I add a configuration variable for the number of confirmations that is required?

**Comment by ecdsa** [comment] 2016-10-10 15:19
closing, since duplicate of #1757

**Closed by ecdsa** 2016-10-10 15:19 UTC
