### ISSUE TITLE
Does not clear old addresses after creating new wallet.

### ISSUE THREAD

**Issue by neocogent** [spesmilo/electrum#1100] opened 2015-03-21 00:58 UTC
I just created a new test wallet. Select any address and right-clicking, choose "Sign/Verify Message".

Dialog pops up. Enter msg. Click Sign. Always get "Address not found" message, shows address and it appears correct.

Come back a few minutes later and different (more, ~20) addresses are in list and they're different from when first created wallet. These ones work for signing.

Now appears when creating a new wallet the addresses from previously loaded wallet do not get cleared out until after sync'ing or some other long process. So any operation is confusing and error prone.

Wallet should clear UI contents upon creation for privacy reasons and just generally not confusing the heck out of people. I could have selected copied/pasted an address in my new wallet and given it to someone without realizing it was from another wallet.

**Comment by ecdsa** [comment] 2015-03-21 06:39
I cannot reproduce that.. what are the exact steps that lead to it?

**Comment by Tafelpoot** [comment] 2015-03-25 14:19
Sounds like he has an older wallet with gap limit 5 as default_wallet. When creating a new wallet, it takes a while before all the new addresses are loaded. He finds this confusing.

**Comment by ecdsa** [comment] 2015-04-03 17:16
closing: cannot reproduce, and the OP is not answering

**Closed by ecdsa** 2015-04-03 17:16 UTC
