### ISSUE TITLE
NoneType oject has no attribute 'get' when sending bitcoins 2.7.12

### ISSUE THREAD

**Issue by kiersrj** [spesmilo/electrum#2072] opened 2016-12-08 16:26 UTC
When trying to send bitcoins i get the error above. Attached is a screenshot.

![electrum-error](https://cloud.githubusercontent.com/assets/24459411/21017920/db987b62-bd62-11e6-8695-28d6dba1d366.PNG)

**Comment by ecdsa** [comment] 2016-12-09 07:43
can you provide full details ? (wallet type, etc)

**Comment by CoolBlackFriend** [comment] 2016-12-09 13:17
I'm helping kiersrj with this issue. When you say wallet type, what do you mean? The user is running Electrum 2.7.12 on Windows 10, and using the electrum exe file.

**Comment by ecdsa** [comment] 2016-12-21 06:45
does the wallet have a seed?

**Comment by ecdsa** [comment] 2016-12-21 11:38
closing since duplicate of #2050

**Closed by ecdsa** 2016-12-21 11:38 UTC

**Comment by ecdsa** [comment] 2017-01-05 07:32
can you provide a full screenshot?
