### ISSUE TITLE
Unbroadcasted transaction appearing their_ctx_htlc_0 **********

### ISSUE THREAD

**Issue by PanosChtz** [spesmilo/electrum#9050] opened 2024-05-13 19:19 UTC
Had lightning channels open (both ACINQ and Trampoline).
Today I all of my lightning payments were failing for no reason. Was trying both trampoline and non-trampoline.
Eventually one of my channels got closed without me selecting to do so. Also an unbroadcasted transaction appears as in title. The transaction date currently is at 677 blocks and has a positive amount. If I delete it, that transaction reappears. Is lightning broken?

**Comment by ecdsa** [comment] 2024-05-14 07:53
no, it means the other party force-closed the channel

**Comment by ecdsa** [comment] 2024-05-30 10:49
closing. probably not a bug. user did not provide txid.

**Closed by ecdsa** 2024-05-30 10:49 UTC
