### ISSUE TITLE
Segwit offline signing issue

### ISSUE THREAD

**Issue by Husogutr** [spesmilo/electrum#3558] opened 2017-12-19 10:21 UTC
Transactions created on watch-only wallet with Segwit (bech32) input have 192 (223 w/ change) bytes size, which is similar to non-Segwit wallet. However, transactions created on seed-entered wallet have 111 (142 w/ change) bytes size.

These transactions are absolutely the same. I use Electrum 3.0.3.

Is this a bug? I don't like the idea signing Txs with seed entered.

**Comment by SomberNight** [comment] 2017-12-19 15:22
Hi. Are you the OP of this [reddit thread](https://www.reddit.com/r/Electrum/comments/7k8prn/segwit_offline_signing_issue/)?

I could not reproduce this.
- What is `Wallet type` and `Script type` in `Wallet`>`Information`? (Is it `standard` and `p2wpkh` respectively?)
- What happens when you compare the byte size of the signed transactions? Those should either be the same (as the txns should be identical) or some of them would be invalid bitcoin txns.
- What happens if you copy the raw unsigned txn from the preview dialog, and then use `Tools`>`Load transaction` to load it back? Does the size change?
- Would you be able to provide raw unsigned transactions? You can use a testnet wallet for this if you want. Note that an unsigned transaction contains your master public key (xpub).

**Comment by seanneko** [comment] 2018-01-20 02:08
I have the same problem in Electrum 3.0.5. Steps to produce:

1) Create a new wallet, select "Import Bitcoin addresses or private keys".
2) Enter a segwit public key on the next screen. In my case I'm using a P2SH-P2WPKH address with a 3 prefix.
3) Create a transaction with 1 input and 1 output. The size displayed is 190 bytes. This is the normal size for a non-segwit transaction.

**Comment by Raulo** [comment] 2018-01-21 11:00
I confirm the bug in 275ba8559.

It's not just a problem with size. The transaction is incorrectly serialized. The problem is both for P2SH-P2WPKH and P2WPKH.

Testcase on testnet. Create a watching only wallet with address 2N1Qeo139CB8yu1Fwik4vbLjaWGoSBKs7G6

Create a transaction sending to itself. Save to disk. Serialized transaction is 

0100000001581a2cbbe8a2c9e19790300bd6a19a052434ce83195f063f38dbed7f24968585000000001b01ff18fda914598974dcbfe76436254ec494eccd34c6b30f727b87fdffffff013c8f01000000000017a914598974dcbfe76436254ec494eccd34c6b30f727b8708391300

Deserialized is

{
    "inputs": [
        {
            "address": "2N1Qeo139CB8yu1Fwik4vbLjaWGoSBKs7G6",
            "num_sig": 1,
            "prevout_hash": "858596247feddb383f065f1983ce3424059aa1d60b309097e1c9a2e8bb2c1a58",
            "prevout_n": 0,
            "pubkeys": [
                "fda914598974dcbfe76436254ec494eccd34c6b30f727b87"
            ],
            "scriptSig": "01ff18fda914598974dcbfe76436254ec494eccd34c6b30f727b87",
            "sequence": 4294967293,
            "signatures": [
                null
            ],
            "type": "p2pkh",
            "x_pubkeys": [
                "fda914598974dcbfe76436254ec494eccd34c6b30f727b87"
            ]
        } 
    ],
    "lockTime": 1259784,
    "outputs": [
        {
            "address": "2N1Qeo139CB8yu1Fwik4vbLjaWGoSBKs7G6",
            "prevout_n": 0,
            "scriptPubKey": "a914598974dcbfe76436254ec494eccd34c6b30f727b87",
            "type": 0,
            "value": 102204
        }
    ],
    "version": 1
}

It's clearly wrong: "type": "p2pkh". Surprisingly, it can be signed in the non-watching wallet but the transaction is obviously invalid. 

Create the same wallet with private key corresponding to address 2N1Qeo139CB8yu1Fwik4vbLjaWGoSBKs7G6: cg1r8SXR246KvNKJ1xfoqfEYgbYSFpkCxmQb7J1FyCsvZPeJh8v4

The serialized transaction is 
01000000000101581a2cbbe8a2c9e19790300bd6a19a052434ce83195f063f38dbed7f249685850000000017160014eaf93b3d4942fca0f800e37631ea181975d79a25fdffffff01748f01000000000017a914598974dcbfe76436254ec494eccd34c6b30f727b87fefffffffffa8f0100000000000201ff53ff049d7cb20394ee2ec08000000029493969d5af07bdca312802a84f43f87f2522ee84d4f880947d10849675bd3d0262c1521f5fd87bbb4055f9f6e866d3eaebd179d5bfb9adac3aec682f12948a6700001a0008391300

Deserialized:

{
    "inputs": [
        {
            "address": "2N1Qeo139CB8yu1Fwik4vbLjaWGoSBKs7G6",
            "num_sig": 1,
            "prevout_hash": "858596247feddb383f065f1983ce3424059aa1d60b309097e1c9a2e8bb2c1a58",
            "prevout_n": 0,
            "pubkeys": [
                "022c70522971fd4bd90ff33a0e7477c65c5b22fba28daaa5f06255b35bb519faeb"
            ],
            "scriptSig": "160014eaf93b3d4942fca0f800e37631ea181975d79a25",
            "sequence": 4294967293,
            "signatures": [
                null
            ],
            "type": "p2wpkh-p2sh",
            "value": 102394,
            "x_pubkeys": [
                "ff049d7cb20394ee2ec08000000029493969d5af07bdca312802a84f43f87f2522ee84d4f880947d10849675bd3d0262c1521f5fd87bbb4055f9f6e866d3eaebd179d5bfb9adac3aec682f12948a6700001a00"
            ]
        }
    ],
    "lockTime": 1259784,
    "outputs": [
        {
            "address": "2N1Qeo139CB8yu1Fwik4vbLjaWGoSBKs7G6",
            "prevout_n": 0,
            "scriptPubKey": "a914598974dcbfe76436254ec494eccd34c6b30f727b87",
            "type": 0,
            "value": 102260
        }
    ],
    "version": 1
}

Now the type and serialization is correct.

**Comment by dabura667** [comment] 2018-01-21 11:05
Can you try it with ypub and zpub instead of addresses?

**Comment by Raulo** [comment] 2018-01-21 11:53
From ypub and zpub, the transaction is correct.

**Comment by dabura667** [comment] 2018-01-21 12:04
The reason for this is that addresses do not contain scriptType information in them, so there is no way for Electrum to know what kind of script they are.

Please use ypub and zpub for offline signing, not addresses.

**Comment by SomberNight** [comment] 2018-01-21 12:16
Oh if that is what OP meant, I'm closing this in favour of https://github.com/spesmilo/electrum/issues/3738

**Closed by SomberNight** 2018-01-21 12:16 UTC

**Comment by Raulo** [comment] 2018-01-21 12:18
Well, I wanted to create a wallet with mixed P2SH-P2WPKH and P2WPKH addresses and sign a transaction from both of the address types offline. 

Currently, it is not possible to have a proper mixed-type wallet. I'd like to use a bech32 wallet but to receive I need also P2SH-P2WPKH wallet and it is not possible to combine transactions from both types.
