### ISSUE TITLE
Virustotal reports 9/64 threats (trojan) on v3.3.2 windows installer

### ISSUE THREAD

**Issue by uFire** [spesmilo/electrum#4974] opened 2018-12-28 11:30 UTC
I've downloaded the v3.3.2 windows installer and I was surprised that it is almost double in size than previous release. I checked it for viruses at virustotal.com and it looks too red to install - 9 out of 64 antiviruses reported a trojan. Any comments from developers? Or maybe this is a false positive?
![screenshot 2018-12-28 13 22 37](https://user-images.githubusercontent.com/19604379/50514078-a0312380-0aa4-11e9-93ae-7648ded1041e.png)

**Comment by Fer646** [comment] 2018-12-28 12:19
same viruses  i downloads ver 3.3.2 from official site-  and i check by gpg it sign by ThomasV  '0x2bd5824b7f9470e6'  6694 D8DE 7BE8 EE56 31BE D950 2BD5 824B 7F94 70E6   
why so?

**Comment by SomberNight** [comment] 2018-12-28 21:20
Duplicate of https://github.com/spesmilo/electrum/issues/3198
Please try to search existing issues first next time

Re larger size, see e.g. https://github.com/spesmilo/electrum/issues/4815

**Closed by SomberNight** 2018-12-28 21:20 UTC
