### ISSUE TITLE
Adjust nLockTime (custom locktime)

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#1685] opened 2016-02-22 22:53 UTC
As an advanced feature (hidden from regular use), it would be cool if the nLockTime could be adjusted.
The broadcast button should probably stay disabled for such transactions.

**Comment by Rspigler** [comment] 2017-05-06 00:48
I was just about to write my own Issue under this same principle in order to enable Electrum users to activate what is often referred to as (and often requested for) a Dead Man's Switch.  I could be wrong, but all that would really be required is a GUI for nLockTime (possibly only enable this under advance settings, as suggested by @ulrichard)

As far as I can tell, Electrum would be the first wallet to enable this feature.

**Comment by Rspigler** [comment] 2017-05-11 03:03
See (https://github.com/spesmilo/electrum/issues/2401) for updated issue/feature request with bounty attached.

**Comment by ysangkok** [comment] 2018-01-09 13:40
@Rspigler Does the bounty apply to this issue too?

**Comment by Rspigler** [comment] 2018-01-16 15:37
@ysangkok, my apologies for the late response.

This issue should probably be closed; @bauerj wrote a great implementation in PR https://github.com/spesmilo/electrum/pull/2405. While this wasn't merged due to @ecdsa believing that the use case wasn't common enough to confuse users with, the work has already been done, and the payment has been sent.  

This can be confirmed here:  https://btc.blockr.io/tx/info/2f9e763141efaa405dccfa4d5b9ea8ec5c9e5eae02d081917e3f20df67a2e05b.

**Comment by botweb** [comment] 2018-11-12 18:56
I would love to have this feature. @ecdsa Wouldn't it be an option to allow such advanced features through a new tab in settings? That way power users and newbies get served.

**Closed** 2020-03-01 08:15 UTC
Labels: enhancement
