### ISSUE TITLE
Fully signed multisig transaction silently fails

### ISSUE THREAD

**Issue by jlopp** [spesmilo/electrum#4807] opened 2018-10-27 14:59 UTC
This wallet setup works correctly on Windows and Linux but something is going wrong on OS X.

Electrum 3.2.3 on testnet
OS X Sierra
Create 3-of-5 p2sh wrapped segwit wallet
First pubkey: import from Ledger Nano S with derivation path m/49/1/0
Second pubkey: import from Trezor One with derivation path m/49/1/0
Third pubkey: import from Trezor One with derivation path m/49/1/0
Fourth pubkey: import master upub
Fifth pubkey: import master ubpub

When I create a transaction, Electrum correctly prompts me for a signature from the Nano S, which I plug in and apply. It then prompts for a signature from the first Trezor, which I plug in and apply. It finally asks for a signature from the second Trezor, which I plug in and apply. But then instead of displaying the fully signed transaction and making it available to broadcast, it says that the transaction is still only partially signed with 2 signatures. We had a user report this issue to us and I've managed to reliably reproduce it.

**Comment by jlopp** [comment] 2018-11-25 22:57
OK, create a 2 of 2 p2sh wrapped segwit wallet with 2 Trezor Ones on path m/49/1/0 and when I try to spend from it it successfully signs with both signatures. However, upon attempting to broadcast the transaction is rejected:

`error: {'code': 1, 'message': 'the transaction was rejected by network rules.\n\n16: bad-txns-vin-empty\n[0100000000010144093c5b4aa5474ba8e194b7238faf9e5a6b90ec9e3e39d49ef14feeab3402f70100000023220020fd5acdc71edcec52407bcbdca64ecf635be8ec9a208af0b820d03cd31cf70afafdffffff0181410f000000000017a9142648f1a865759c97d97602276e1af978f5b394128704004730440220224268e43d640d9dcf8b5cd25f903eaabbdc9464dab57b83277e5131f8890bd202200a623f343b81d9c1c0c0b4f2cd2e4fbaccbe15cf0e8a1654c04d4eec6582a35601473044022046e859a34249a9ae0bae395713bb5079f946a7a118ee4cbdc8a38cc96ad4cba6022052cfbec675aad17d054bcb25e0f8a9fee612b1a955b968cccf57c66891475e4801475221028d8cde317b99853bba911cc83f921154407161a6b40451f591d23ef6a51d8fb521037d5b226f1ec67247013be73b4895174ab3db1eaeeae4ab459b59661c01af8f0452ae720d1600]'}`

**Comment by SomberNight** [comment] 2018-11-25 22:59
Please try with another server.
`electrum-testnet-unlimited.criptolayer.net` on testnet is apparently running some shitty bitcoind (old BU?....) that does not accept segwit txns into its mempool.

**Comment by SomberNight** [comment] 2018-11-25 23:06
Note: my testnet node accepts it.

```
$ bitcoin-cli testmempoolaccept \[\"0100000000010144093c5b4aa5474ba8e194b7238faf9e5a6b90ec9e3e39d49ef14feeab3402f70100000023220020fd5acdc71edcec52407bcbdca64ecf635be8ec9a208af0b820d03cd31cf70afafdffffff0181410f000000000017a9142648f1a865759c97d97602276e1af978f5b394128704004730440220224268e43d640d9dcf8b5cd25f903eaabbdc9464dab57b83277e5131f8890bd202200a623f343b81d9c1c0c0b4f2cd2e4fbaccbe15cf0e8a1654c04d4eec6582a35601473044022046e859a34249a9ae0bae395713bb5079f946a7a118ee4cbdc8a38cc96ad4cba6022052cfbec675aad17d054bcb25e0f8a9fee612b1a955b968cccf57c66891475e4801475221028d8cde317b99853bba911cc83f921154407161a6b40451f591d23ef6a51d8fb521037d5b226f1ec67247013be73b4895174ab3db1eaeeae4ab459b59661c01af8f0452ae720d1600\"\]
[
  {
    "txid": "8df550fdec13445eab4ed1d231dfc2701e66897c91e8ee3313c70775200faaf7",
    "allowed": true
  }
]
```

**Comment by jlopp** [comment] 2018-11-26 13:46
Back to the drawing board. Anything else you'd like me to test?

**Comment by matejcik** [comment] 2019-10-10 15:59
this might effectively be a duplicate of #4806 (Electrum not recognizing device unplug/replug), which is now resolved.

**Comment by SomberNight** [comment] 2019-10-10 16:21
Okay, makes sense.

**Closed by SomberNight** 2019-10-10 16:21 UTC
Labels: hw-trezor, topic-transactions
