### ISSUE TITLE
Ecryption of wallet files from hardware wallet

### ISSUE THREAD

**Issue by steff123** [spesmilo/electrum#6900] opened 2020-12-31 19:34 UTC
Hello all,
Currently it is only possible to encrypt the wallet file with a hardware itself. Because of this i need the hardware wallet every time when I open the wallet (read only). But I'd like to store the hardware at another place.
Is it possible to enter passphrase manually for the encryption of the files? 

Regards Steffen

**Comment by ecdsa** [comment] 2021-01-01 12:06
duplicate of #5562

**Closed by ecdsa** 2021-01-01 12:06 UTC
