### ISSUE TITLE
Strange behavior of "Fee" value

### ISSUE THREAD

**Issue by ldz1** [spesmilo/electrum#5403] opened 2019-06-03 17:10 UTC
Steps to reproduce:

- version 3.3.6, desktop version, Linux
- watching only wallet (probably not important)

1. Open "Send" tab
2. Provide "Pay to" address.
3. Select "Max" (let say the "Fee" is now 135 sat/byte).
4. Change "Fee" (for example enter "5" sat/byte).
5. Set cursor inside "Description" inputbox.
6. Change tab (for instance, "Receive")
7. Go back to "Send"
8. Fee is still "5" 
9. Set the focus inside "Fee" input box.
10. Switch to another tab.
11. Go back to "Send"
12. Fee is sometimes "5" and sometimes "135". It is a bit random. 
13. If fee is still 5 please switch to another tabs.

Notice, the randomness occurs only when mouse cursor inside Fee input box. No problem when cursor inside "Description".

**Comment by SomberNight** [comment] 2019-06-03 18:18
duplicate of https://github.com/spesmilo/electrum/issues/5250 ?

**Comment by ldz1** [comment] 2019-06-03 18:54
@SomberNight yes, sorry. But I can definitely say, the behaviors seems to be random. The value is not always changing after switch between tabs when cursor inside fee.

**Comment by SomberNight** [comment] 2019-06-03 20:25
thanks for the report;
closing as duplicate

**Closed by SomberNight** 2019-06-03 20:25 UTC
