### ISSUE TITLE
Fee slider should go higher

### ISSUE THREAD

**Issue by ihendley** [spesmilo/electrum#2181] opened 2017-02-20 19:35 UTC
Due to network congestion over the past two months or so I have been forced to manually edit all my fees, because the fee slider maxes out at 0.001 BTC/kB. See [here](https://bitcoinfees.21.co/#delay) for fee vs confirmation time estimates. Right now one would need >= 0.00141 BTC/kB for a reasonable likelihood of making the next block.

0.002 BTC/kB would be a good maximum for the slider, in my opinion.

**Comment by ecdsa** [comment] 2017-02-23 16:11
I will add that.
in the meantime, in the console type `setconfig('max_fee_rate', 200000)` and restart electrum.

**Comment by ecdsa** [comment] 2017-02-23 16:12
closing, since duplicate of #2112

**Closed by ecdsa** 2017-02-23 16:12 UTC
