### ISSUE TITLE
Upon receiving LN payment, history tab item fails to lookup corresponding invoice

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#7845] opened 2022-06-07 12:51 UTC
scenario:
    - Alice creates an invoice
    - Bob pays the invoice
    - in Alice's history tab, LN payment item has no description
        - and, after double-clicking, "lightning invoice" field is empty

The invoice-lookup is using the payment-hash, which presumably got broken in https://github.com/spesmilo/electrum/pull/7730:
https://github.com/spesmilo/electrum/blob/0ed4fea899f551c7299b2be53e059d00a722be91/electrum/gui/qt/lightning_tx_dialog.py#L55-L56

Affects both Qt and kivy.

**Comment by ecdsa** [comment] 2022-06-14 09:15
The lookup in the dialog could be fixed in the same way as in 2117118047b2ed41e9906655b5482d8faa85ae51

The label issue is more annoying, because it points to an older issue.

Before merging #7730, we called `wallet.set_label` in `lnworker.add_request`. Now we call `wallet.add_payment_request`, which calls `set_label`, but it does it with the request key instead of the payment hash; this is why it is not displayed correctly.

The issue is that this is dirty: we are adding unnecessary labels.
See the comment here: https://github.com/spesmilo/electrum/blob/master/electrum/wallet.py#L2476
As it says, it would be better not to set the label, but to have it returned as a default label, similar to 
`_get_default_label_for_txid`

**Closed** 2022-06-14 11:41 UTC
Labels: bug 🐞

**Comment by accumulator** [comment] 2022-06-14 14:25
This is probably wrong:
https://github.com/spesmilo/electrum/blob/master/electrum/wallet.py#L2352

**Comment by ecdsa** [comment] 2022-06-14 15:14
> This is probably wrong (typo?) https://github.com/spesmilo/electrum/blob/master/electrum/wallet.py#L2352

indeed, thanks. fixed in 7df24f0ad
