### ISSUE TITLE
Latest version returned by https://electrum.org/version needs a bump

### ISSUE THREAD

**Issue by Coding-Enthusiast** [spesmilo/electrum#6449] opened 2020-07-29 06:56 UTC
It still returns the old version (3.3.8) and that is [causing confusion](https://bitcointalk.org/index.php?topic=5265315.0) for some who have upgraded to new 4+ version.

**Comment by AbdussamadA** [comment] 2020-07-29 10:28
there's a check to see whether it's newer than the installed version:

https://github.com/spesmilo/electrum/blob/4.0.2/electrum/gui/qt/update_checker.py#L77

so it should not be displaying an alert over this.

**Comment by Coding-Enthusiast** [comment] 2020-07-29 11:09
You can manually check for update from Help menu and it will show last version to be `3.3.8` while your version is higher.  
![LastVersion](https://user-images.githubusercontent.com/20510382/88793015-6741bf00-d1b1-11ea-89db-e04057359403.png)

**Comment by jstok** [comment] 2020-07-29 13:10
Duplicate of #6338 and #6393. The issue was raised quite sometime ago and hasn't been fixed yet.

**Comment by ecdsa** [comment] 2020-07-29 16:07
closing because duplicate

**Closed by ecdsa** 2020-07-29 16:07 UTC
