### ISSUE TITLE
My electrum got hacked

### ISSUE THREAD

**Issue by Myroslav12345** [spesmilo/electrum#6975] opened 2021-01-27 17:28 UTC
I have no idea how or what happened exactly, i have only had electrum for a fortnight and within that time all my bitcoin got transferred out.
how is this even possible? What an incredibly easy to hack program if that is the case. I am appalled and down £160. My dad died this year and i haven't got a pot to piss in. that's a lot of money to me at this time. 
So any ideas?

**Comment by SomberNight** [comment] 2021-01-27 19:55
There is hardly no useful information in your comment. How do you expect anyone to even attempt to help without any specifics?

**Comment by MacGregorsk** [comment] 2021-01-27 20:06
Hi Myroslav12345,

I just had a problem with Electrum, looking like yours  : all history is there but balance shows 0 and I can't send BTC anywhere like if there really were 0 on the wallet. So I immediately logged into another software using the same seed and all the coins where still there, despite Electrum displaying 0.

**Comment by SomberNight** [comment] 2021-01-27 20:48
> all history is there (and no sending of the funds anywhere) but balance shows 0

Would you be so kind as to upload a screenshot of your History tab? It sounds like the displayed balance is inconsistent with the displayed history; if so that would clearly be a bug.

**Comment by MacGregorsk** [comment] 2021-01-29 02:02
![Electrum screenshot History tab](https://user-images.githubusercontent.com/66751202/106221513-118cb480-61de-11eb-9fe7-2c1e2e1f924f.png)


Last line never happened and is only listed on Electrum.

**Comment by SomberNight** [comment] 2021-01-29 02:07
> Last line never happened and is only listed on Electrum.

That sounds weird. What happens if you look up the txid of that transaction on a block explorer? Can the block explorer find the tx?

**Comment by MacGregorsk** [comment] 2021-01-29 03:23
The block explorer found the transaction. And SEND and RECEIVE tabs show 1 transaction each, not summing up the 4 from HISTORY tab.

![Electrum RECEIVE tab](https://user-images.githubusercontent.com/66751202/106227282-3b97a400-61e9-11eb-8bfa-93a27bb91d1b.PNG)

Not sure I want to display too many descriptions and the other software I use on public place. Maybe by pictures on a non-cyphered mail or by Signal/Telegram/Whatsapp.

**Comment by ecdsa** [comment] 2021-01-29 10:06
@MacGregorsk : Your issue does not seem to be related to the issue raised by @Myroslav12345 
 - The send and receive tabs show invoices. there is nothing wrong with the history tab showing more transactions. 
 - If you logged in another software that shows a different balance, that is beyond our control. (maybe your other software is using other derivations/addresses and combining them in an aggregate balance, etc). You should first understand what a BIP39 seed is and how it works.

I am closing this, because the OP is unresponsive.

**Closed by ecdsa** 2021-01-29 10:06 UTC

**Comment by Myroslav12345** [comment] 2021-01-30 11:37
Hey please open this back up. I have been looking after my mother and haven't had chance to reply..

**Comment by Myroslav12345** [comment] 2021-01-30 11:38
Could you let me know what alternative program you used to check your seed?

**Comment by Myroslav12345** [comment] 2021-01-30 11:47
MacGregorsk it looks exactly the same as the issue you have described. I am however unable to work out how to login from my passphrase onto another program. Any help would be appreciated.

**Comment by Myroslav12345** [comment] 2021-01-30 11:49
![Uploading image.png…]()

**Comment by Myroslav12345** [comment] 2021-01-30 11:57
![electrum](https://user-images.githubusercontent.com/78101384/106355813-50ac2a00-62f2-11eb-8e05-e5a7a9b5211b.png)

**Comment by MacGregorsk** [comment] 2021-02-03 01:14
Myroslav : install another software, there click on 'restore' or 'restore wallet' and then enter your seed when prompted. You will then access the same BTC wallet you use on Electrum. At that point you will be aware of your real balance. Then please come back here tell us what's up.

ecdsa : honestly I don't know if it has to be posted in this thread or another one, but when OP said 'all his bitcoin got transferred out' I supposed he got fooled by Electrum like I did. Because yup, at first, I tought I had been hacked, like he did, but when I plugged another non-agregated wallet all the BTC balance was correctly displayed. Those wallets has been created in january and share one seed, and no more. However it is normal you are cautious.
About the historic stuff, I am not expert and I prefer stop talking about it since it blurs the problematic.

However I don't know how to help devs to reproduce the bug as I can't remember any specific actions I could have done leading to this result. Except I did not transfered out the money.

**Comment by ecdsa** [comment] 2021-02-03 12:34
@Myroslav12345 it is likely that your seed has been stolen, but there is not information in your report to help you more than that. 

@MacGregorsk your issue is caused by the use of a BIP39 seed. We warn our users not to use this type of seed with Electrum, and you should have seen that warning when you imported your seed. I believe that if @Myroslav12345 had used a BIP39 seed, he would know it, and he would have told us in his report.

**Comment by fapinheiro** [comment] 2024-10-14 02:09
@Jessie-1 , I guess this is because of "...BIP39 seeds do not include a version number, which compromises compatibility with future software. We do not guarantee that BIP39 imports will always be supported in Electrum.." a peace extracted from github file seed_dialog.py
