### ISSUE TITLE
Electrum hangs if closed with no Internet connection

### ISSUE THREAD

**Issue by marioxcc** [spesmilo/electrum#1106] opened 2015-03-24 01:52 UTC
When I open Electrum while having Internet connectivity and close it when connectivity is lost (and the synchronization indicator is red), the window closes, but it the Python interpreter doesn't (it doesn't returns to the shell prompt), not even if I interrupt it (SIGINT). Eventually, after several seconds, it displays:

    Traceback (most recent call last):
      File "/home/electrum/Electrum-2.0.3/lib/util.py", line 320, in _send
        sent = self.socket.send(out)
      File "/usr/lib/python2.7/ssl.py", line 198, in send
        v = self._sslobj.write(data)
    error: [Errno 104] Conexión reinicializada por la máquina remota (Spanish for “connection reset by remote machine”)
    Traceback (most recent call last):
      File "/home/electrum/Electrum-2.0.3/lib/util.py", line 320, in _send
        sent = self.socket.send(out)
      File "/usr/lib/python2.7/ssl.py", line 198, in send
        v = self._sslobj.write(data)
    error: [Errno 32] Tubería rota (Spanish for “broken pipe”)

It is necessary to kill the Python interpreter with SIGKILL. After restarting (with Internet connection), it works again with apparently no corruption.

Tested with GNU/Linux and Python 2.7.3, launched in place with “./electrum”.

Regards.

**Comment by ecdsa** [comment] 2015-03-24 08:44
how did you lose internet connectivity?
I tried to reproduce it by closing the wifi, but it does not hang

**Comment by tunkaflux** [comment] 2015-03-28 18:52
I also cannot reproduce this problem by stopping my electrum-server and then quitting Electrum. Can you try with a newer Python version? (I'm aware of SSL problems in older Python versions...)

**Comment by ecdsa** [comment] 2015-04-02 13:15
closing: OP is not answering, and I cannot reproduce the bug

**Closed by ecdsa** 2015-04-02 13:15 UTC
