### ISSUE TITLE
SSL certificate verify failed

### ISSUE THREAD

**Issue by AlexanderPavlenko** [spesmilo/electrum#1556] opened 2015-11-18 13:08 UTC
For some reason Electrum 2.5.4 on Windows does not accept SSL certificate from https://gear.mycelium.com, althought https://www.ssllabs.com/ssltest/analyze.html?d=gateway.gear.mycelium.com&hideResults=on says it is valid.

```
>> execfile("C:\Program Files\Electrum\lib\paymentrequest.py");
>> get_payment_request("https://gateway.gear.mycelium.com/gateways/.../orders/.../invoice");
Traceback (most recent call last):
  File "C:\Program Files\Electrum\lib\paymentrequest.py", line 63, in get_payment_request
    response = requests.request('GET', url, headers=REQUEST_HEADERS)
  File "Z:\home\voegtlin\electrum\contrib\build-wine\build\deterministic\out00-PYZ.pyz\requests.api", line 50, in request
  File "Z:\home\voegtlin\electrum\contrib\build-wine\build\deterministic\out00-PYZ.pyz\requests.sessions", line 468, in request
  File "Z:\home\voegtlin\electrum\contrib\build-wine\build\deterministic\out00-PYZ.pyz\requests.sessions", line 576, in send
  File "Z:\home\voegtlin\electrum\contrib\build-wine\build\deterministic\out00-PYZ.pyz\requests.adapters", line 433, in send
SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

**Comment by gits7r** [comment] 2015-11-18 15:35
Can you try deleting the certificate with this name for your 'certs' folder inside electrum data directory and try again? Maybe the server changed the certificate and you have the old version cached.

**Comment by ecdsa** [comment] 2015-11-18 18:02
@gits7r that's something different. there's no cert pinning for payment requests.

**Comment by Makulia** [comment] 2016-02-09 21:22
Any progress on this one?

**Comment by ecdsa** [comment] 2016-02-27 05:47
electrum 2.6 binaries come with updated SSL certificates. 
can you test if the issue is fixed?

**Comment by Makulia** [comment] 2016-03-02 10:53
Thanks, will do!

**Comment by ecdsa** [comment] 2016-05-20 09:23
closing this; I assume it is fixed, since I did not hear about it anymore.

**Closed by ecdsa** 2016-05-20 09:23 UTC
