### ISSUE TITLE
Interference when using two Trezors

### ISSUE THREAD

**Issue by matejcik** [spesmilo/electrum#4404] opened 2018-06-04 16:47 UTC
I'm trying to have two wallets open, secured by two separate Trezor devices.
This *mostly* works. However, it's possible to cause interference in the following scenario:

1. in wallet 1, go to Addresses tab
2. in wallet 2, prepare and Preview a transaction
3. in wallet 1, right-click an address and "Show on TREZOR"
4. while the "please check your trezor" dialog is open, click "Sign" in the transaction preview

expected: second Trezor starts signing

actual: Electrum goes haywire

if the "show address" device is a T1, then the sign attempt switches its display to QR view (which is actually a T1 bug). That allows recovery, because when the address view is confirmed on device, Electrum resumes the sign operation on the other Trezor.

If the "show address" is a TT, there's a bug (possibly TT's) that clicking Cancel raises an "unexpected message". In this case, Electrum never works again. You can close all windows and the UI is responsive (i.e., not frozen), but nothing does anything anymore and the only way out is force close.

I couldn't figure out where the interference is coming from - are the Trezor connections somehow shared under the hood? I _think_ it's not in trezorlib, but it's still possible, I suppose.

**Comment by SomberNight** [comment] 2018-06-07 12:36
Ahh it is due to `scan_devices`, that breaks the separation..
I introduced the bug in https://github.com/spesmilo/electrum/commit/85b36e027f8cada43aa755fdcef9291ab45a5e06 :/
wallet1 will get pinged when you start signing on wallet2

**Comment by SomberNight** [comment] 2018-06-07 13:11
The original problem that commit is trying to fix affects all the hardware wallets except trezor; presumably due to the custom enumeration stuff.
I've tested with Trezor One (no), Trezor T (no), Ledger Nano S (yes), Ledger HW.1 (yes), KeepKey (yes), DigitalBitbox (yes).

**Comment by SomberNight** [comment] 2018-11-16 18:31
Further interference in case of tx signing is here:
https://github.com/spesmilo/electrum/blob/32af83b7aede02f0b9bb3e8294ef2dc0481fb6de/electrum/plugins/trezor/trezor.py#L316-L317

(TrezorPlugin is singleton; shared among the wallets)

**Comment by matejcik** [comment] 2018-11-16 18:41
i'm fixing that one as part of #4817

**Comment by matejcik** [comment] 2018-11-16 18:47
Still not sure what to do about the original bug. It might go away by itself if I manage to clean up exception handling.

Or if the problem that's solved through `scan_devices` (which I don't understand very well) doesn't affect Trezor, maybe the solution is just to return True from `has_usable_connection`?

**Comment by SomberNight** [comment] 2018-11-16 19:12
Well `has_usable_connection` is used elsewhere too now, e.g. https://github.com/spesmilo/electrum/commit/5a508f7b8d07835d54aec8b9c22a9b2c25609357

But wait; actually, with latest firmwares on TT and T1, and on electrum master, I can no longer reproduce the issue here. Maybe the way the ping is handled changed?

**Comment by SomberNight** [comment] 2018-12-07 02:08
closing due to https://github.com/spesmilo/electrum/pull/4875

**Closed by SomberNight** 2018-12-07 02:08 UTC
Labels: bug, hw-trezor
