### ISSUE TITLE
Signing transaction

### ISSUE THREAD

**Issue by brokenledger** [spesmilo/electrum#3489] opened 2017-12-09 21:27 UTC
Hello,

Electrum 3.0.2 on a win 10 computer connected to a ledger nano s with the latest firmware. 

Electrum (and the official ledger chrome app) both fail to send BTC from my nano s. I open the Electrum app (it has been directed to use segwit during the setup the process) and copy/paste a BTC destination address from an exchange into the the "pay to" field. I then click max, and hit send. The app will confirm the amounts again, and then I grab the ledger nano and hit confirm (it only requests it one time for the total transaction). 

Then Electrum sits there at "signing transaction" and the app becomes unresponsive. It has been an hour at this stage. 

Any advice? Ledger is claiming it is a bug with electrum even though they told me to use electrum because their is busted.

**Comment by lxp1991** [comment] 2017-12-10 02:48
Do we have any news on this? I have the same issue. I'm using Electrum 3.0.2, and Windows 10, ledger nano s firmware 1.3.1.

**Comment by SomberNight** [comment] 2017-12-10 05:05
This is a duplicate of https://github.com/spesmilo/electrum/issues/3264

You can try the workaround mentioned in https://github.com/spesmilo/electrum/issues/3264#issuecomment-345414501

This will be fixed in the next minor release, which should come very soon.

**Closed by SomberNight** 2017-12-10 05:05 UTC

**Comment by ecdsa** [comment] 2017-12-13 15:40
note: 3.0.3 has been released now
