### ISSUE TITLE
Trezor stopped working

### ISSUE THREAD

**Issue by molecular** [spesmilo/electrum#1926] opened 2016-09-14 05:58 UTC
I just pulled to new master. a3b4409e6e8d1c510f53494ca068633ce03f0cc7

Electrum prompted me to convert my wallet to new version, which I accepted.

The wallet comes up "watch only" (a popup tells me this)

I noticed the trezor plugin was unchecked in the plugin list, so I checked it and resterted electrum: still comes up with "This wallet is watch only".

Nothing on stdout/stderr

**Comment by molecular** [comment] 2016-09-14 06:06
I restored the wallet from an older file which now works. Not sure what happened.

**Comment by molecular** [comment] 2016-09-14 06:12
it happened again with a different wallet. That wallet was split (from multiple accounts) by an earlier version of electrum. When opening that <wallet>.0 file electrum wants to "convert from an older version of electrum" and then the wallet is watch-only.

**Comment by ecdsa** [comment] 2016-09-15 07:34
do you still have a copy of the trezor wallet before converting to the new format?

**Comment by molecular** [comment] 2016-09-15 21:12
yes, that's the "older file" I mentioned above. I had to use it to access my coins.

**Comment by ecdsa** [comment] 2016-09-16 05:59
oh, so the problem is only with a wallet file created by an older development version?
in that case it should be closed indeed.

**Closed by ecdsa** 2016-09-16 05:59 UTC

**Comment by molecular** [comment] 2016-09-16 11:49
yes
