### ISSUE TITLE
Can't connect, unless EXE located on desktop.

### ISSUE THREAD

**Issue by Red-Squid** [spesmilo/electrum#1866] opened 2016-07-11 23:14 UTC
I'm using the Windows 'portable' version; which automatically places it's data in a folder on the desktop. I don't want it there, I have a 'portable' app location, that gets backed up to the cloud securely; and can be quickly and easily moved around as needed.

When I open the portable EXE from the desktop, with the Data/Wallet folder on the desktop, everything works. Electrum connects to servers like I would expect.

When I move the EXE, and the folder to 'anywhere else' and run the EXE, it uses the Data/Wallet, like I would expect, but it DOES NOT connect to any servers. And it will not regardless of what I do in settings.

This is just silly!

**Comment by Red-Squid** [comment] 2016-07-11 23:18
Funny, I just noticed that Electrum portable also created the Data/Wallet folder in the temp folder in which the EXE was placed during it's first run... as well as on the desktop. But it only created the wallet file in the folders on the desktop.

So apparently it assumes it's located on the desktop, but it also creates Data/Wallet folders wherever it is upon load, and it won't connect to servers unless it's located on the desktop?

This is one very confused portable application.

**Comment by ecdsa** [comment] 2016-10-09 07:26
seems related to #1962

**Comment by ldz1** [comment] 2019-05-09 23:20
Is the error still present? I have tried to reproduce the bug without success. 

My steps:
1. Download portable windows exe (3.3.5).
2. Move exe to desktop.
3. Run electrum, create new wallet.
4. New folder was created on desktop.
5. Move exe and the new folder to another location.
6. Run electrum from the new location.
7. Connection status is green, electrum is connected with multiple nodes.

Windows Version: Win10, 1803.

**Comment by SomberNight** [comment] 2022-03-23 17:05
A lot of code and build scripts changed since the issue was opened. Probably not applicable anymore. Closing.

**Closed by SomberNight** 2022-03-23 17:05 UTC
Labels: bug 🐞, OS-windows 🪟
