### ISSUE TITLE
Windows crash popup after application is closed: "electrum-4.0.9.exe has stopped working"

### ISSUE THREAD

**Issue by random652** [spesmilo/electrum#6989] opened 2021-02-03 10:05 UTC
Bug:
**electrum-4.0.9.exe has stopped working**
A problem caused the program to stop working correctly. Please close the program.
"Close the program" button is available to click. Clicking the button then closes the error window.

Full process description:
I open Electrum, type in my password, load my wallet. I eventually close the program via the X in the corner of the Electrum window (after doing some bitcoin transactions _or_ doing no transactions at all. _Irrelevant_)

1 or 2 seconds passes. Error window pops up. This problem has occurred dozens of times since Electrum was "updated" *cough _yeah right_ cough* to version 4.0.9. I never encountered this problem on previous versions.

OS: Win7 64bit, SP1
Electrum version: 4.0.9, installed version
Memory: 16GB
AMD Phenon II x4 965 Processor 3.40Ghz
No other applications running while using Electrum
![error](https://user-images.githubusercontent.com/78475816/106731355-6022c000-65dd-11eb-945c-e5dec805bd31.jpg)

**Comment by ecdsa** [comment] 2021-02-03 15:24
duplicate of #6889

**Closed by ecdsa** 2021-02-03 15:24 UTC
