### ISSUE TITLE
Error while sending bitcoin

### ISSUE THREAD

**Issue by zottirik** [spesmilo/electrum#2553] opened 2017-06-25 04:03 UTC
Sometimes I get this error;
error: The transaction was rejected by network rules.  (16: mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation)

What could cause this?

**Comment by takinbo** [comment] 2017-06-26 08:39
Can you provide more details about the transaction? Are you spending from a multisig address?

**Comment by dabura667** [comment] 2017-06-26 09:34
It means the redeemscript or pubkey was not the same as the one hashed for the utxo.

What versions are you using?

**Comment by zottirik** [comment] 2017-06-27 15:39
2.8.3
I am using daemon.

**Comment by dabura667** [comment] 2017-06-27 16:23
Tell me more about your usage... I can't reproduce?

Are you running scripts on multiple threads and processes making 1000 calls to sendmany every second? (lol)

Your original question is answered though:

Q: What could cause this?

A: It is definitely caused by the public key (or redeemscript, if multisig) in the signed transaction's scriptSig not matching the pubkey hash in the scriptPubkey being referred to by the input... This means that one of 2 things is getting swapped out. 1. the input txid referrer. 2. the public key itself (or redeemscript)

Did you, by any chance, manually create a multisig address by using createmultisig? (that seems like it would cause problem, as it is legacy code.)

**Comment by ecdsa** [comment] 2017-06-30 10:26
could be #2566 (fixed) or #2509 (not fixed yet)
anyway, closing this report because OP is not answering

**Closed by ecdsa** 2017-06-30 10:26 UTC

**Comment by zottirik** [comment] 2017-07-06 01:17
Sorry for late answer,
The problem is still going on, I upgraded Electrum to 2.9.0, but some addresses cause this error.
