### ISSUE TITLE
Suggestion:   Allow Testnet

### ISSUE THREAD

**Issue by cluelessperson** [spesmilo/electrum#1705] opened 2016-03-07 06:24 UTC
Again, I feel we need to make electrum/bitcoin as approachable as possible for laymen.

I feel it's important to make it possible to create an electrum wallet for testnet.
This would allow new users to play with functionality, allowing comfort to be built with application before requiring financial investment.

Thoughts?

**Comment by dabura667** [comment] 2016-03-07 10:59
Copay allows testnet. That's good enough for me.

I don't think Electrum would be a good candidate for offering testnet...

**Comment by EagleTM** [comment] 2016-03-07 11:47
IIRC there was a fork / patches for testnet a while back, maybe someone knows more about it.
I don't believe we'll see this in electrum mainline anytime soon though, as technically it's an altcoin.

**Comment by wozz** [comment] 2016-03-07 12:55
I had a fork with testnet enabled (sometime around version 2.0 or so). The primary issue is that it requires keeping a server up and running just for testnet and no one seems willing to do that. Getting the code working isn't that difficult.

**Comment by ecdsa** [comment] 2016-08-25 20:08
duplicate of #541

**Closed by ecdsa** 2016-08-25 20:08 UTC
Labels: enhancement
