### ISSUE TITLE
ImportError: No module named socks. PySocks is installed though.

### ISSUE THREAD

**Issue by kintarowonders** [spesmilo/electrum#2488] opened 2017-06-03 07:35 UTC
Electrum no longer seems to work. I'm running the Fedora 26 beta, though I get most my python packages with pip.
It gives this output...
```
$ electrum 
Traceback (most recent call last):
  File "/usr/bin/electrum", line 98, in <module>
    from electrum import bitcoin, network
  File "/usr/lib/python2.7/site-packages/electrum/__init__.py", line 6, in <module>
    from network import Network, pick_random_server
  File "/usr/lib/python2.7/site-packages/electrum/network.py", line 35, in <module>
    import socks
```
This is despite PySocks being installed, I can't make much sense of the problem. It might be an issue with Python itself, but I have doubts about that. Other Python software on my system is working fine. 

```
$ sudo pip2 install https://download.electrum.org/2.8.3/Electrum-2.8.3.tar.gz

WARNING: Running pip install with root privileges is generally not a good idea. Try `pip2 install --user` instead.                                                                                                              
Collecting https://download.electrum.org/2.8.3/Electrum-2.8.3.tar.gz
  Downloading https://download.electrum.org/2.8.3/Electrum-2.8.3.tar.gz (2.3MB)
    100% |████████████████████████████████| 2.3MB 241kB/s 
Requirement already satisfied: pyaes in /usr/lib/python2.7/site-packages (from Electrum==2.8.3)
Requirement already satisfied: ecdsa>=0.9 in /usr/lib/python2.7/site-packages (from Electrum==2.8.3)
Requirement already satisfied: pbkdf2 in /usr/lib/python2.7/site-packages (from Electrum==2.8.3)
Requirement already satisfied: requests in /usr/lib/python2.7/site-packages (from Electrum==2.8.3)
Requirement already satisfied: qrcode in /usr/lib/python2.7/site-packages (from Electrum==2.8.3)
Requirement already satisfied: protobuf in /usr/lib64/python2.7/site-packages (from Electrum==2.8.3)
Requirement already satisfied: dnspython in /usr/lib/python2.7/site-packages (from Electrum==2.8.3)
Requirement already satisfied: jsonrpclib in /usr/lib/python2.7/site-packages (from Electrum==2.8.3)
Requirement already satisfied: PySocks>=1.6.6 in /usr/lib/python2.7/site-packages (from Electrum==2.8.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests->Electrum==2.8.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests->Electrum==2.8.3)
Requirement already satisfied: idna<2.6,>=2.5 in /usr/lib/python2.7/site-packages (from requests->Electrum==2.8.3)
Requirement already satisfied: urllib3<1.22,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests->Electrum==2.8.3)
Requirement already satisfied: six in /usr/lib/python2.7/site-packages (from qrcode->Electrum==2.8.3)
Requirement already satisfied: setuptools in /usr/lib/python2.7/site-packages (from protobuf->Electrum==2.8.3)
Requirement already satisfied: appdirs>=1.4.0 in /usr/lib/python2.7/site-packages (from setuptools->protobuf->Electrum==2.8.3)
Requirement already satisfied: packaging>=16.8 in /usr/lib/python2.7/site-packages (from setuptools->protobuf->Electrum==2.8.3)
Requirement already satisfied: pyparsing in /usr/lib/python2.7/site-packages (from packaging>=16.8->setuptools->protobuf->Electrum==2.8.3)
Installing collected packages: Electrum
  Found existing installation: Electrum 2.8.2
    Uninstalling Electrum-2.8.2:
      Successfully uninstalled Electrum-2.8.2
  Running setup.py install for Electrum ... done
Successfully installed Electrum-2.8.3
```
It clearly installs everything fine, but can't seem to import socks.

**Comment by ecdsa** [comment] 2017-06-12 10:32
I have no idea what that is, but I don't think the issue is with electrum

**Comment by ecdsa** [comment] 2017-06-12 10:33
maybe you installed socks with python3?

**Comment by hegjon** [comment] 2017-06-13 21:51
You could consider using the packages built by Fedora https://fedoramagazine.org/bitcoin-fedora-electrum/

**Comment by ecdsa** [comment] 2017-06-30 07:47
closing; OP not answering, and the issue is not with electrum

**Closed by ecdsa** 2017-06-30 07:47 UTC

**Comment by Blackwolf-Iran** [comment] 2017-07-06 21:49
Hi 

All You need : 

> pip install PySocks
> sudo apt-get install python-socks

g00d luck !

**Comment by hegjon** [comment] 2017-07-07 09:45
apt-get install wont work on Fedora

**Comment by ecdsa** [comment] 2017-07-07 09:50
well, manually remove PySocks from /usr/lib/python2.7/site-packages and reinstall...
