### ISSUE TITLE
Sending "!" (.059) with dynamic fees enabled and FEE: 0.00006    :(

### ISSUE THREAD

**Issue by N0X-X** [spesmilo/electrum#2087] opened 2017-01-02 07:07 UTC
Just realized. 6hr ...No confirmations https://blockchain.info/tx/d6fa98db68054d00b191110c331949a8deb9943b7e7f3e57f93e13fa7c73c9fa

**Comment by dabura667** [comment] 2017-01-02 07:19
Your transaction will probably confirm within the next 4 hours or so.

Do you know which server you were connected to when you sent this transaction out?

**Comment by N0X-X** [comment] 2017-01-02 08:08
I think ulrichard.ch but I cant be certain. 2 years ago I post a 1.3 w/o any fee in a lapse of thought, and it settled so i'm not worried about it. Maybe under details change ECT:Unknown (low fee) to ECT: Eventually (low fee) incase it happens to someone else so they don't have a heart attack. The ! triangle looks menacing enough. lol

**Comment by ecdsa** [comment] 2017-01-02 09:12
maybe your client didnt have time to request the suggested fee when you made the tx.
was it fully synchronized?

**Comment by N0X-X** [comment] 2017-01-02 09:34
It looked to be however I made the transaction between two wallets on the same desktop. Both set to select server automatically. Could simultaneous connections have caused this?

**Comment by ecdsa** [comment] 2017-01-02 10:05
I don't think so. try to reproduce the issue, you test without sending the transaction using the 'preview' button

**Comment by ecdsa** [comment] 2017-01-09 11:54
my best guess is that the suggested fee was missing.
if that is true, it should be fixed in a2e7fc32ef4663c153dbe2f078b28bb1b2f0da20
closing this issue, because the OP did not answer if he can reproduce.

**Closed by ecdsa** 2017-01-09 11:54 UTC

**Comment by ecdsa** [comment] 2017-01-11 18:00
btw, which version of Electrum were you using?

**Comment by ecdsa** [comment] 2017-01-11 18:31
ok, here is the most likely explanation: dust inputs were removed by the coin chooser, thus reducing the fee. the "send max !" function does not use the coin choser anymore, so this is fixed.
