### ISSUE TITLE
Electrum 2.9.3 OS X Crash sending transaction

### ISSUE THREAD

**Issue by manologin** [spesmilo/electrum#2728] opened 2017-08-11 07:05 UTC
When trying to send a transaction the Electrum 2.9.3 (OS X Sierra) app crashes - reverted to version 2.9.2 - works fine.
The problem seems to happen only when trying to send or preview a new transaction. The problem still happens after reinstalling the Electrum 2.9.3 and even when cleaning up all the contents of the ~/.electrum folder

**Comment by ecdsa** [comment] 2017-08-11 08:54
sorry about that. 
I made a new dmg file; an you try it and let me know if it is fixed?

**Comment by pmitchev** [comment] 2017-08-11 13:15
Not fixed, just downloaded and tried

**Comment by ecdsa** [comment] 2017-08-11 14:04
I cannot reproduce that.
is there any error message in the osx console?

**Comment by azteke** [comment] 2017-08-12 12:37
I'm experiencing the same issue. It also crashes when I press the command key when the cursor is blinking in the 'Pay to' field. (cannot paste a bitcoin address using command-v).

**Comment by ecdsa** [comment] 2017-08-12 13:23
is there any error message in the osx console?

**Comment by pmitchev** [comment] 2017-08-12 13:44
This is the only thing I am getting on "electrum" search in console. I hope it helps:

> [Electrum pid 48900 mux-aware] exiting, non-mux-aware app count 0, runtime: 0:02:43.774

**Comment by manologin** [comment] 2017-08-12 16:06
@ecdsa I think the problem can be the new "icons"... but I am no specialist. The problem can be reproduced by simple pressing the Command key at the Send dialog, just like @azteke said.

Running from OS X terminal gives me the message when app crashes:

**Illegal instruction: 4**


For debugging I am attaching the Apple Error Report 
[Electrum_2_9_3_crash_Sierra.txt](https://github.com/spesmilo/electrum/files/1219892/Electrum_2_9_3_crash_Sierra.txt)

The most relevant message, in my opinion:

> Notes:                 Translocated Process
> 
> Crashed Thread:        0  Dispatch queue: com.apple.main-thread
> 
> Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
> Exception Codes:       0x0000000000000001, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Termination Signal:    Illegal instruction: 4
> Termination Reason:    Namespace SIGNAL, Code 0x4
> Terminating Process:   exc handler [0]
>

**Comment by philrosenthal** [comment] 2017-08-17 03:11
I am able to reproduce this on my Mac Pro desktop, but not on my Macbook Pro.

Both running the same 2.9.3 version.

**Comment by rex4539** [comment] 2017-08-17 14:42
100% reproducible here too.

1. Click on Send tab.
2. Press the Command key on keyboard.


[Electrum_2017-08-17-173748_MacBook-Pro-2011.txt](https://github.com/spesmilo/electrum/files/1231615/Electrum_2017-08-17-173748_MacBook-Pro-2011.txt)

**Comment by rex4539** [comment] 2017-08-17 14:49
Running on the dubugger gives the following:

`* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x00000001072dc354 QtGui.so`___lldb_unnamed_symbol10595$$QtGui.so + 94
QtGui.so`___lldb_unnamed_symbol10595$$QtGui.so:
->  0x1072dc354 <+94>:  bextrl %edx, 0x8(%rcx), %ebx
    0x1072dc35a <+100>: movq   %rax, %rdi
    0x1072dc35d <+103>: callq  0x1072f2aa8               ; symbol stub for: PyEval_RestoreThread
    0x1072dc362 <+108>: movq   %rbx, %rdi
Target 0: (Electrum) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
  * frame #0: 0x00000001072dc354 QtGui.so`___lldb_unnamed_symbol10595$$QtGui.so + 94
    frame #1: 0x00000001052fcbac Python`PyEval_EvalFrameEx + 11238
    frame #2: 0x00000001052f9de5 Python`PyEval_EvalCodeEx + 1579
    frame #3: 0x00000001052a0651 Python`___lldb_unnamed_symbol512$$Python + 330
    frame #4: 0x0000000105282cda Python`PyObject_Call + 97
    frame #5: 0x000000010528d4d5 Python`___lldb_unnamed_symbol193$$Python + 163
    frame #6: 0x0000000105282cda Python`PyObject_Call + 97
    frame #7: 0x0000000105302528 Python`PyEval_CallObjectWithKeywords + 159
    frame #8: 0x00000001061d368a sip.so`___lldb_unnamed_symbol160$$sip.so + 76
    frame #9: 0x00000001061cfa38 sip.so`___lldb_unnamed_symbol68$$sip.so + 152
    frame #10: 0x000000010700bf6d QtGui.so`sipVH_QtGui_14(PyGILState_STATE, void (*)(_sipSimpleWrapper*, PyGILState_STATE), _sipSimpleWrapper*, _object*, QKeyEvent*) + 35
    frame #11: 0x00000001071cfa31 QtGui.so`sipQPlainTextEdit::keyPressEvent(QKeyEvent*) + 85
    frame #12: 0x00000001077a41f4 QtGui`QWidget::event(QEvent*) + 3508
    frame #13: 0x0000000107aa1843 QtGui`QFrame::event(QEvent*) + 45
    frame #14: 0x0000000107b15888 QtGui`QAbstractScrollArea::event(QEvent*) + 592
    frame #15: 0x0000000107b2e18d QtGui`QPlainTextEdit::event(QEvent*) + 747
    frame #16: 0x00000001071cf4d6 QtGui.so`sipQPlainTextEdit::event(QEvent*) + 98
    frame #17: 0x00000001077612cc QtGui`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 194
    frame #18: 0x0000000107762f92 QtGui`QApplication::notify(QObject*, QEvent*) + 2822
    frame #19: 0x000000010703dedc QtGui.so`sipQApplication::notify(QObject*, QEvent*) + 106
    frame #20: 0x0000000106600474 QtCore`QCoreApplication::notifyInternal(QObject*, QEvent*) + 118
    frame #21: 0x00000001077648c8 QtGui`___lldb_unnamed_symbol1449$$QtGui + 45
    frame #22: 0x00000001077c1ca9 QtGui`___lldb_unnamed_symbol2452$$QtGui + 226
    frame #23: 0x000000010771801c QtGui`___lldb_unnamed_symbol619$$QtGui + 80
    frame #24: 0x000000010770d2dc QtGui`___lldb_unnamed_symbol376$$QtGui + 49
    frame #25: 0x00007fff4c8b0ae1 AppKit`-[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 5040
    frame #26: 0x00007fff4c8af314 AppKit`-[NSWindow(NSEventRouting) sendEvent:] + 497
    frame #27: 0x000000010771123f QtGui`___lldb_unnamed_symbol449$$QtGui + 113
    frame #28: 0x00007fff4c710d3a AppKit`-[NSApplication(NSEvent) sendEvent:] + 3154
    frame #29: 0x00000001077156b0 QtGui`___lldb_unnamed_symbol542$$QtGui + 97
    frame #30: 0x00007fff4bf72a3c AppKit`-[NSApplication run] + 812
    frame #31: 0x000000010771dbcb QtGui`___lldb_unnamed_symbol701$$QtGui + 1725
    frame #32: 0x00000001065fd925 QtCore`QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 77
    frame #33: 0x00000001065fda9f QtCore`QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 365
    frame #34: 0x00000001066008ce QtCore`QCoreApplication::exec() + 200
    frame #35: 0x000000010703ef51 QtGui.so`___lldb_unnamed_symbol672$$QtGui.so + 79
    frame #36: 0x00000001052fcbac Python`PyEval_EvalFrameEx + 11238
    frame #37: 0x00000001052f9de5 Python`PyEval_EvalCodeEx + 1579
    frame #38: 0x0000000105302be2 Python`___lldb_unnamed_symbol1478$$Python + 290
    frame #39: 0x00000001052fcae8 Python`PyEval_EvalFrameEx + 11042
    frame #40: 0x0000000105302b84 Python`___lldb_unnamed_symbol1478$$Python + 196
    frame #41: 0x00000001052fcae8 Python`PyEval_EvalFrameEx + 11042
    frame #42: 0x00000001052f9de5 Python`PyEval_EvalCodeEx + 1579
    frame #43: 0x00000001052fa214 Python`PyEval_EvalFrameEx + 590
    frame #44: 0x00000001052f9de5 Python`PyEval_EvalCodeEx + 1579
    frame #45: 0x0000000105302be2 Python`___lldb_unnamed_symbol1478$$Python + 290
    frame #46: 0x00000001052fcae8 Python`PyEval_EvalFrameEx + 11042
    frame #47: 0x00000001052f9de5 Python`PyEval_EvalCodeEx + 1579
    frame #48: 0x00000001052f97b4 Python`PyEval_EvalCode + 32
    frame #49: 0x000000010531afdf Python`___lldb_unnamed_symbol1608$$Python + 49
    frame #50: 0x000000010531b086 Python`PyRun_FileExFlags + 130
    frame #51: 0x000000010531ac03 Python`PyRun_SimpleFileExFlags + 697
    frame #52: 0x000000010000275b Electrum`py2app_main + 2683
    frame #53: 0x000000010000117a Electrum`main + 650
    frame #54: 0x0000000100000be4 Electrum`start + 52`

(lldb) disassemble
QtGui.so`___lldb_unnamed_symbol10595$$QtGui.so:
    0x1072dc2f6 <+0>:   pushq  %rbp
    0x1072dc2f7 <+1>:   movq   %rsp, %rbp
    0x1072dc2fa <+4>:   pushq  %r14
    0x1072dc2fc <+6>:   pushq  %rbx
    0x1072dc2fd <+7>:   subq   $0x20, %rsp
    0x1072dc301 <+11>:  leaq   -0x28(%rbp), %rcx
    0x1072dc305 <+15>:  movq   %rdi, (%rcx)
    0x1072dc308 <+18>:  leaq   -0x20(%rbp), %rdi
    0x1072dc30c <+22>:  movq   $0x0, (%rdi)
    0x1072dc313 <+29>:  leaq   0x226ed6(%rip), %r14      ; sipAPI_QtGui
    0x1072dc31a <+36>:  movq   (%r14), %rbx
    0x1072dc31d <+39>:  leaq   0x156bac(%rip), %rax      ; sipExportedTypes_QtGui
    0x1072dc324 <+46>:  movq   0x17a8(%rax), %r8
    0x1072dc32b <+53>:  leaq   0x4dcac(%rip), %rdx       ; "'B'"
    0x1072dc332 <+60>:  leaq   -0x18(%rbp), %r9
    0x1072dc336 <+64>:  xorl   %eax, %eax
    0x1072dc338 <+66>:  callq  *0x280(%rbx)
    0x1072dc33e <+72>:  testl  %eax, %eax
    0x1072dc340 <+74>:  je     0x1072dc36c               ; <+118>
    0x1072dc342 <+76>:  callq  0x1072f2aae               ; symbol stub for: PyEval_SaveThread
    0x1072dc347 <+81>:  movq   -0x18(%rbp), %rcx
    0x1072dc34b <+85>:  movq   0x20(%rcx), %rcx
    0x1072dc34f <+89>:  movl   $0x10f, %edx              ; imm = 0x10F 
->  0x1072dc354 <+94>:  bextrl %edx, 0x8(%rcx), %ebx
    0x1072dc35a <+100>: movq   %rax, %rdi
    0x1072dc35d <+103>: callq  0x1072f2aa8               ; symbol stub for: PyEval_RestoreThread
    0x1072dc362 <+108>: movq   %rbx, %rdi
    0x1072dc365 <+111>: callq  0x1072f2a6c               ; symbol stub for: PyBool_FromLong
    0x1072dc36a <+116>: jmp    0x1072dc397               ; <+161>
    0x1072dc36c <+118>: movq   (%r14), %rax
    0x1072dc36f <+121>: movq   -0x20(%rbp), %rdi
    0x1072dc373 <+125>: leaq   0x34ec6(%rip), %rdx       ; sipStrings_QtGui
    0x1072dc37a <+132>: leaq   0x16750(%rdx), %rsi
    0x1072dc381 <+139>: addq   $0x15241, %rdx            ; imm = 0x15241 
    0x1072dc388 <+146>: leaq   0x221fc1(%rip), %rcx      ; sipTypeDef_QtGui_QWidget + 4008
    0x1072dc38f <+153>: callq  *0x2a0(%rax)
    0x1072dc395 <+159>: xorl   %eax, %eax
    0x1072dc397 <+161>: addq   $0x20, %rsp
    0x1072dc39b <+165>: popq   %rbx
    0x1072dc39c <+166>: popq   %r14
    0x1072dc39e <+168>: popq   %rbp
    0x1072dc39f <+169>: retq

**Comment by bambooeater** [comment] 2017-08-17 20:15
Same issue here, it crashes when trying to paste the recipient address.

Attached the Console output.

[Electrum_2017-08-17-002000_macbookpro-235.crash.txt](https://github.com/spesmilo/electrum/files/1232487/Electrum_2017-08-17-002000_macbookpro-235.crash.txt)

**Comment by dawatz** [comment] 2017-08-19 02:47
fixed by reverting to 2.9.2

**Closed** 2017-10-07 07:55 UTC

**Comment by BM5k** [comment] 2017-10-19 08:51
This is still an issue with 2.9.3 & macOS 10.12.6 (16G29)
