### ISSUE TITLE
Electrum Big Sur 

### ISSUE THREAD

**Issue by mistapinguin** [spesmilo/electrum#6730] opened 2020-11-14 12:47 UTC
Dear developers,

Electrum is not opening up on Big Sur.
Is this a bug or can you help me?

**Comment by Igv0** [comment] 2020-11-14 14:07
> Dear developers,
> 
> Electrum is not opening up on Big Sur.
> Is this a bug or can you help me?

The same problem((((

**Comment by leogela** [comment] 2020-11-14 14:36
Same problem !! It's a bug...

**Comment by ELHARAKA** [comment] 2020-11-14 15:47
Me too, since the last 3 Days. after I force close it, I get this error

<img width="1440" alt="Screenshot 2020-11-14 at 16 44 08" src="https://user-images.githubusercontent.com/35965906/99151068-e42d7180-2698-11eb-89e3-2973de24be2f.png">

**Comment by SomberNight** [comment] 2020-11-14 19:01
duplicate of https://github.com/spesmilo/electrum/issues/6461
will be fixed in next release

**Closed by SomberNight** 2020-11-14 19:01 UTC

**Comment by Igv0** [comment] 2020-11-15 17:13
> duplicate of #6461
> will be fixed in next release

You're closing this topic but you're not saying when you're going to fix it!!!! Why?

**Comment by SomberNight** [comment] 2020-11-15 18:47
This specific topic was closed because it is a duplicate. It's already fixed on master, which means the next release will contain the fix.

To be clear, even in the meantime, you can access your coins, as you could
- run from source (see e.g. https://github.com/spesmilo/electrum/issues/6461#issuecomment-709218267)
- fire up a VM with e.g. older macOS or GNU/Linux or Windows and run from there
- use an Android phone and run from there
- use another PC of yours and run from there

Also, you might want to consider using an operating system that does not break userspace. Sane OS maintainers would consider this whole issue a bug in the OS, not the other way around.

Anyway, we will try to do a release soon, probably in the coming week.

**Comment by SomberNight** [comment] 2020-11-18 22:28
(there are some external links pointing to this issue instead of the original, so reposting here as well)

we have released Electrum 4.0.5 now, with the workaround of using old PyQt5

**Comment by Igv0** [comment] 2020-11-18 22:58
Thanks a lot)
