### ISSUE TITLE
Mac Big Sur - Won't Open

### ISSUE THREAD

**Issue by shaggy35** [spesmilo/electrum#6729] opened 2020-11-13 18:38 UTC
Can't get electrum to open on new mac OSX Big Sur. Just hangs. Have tried re-installing, still a no go.

**Comment by monosux** [comment] 2020-11-13 20:29
Same here

**Comment by brewsterkahle** [comment] 2020-11-13 23:07
same.   icon appears in launch bar, but the main window does not come up on 4.03.   installed 4.04, same thing.

**Comment by SomberNight** [comment] 2020-11-14 02:44
duplicate of https://github.com/spesmilo/electrum/issues/6461
please search existing issues before opening a new one

**Closed by SomberNight** 2020-11-14 02:44 UTC
