### ISSUE TITLE
Electrum with ledger stuck 

### ISSUE THREAD

**Issue by kgelinas** [spesmilo/electrum#3385] opened 2017-11-27 01:04 UTC
on confirm transaction on your ledger nano S
I have confirmed the transaction but it still ask me to confirm it

OS Windows 10
Version 3.0 updated to 3.0.2 same issues

**Comment by SomberNight** [comment] 2017-11-27 04:25
Is this a duplicate of #3264 ?
Please try https://github.com/spesmilo/electrum/issues/3264#issuecomment-345414501

**Comment by kgelinas** [comment] 2017-11-27 17:57
Tried it and does not work.
also if it's a dupplicate and not corrected in the current version why is it closed?

**Comment by SomberNight** [comment] 2017-11-27 18:08
Could you describe the issue you're experiencing in detail?

That is closed because the fix for it is already in the master branch, but not in a release yet.

**Comment by kgelinas** [comment] 2017-11-27 18:28
I pu my ledger Nano S in Bitcoin Mode
Open Electrum with the wallet that I have set with the Ledger Nano S
I try to send a payment from my account to another one (pay to filled with the right wallet and right ammount
click send and the message "Confirm transaction on your Ledger device..." appear
the first time the ledger asked me to approve this transaction and Electrum never receive the information. It kust keep looping with the message "Confirm transaction on your Ledger device..."

after this I never could get to the part where my ledger nano s ask me to approve the transaction.
I will try the debian version tonight in live CD

P.S. I also tried to update the ledger.py with the version that supposedly fix the popup I believe that the only change that was done and still can't send the payment.

**Comment by kgelinas** [comment] 2017-11-28 17:40
could not have it working on debian will try later but now with 3.0.2 on another computer and even if i have enough money in my wallet electrum is saying not enough funds....

**Comment by kgelinas** [comment] 2017-11-29 03:01
same message on Debian not enough funds even if it does say that there's more left....

do you need more information?

**Comment by kgelinas** [comment] 2017-11-30 14:44
@SomberNight 
Any update?????
anything I can do to help you have a diagnostics?

**Comment by SomberNight** [comment] 2017-11-30 15:14
> the first time the ledger asked me to approve this transaction and Electrum never receive the information. It kust keep looping with the message "Confirm transaction on your Ledger device..."

This very much sounds like https://github.com/spesmilo/electrum/issues/3264

> even if i have enough money in my wallet electrum is saying not enough funds....

This sounds unrelated. You're probably trying to send almost all your coins, and don't have enough left to pay fees (or similar).

Hence, I still think that the original problem is just a duplicate of the mentioned issue.

**Comment by kgelinas** [comment] 2017-11-30 15:58
If i enter anything other that 0 now it say not enough funds and non I tried to only send a portion of my funds

I was only doing some test before transfering all my fund there's some reward from a pool I received
I have 0.0008... and was trying to transfert a small portion of this to another wallet. heck even the max button is saying this...

anyway here's my wallet if you want anyway with electrum this is now worth nothing...
https://blockchain.info/address/1MqvRpAfrLuucpecuVoF9Xq214V7Axrw6a

thanks god I didin't used this wallet with my slushpool account after they paid me the 0.1 I helped mined...

also if this is a dup I can also replicate the result in debian which in the original issues it's working on debian.

**Comment by kgelinas** [comment] 2017-11-30 16:00
also do you have a release that I could use on Windows with the fix we could test this to make sure.

**Comment by SomberNight** [comment] 2017-11-30 17:34
> do you have a release that I could use on Windows

You can try with 2.9.3, for the purposes of regaining access, not debugging.

> You're probably trying to send almost all your coins, and don't have enough left to pay fees (or similar).

> I have 0.0008... 

As painful as this might sound, that is quite a low amount compared to fees these days. You could try enabling manual fee editing, and set a really low fee. 

> if this is a dup I can also replicate the result in debian which in the original issues it's working on debian

Again, the "not enough funds" problem is unrelated to Ledger. AFAI could understand, you did not replicate the Ledger tx-signing problem ( https://github.com/spesmilo/electrum/issues/3264 ) on debian. Even if you did, that problem is to do with threading and really might appear (or not appear) on any machine in a seemingly random way.

Sorry but I'm closing this, but feel free to reply if you have relevant information to add.

**Closed by SomberNight** 2017-11-30 17:34 UTC
