### ISSUE TITLE
[GUI-QT/Network] Proxy settings are not saved when 'Use Tor' is toggled

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#2750] opened 2017-08-15 01:39 UTC
I'm on using the Windows Installer 2.9.3 (release) version of Electrum.

- Go to Network/Proxy tab.
- Configure a proxy manually.
    - 	Select SOCKS5 from dropdown.
    - 	Enter 1.2.3.4 as host address.
    - 	Enter 1080 as port.
- Click "User Tor proxy at port 9050".
    - _Note that host and port changes to 127.0.0.1:9050_
- Go to "Server" tab.
- Go back to "Proxy" tab.

---

- Expected behaviour:
    -  host and port are set to 127.0.0.1:9050
    -  Checkbox "User Tor proxy at port 9050" is enabled
- Actual behaviour:
    - 	host and port are back to 1.2.3.4:1080
    - 	Checkbox "User Tor proxy at port 9050" is enabled

**Comment by ecdsa** [comment] 2017-08-15 05:34
duplicate of #2747 
please take the time to check existing issues before you post

**Comment by SomberNight** [comment] 2017-08-15 10:23
It is not a duplicate of #2747 as that is about persisting the setting to disk, while this issue details how the proxy settings are not saved even to the in-memory dictionary/simple_config.

Please follow the instructions in the OP to see for yourself. I wrote a PR for both this issue (#2751) and the one you referenced (#2754), and it is quite clear that they are separate.

**Comment by ecdsa** [comment] 2017-08-15 10:42
ok, sorry

**Closed** 2017-08-15 10:48 UTC
