### ISSUE TITLE
Can't sign 2 of 3 multisig transaction

### ISSUE THREAD

**Issue by qirtaiba** [spesmilo/electrum#3108] opened 2017-10-24 17:56 UTC
When I try to sign a 2 of 3 multisig transaction I get this error:

    Server-side exception: <Fault -32603: Server error: File "/usr/local/lib/python3.4/dist-packages/Electrum-3.0-py3.4.egg/electrum/keystore.py", line 65, in get_tx_derivations | IndexError: list index out of range
    >
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/jsonrpclib_pelix-0.3.1-py3.4.egg/jsonrpclib/SimpleJSONRPCServer.py", line 376, in _dispatch
        return func(*params)
      File "/usr/local/lib/python3.4/dist-packages/Electrum-3.0-py3.4.egg/electrum/daemon.py", line 267, in run_cmdline
        result = func(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/Electrum-3.0-py3.4.egg/electrum/commands.py", line 94, in func_wrapper
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/Electrum-3.0-py3.4.egg/electrum/commands.py", line 246, in signtransaction
        self.wallet.sign_transaction(tx, password)
      File "/usr/local/lib/python3.4/dist-packages/Electrum-3.0-py3.4.egg/electrum/wallet.py", line 1129, in sign_transaction
        if k.can_sign(tx):
      File "/usr/local/lib/python3.4/dist-packages/Electrum-3.0-py3.4.egg/electrum/keystore.py", line 77, in can_sign
        return bool(self.get_tx_derivations(tx))
      File "/usr/local/lib/python3.4/dist-packages/Electrum-3.0-py3.4.egg/electrum/keystore.py", line 65, in get_tx_derivations
        if x_signatures[k] is not None:
    IndexError: list index out of range
    Traceback (most recent call last):
      File "/usr/local/bin/electrum", line 4, in <module>
        __import__('pkg_resources').run_script('Electrum==3.0', 'electrum')
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 534, in run_script
        self.require(requires)[0].run_script(script_name, ns)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1438, in run_script
        execfile(script_filename, namespace, namespace)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 59, in execfile
        exec(compile(open(fn).read(), fn, 'exec'), globs, locs)
      File "/usr/local/lib/python3.4/dist-packages/Electrum-3.0-py3.4.egg/EGG-INFO/scripts/electrum", line 423, in <module>
        result = server.run_cmdline(config_options)
      File "/usr/local/lib/python3.4/dist-packages/jsonrpclib_pelix-0.3.1-py3.4.egg/jsonrpclib/jsonrpc.py", line 650, in __call__
      File "/usr/local/lib/python3.4/dist-packages/jsonrpclib_pelix-0.3.1-py3.4.egg/jsonrpclib/jsonrpc.py", line 532, in _request
      File "/usr/local/lib/python3.4/dist-packages/jsonrpclib_pelix-0.3.1-py3.4.egg/jsonrpclib/jsonrpc.py", line 1220, in check_for_errors
    jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "/usr/local/lib/python3.4/dist-packages/Electrum-3.0-py3.4.egg/electrum/keystore.py", line 65, in get_tx_derivations | IndexError: list index out of range\n')

However when I sign the same transaction using coinb.in, then I am able to broadcast it with electrum.

**Comment by SomberNight** [comment] 2017-10-24 18:17
Duplicate of #3059 ?

**Comment by ecdsa** [comment] 2017-10-25 19:38
yes

**Closed by ecdsa** 2017-10-25 19:38 UTC
