### ISSUE TITLE
can't send btc after update

### ISSUE THREAD

**Issue by Barracuda116** [spesmilo/electrum#8386] opened 2023-05-04 11:04 UTC
when sending btc the electrum application on android, is throwing an error: We're sorry that something went wrong while working.

**Comment by Barracuda116** [comment] 2023-05-04 11:12
The Electrum application is installed on a smartphone with the Android operating system. Recently, the Electrum app has updated itself. At the moment, it is not possible to withdraw btc. The application is throwing an error. Writes: We're sorry that something went wrong while working. There is no seed phrase in the settings. I don't remember it. So far the wallet has been working fine.

**Comment by SomberNight** [comment] 2023-05-04 15:36
"Something went wrong while executing Electrum" is a generic text shown when there is an error that the crash reporter can handle and the crash reporter appears. You should send the crash report using that same dialog.

To be able to help you here, we would need relevant details from the crash report itself. At a very minimum, the last line of the traceback.

btw is this with a 2fa wallet?
I guess this might be a duplicate of https://github.com/spesmilo/electrum/issues/8368, which will be fixed in the next version, 4.4.2. The new version should be released soon.

**Closed by SomberNight** 2023-05-04 15:36 UTC

**Comment by Barracuda116** [comment] 2023-05-04 16:41
Yes, this is error  with a 2fa wallet
