### ISSUE TITLE
standard wallet has mixed script type addresses. wallet file corrupted or malware

### ISSUE THREAD

**Issue by guillehaddad** [spesmilo/electrum#4790] opened 2018-10-22 20:32 UTC
I'm trying to send some funds from my wallet but i keep getting the error below. I'm using electrum 3.2.3... A weird thing i've noticed is i have adresses starting with 3 (pe 3ENstJYCK9eyhEeXrq5XNE685RrMKi6WmP) and some starting with 1 (pe 1H1L1emw7Uyq4R9afp81BvyCE1xKge3PUd), thought i should have only one or the other...

error: {'code': 1, 'message': 'the transaction was rejected by network rules.\n\nmandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element) (code 16)

**Comment by SomberNight** [comment] 2018-10-22 21:14
In the menu bar, go to `Wallet` > `Information`.
What is `Wallet type` and `Script type`?

**Comment by guillehaddad** [comment] 2018-10-22 22:44
standard and p2pkh

**Comment by SomberNight** [comment] 2018-10-23 01:08
Like you said, in that kind of wallet, there should not be a mix of "1.." and "3.." addresses. Specifically, all addresses should be "1.." addresses in this case. Your wallet file has either been corrupted somehow (but I doubt Electrum itself did this), or I would guess there is some kind of malware injecting its own addresses into your wallet file, hoping you receive coins there.
You should check the GPG signature or share the hash of the Electrum binary you've downloaded (what OS?). You should restore from seed, preferably on another machine.

**Comment by guillehaddad** [comment] 2018-10-23 11:35
i did check gpg sig before intalling it... i m using linux and even though i m no expert, i m not a new to btc and i ve been using electrum for years now... i can see the wallet got corrupted some how now looking at the wallet file... it started with p2pkh and all of the sudden it changes to p2wpkh... funds havent moved yet and i do keep my os update and dont install garbage on it, so i dont believe its some kind of malaware... the thing is as u said, all addresses should be p2pkh, but i ve deposited in a p2wpkh address... ive been trying to recover it using seed or xprivkey but havent had any success so far... is there anything  someone can think of that can help recover this funds? thanks a lot anyways

**Comment by SomberNight** [comment] 2018-12-02 21:52
Have you managed to recover these coins? If not, do you mind sharing the address where they are stuck?

**Comment by ecdsa** [comment] 2018-12-13 09:41
@guillehaddad 
 - why are you mentioning p2wkph? p2wpkh addresses do not start with a "3", they start with "bc1"
 - do you still have the wallet file?
 - can you post the complete error message (with the hexadecimal transaction)

**Comment by ecdsa** [comment] 2018-12-13 09:52
if you still have the wallet file, please post a screenshot of the "addresses" tab with the mixed type of addresses

**Comment by SomberNight** [comment] 2019-02-06 19:32
Please take a look at potential explanation in #5082
Does that seem feasible?

**Comment by ecdsa** [comment] 2019-02-08 08:46
closing this, because the issue is explained.  please follow-up in #5082

**Closed by ecdsa** 2019-02-08 08:46 UTC
Labels: maybe-malware, question
