### ISSUE TITLE
Trezor plugin does not restore all bip44 accounts 

### ISSUE THREAD

**Issue by Perlover** [spesmilo/electrum#1128] opened 2015-04-03 01:23 UTC
Hi,

Electrum 2.0.4 has incorrect definition of used account when it restores accounts from seed (BIP44).
If an account has zero balance of bitcoins but it was used (has non-zero transaction amounts) - the correct behaviour is to decide is this account as used or not by amount Txs and to continue calculate addresses if an amount of Txs > 0. The Electrum's behaviour is incorrect - it decides that account was not used if balance is zero and the Electrum stops calculations of addresses so it doesn't see new addresses which are used later in old accounts but where account balances are zero. If i want to see old accounts i should put bitcoins in these accounts again (this is not problem of gaps)

So the Electrum should decide used account by amount of transactions for address/account but not by balances in these addresses/account.

**Comment by ecdsa** [comment] 2015-04-03 05:53
were you restoring a trezor wallet?

**Comment by ecdsa** [comment] 2015-04-04 14:46
closing, no answer from OP.
fyi, only trezor wallets uses bip44 in electrum

**Comment by Perlover** [comment] 2015-04-04 16:24
fucked support
no answer 24 hour -> closed ticket, problem resolved

**Comment by ecdsa** [comment] 2015-04-04 16:34
please answer my question: was it a trezor seed?

**Comment by Perlover** [comment] 2015-04-04 21:55
Hi,

I don't understand your questions
Yes, it was a trezor. But there was no seed because i not intered seed in Electrum.
Electrum works as watch-only walet. So now you know answer to your question?

**Comment by Perlover** [comment] 2015-04-04 22:01
So again by other words.
I have the Trezor device installed, the seed into Trezor.
There is some accounts, for example: acount 1, acount 2, account 3 and account 4.
All four accounts were used (transactions were there). Account 5 and so on - addresses from these accounts not used yet.
But account 1 and account 2 have non-zero current balances but account 3 & account 4 are empty now. But addersses were used!

Normal software BIP44 (MyTrezor.com & Mycelium) restores from xPub key from seed of Trezor and they show account 3  & account 4 as zero-belenced BECAUSE TRANSACIONS WERE THERE.

The Electrum restores acount 1 & account 2. Finish. No there account 3 & account 4. I THINK IT HAPPENS because Electrum sees zero-balances in account 3 & account 4 and thinks that these accounts should not be restores as not-used.

**Comment by Perlover** [comment] 2015-04-04 22:06
> Electrum 2.0.4 has incorrect definition of used account when it restores accounts from seed (BIP44).
Sorry, my mistake
I mean other, i described in last message. Yes, not from seed. Sorry

**Comment by Perlover** [comment] 2015-04-06 20:45
Now i restored watch-only Trezor wallet again
I had zero-balance in middle account (example: acc1 >0, acc2 > 0, acc3 = 0, acc4 > 0) and the Electrum 2.0.4 restored all accounts. May be there is bug in case as acc1 >0, acc2 > 0, acc3 = 0, acc4 =0 (all accounts were used: Txs amount > 0) - i had in this scheme that the Electrum restored only acc1 & acc2.


So now i cannot reproduce bug again (but now i added some funds in last zero account again)

So may be ticket should be closed.

Best regards

**Comment by ecdsa** [comment] 2015-04-07 04:44
indeed, if two consecutive accounts are empty, then it stops restoring. that's expected behaviour.

**Comment by Perlover** [comment] 2015-04-07 09:01
I am sure it's not correct behaviour if the Electrum thinks that an account is empty by zero balance. It should be done through zero amount of transactions in account.

Example:

I have Trezor and i used 4 account for example: acc1 > 0, acc2 > 0, acc3 > 0 and acc4 > 0. But in some moment i moved whole bitcoins from acc2 & acc3. Then i decided to restore Trezor wallet (watch-only mode of course) in the Electrum. I connected a trezor device,  created hardware wallet. And what? I will see only acc1? But how can i get an access to acc4 where i have bitcoins too? A typical user will think that he was robbed.

Is it ok how do you think? I think BIP44 standard described other gap algoritms for restoring...

**Comment by Perlover** [comment] 2015-04-07 09:03
https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#Account_discovery

    3. scan addresses of the external chain; respect the gap limit described below
    4. if no transactions are found on the external chain, stop discovery
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    5. if there are some transactions, increase the account index and go to step 1

**Comment by ecdsa** [comment] 2015-04-07 16:25
it's not because the account has a zero balance.
it's because it looks at the first address of an account in order to decide if the account is used.

**Comment by Perlover** [comment] 2015-04-07 16:29
It's not correct behaviour. BIP44 defines how should be done this: gap 20 addresses, so account will not be used only if first 20 addresses are not used (zero transactions).
It is strange that this idea requires so much explanation here.

**Comment by ecdsa** [comment] 2015-04-07 16:44
it took me some time to understand what you were talking about, because you described the problem as if Electrum was not creating the account because of a zero balance. When you report a bug, you should describe what you see, and not try to make interpretations.

**Comment by kyuupichan** [comment] 2015-12-24 05:48
I will take a look at fixing this before year end

**Closed** 2015-12-25 14:35 UTC
Labels: Trezor
