### ISSUE TITLE
Can't reproduce AppImage Electrum-3.3.8 (Cython version not pinned down, needed for hidapi at build time)

### ISSUE THREAD

**Issue by margre8** [spesmilo/electrum#5859] opened 2019-12-23 18:53 UTC
After build Electrum 3.3.8 AppImage and compare files via sha256 I see the files aren't same.

### Official release:

> fd2526f7a37530bb655375d3c95ce6a51e3c2beb83ff88a54e28aa365033794a

### My build:

> f97b75af5265ff2cea7a32b56da7f4b7a6bb0b4e0bffae3b6fb037a5e635af6e

### OS:
Ubuntu 18.04.3

### Docker version:
19.03.5

Thank you for help

**Comment by SomberNight** [comment] 2019-12-24 02:36
ACK. reproducibility is now broken for `electrum-3.3.8-x86_64.AppImage`.
It definitely used to work.

I now built the same differing binary you got (`f97b75af5265ff2cea7a32b56da7f4b7a6bb0b4e0bffae3b6fb037a5e635af6e`).

I have now added some notes about this in the README:
https://github.com/spesmilo/electrum/tree/b3c0231b2b32b27cd4dbb417d0e400f0a72aac4b/contrib/build-linux/appimage#how-to-investigate-diff-between-binaries-if-reproducibility-fails

-----

In this case, the direct cause of the diff is the following:
```
$ cat d
1859c1859
< e5fafadac5c381a448d5821c32c1d03c9837097157bf6817a6c245e38104b19c  ./usr/lib/python3.6/site-packages/hidraw.cpython-36m-x86_64-linux-gnu.so
---
> d21816003e11f8a083a4ef6863863147f8f212a54a62a4ac2aabc38e2b8c0748  ./usr/lib/python3.6/site-packages/hidraw.cpython-36m-x86_64-linux-gnu.so
2155c2155
< 56017ed4859765f1326b91785f983f78a1c34138ede0640aaf9e4f8c6a0ec940  ./usr/lib/python3.6/site-packages/hid.cpython-36m-x86_64-linux-gnu.so
---
> 7fdf91caea39c60de71419bd16a7a5f50296869fda55de13850aa72f5aca9b30  ./usr/lib/python3.6/site-packages/hid.cpython-36m-x86_64-linux-gnu.so
```

I will try to investigate why these hid/hidraw shared objects changed, later. Feel free to pitch in if you have ideas.

**Comment by margre8** [comment] 2019-12-24 08:45
I have got an idea, this could by caused by time settings on computer (release AppImage was created in july).

**Comment by margre8** [comment] 2019-12-25 08:37
Same problem is in Electrum-ltc too and in Electrum-ltc some files in my build missing see: https://github.com/pooler/electrum-ltc/issues/230

**Comment by margre8** [comment] 2019-12-25 18:45
I got a next idea, if Python 3.6 is build from source, I think python might download some dependences (libraries, etc.) and if this dependences has no version and hash prefixes there is a change to they might be updated (after you release Electrum-3.3.8) and that's why are these two files different.

**Comment by margre8** [comment] 2020-01-21 20:05
@SomberNight I have a question, this hid/hidraw modules is from hidapi package (https://github.com/spesmilo/electrum/blob/master/contrib/deterministic-build/requirements-hw.txt) downloaded by pip? If yes is this package precompilated?

**Comment by margre8** [comment] 2020-01-21 20:06
I have found this issue in Electron-cash too.

**Comment by SomberNight** [comment] 2020-01-21 20:24
> this hid/hidraw modules is from hidapi package (https://github.com/spesmilo/electrum/blob/master/contrib/deterministic-build/requirements-hw.txt) downloaded by pip? If yes is this package precompilated?

Yes, it's related to the hidapi package. I believe it is built from source.

> I have found this same issue in Electron-cash too.

You should report it to them then.
@EchterAgo seems to be quite adept in related matters.

**Comment by margre8** [comment] 2020-01-21 20:33
@SomberNight Thank you for quick reaction, I report it ASAP. It seems this issue is manifesting across all Electrum forks.

**Comment by margre8** [comment] 2020-01-21 20:42
https://github.com/Electron-Cash/Electron-Cash/issues/1778 Opened.

**Comment by margre8** [comment] 2020-01-21 20:52
> I got another idea, if Python 3.6 is build from source, I think python might download some dependences (libraries, etc.) and if this dependences has no version and hash prefixes. There is a change this hypothetical dependences has been updated (after you release Electrum-3.3.8) and that's why these two files are different.

I guess this isn't core of problem. I will continue investigating this issue. @SomberNight If I'll find out anything I will tell you.

**Comment by EchterAgo** [comment] 2020-01-22 04:51
Differences in compiled binaries are likely fixed by this commit:

https://github.com/spesmilo/electrum/commit/880bd168835a703832dccb368099ec3cd2bdbb63#diff-c902be315a5ed89a4de7aae8d3d32287

@margre8 or @SomberNight please share your generated AppImage and I will try to confirm this.

**Comment by SomberNight** [comment] 2020-01-22 05:31
@EchterAgo uploaded to https://filebin.net/oypfb983gpdj4ixr

```
$ sha256sum electrum-3.3.8-x86_64.AppImage_build20200122
f97b75af5265ff2cea7a32b56da7f4b7a6bb0b4e0bffae3b6fb037a5e635af6e  electrum-3.3.8-x86_64.AppImage_build20200122
```

**Comment by EchterAgo** [comment] 2020-01-22 05:45
Ok, those differences are not those fixed by https://github.com/spesmilo/electrum/commit/880bd168835a703832dccb368099ec3cd2bdbb63

We use exactly the same hashes for `hidapi` in Electron Cash and it still produces the same build hashes. From the disassembly it looks like it moves something into a struct at a different offset, 8 bytes after the original version. This happens right before function calls to python and iconv.

Diffoscope log: https://ec.loping.net/ichundes/diffo.log

**Comment by EchterAgo** [comment] 2020-01-22 06:00
I also just reproduced the `f97b75af5265ff2cea7a32b56da7f4b7a6bb0b4e0bffae3b6fb037a5e635af6e` build.

**Comment by EchterAgo** [comment] 2020-01-22 07:15
Ok, so the values that changed are references to the line numbers of generated C code by Cython that get passed to `__Pyx_AddTraceback`. The line numbers of `hid.pyx` and `hidraw.pyx` are also included, so the `cython-hid` module has not changed. What has changed is the C code that Cython generates from them. I really have a hard time believing both files were generated by the same Cython version.

**Comment by EchterAgo** [comment] 2020-01-22 07:30
https://github.com/spesmilo/electrum/commit/ec496a8222938a070fd864571b9d97b4af6f42fc#diff-5ffd2d998da570702d03c74063cef5ed

Looks like I broke this :) Cython is not needed at runtime, but the version should still be enforced at build time.

**Comment by cculianu** [comment] 2020-01-22 08:31
Yeah it looks like as new Cython versions are released, building `hidapi` ends up downloading "latest Cython" (if it's not already installed in the build environment), which in turn affects reproducibility.

The fix:

1. Hard-code a Cython version in the `requiredments-hw.txt` for deterministic builds, then
2. Let hidapi build using that implicitly.
3. Removing the `Cython` package in the build env after the hw wallet stuff is built (AppImage only -- Windows and macOS don't pick it up anyway).

**Comment by SomberNight** [comment] 2020-01-22 09:23
What guarantees that the pinned Cython is installed before hidapi is built? Is pip smart enough for this?
-------- Original Message --------

**Comment by cculianu** [comment] 2020-01-22 09:40
> What guarantees that the pinned Cython is installed before hidapi is built? Is pip smart enough for 

You know what? I asked myself the same question as we were doing this -- the problem is hidapi doesn't have Cython as a requirement for installation so pip might only "see" the requirement when it tries to build (it's a build requirement, not an installation requirement).

That's a very good question and deserves further investigation.

**Comment by cculianu** [comment] 2020-01-22 09:47
A superficial google search shows pip is not that smart.. at least.. judging by the number of github issues related to it not seeing `build_requires` when it does its initial dependency resolution.. unless i'm mistaken or they have since fixed it.  Here is a github thread: https://github.com/pypa/pip/issues/2381

**Comment by EchterAgo** [comment] 2020-01-22 09:51
Pip will go through the requirements file line by line. If a dependency of the current line is not yet installed, it will install it. Since Cython is on the first line, it will be installed first. What is more concerning to me is that the deterministic requirements do not preserve ordering and instead orders alphabetically.

EC's current install order can be seen in this build log:

https://ec.loping.net/4.0.13-dev1-24-gdb9b092f0/build-linux-appimage.log

**Comment by cculianu** [comment] 2020-01-22 09:53
Ah so there is a guarantee we can impose by just having it "appear first" in the file? Cool!  Thanks for that. 
 
> What is more concerning to me is that the deterministic requirements do not preserve ordering and instead orders alphabetically.

We definitely shouldn't be ordering alphabetically then, right?  Ordering should be what we think the natural order is (esp. if some deps are **build** deps which pip can't "see").... Correct?

**Comment by EchterAgo** [comment] 2020-01-22 09:54
The order in the deterministic reqs should be the same as it would install from the regular reqs.

**Comment by SomberNight** [comment] 2020-01-22 10:43
> The order in the deterministic reqs should be the same as it would install from the regular reqs.

well... I'm not too happy about this still... the whole thing seems very fragile

@achow101 you might be interested in this issue too, re HWI.
Right now, I see that Cython is not pinned in https://github.com/bitcoin-core/HWI/blob/4c13daed3b62635320e2411c1dd6a8ee307012e5/poetry.lock, only hidapi, so I guess that too must be susceptible to sudden silent reproducibility failure.
However, as HWI is using poetry, and not a custom hack like us, I am curious if that opens up the way for a cleaner solution.

**Comment by SomberNight** [comment] 2020-01-22 11:28
In any case, thank you for investigating this @EchterAgo

**Comment by EchterAgo** [comment] 2020-01-22 11:29
I have a way to generate the deterministic requirements in installation order now. I'll ping you once I tested it enough.

**Comment by margre8** [comment] 2020-01-22 16:20
big thanks for everyone, thank you very much for help.

**Comment by achow101** [comment] 2020-01-22 18:33
> @achow101 you might be interested in this issue too, re HWI.
> Right now, I see that Cython is not pinned in https://github.com/bitcoin-core/HWI/blob/4c13daed3b62635320e2411c1dd6a8ee307012e5/poetry.lock, only hidapi, so I guess that too must be susceptible to sudden silent reproducibility failure.

It looks like it is.

> However, as HWI is using poetry, and not a custom hack like us, I am curious if that opens up the way for a cleaner solution.

Poetry uses pip in the background and I can't find any special handling for Cython. So I don't think it helps here.

**Comment by SomberNight** [comment] 2020-02-14 19:17
Closing this as the immediate issue is solved by the above commits (https://github.com/spesmilo/electrum/commit/80025a3af4fa6e456aeac089d41ff4530755b818 and https://github.com/spesmilo/electrum/commit/4406eebbfef0ccd0a748b4bf4bf190f3c612a6a0).

**Closed by SomberNight** 2020-02-14 19:17 UTC
Labels: OS-linux 🐧, build/packaging, reproducible/deterministic builds

**Comment by SomberNight** [comment] 2020-12-12 01:48
> Yeah it looks like as new Cython versions are released, building hidapi ends up downloading "latest Cython" (if it's not already installed in the build environment), which in turn affects reproducibility.

Yes; to be explicit, this happens because `hidapi` specifies `Cython` in [`setup_requires` only](https://github.com/trezor/cython-hidapi/blob/506d726cc69c527233545d72bf56efd0802096f5/setup.py#L125-L126).


See https://pip.pypa.io/en/stable/reference/pip_install/#controlling-setup-requires
and https://github.com/pypa/setuptools/issues/1916#issuecomment-743350566

> Setuptools offers the setup_requires setup() keyword for specifying dependencies that need to be present in order for the setup.py script to run. Internally, Setuptools uses easy_install to fulfill these dependencies.
>
> pip has no way to control how these dependencies are located. None of the package index options have an effect.

I think we should try to hard fail if this were to happen. I will do a PR soon.
