### ISSUE TITLE
[segwit] different txid?

### ISSUE THREAD

**Issue by lzsaver** [spesmilo/electrum#2904] opened 2017-09-20 23:20 UTC
Electrum 3.0 master branch git 77eb62b

Electrum shows different txid before and after I sign my segwit transaction. The first one is the right one, all blockexplorers show it, but what is the second one? It seems not okay for segwit.

**Comment by SomberNight** [comment] 2017-09-21 00:25
Can you give more details? (e.g. what type of wallet and keystore)
On testnet, I created a "segwit" Standard_Wallet with a BIP32_KeyStore, and tried to send a 1 in 2 out tx (with input and both outputs controlled by the wallet). I couldn't reproduce the issue.

**Comment by ecdsa** [comment] 2017-09-21 08:06
that's a bug, txid should not change. 
please give details

**Comment by lzsaver** [comment] 2017-09-21 13:05
Here is an example from the main net.
Right txid - 00baea865ddfbbe9578205be36950dd16a22d82d8705a708d77b9d42ef2576f6
Wrong txid - 8cdb3f00549e39a594ba493fe0e2622d0dd0f7952d7c58960d3ed425524c836d

Electrum shows only the wrong one in the UI. But it writes the right one to the wallet file.
It is the standard wallet with the hardware trezor keystore, the derivation is m/49'/0'/0'.
Do you need more details?

**Comment by ecdsa** [comment] 2017-09-22 09:32
are you sure you were on 77eb62b4cb580f1bd6b1e47d7aece0a46f0aa05e, and not on an earlier commit?

**Comment by lzsaver** [comment] 2017-09-22 15:45
Yes, I am.

Here is my new tx using git 348ef7d.
Right txid: ab9af73351f0fc1a1fdd1759d851930ae20d2e6861506101d2fe9c9cecfa3e88
Wrong txid: 1aa914cea53dcae5c9e02834f341b746856fca662d317887b627757f33baf0a7

Screenshots:
https://ipfs.io/ipfs/zdj7WiYuWMuRJfRhEoX38A28yxDZT9uZDUXCo5sKMdqWQ76H8/electrum-unsigned.png
https://ipfs.io/ipfs/zdj7WkALfckRfebByijQpWZrgXqwmm1sXrkuoGupvHqodm3qA/electrum-signed.png

**Comment by ecdsa** [comment] 2017-09-23 01:25
ok, I see the issue.
the txid is wrong in the tx details window, after the tx has been broadcast

**Comment by lzsaver** [comment] 2017-09-23 03:00
That's right. Also this issue appears if I copy my signed tx and load it from the text without broadcasting it.

**Comment by ecdsa** [comment] 2017-09-23 03:27
fixed in ab2d0f389c939adf0d89b8ec39b22132c0aeff3e

**Closed by ecdsa** 2017-09-23 03:27 UTC
