### ISSUE TITLE
Local incoming transaction

### ISSUE THREAD

**Issue by freezable** [spesmilo/electrum#5472] opened 2019-06-29 23:15 UTC
I have a incoming transaction with the status local as you can see: 
https://gyazo.com/63da7c5d14fb2e27e728e13a1f1519d6

I tried to lookup what it means and it was said that it means that the transaction was created but not signed/broatcasted yet. This all makes sense but what does it mean when its an INCOMING transaction. It cannot be not broatcasted because then I wouldn't see it, right? 
I tried to broadcast it but it says "Missing input".

Could someone please explain what this exactly is, how it happend and what to do with it?

**Comment by SomberNight** [comment] 2019-06-29 23:54
dupe of https://github.com/spesmilo/electrum/issues/5473

**Closed by SomberNight** 2019-06-29 23:54 UTC
