### ISSUE TITLE
"Install with PIP" does not work after upgrading to Ubuntu 24.04

### ISSUE THREAD

**Issue by BTCBellyButton** [spesmilo/electrum#9212] opened 2024-09-21 03:20 UTC
`python3 -m pip install --user Electrum-4.5.5.tar.gz`
 
```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

```

**Comment by DireWolfM14** [comment] 2024-09-25 02:18
Try this tutorial:
https://bitcointalk.org/index.php?topic=5456909.msg62430610#msg62430610

**Comment by SomberNight** [comment] 2024-09-26 09:36
duplicate of https://github.com/spesmilo/electrum/issues/8328

**Closed by SomberNight** 2024-09-26 09:36 UTC
