### ISSUE TITLE
Electrum not working on Mac OS Big Sur

### ISSUE THREAD

**Issue by regedittap** [spesmilo/electrum#6726] opened 2020-11-12 02:38 UTC
![image](https://user-images.githubusercontent.com/8253590/98888515-1ab98f80-24d3-11eb-866e-4e9639fb8f31.png)

The app is not launching and got this error on macos logs

**Comment by SomberNight** [comment] 2020-11-12 05:34
duplicate of https://github.com/spesmilo/electrum/issues/6461

**Closed by SomberNight** 2020-11-12 05:34 UTC
