### ISSUE TITLE
Nothing happens when importing using seed

### ISSUE THREAD

**Issue by elav** [spesmilo/electrum#3512] opened 2017-12-13 04:28 UTC
Hi. 

I'd like to know if I'm doing something wrong. I am using Electrum 3.0.2 in Linux. I forgot the password for my wallet, however, I have the 13 words and the Master Public Key. 

I followed the instructions offered to restore the wallet, the only difference is that I marked the option to encrypt the new .. I put my 13 words, and created a new wallet, but empty .. the previous one is still active, but now it says: imported What am I doing wrong? I'm afraid of losing my money.

Cheers

**Comment by SomberNight** [comment] 2017-12-13 09:52
Where does it say "imported"?

- Make sure that your client has synced. Is the orb in the lower right green?
- Can you compare addresses to check that the wallet you restored is the same logical wallet?

**Comment by ecdsa** [comment] 2017-12-13 10:02
you cannot recover imported private keys from seed

**Comment by elav** [comment] 2017-12-13 13:40
Thanks for answering.

Maybe I did not explain myself well. I have a wallet that has money, but I have had that wallet for a long time and I do not remember the password, so I can not send anything.

As I read in the documentation, you can recover that money if we create / restore a new wallet and use the 13 words that Electrum generates when we create the wallet for the first time.

That's what I want to do, restore my money in a new wallet (I do not know if it's new, restored, imported) to have control over my password.

The word imported comes out in the title bar of Electrum, in my original wallet, the first one. But in the new wallet it says that my balance is zero.

Thanks

**Comment by SomberNight** [comment] 2017-12-13 13:46
> the 13 words that Electrum generates

For reference, those are usually called "seed words" or just "seed".

> The word imported comes out in the title bar of Electrum, in my original wallet, the first one

Ok, so @ecdsa's comment applies.
Your original wallet contains imported private keys. That walled was not generated from seed words, hence you can not restore/recreate it from seed words.
Those 13 words that you have found are most likely for a different wallet.

**Comment by elav** [comment] 2017-12-13 14:45
But it is that the word Imported appeared after I tried to restore the new wallet using the 13 words. I have never imported my wallet, I believe it a few years ago and I never felt the need to do it.

Then is there something I can do? I followed the steps indicated for when you lose the password, and this is what happened. Thanks

**Comment by SomberNight** [comment] 2017-12-13 14:50
Open your original wallet file (the one you want to regain access to) using a recent version (3.0.x) of Electrum.
In the top menu bar, go into `Wallet`>`Information`. What is `Wallet type` there?

**Comment by elav** [comment] 2017-12-13 16:20
Now he says:

Wallet Name: default_wallet
Wallet Type: Imported
Script Type: Address

But that's where the question is, before creating the new wallet, Imported did not say ..

Now, in the new one, it says:

Wallet Name: MyWallet
Wallet Type: Standart
Script Type: p2pkh

And add the Master Publication key below, which is the same as the previous wallet. And I know it's the same, because I saved those data when I created the first wallet.

**Comment by SomberNight** [comment] 2017-12-13 19:11
First, again, "imported" wallets can not be recovered from seed words.
It is possible though that you imported individual private keys or addresses FROM a seeded wallet, into an imported wallet.

It is also possible that the seed words you saved/wrote down are for a different wallet.
Unhide/show the `Addresses` tab using the `View` menu, and compare the addresses between the wallets.

**Comment by elav** [comment] 2017-12-13 21:19
It seems they still do not understand me. The main wallet, the one that has the money, I did not import it, I believe it a few years ago, and now, after creating a new wallet, it is that the main wallet says Imported. It's the weird thing, it's what I do not understand .. why does Imported say now if I did not import it?

Reviewing the addresses, the main wallet (which I repeat did not matter), only has one address, but the other wallet, the new wallet, which I tried to import using the seed, has 20 different addresses.

I show you the picture of both. For reasons of privacy, I deleted the information from my balance.

![screenshot_20171213_151725](https://user-images.githubusercontent.com/800918/33963010-0ec752cc-e019-11e7-9db5-c3b9c5f6bfa4.png)

**Comment by SomberNight** [comment] 2017-12-16 19:23
The wallet named "default_wallet" (top of the picture) contains a single imported private key. It is NOT a wallet that has a seed. You can NOT restore that from seed words.

(It might be the case that you exported a single private key from a seeded wallet and created "default_wallet" from that, and in that case you can restore the original wallet if you have the seed words for that.)

The seed words that you do have seem to be for a different wallet.

> For reasons of privacy, I deleted the information from my balance

You should also obfuscate the address itself in that case.

This issue is not a bug, GitHub is mainly for development, I'm closing this, sorry.
You can try to get help on Bitcointalk or Reddit or IRC: https://electrum.org/#community (if you do, you should probably link to this issue)

**Closed by SomberNight** 2017-12-16 19:23 UTC
