### ISSUE TITLE
Silent crash on Windows7 if path to AppData\Roaming\Electrum contains national characters

### ISSUE THREAD

**Issue by eug13768** [spesmilo/electrum#2376] opened 2017-04-30 08:09 UTC
In case there are national characters in the path to AppData\Roaming\Electrum - for example, username in OS is "Администратор", then the full path looks like C:\Users\Администратор\AppData\Roaming\Electrum - and it is silently crashing on "Generating your addresses" or so.

**Comment by dabura667** [comment] 2017-04-30 14:31
What version of Electrum are you using? This issue was fixed a long time ago.

**Comment by eug13768** [comment] 2017-04-30 17:05
2.8.2. I tried a few older versions with the same result. 

I have not seen any errors (where are logs, btw?), it's just the fact that it did not run as I explained and it run without issues under the user with pure EN profile name/path.

Any additional steps / information to debug it?

**Comment by hjaeresen** [comment] 2017-06-19 07:46
I see a similar problem. 
I'm using Electrum 2.8.3. Just did a clean install and generated a default_wallet. 
When I start the client now, and enter the password for default_wallet, Electrum silently crashes. 
I'm on Windows 10 pro, 64 bit on a Lenovo P50, 32 gb, Intel i7-6820 2.70 GHz. 
My AppData\Roaming\Electrum path contains national character, as my user name includes the Danish letter "æ" (a+e ligature).

Is there any way to make Electrum use a different folder that the user's AppData folder?

**Comment by ecdsa** [comment] 2017-07-03 10:21
closing, duplicate of #2269

**Closed by ecdsa** 2017-07-03 10:21 UTC
