### ISSUE TITLE
Channel amount cannot be changed manually in input box once "max" is clicked

### ISSUE THREAD

**Issue by strk** [spesmilo/electrum#9104] opened 2024-06-23 07:51 UTC
In the "open channel" dialog, the "amount" field can be modified manually just fine until the "max" button is pressed. From then on, there is no way to manually specify an amount and you can only switch betwene "max" and "min" amounts.

This is with version 4.5.5

**Comment by accumulator** [comment] 2024-10-08 10:33
Can't reproduce. Can you give more information?

**Comment by strk** [comment] 2024-10-08 12:11
I just tried on Android, version 4.5.5 and could not reproduce there (also, there is no "min" button there) so I guess this was on a GNU/Linux system.

BTW I noticed on Android the warning about need to backup the wallet to recover channels, which is currently not possible (is my understanding) due to #8996

**Comment by accumulator** [comment] 2024-10-08 12:15
> BTW I noticed on Android the warning about need to backup the wallet to recover channels, which is currently not possible (is my understanding) due to #8996

The backup is referring to a channel backup, which is not a full wallet backup, but can be used as an emergency method to close the channel from another instance of the wallet with the same seed.

**Comment by accumulator** [comment] 2024-10-08 14:56
fixed in 1d7ccb392806209dc3bedb7cf5d70f16201ceca1

**Closed by accumulator** 2024-10-08 14:56 UTC
Labels: awaiting-response 💤
