### ISSUE TITLE
tx size and fee rate in transaction details dialog

### ISSUE THREAD

**Issue by Rogach** [spesmilo/electrum#8434] opened 2023-05-15 11:17 UTC
In the transaction details dialog the size is shown as "bytes", but in fact the number shown is for vbytes. Same goes for the fee rate - the label is "sat/byte", but in fact it's sat/vB.

I think most explorers and fee rate monitors are using "vB" or "vbyte" units, so this difference in units might be confusing to the user.

Perhaps we can show fee rate as "sat/vB", and transaction size using both values? E.g. `Size: 178 vB (340 bytes)`.

**Comment by Rogach** [comment] 2023-05-15 11:18
(I'll be willing to make a PR if such a change is deemed useful)

**Comment by de-served** [comment] 2023-05-16 06:41
Let it be than it won't be. If it will not add more bugs than there are - why not IMHO?

**Comment by SomberNight** [comment] 2023-05-16 13:13
This is a duplicate of https://github.com/spesmilo/electrum/issues/6961
Feel free to comment there instead.

**Closed by SomberNight** 2023-05-16 13:13 UTC
