### ISSUE TITLE
stolen funds

### ISSUE THREAD

**Issue by Adinis0** [spesmilo/electrum#2180] opened 2017-02-20 12:40 UTC
0,497311 btc was stolen from my electrum. there is no trojan or something like that on my computer. Can you help me to get back my btc?

**Comment by JazzTp** [comment] 2017-02-20 12:44
Hi I'm a newbie but I think you should provide more info, like:

Operative system type and version

Electrum version

Wallet type

Whether or not you were keeping a SEPARATE OFFLINE COLD STORAGE.

**Comment by Adinis0** [comment] 2017-02-20 12:48
Windows 8
Electrum 2.7.18

![screenshot 2](https://cloud.githubusercontent.com/assets/25901851/23125653/e4294abe-f740-11e6-9bbb-725b6c16e756.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/25901851/23125652/e427d242-f740-11e6-8ec2-40e776c84b8d.png)

**Comment by JazzTp** [comment] 2017-02-20 13:08
Don't see if you were using an offline cold storage, which I have always
considered mandatory.

A system is safe until it's not, e.g.
https://themerkle.com/top-3-types-of-bitcoin-mining-malware/

**Comment by JazzTp** [comment] 2017-02-20 13:15
Let me add: here they deal with bugs in the Electrum software, and unless
you provide evidence that the loss of funds is due to some bug, they will
just close this issue. In similar cases I've read "recovery but possible",
so again provide all possible info (but no cold storage => risk).

**Comment by bauerj** [comment] 2017-02-20 16:58
What about the second transaction? Did you do that?

**Comment by Adinis0** [comment] 2017-02-20 19:13
I didn't make 2 last transactions. I don't know what evidence do you need to see. I've opened my electrum today morning to send btc, but instead I see 0.

**Comment by JazzTp** [comment] 2017-02-21 02:29
"Evidence" _normally_ here, as for what I read so far, means steps to reproduce the issue.

I'm following these issues in the process of better documenting myself, as I said I'm relatively a newbie... but since the very beginning I've adopted the recommended precautions.

If you were not using an offline cold storage to keep your private key out of reach from any possible attack, including any new virus able to bypass your system defenses, I'd frankly think - I might be wrong - that the most likely explanation is that your system was penetrated by an attacker.

Here goes that link again: https://themerkle.com/top-3-types-of-bitcoin-mining-malware/

Antivirus and firewall softwares are generally "behind" attackers' newest techniques, seldom ahead, they address them _after_ encountering them.

(I read in articles of an attack which passed through unaware personnel of a mobile telephony company... the attacker could easily have the victim's account transferred to a new number and voilà, as the man was accessing many accounts of various nature from his mobile phone, millions worth in bitcoins were stolen... So again: I'd never trust anything but an _**offline**_ cold storage, being it a hardware wallet of Electrum itself running on an offline machine, if it is a laptop it might be a good idea to disconnect the power line from all radio modules [wifi + GMS], anyways no remote management activated, strong password on the BIOS settings, all networking disabled by BIOS not only via the OS, ethernet cable unplugged. I'd only sign outgoing transactions _there_.)

**Comment by ecdsa** [comment] 2017-02-21 19:16
sorry for your loss, but this is not the place to report this.

**Closed by ecdsa** 2017-02-21 19:16 UTC

**Comment by JazzTp** [comment] 2017-02-28 23:13
Adding a link to relevant information (get the PDF from this page):
http://www.tcij.org/resources/handbooks/infosec
