### ISSUE TITLE
ColdCard MK3 mostly useless with electrum

### ISSUE THREAD

**Issue by gustavonalle** [spesmilo/electrum#5970] opened 2020-02-15 09:54 UTC
Electrum version: 3.3.8
ColdCard MK3 Version: 3.0.6
MacOS 10.15.3

Problems I am facing:
* PSBT generated by electrum for a P2WPKH transaction cannot be signed by Coldcard:
      ```FAILURE: none of the keys involved in this tx belong to this coldcard need XYZ```
* Using ColdCard though USB (paring) shows it as connected, but doesn't show any past transactions or UTXO

What am I missing?

**Comment by gustavonalle** [comment] 2020-02-15 09:59
No errors in the debug log too:
```
D | util.profiler | AddressSynchronizer.load_local_history 0.0000
D | util.profiler | AddressSynchronizer.check_history 0.0002
D | util.profiler | AddressList.update 0.0067
I | plugin.DeviceMgr | getting client for keystore
I | plugin.DeviceMgr | scanning devices...
D | util.profiler | WalletStorage.write 0.0000
D | util.profiler | Deterministic_Wallet.try_detecting_internal_addresses_corruption 0.0572
D | util.profiler | ElectrumWindow.load_wallet 0.0825
I | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
D | util.profiler | Abstract_Wallet.get_full_history 0.0002
D | util.profiler | HistoryModel.refresh 0.0008
D | util.profiler | AddressList.update 0.0067
I | plugin.DeviceMgr | Registering <CKCCClient: xfp=xxxxxxx label='Coldcard xxxxxxxx'>
I | plugins.coldcard.coldcard | Derive xtype = 'p2wpkh'
I | plugin.DeviceMgr | end client for keystore
```

**Comment by ecdsa** [comment] 2020-02-15 10:38
closing as duplicate of #5969

**Closed by ecdsa** 2020-02-15 10:38 UTC

**Comment by gustavonalle** [comment] 2020-02-15 10:44
The PSBT is mostly likely a duplicate, but what about the fact I cannot see any transaction when connecting via USB?
