### ISSUE TITLE
payment failure HTLC value sum would exceed max allowed

### ISSUE THREAD

**Issue by mmeloni** [spesmilo/electrum#8830] opened 2024-01-18 21:12 UTC
Electrum is returning a payment error:
```
payment failure: PaymentFailure('HTLC value sum (sum of pending htlcs: 0.0 sat plus new htlc: ******* sat) would exceed max allowed: 225000.0 sat')
```

There is no explanation on how to fix in UI. Its possible to have some clue of whats going on inspecting debug log, but its not sufficient to address the problem

**Comment by SomberNight** [comment] 2024-01-19 02:13
- So you are trying to make a payment and it fails with this error?
- Out of curiousity, what is the channel capacity (approx) -- i.e. how does it compare to the mentioned max_htlc_value_in_flight_msat?
- Are you using trampoline?
- Can you say who the remote node is; and do you perhaps know what lightning implementation they run?
- Do you have other channels that the path finding could try to use, and it's just not trying them, or is this the only channel you have open?
- If you have debug logs, even if you don't want to share the whole log, could you share the full traceback for the exception?

**Comment by mmeloni** [comment] 2024-01-20 07:58
Tnx @SomberNight:

> So you are trying to make a payment and it fails with this error?

Yes

> Out of curiousity, what is the channel capacity (approx) -- i.e. how does it compare to the mentioned max_htlc_value_in_flight_msat?

Capacity: 500000 sat vs 315236.52 sat
> Are you using trampoline?

yes
> Can you say who the remote node is; and do you perhaps know what lightning implementation they run?

I dont know, maybe there is a way to know? 
> Do you have other channels that the path finding could try to use, and it's just not trying them, or is this the only channel you have open?

There was only a single opened channel
> If you have debug logs, even if you don't want to share the whole log, could you share the full traceback for the exception?

Sure:
```
20240118T195844.610757Z |    DEBUG | util.profiler | JsonDB.write_and_force_consolidation 0.0097 sec
20240118T195844.620378Z |     INFO | storage.WalletStorage | saved /home/******
20240118T195844.620563Z |    DEBUG | util.profiler | JsonDB.write_and_force_consolidation 0.0055 sec
20240118T195844.620735Z |     INFO | lnworker.LNWallet.[mywallet] | pay_invoice starting session for RHASH=*******. using_trampoline=True. invoice_features=['VAR_ONION_OPT', 'PAYMENT_SECRET_REQ', 'BASIC_MPP_OPT']
20240118T195844.620897Z |     INFO | lnworker.LNWallet.[mywallet] | invoice status triggered (2) for key ******* and status 4
20240118T195844.621449Z |     INFO | lnworker.LNWallet.[mywallet] | channels_with_funds: {(b'*******', b'*******'): 431054552}
20240118T195844.622894Z |     INFO | lnworker.LNWallet.[mywallet] | suggest_split 315204000 returned 1 configurations
20240118T195844.622981Z |     INFO | lnworker.LNWallet.[mywallet] | trying split configuration: dict_values([[315204000]]) rating: 2.068043527406664
20240118T195844.630428Z |     INFO | lnworker.LNWallet.[mywallet] | created route with trampoline fee level=1
20240118T195844.630634Z |     INFO | lnworker.LNWallet.[mywallet] | trampoline hops: ['*******', '*******']
20240118T195844.630723Z |     INFO | lnworker.LNWallet.[mywallet] | per trampoline fees: 32520
20240118T195844.631187Z |     INFO | lnworker.LNWallet.[mywallet] | adding route 315204000 32520 115850552
20240118T195844.631376Z |     INFO | lnpeer.Peer.[LNWallet, 03ecef675b-81219fec] | lnpeer.pay len(route)=1
20240118T195844.631504Z |     INFO | lnpeer.Peer.[LNWallet, 03ecef675b-81219fec] |   0: edge=825691x14x2 hop_data=<OnionHopsDataSingle. payload={'amt_to_forward': {'amt_to_forward': 315236520}, 'outgoing_cltv_value': {'outgoing_cltv_value': 826955}, 'payment_data': {'payment_secret': b'*******', 'total_msat': 315236520, 'amount_msat': 315236520}}. hmac=None>
20240118T195844.631604Z |     INFO | lnpeer.Peer.[LNWallet, 03ecef675b-81219fec] | adding trampoline onion to final payload
20240118T195844.631864Z |     INFO | lnpeer.Peer.[LNWallet, 03ecef675b-81219fec] | lnpeer.pay len(t_route)=2
20240118T195844.632074Z |     INFO | lnpeer.Peer.[LNWallet, 03ecef675b-81219fec] |   0: t_node=******* hop_data=<OnionHopsDataSingle. payload={'amt_to_forward': {'amt_to_forward': 315204000}, 'outgoing_cltv_value': {'outgoing_cltv_value': 826379}, 'outgoing_node_id': {'outgoing_node_id': b'*******'}, 'invoice_features': {'invoice_features': <None: 0x24200>}, 'invoice_routing_info': {'invoice_routing_info': b"*******"}, 'payment_data': {'payment_secret': b"*******", 'total_msat': 315204000}}. hmac=b'*******'>
20240118T195844.632236Z |     INFO | lnpeer.Peer.[LNWallet, 03ecef675b-81219fec] |   1: t_node=******* hop_data=<OnionHopsDataSingle. payload={'amt_to_forward': {'amt_to_forward': 315204000}, 'outgoing_cltv_value': {'outgoing_cltv_value': 826379}, 'payment_data': {'payment_secret': b"*******", 'total_msat': 315204000}}. hmac=b'*******'>
20240118T195844.633360Z |     INFO | lnpeer.Peer.[LNWallet, 03ecef675b-81219fec] | starting payment. len(route)=1.
20240118T195844.633821Z |     INFO | lnworker.LNWallet.[mywallet] | payment failure: PaymentFailure('HTLC value sum (sum of pending htlcs: 0.0 sat plus new htlc: 315236.52 sat) would exceed max allowed: 225000.0 sat')
20240118T195844.634031Z |     INFO | lnworker.LNWallet.[mywallet] | pay_invoice ending session for RHASH=*******. success=False
20240118T195844.638273Z |     INFO | storage.WalletStorage | saved /home/******
20240118T195844.638406Z |    DEBUG | util.profiler | JsonDB.write_and_force_consolidation 0.0041 sec
20240118T195844.638505Z |     INFO | lnworker.LNWallet.[mywallet] | invoice status triggered (2) for key ******* and status 0
```

**Comment by SomberNight** [comment] 2024-01-30 02:42
I think this is a duplicate of https://github.com/spesmilo/electrum/issues/8533

**Closed by SomberNight** 2024-01-30 02:42 UTC
