### ISSUE TITLE
Error Signing a TX with Trezor One. Electrum 3.3.8

### ISSUE THREAD

**Issue by Mengeroshi** [spesmilo/electrum#6245] opened 2020-06-20 07:50 UTC
![Electrum-error](https://user-images.githubusercontent.com/44041766/85196420-bf76ce80-b29f-11ea-9986-8595fc1c6e41.png)
This is the message that I get when I want to sign the TX with my Trezor One.
Firmware Updated.
It's a PWPKH Derivation Key.

**Comment by prusnak** [comment] 2020-06-20 11:00
Duplicate of https://github.com/spesmilo/electrum/issues/6214

This is already fixed in master and the fix will be published in the upcoming 4.0 release of Electrum.

**Comment by Mengeroshi** [comment] 2020-06-20 21:08
> Duplicate of #6214
> 
> This is already fixed in master and the fix will be published in the upcoming 4.0 release of Electrum.

When will be realesed?

**Comment by SomberNight** [comment] 2020-06-20 22:47
very soon

**Closed by SomberNight** 2020-06-20 22:47 UTC
