### ISSUE TITLE
transaction was rejected by network rules.\n\nmandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation) + Seed restore issue

### ISSUE THREAD

**Issue by MrSoapDealer** [spesmilo/electrum#5066] opened 2019-02-04 22:13 UTC
Background:
- Using Tails 3.11 with persistence
- Using Electrum 3.1.3
- All my addresses start with "1"
- When on Windows 10, using Electrum 3.3.2

I've only downloaded Tails off the official website, all the updates were automated after. I've never manually updated Electrum so always just used the stock version Tails provides. Windows wise official Electrum site, I also have working wallets there.

Issue:

I created a new standard 12 seed encrypted wallet on Electrum 3.1.3 via Tails OS 3.11. All went routine, wallet syncd. I sent coin to two of the receiving addresses in Wallet 1. Funds immediately shown unconfirmed, as they confirm the transactions complete, all is well. Once I tried sending these coins out is where the issues start. This is the error when trying to broadcast:

error: {'message': 'the transaction was rejected by network rules.\n\nmandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation) (code 16)\n[0100000002ea6501d36bfefbcb5974fcc7d88033887b4a7c82d24390alae2256614ee8ec2b000000006b4830450'code': 1}

I tried switching servers and gave it another few tries, same error. Going another route I switched to a different OS (Windows 10, Electrum 3.3.2) I went through restoring my seed of Wallet 1. After sync this wallet has no balance nor transactions and all of the addresses do not match compared to Wallet 1 on Tails. I tried to sweep the keys but that gives error of no inputs when trying to broadcast. Importing leads me to a different address. The xpubs on Tails and restored seed on Windows do match.

I made another new standard wallet on Tails, all went same as above. Sent coin to Wallet 2, received and balance shows correctly. Get the same error code trying to broadcast out. Repeated the same steps above and got same result. Seed opens non matching wallet, xpubs match.

Sometime during or after I recieved the coins I gained 16 new addresses ontop of my 20 orginal. I ran sign/verify tests on each address. In both wallets the first 20 give an error of wrong signature when trying to verify sig. The 16 addresses that follow do pass verifying. The 6 change addresses also give error of wrong signature. The coins are within those first 20 unable to verify signature. I also checked sign/verify on the restored seeds on Windows, all 20 addresses pass.

I made another new wallet 3 via Tails. This remains unused, theres 20 addresses that all pass a sign/verify check. Havent done any other tests besides checking its xpub on blockchain.

Further inspection on blockchain.info I looked up each individual transaction, all is correct balance wise; still unspent. When I search both wallets 1 and 2 xpubs they bring me to empty wallets with zero transaction history.

Another odd thing is when I enter my wallet 1 seed for restoring, halfway through the fifth word it let's me hit next. Brings me into another different wallet with no matching addresses, doesnt match original wallet 1 nor restored wallet 1. Not sure if that pertains to the issue.

Even when I run a fresh Tails without persistence session trying to restore seeds it brings me into the wallets that the restore on Windows gives me, addresses match and pass sign/verify. I can only see these transactions and balance when logged into the wallets on Tails (persistence) where both orginal files were created/stored. I'm able to check my seeds and keys as I can still login aswell but unable to move any funds around or transfer.

- Note I recently just did the upgrade to Tails 3.12 but had no changes in issues
- I can send xpubs and received addresses if it helps the investigation

**Comment by SomberNight** [comment] 2019-02-06 19:31
Please take a look at potential explanation in https://github.com/spesmilo/electrum/issues/5082
As you were using Tails with persistence, I assume you were storing the wallet files on a USB flash drive?
Does the explanation seem feasible?

**Comment by ecdsa** [comment] 2019-02-08 08:46
closing this, because the issue is explained.  please follow-up in #5082

**Closed by ecdsa** 2019-02-08 08:46 UTC

**Comment by MrSoapDealer** [comment] 2019-02-09 17:15
Thank Yous for the investigation! This definitely sounds what caused the issue, electrum wizard overwriting my "old deleted" wallet but keeping the old addresses and giving me a new seed. Now time to try my best to recover the old seed from an overwritten text file if that's even plausible.
