### ISSUE TITLE
Preferences window does not come up under Ubuntu 18.04

### ISSUE THREAD

**Issue by chkoreff** [spesmilo/electrum#4639] opened 2018-08-17 20:44 UTC
I upgraded to Ubuntu 18.04 today.  Now the preferences window does not come up in Electrum.  I'm running version 2.6.4.

When I click the little monkey-wrench icon to bring up Preferences, or try it from the menu Tools/Preferences, I see this error in /var/log/syslog:

~~~
Aug 17 16:43:25 laptop electrum_electrum.desktop[2452]: Traceback (most recent call last):
Aug 17 16:43:25 laptop electrum_electrum.desktop[2452]:   File "/snap/electrum/2/gui/qt/main_window.py", line 82, in onPress
Aug 17 16:43:25 laptop electrum_electrum.desktop[2452]:     self.func()
Aug 17 16:43:25 laptop electrum_electrum.desktop[2452]:   File "/snap/electrum/2/gui/qt/main_window.py", line 2773, in settings_dialog
Aug 17 16:43:25 laptop electrum_electrum.desktop[2452]:     system_cameras = qrscanner._find_system_cameras()
Aug 17 16:43:25 laptop electrum_electrum.desktop[2452]:   File "/snap/electrum/2/lib/qrscanner.py", line 70, in _find_system_cameras
Aug 17 16:43:25 laptop electrum_electrum.desktop[2452]:     name = open(os.path.join(device_root, device, 'name')).read()
Aug 17 16:43:25 laptop electrum_electrum.desktop[2452]: IOError: [Errno 13] Permission denied: '/sys/class/video4linux/v4l-touch0/name'
Aug 17 16:43:25 laptop kernel: [  568.345830] audit: type=1400 audit(1534538605.623:83): apparmor="DENIED" operation="open" profile="snap.electrum.electrum" name="/sys/devices/rmi4-00/rmi4-00.fn54/video4linux/v4l-touch0/name" pid=2452 comm="python2" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
~~~

**Comment by SomberNight** [comment] 2018-08-17 21:09
Looks like duplicate of https://github.com/spesmilo/electrum/issues/2603

> I'm running version 2.6.4.

Please update.
I'm guessing you might have installed from the snap store, however the package there is not maintained by us.

**Closed by SomberNight** 2018-08-17 21:09 UTC

**Comment by chkoreff** [comment] 2018-08-17 21:37
That was the problem -- installing from the Snap store.  After I upgraded to Ubuntu 18.04 the Electrum client I already had installed would no longer come up, so I figured oh well I'll just install it from Snap.  I re-entered my seed phrase and all that.

Turns out my original ~/.electrum directory is still fine, and all I had to do to clean up everything was to go through the normal install.  I first uninstalled the Snap version just in case, then:

sudo apt-get install python3-setuptools python3-pyqt5 python3-pip
# (nothing to do there, but still)
sudo pip3 install https://download.electrum.org/3.2.2/Electrum-3.2.2.tar.gz

Now I have 3.2.2 and Preferences works fine.  Thanks, it's beautiful.
