### ISSUE TITLE
Can't open Electrum 3.0.2 (win10)

### ISSUE THREAD

**Issue by thomasog** [spesmilo/electrum#3353] opened 2017-11-22 01:18 UTC
Hi all,

I'm trying to use Electrum 3.0.2 in a Windows 10 machine, but it simply won't open after installing. The portable version appears to have the same problem.

I've read some topics in bitcointalk suggesting erasing the wallet files, but this is a clean windows install, and Electrum was never used in this computer before.

If anyone knows what could be happening, I would be glad. 

Thanks in advance

**Comment by SomberNight** [comment] 2017-11-22 01:33
duplicate of #3290

Could you share more details of your windows install (or whatever comes to mind that might be related)?

If it's a clean install, it might be relatively easy to reproduce. What version of Windows 10? How did you install it? Any chance of having a hash of an `.iso` that I could get or similar?

**Comment by thomasog** [comment] 2017-11-22 01:44
Windows 10 pro
Version 1709
OS Build 16299.64

Installed from usb stick, using mediacreationtool.exe (https://www.microsoft.com/software-download/windows10).

I've just tried previous versions. 3.0.1 and 3.0 didn't work, same problem. Version 2.9.3 worked perfectly.

**Comment by yorickdowne** [comment] 2017-11-22 13:20
Any AV products running? What you expect to see is a warning by Windows via SmartScreen, because Electrum isn't signed. If you have AV that prevents unsigned binaries, those might block it.

**Comment by SomberNight** [comment] 2017-11-22 13:42
I haven't been able to reproduce this yet.

I downloaded the media creation tool and created a Windows installer `.iso` (x64, US English).
After installing it in a VirtualBox VM, the version was [Version 10.0.16299.15].
I downloaded Firefox, and then one of the official Electrum 3.0.2 binaries. Electrum started without problems.
Then I ran Windows Update, and rebooted the VM; the version now was [Version 10.0.16299.64]. Electrum started without problems again.

**Comment by thomasog** [comment] 2017-11-22 13:42
I'm using Windows Defender

Antimalware client version: 4.12.16299.15
Engine version: 1.1.14306.0
Antivirus definition: 1.257.809.0
Antispyware definition: 1.257.809.0
Network inspection system engine version: 2.1.14.202.0
Network inspection system definition version: 118.2.0.0

Smartscreen configured to warn, but no screen appears when I try to run Electrum.

**Comment by ignus2** [comment] 2017-11-23 19:00
This happened to me only when there were other zombie instances of electrum running. After I killed all stale instances of electrum through the task manager, it started without problems.
What that means though is electrum sometimes gets stuck when closed and doesn't exit properly.

**Comment by SomberNight** [comment] 2022-10-10 01:46
Lots have changed re the Windows build since this was opened. Closing.

**Closed by SomberNight** 2022-10-10 01:46 UTC
Labels: OS-windows 🪟
