### ISSUE TITLE
Incompatible library error when opening a Coldcard skeleton wallet

### ISSUE THREAD

**Issue by fjsousa** [spesmilo/electrum#8116] opened 2023-01-03 16:11 UTC
Got this error when trying to open a skeleton wallet created with a Coldcard (MK4):

![image](https://user-images.githubusercontent.com/4125060/210393653-add09f0f-5fc5-461e-9f4f-fef8d91109de.png)

Installed electrum from source on a fedora 36 with:
```
sudo dnf install PyQt5 python3-setuptools  libsecp256k1 python3-cryptography python3-setuptools python3-pip
wget https://download.electrum.org/4.3.3/Electrum-4.3.3.tar.gz
python3 -m pip install --user Electrum-4.3.3.tar.gz
```

**Comment by SomberNight** [comment] 2023-01-03 16:15
Is there more info, e.g. a traceback, in the [debug logs](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging)?

**Comment by fjsousa** [comment] 2023-01-03 16:19
I reinstalled [ckcc-protocol](https://github.com/Coldcard/ckcc-protocol with `python3 -m pip install --user ckcc-protocol` and the error went away.

**Comment by SomberNight** [comment] 2023-01-03 16:24
Well, ok, it works for me with `ckcc-protocol==1.3.2`. Until someone can reproduce, closing.

**Closed by SomberNight** 2023-01-03 16:24 UTC
