### ISSUE TITLE
Hangs after setting wallet password

### ISSUE THREAD

**Issue by daveherts** [spesmilo/electrum#2599] opened 2017-07-12 16:37 UTC
Strange issue, If i set a wallet password electrum says "not responding" and hangs. When i restart electrum the wallet has no password. I am using Windows 10 and electrum 2,8.3

**Comment by bauerj** [comment] 2017-07-12 16:38
Can you reproduce that when you create a second wallet?

**Comment by daveherts** [comment] 2017-07-12 16:39
yes does the same, dont know if this has any bearing on it, but wallet was created by importing private keys

**Comment by bauerj** [comment] 2017-07-12 16:45
How many private keys?

**Comment by daveherts** [comment] 2017-07-12 16:47
2

**Comment by bauerj** [comment] 2017-07-12 16:52
I can't reproduce this with two private keys.

Can you try importing this keys?

    5HpHagT65TZzG1PH3CSu63k8DbpvD8s5ip4nEB3kEsreAnchuDf  
    5HpHagT65TZzG1PH3CSu63k8DbpvD8s5ip4nEB3kEsreAvUcVfH

**Comment by daveherts** [comment] 2017-07-12 17:01
does the same

**Comment by daveherts** [comment] 2017-07-12 17:08
seems to be if the encrypt box is ticked

**Comment by bauerj** [comment] 2017-07-12 17:12
Do you use the installer version? Does your username contain non-ASCII characters?

**Comment by ecdsa** [comment] 2017-07-12 17:13
probably same as #2470 
what is the size of your wallet file? are you on OSX?

**Comment by ecdsa** [comment] 2017-07-18 07:35
closing, probable duplicate and OP is not answering.

**Closed by ecdsa** 2017-07-18 07:35 UTC
