### ISSUE TITLE
Not able to withdraw any coin at all

### ISSUE THREAD

**Issue by Grayman102** [spesmilo/electrum#8381] opened 2023-05-03 14:49 UTC
I have been having this issue for a few days now and it goes something along these lines. When I go to send any amount from my Electrum wallet to another wallet, (except for when I try to send the max amount) I have a second output address that won't change and contains the word Yuan in the address so it makes me wonder if I've been hacked by a Chinese hacker that want me to pay them more than 100% of what I am sending because if I try to send 10mbtc, the yuan address says 13 mbtc. Also, the bug report says the error type: bool object is not callable. I have no idea how to fix this bug but Ive never experienced it before and I'm not able to touch any of my coin. Saw a post that this would be fixed in the next update but as of 5/3/23 the issue still exists and I still cannot access any of my funds.

**Comment by SomberNight** [comment] 2023-05-03 15:14
> When I go to send any amount from my Electrum wallet to another wallet, (except for when I try to send the max amount) I have a second output address 

Is the second output address colored yellow (or green)? Then it is just a normal [change address](https://en.bitcoin.it/wiki/Change).

> contains the word Yuan in the address 

Sounds like random chance.

> the bug report says the error type: bool object is not callable

Do you have a 2FA wallet?
This is probably a duplicate of: https://github.com/spesmilo/electrum/issues/8368 and https://github.com/spesmilo/electrum/issues/8375

**Comment by Grayman102** [comment] 2023-05-03 20:14
Yes I have a 2fa wallet and I saw the issue on another post. Do you have an
idea when the update will be released and when I'll be able to access my
coin again?

**Closed** 2023-05-03 23:27 UTC
Labels: bug 🐞, duplicate 👥

**Comment by Grayman102** [comment] 2023-05-04 01:46
Ok, thank you.
