### ISSUE TITLE
Error Visual C++ Runtime Library

### ISSUE THREAD

**Issue by Marokovan** [spesmilo/electrum#1440] opened 2015-09-04 04:02 UTC
Hello

When run the portable ver 2.4.4 Win 7, Error Visual C++ Runtime Library
RunTime Error!
R6034

After clicking OK, the program starts. but it is annoying error with every run.

No problem with portable ver. 1.9.8

Thank you
![screenshot 1](https://cloud.githubusercontent.com/assets/14120410/9676352/81a69656-52ca-11e5-9481-bd8fa84cccb7.jpg)

**Comment by triorr** [comment] 2015-09-04 04:46
duplicate of issue #1000

**Closed** 2015-09-04 06:16 UTC
