### ISSUE TITLE
Nano Ledgers shows wrong address when sending funds to only one p2wpkh address

### ISSUE THREAD

**Issue by derHase85** [spesmilo/electrum#3987] opened 2018-02-28 16:23 UTC
I've generated a p2wpkh ledger nano wallet and wanted to transfer all my funds from a p2wpkh-p2sh ledger nano to it.

I've generated a new transaction and choose one single bech32 receiving address from the p2wpkh wallet. I've selected MAX to send all funds. When it comes to sign the transaction, the address shown on the ledger is not a bech32 address type, but a legacy address. Signing works, sending works and I receive the funds at my bech32 address.

The wallet is a bip84 wallet

I've tested some possible types of transactions:

several p2wpkh-p2sh inputs to one p2wpkh output, all funds -> nano shows legacy address
several p2wpkh inputs to one p2wpkh output, all funds -> nano shows legacy address
several p2wpkh inputs to several p2wpkh outputs, not all funds -> nano shows bech32 addresses
several p2wpkh inputs to several p2wpkh outputs, all funds -> nano shows bech32 addresses

electrum, ledger and btchip are the latest versions from git

**Comment by SomberNight** [comment] 2018-02-28 16:28
dupe of https://github.com/spesmilo/electrum/issues/3543

**Closed by SomberNight** 2018-02-28 16:28 UTC
Labels: duplicate, hw-ledger
