### ISSUE TITLE
Import funds (private key)

### ISSUE THREAD

**Issue by jonjonez** [spesmilo/electrum#8879] opened 2024-02-08 15:28 UTC
Today, to import a private key into Electrum, we need to create a specific wallet to import keys and addresses, but there is a problem with that, when spending funds from the address that had the private key imported, there is no change address configured, the remaining funds will remain at the address used., which is not recommended as Bitcoin uses change addresses for its transactions for remaining funds to preserve user privacy.

Wouldn't it be better if instead of creating a new file just to import private keys, import private keys directly into an HD wallet? This way, when spending the private key, the remaining funds would return to the next keypair change index of the existing hd wallet created by electrum.

The imported private key would continue to be part of the keypair of the file that contains the current wallet created by Electrum and would be located in the addresses tab with a new section called: imported (just as it was in the past, I think electrum before version 2.0 worked exactly like this).

You may say that this is insecure, but in fact the bitcoin core wallet works exactly like this (and Electrum also used to), because assuming you added this feature, users who don't understand how transactions work could create a new hd seed in the electrum just to spend funds from a paperwallet, import a paperwallet, send funds to a new address by paying something, and without him knowing, the remaining funds would return to the change index of the new hd wallet created by him at Electrum, but in his head the remaining funds would remain in the private key of the paperwallet, so he deletes the electrum wallet along with its file that contains the hd wallet and would only keep the paperwallet (thinking that the remaining funds would be there, but they are in the change index of the hd wallet ).

To avoid this, I suggest putting a warning, a disclaimer pointing out that the remaining funds would go to a change address created by the new wallet and not the imported private key.

**Comment by SomberNight** [comment] 2024-02-08 16:18
For a newbie, the easiest and safest thing to do is to sweep the private key.
As an advanced user, you can create an imported wallet, and use pay-to-multi (batched payment) where you directly pay whatever amount you want to whomever and also send the rest to a change address in your other (HD) wallet.

> The imported private key would continue to be part of the keypair of the file that contains the current wallet created by Electrum and would be located in the addresses tab with a new section called: imported (just as it was in the past, I think electrum before version 2.0 worked exactly like this).

There is a reason the feature was removed. As you yourself pointed it out, there are footguns when mixing a seed-based wallet and imported keys. The more common footgun AFAIU was the reverse of what you described: users would only back up the seed and not the original imported keys, and when restoring from seed they lost the coins that were not yet moved from the imported keys.

I acknowledge that for the advanced user, this is not fully satisfactory, there are use cases that are difficult or impossible with the current model. For those, https://github.com/spesmilo/electrum/issues/6016 is still on the roadmap.

I see you also found https://github.com/spesmilo/electrum/issues/7244, I would consider this issue largely a duplicate of that one (and certainly this one is a subset of https://github.com/spesmilo/electrum/issues/6016). So I will close this one.

**Closed by SomberNight** 2024-02-08 16:18 UTC
