### ISSUE TITLE
Windows Install: Camera Function not working (QR codes, zbar issue, scan, scanner)

### ISSUE THREAD

**Issue by BittBurger** [spesmilo/electrum#6018] opened 2020-03-05 19:18 UTC
I apologize in advance, as I have zero experience with GitHub but was directed here.  So any rules I break or content I inadvertantly omit, please forgive.  I'm just going to write this in "longhand" and plain english:

I have two laptops, both with Windows 10 installed.  On both laptops, when clicking the "Send" tab, and then the black camera icon in the top-right corner, two popup windows appear, and one contains error text.  I am given the option to retry, abort, or ignore.  No matter which option I select, the program closes fully.  Screen cap attached.
![photo_2020-03-04_14-41-19](https://user-images.githubusercontent.com/9684377/76016832-ec22f800-5ef3-11ea-8622-8c8dd558bdd0.jpg)

As this has been checked on two unrelated machines I will make the assumption that it's fairly easy to duplicate on any machine, but, version is 3.3.8 and windows camera driver information:
Intel AV Stream Camera 2500.   Driver:  Intel  / Version 30.15063.6.8611 built in camera into top of laptop screen.

I don't know why this would be relevant but its weirdly relevant in several other app bugs I've seen:  I have Norton Internet Security Version 22.20.1.69 and Malwarebytes 4.0.4.49 / Update Package 1.0.20268 / Component Package 1.0.823 installed.

EDIT: text on image:
```
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: ...
File: zbar/video/dshow.c
Line: 518

Expression: img->datalen == bufferlen

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by MrNaif2018** [comment] 2020-03-05 19:27
From investigating it looks like it might be zbar problem, I didn't find that issue in electrum's issues list(I was helping BittBurger), but I found ElectronCash had that issue before, it looks like they solved that by using native QtMultimedia functions instead of zbar(which is from 2012, which looks like might not support newer cameras).
Although there is a newer zbar version as from discussion in related issue:
https://github.com/mchehab/zbar/
Related issues and PRs:
https://github.com/Electron-Cash/Electron-Cash/issues/1282 (that same error)
https://github.com/Electron-Cash/Electron-Cash/pull/1376 (PR which probably fixed it)

**Comment by SomberNight** [comment] 2020-03-06 00:29
Thanks for the report.
That PR from Electron Cash is huge. It should be tested; I imagine it could be ported.

**Comment by SomberNight** [comment] 2020-09-15 15:42
I have ported a part of the changes related to https://github.com/Electron-Cash/Electron-Cash/pull/1376 in https://github.com/spesmilo/electrum/pull/6593, now merged.
It would be good if someone who can reproduce this crash could test with master now.

**Comment by SomberNight** [comment] 2020-10-14 15:39
I think the above change should have fixed this, so closing until someone says otherwise.

**Comment by garethjwhelan** [comment] 2021-06-07 19:46
On Electrum 4.1.2

![Capture](https://user-images.githubusercontent.com/26350070/121078072-c06a7e00-c7d8-11eb-85dd-931f6ab184ea.PNG)

This happens on two Win10 machines less than 1 yr old:
i) when I go to Tools; Load Transaction; From QR Code
ii) when I go to Send; then click on the camera icon to the right of the Pay to form field.

For me, as per the discussion above, this does not happen on the current version of Electron Cash (4.2.4) which scans perfectly.

**Comment by SomberNight** [comment] 2021-06-25 15:55
I have ported the changes from Electron Cash that uses QtMultimedia to access the camera (in https://github.com/spesmilo/electrum/pull/7365).
There are also some other changes, but in short, for the Windows binary we will use that method to scan QR codes.
I still could not reproduce this issue however, hopefully this fixes it.

**Closed by SomberNight** 2021-06-25 15:55 UTC
Labels: OS-windows 🪟, Qt ✨, bug 🐞, camera
