### ISSUE TITLE
Payment requests disappearing

### ISSUE THREAD

**Issue by chill117** [spesmilo/electrum#1641] opened 2016-01-22 22:29 UTC
I am experiencing the same issue that this person from [bitcointalk.org](https://bitcointalk.org/index.php?topic=1317287.0) is having.

I am using the `addrequest` command to generate payment requests in an electrum wallet, as part of an e-commerce website integration. I use `getrequest` to check on the previously generated payment requests, to see if payment has been received yet. The request appears to be created after using `addrequest`, but at some point the request disappears from my electrum wallet.

A few more details:
* Electrum version 2.5.4
* OS is Ubuntu 14.04
* Using a wallet restored from a master public key
* I started seeing this issue after the wallet had 4+ received transactions
* The wallet has about 30+ payment requests.

**Comment by ecdsa** [comment] 2016-01-23 07:56
I think I had it too; it was caused by a race condition between the daemon and the command being executed. it has been fixed in 2.6 (git head, unreleased), with the new daemon.
please try with it.

**Comment by ecdsa** [comment] 2016-01-23 07:57
note: the help page has also been updated for 2.6
http://docs.electrum.org/en/latest/merchant.html

**Comment by chill117** [comment] 2016-01-23 15:06
Thank you for the response. I switched to the latest code (master branch), and it appears that things are working smoother. I will let you know if I run into the problem again.

**Closed** 2016-01-25 04:15 UTC
