### ISSUE TITLE
Electrum doesn't seem to respect exact BTC value when conversion plugin enabled

### ISSUE THREAD

**Issue by zanglebert** [spesmilo/electrum#1357] opened 2015-07-13 14:23 UTC
Electrum 2.3.2
OS X 10.10.4

Hey. Noticed a problem with the conversion plugin that I didn't have before.

I set the transmission value to 0.014 BTC, the conversion plugin (that I have enabled) automatically shows 4 USD in the box next to it, but when I signed the tx, the window that allows me to double check the tx before broadcasting showed that the BTC was *slightly* lower than 0.014, 0.01398 or so.

I suspected (but can't be sure) that maybe the tx takes the BTC value by converting back from the USD value (which was set by my setting of a BTC amount).

Possible? 

Or maybe I'm on the wrong track, and the reasons is completely different. In any case, I have disabled the plugin for now, in which case the BTC amount transferred is identical to the one I set.

**Comment by ecdsa** [comment] 2015-07-13 17:39
I cannot reproduce this. what is the exact sequence of actions that you followed?

**Comment by ecdsa** [comment] 2015-08-05 16:24
I believe you visited the USD amount box, and pressed a key while visiting it, that left the USD amount unchanged, but sent a signal to update the BTC amount

**Comment by ecdsa** [comment] 2015-08-06 10:57
fixed in 2515fc9b6a2669e32820a81b527eccdaac7a21d8
the value of the field will change to blue if it's auto fill

**Closed by ecdsa** 2015-08-06 10:57 UTC

**Comment by zanglebert** [comment] 2015-08-06 13:23
Thanks for looking into it again.

I also tried to reproduce it a few times, but didn't manage. Your explanation what might have happened originally makes sense.
