### ISSUE TITLE
Electrum Executable for OS X is 2.9.2 not 2.9.3 

### ISSUE THREAD

**Issue by TokenHash** [spesmilo/electrum#2960] opened 2017-10-02 19:40 UTC
Hi @ElectrumWallet the link to the Executable for OS X on your download page is for version 2.9.2, not 2.9.3:

https://download.electrum.org/2.9.2/electrum-2.9.2.dmg

I tried changing the link to 2.9.3 like this:

https://download.electrum.org/2.9.3/electrum-2.9.3.dmg

And it worked, but please confirm if it's legit? 

Thanks!

**Comment by SomberNight** [comment] 2017-10-02 19:42
There is a problem with 2.9.3 on Mac. See #2728.
Also, issue is duplicate of #2847, #2958.
Please search other issues before opening new ones.

**Comment by TokenHash** [comment] 2017-10-02 19:52
Thanks, will do.

**Closed** 2017-10-02 19:52 UTC
