### ISSUE TITLE
keyboard not resize in android electrum wallet

### ISSUE THREAD

**Issue by GabrielRCL** [spesmilo/electrum#8691] opened 2023-11-16 00:34 UTC
im using Samsung Galaxy A01 and bitcoin electrum wallet
When I go to enter my seed to recover my bitcoin wallet the keyboard does not resize and I cannot press the "P" key

video:
https://www.veed.io/view/f015eceb-b39d-4de0-a22e-9b146904c9ac

**Comment by accumulator** [comment] 2023-11-16 11:06
duplicate of #8611, and already fixed. This will be available in the next release.

**Closed by accumulator** 2023-11-16 11:06 UTC
Labels: duplicate 👥
