### ISSUE TITLE
Trezor multisig stopped working

### ISSUE THREAD

**Issue by ELM4Ever** [spesmilo/electrum#1429] opened 2015-08-30 02:32 UTC
OSX and Linux. 
Official Electrum releases v2.4.2 or above, or master from Github.  
Python-trezor library at v0.6.5 or v0.6.6

Created a multisig wallet with the XPUB of Trezor.  When comes time to sign with the Trezor, after importing the partially signed transaction into the Trezor wallet, pressing the SIGN button displays briefly the window "Signing Transaction" then the button is greyed out  and nothing else happens.  It used to work...  I get the same  

Traceback (most recent call last):
  File "/Users/xxx/Downloads/electrum-20150829/gui/qt/util.py", line 43, in run
    self.result = self.run_task()
  File "/Users/xxx/Downloads/electrum-20150829/gui/qt/main_window.py", line 1334, in sign_thread
    self.wallet.sign_transaction(tx, password)
  File "/Users/xxx/Downloads/electrum-20150829/plugins/trezor.py", line 494, in sign_transaction
    self.plugin.sign_transaction(tx, prev_tx, xpub_path)
  File "/Users/xxx/Downloads/electrum-20150829/plugins/trezor.py", line 236, in sign_transaction
    inputs = self.tx_inputs(tx, True)
  File "/Users/xxx/Downloads/electrum-20150829/plugins/trezor.py", line 285, in tx_inputs
    xpub, s = BIP32_Account.parse_xpubkey(x_pubkey)
  File "/Users/xxx/Downloads/electrum-20150829/lib/account.py", line 347, in parse_xpubkey
    assert is_extended_pubkey(pubkey)
AssertionError
Traceback (most recent call last):
  File "/Users/xxx/Downloads/electrum-20150829/gui/qt/util.py", line 55, in close
    if type(self.result) is not tuple:
AttributeError: 'WaitingDialog' object has no attribute 'result'

**Comment by ecdsa** [comment] 2015-08-30 16:58
I cannot reproduce this..
could you post the partially signed transaction?

**Comment by ecdsa** [comment] 2015-08-30 16:59
also, make sure the partially signed transaction was created by a recent version of Electrum

**Comment by ELM4Ever** [comment] 2015-08-30 18:12
Just downloaded v.2.4.3 from the release section and created a new partially signed transaction. Still not working - same Traceback. 
Partially signed tx:

{
    "hex": "0100000001fb6c2b07e8d6c22a8c2b341bbbd3d6acea60f7f954503359d1457f1ea259597c00000000c9004930460221009a30e3648a7d69419ad76bcd83847a095163a97623533dd18db06b12ad6f8d0802210096c5514ebe5c29f402bd8f551d1d34b04c004b61d6e626add3e4ef23217e8a470101ff4c7a52210238bf92fa626f859ea1de65d2f879a8d74ebbbb6a07681e46e4304707e6a3ac9f4c53ff0488b21e030073245280000000f97f28194fe8d94ad8f73bd2ba531f9d06ffa0545bf6e2ab2242893e58b107890257ff32500058c3781b2ed63ab7ddc183606e361d36c0f5289d74eb2edb77ebe10000000052aeffffffff014c7a01000000000017a91492a75406e4dfdba8b56e53fb97cd1dbe704adccc8700000000", 
    "complete": false
}

**Comment by ecdsa** [comment] 2015-08-30 21:05
thanks! I think I see the problem

**Comment by ELM4Ever** [comment] 2015-08-31 01:34
If I create the same transaction, but do not sign it with the multisig wallet first, next Load it into the Trezor wallet and attempt to sign it, the following error window appears: "local variable 'account_derivation' referenced before assignment" , with the traceback:
Traceback (most recent call last):
  File "/.../Electrum-2.5-py2.7.egg/electrum_gui/qt/util.py", line 43, in run
    self.result = self.run_task()
  File "/.../Electrum-2.5-py2.7.egg/electrum_gui/qt/main_window.py", line 1334, in sign_thread
    self.wallet.sign_transaction(tx, password)
  File "/.../Electrum-2.5-py2.7.egg/electrum_plugins/trezor.py", line 492, in sign_transaction
    xpub_path[xpub] = account_derivation
UnboundLocalError: local variable 'account_derivation' referenced before assignment

Copy of tx:

{
    "hex": "0100000001fb6c2b07e8d6c22a8c2b341bbbd3d6acea60f7f954503359d1457f1ea259597c00000000b40001ff01ff4cad524c53ff0488b21e000000000000000000040b686cff01409fb3045d34441d3ff2dc15b28679d509ae7d015877bdc245e8031d8dc16c569ed7738ab42ff36d5f999b7ad31bd26f23f3ed9c418abeb792ad30000000004c53ff0488b21e030073245280000000f97f28194fe8d94ad8f73bd2ba531f9d06ffa0545bf6e2ab2242893e58b107890257ff32500058c3781b2ed63ab7ddc183606e361d36c0f5289d74eb2edb77ebe10000000052aeffffffff014c7a01000000000017a91492a75406e4dfdba8b56e53fb97cd1dbe704adccc8700000000", 
    "complete": false
}

**Comment by ecdsa** [comment] 2015-09-01 16:17
should be fixed now

**Comment by ELM4Ever** [comment] 2015-09-01 17:42
With Pull Request 1436 merged, it works like a charm for both Trezor and KeepKey - Thanks!

**Closed** 2015-09-01 19:42 UTC
