### ISSUE TITLE
Can not export some private keys

### ISSUE THREAD

**Issue by alexandrz** [spesmilo/electrum#5842] opened 2019-12-15 14:41 UTC
I am not able to export some keys. It works for some keys, but not for other.

Electrum 3.3.8 (installed from official `.dmg` archive)
MacOS 10.15.2

I had the same issue with older versions of Electrum.

```
➜  ~ /Applications/Electrum.app/Contents/MacOS/Electrum -w ~/.electrum/wallets/some_wallet getprivatekeys <bitcoin address>
WARNING: ALL your private keys are secret.
Exposing a single private key can compromise your entire wallet!
In particular, DO NOT use 'redeem private key' services proposed by third parties.
Traceback (most recent call last):
  File "run_electrum", line 416, in <module>
  File "run_electrum", line 164, in init_cmdline
  File "electrum/storage.py", line 84, in get
AttributeError: 'WalletStorage' object has no attribute 'db'
[8974] Failed to execute script run_electrum```

**Comment by SomberNight** [comment] 2019-12-15 18:57
Ok, I can reproduce. 
https://github.com/spesmilo/electrum/blob/e81f4bdcd11a072e7c4f38fb1c7eec19c2f7e1a8/run_electrum#L162-L164
To trigger, you need a daemon running, and the wallet to be storage-encrypted.

This should already be fixed on master, since https://github.com/spesmilo/electrum/commit/9cfeadea706dbbb46b1a4ab7b38ec11a4f527669, which reversed the order of the tests. 
(`storage.is_encrypted() or storage.get('use_encryption')`)

As a workaround, stop the daemon.

**Closed by SomberNight** 2019-12-15 18:57 UTC
Labels: CLI/RPC, bug
