### ISSUE TITLE
Electrum on Wheezy (no KDE/Gnome) refuses to load the GUI

### ISSUE THREAD

**Issue by Veek** [spesmilo/electrum#934] opened 2014-11-23 14:54 UTC
I installed Electrum from the website (the wheezy packages failed to install with python dependency errors). When i start it: electrum -v, I get the 'Create a wallet' dialog so I click 'Next' and it starts downloading chunks and at 331282 it stops and just sits.. no GUI, just the xterm console.
Ctrl-C doesn't work, so i kill it. electrum -g gtk gives errors. So i try electrum -v -g qt and it connects to "connected to ecdsa.net 50002" but 'Create Wallet' doesn't work. So I kill it again.

Then i do: electrum create
Password and stuff

electrum now works with GUI

Requesting chunk: 161
validated chunk 326591
Requesting chunk: 162
validated chunk 328607
Requesting chunk: 163
validated chunk 330623
Requesting chunk: 164
validated chunk 331282

**Comment by ecdsa** [comment] 2015-05-23 09:48
is this still the case with recent versions?
I cannot reproduce that bug

**Comment by ecdsa** [comment] 2015-08-19 10:07
closing, no answer from @Veek

**Closed by ecdsa** 2015-08-19 10:07 UTC
