### ISSUE TITLE
Error deleting encrypted imported wallet with zero keys

### ISSUE THREAD

**Issue by QinMing** [spesmilo/electrum#3254] opened 2017-11-09 09:40 UTC
![image](https://user-images.githubusercontent.com/8622078/32598279-3c1e4b36-c4ee-11e7-81b3-ae088a0d8d65.png)

When I click File > Delete, and type in the password, I got an error saying  "list index out of range".
My password was "verycomplicatedpassword". 
Or it could be because I don't have any address in the wallet?

**So question is, should I just delete the wallet file? Is that all this does?**

OS: 16.04.1-Ubuntu

**Comment by SomberNight** [comment] 2017-11-09 09:48
Could you please start Electrum with the `-v` flag, try to reproduce, and then give the associated stack trace? (which will hopefully get printed in terminal)

**Comment by SomberNight** [comment] 2017-11-09 10:01
> So question is, should I just delete the wallet file? Is that all this does?

You can just delete the wallet file, yes. But please provide debugging info so that we can fix this.

**Comment by ecdsa** [comment] 2017-11-09 10:30
ok, I can reproduce it: 
1. create an Imported wallet with some private keys
2. encrypt the wallet 
3. delete all the private keys from the wallet

the wallet rremains 'encrypted' even though there is no more privkey in the wallet file.
this causes password verification to fail.

**Comment by SomberNight** [comment] 2017-11-09 12:28
Ok, so the problem is with `check_password()`:
https://github.com/spesmilo/electrum/blob/ccc94155429241c3d344183a4efdddbbcf6736cf/lib/keystore.py#L139-L141

`check_password()` could be made to return if there are no keys in the keystore... which would probably be okay for non-encrypted wallets, but in case of encrypted wallets that would allow to change the password without knowing the current password (if the wallet is already open). Also note that `keystore` is abstracted away from whether the wallet storage is encrypted.

We could also change how `check_password()` works. Say, if we stored a hash of the password in storage, it could test against that. This kind of change would have implications for password cracking speeds, so it needs some thought; but it would also be useful for encrypting watch-only wallets (#3183).

**Comment by ecdsa** [comment] 2017-11-11 10:51
another option is to forbid deletion of the last private key in a wallet.
there is no point keeping a wallet without keys.

**Comment by jaonoctus** [comment] 2017-12-04 23:37
Now i have same issue, but with message `invalid password`. But i can login into the wallet with this password. I just copy and paste and it fails when i try delete the wallet file.

**Comment by SomberNight** [comment] 2017-12-05 00:23
@jaonoctus then it's a different issue.

What version is this with? If older than 3.0.2, then that might already be fixed by https://github.com/spesmilo/electrum/commit/83443732c410a5c5a808c0efa3f2cd7f0d465501

**Comment by jaonoctus** [comment] 2017-12-05 00:33
@SomberNight i was using the 3.0

I run `sudo pip3 install https://download.electrum.org/3.0.2/Electrum-3.0.2.tar.gz` and now it works.

Thanks :smile:

**Closed** 2020-05-22 14:26 UTC
Labels: bug, priority-low
