### ISSUE TITLE
RuntimeError('DataError: bytes overflow')

### ISSUE THREAD

**Issue by rav242** [spesmilo/electrum#8866] opened 2024-02-04 06:57 UTC
Hi!
Cant sign a transaction with 26 inputs to 1 output. Got error:
RuntimeError('DataError: bytes overflow')

Size: 1810 bytes
All inputs are from SegWit transactions. Output is Segwit Tx.

Using trezor

**Comment by SomberNight** [comment] 2024-02-04 07:09
Hi.
- is it a trezor model one (original trezor)?
- is the wallet multisig?

**Comment by rav242** [comment] 2024-02-04 07:28
trzor one
no multisig

I removed half inputs and signed a tx.
There were 2 change-inputs I removed them from the tx as well.

**Comment by SomberNight** [comment] 2024-02-04 07:42
Ok. Most likely then this is a duplicate of https://github.com/spesmilo/electrum/issues/8813.

I guess one of the inputs you are trying to spend was created by a transaction (prev_tx/parent_tx) where at least some of the inputs were using segwit multisig. (e.g. someone paid you who was using multisig)
The linked bug prevents you to spend that UTXO using a Trezor One.

This is already fixed on the master branch, you can wait for the next release with the fix, or go back to 4.4.6 for the time being.
If you go back to 4.4.6, you will have to re-create the wallet file using the wizard, as the wallet db was upgraded when you opened it with 4.5.x and downgrades are not implemented.

**Closed by SomberNight** 2024-02-04 07:42 UTC
Labels: hw-trezor

**Comment by rav242** [comment] 2024-02-04 09:05
thank you
