### ISSUE TITLE
new attack?

### ISSUE THREAD

**Issue by Dzianissmit** [spesmilo/electrum#5004] opened 2019-01-13 17:00 UTC
**few min ago i recieve this mss**
error: {'code': 'Error sending transaction', 'message': '
Upgrade required (2019-002 v3.3.2)
A new version of the Electrum protocol is available and recommended for all users.
Transactions can only be sent after applying the update.
https://github.com/spesmilan/electrum/releases
Please visit the link above to find instructions on how to upgrade to Electrum v3.3.2.'}

**Comment by AbdussamadA** [comment] 2019-01-13 17:01
that's another phishing message. ignore it.

**Comment by Dzianissmit** [comment] 2019-01-13 17:02
> that's another phishing message. ignore it.

i can't ignore, this window open when i try sent btc

**Comment by doremon1** [comment] 2019-01-13 17:05
Change server and try again. You can change server by going to "Tools->network"

**Comment by AbdussamadA** [comment] 2019-01-13 19:18
> But i dont save server

What does that mean? To change server go to tools > network or click on the orb icon in the bottom right, switch to server tab, uncheck select server automatically, right click on a server in the list there and choose use server.  Left clicking or double clicking a server in the list doesn't do it. If you're wondering what servers to use then one of the longstanding servers like the hsmith or bauerj servers will be good.

**Comment by ecdsa** [comment] 2019-01-14 10:24
@AbdussamadA I guess it means he does not know which server he used in the first place

**Comment by ecdsa** [comment] 2019-01-14 10:55
closing, as the issue is already known

**Closed by ecdsa** 2019-01-14 10:55 UTC
