### ISSUE TITLE
Microsoft Visual C++ Runtime error on windows displayed on start of Electrum 2.0 beta

### ISSUE THREAD

**Issue by DaReaper** [spesmilo/electrum#1000] opened 2015-02-02 08:43 UTC
Whenever I run Electrum 2.0 Beta, before the wallet loads I get a C++ runtime error. I've tried this both on my laptop and desktop, both running windows 7 and WIndows 8.1 respectively.

Error information Screenshot: http://i.imgur.com/DqkmIrX.png

I also have Electrum 1.9.8 installed.

**Comment by tl121** [comment] 2015-02-03 20:56
I had a similar problem on my 64 bit Windows 8.1 system.  This had previously had Electrum 1.9.8 but no other Electrum related software or required packages.  Before running the test I uninstalled Electrum 1.9,8 and deleted the user directory in Roaming\Electrum,

I did not get this error on my 64 bit  Windows 7 system and was able to install the 2.0 beta .exe and run it without error, restoring an older software wallet from seed.  However, I had already been running an earlier version of Electrum 2.0 from source including all of the necessary packages needed to run Electrum 2.0 and Trezor support, which included a 32 bit installation of Python-Qt, Cython, etc. as necessitated by the use of the free 32 bit Microsoff C++ runtine library.

**Comment by shsmith** [comment] 2015-02-06 03:52
This error occurs only when MSVCR90.DLL is found in your %PATH%.  
Developers can reproduce the error message by placing a copy of MSVCR90.DLL in the same folder as electrum-2.0-beta.exe.

**Comment by tl121** [comment] 2015-02-06 18:46
I found that whether the error appeared or not depended on the particular file that I put in the folder with electrum-2.0-beta.exe.  My system had 30 copies of mscvr90.dll.  Some gave an error and some didn't.  I found no particular way to characterize whether a file would would give the error, not in terms of modification date, file size, or even product version.  A clear case of Windows .DLL hell.

**Comment by Tritonio** [comment] 2015-03-02 17:28
I read this post: https://stackoverflow.com/questions/14552348/runtime-error-r6034-in-embedded-python-application

And found out that, IN MY CASE, it was my Python installation that caused this problem by adding it's own msvcr dll in my system path.

You can use a simple autoit3 script like this to launch Electrum without getting this error:

EnvSet("PATH", "")
Run("electrum-2.0.exe")

**Comment by ecdsa** [comment] 2015-03-23 11:06
does electrum still start after that message is displayed, or does it terminate the program?

**Comment by Tritonio** [comment] 2015-03-23 12:55
It starts properly after pressing "OK" or whatever button there is.

**Comment by tl121** [comment] 2015-03-23 16:09
While I was having the problem with the beta test versions (before I fixed the .dll situation) dismissing the error dialog box left the program running, just as with Tritonio.

The good news is that the 2.0.2 and 2.0.3 release Windows installers do not generate this error.

**Comment by ecdsa** [comment] 2015-05-22 06:16
so, it seems to be fixed now.

**Comment by jdreesen** [comment] 2015-06-10 20:31
Just installed v2.2 and hat this exact error :(

electrum starts after clicking `ok` but can I be sure my bitcoin are safe?

**Comment by leafcutterant** [comment] 2015-06-13 19:06
The portable version of 2.3.1 has this too. I'm on Windows 7 x64.

**Comment by kmpm** [comment] 2015-07-07 09:36
2.3.2 portable and standalone has this issue. Windows 7 x64

**Comment by triorr** [comment] 2015-09-02 22:20
Just rename the app to "electrum.exe" and it will be fixed .

**Comment by leafcutterant** [comment] 2015-09-03 07:52
Wow, @triorr 's advice works. Thank you!

**Comment by ecdsa** [comment] 2015-09-03 08:53
any idea why it works?

**Comment by leafcutterant** [comment] 2015-09-03 18:27
@ecdsa - I have no idea. I'm no programmer (so this may make no sense) but I guess that something in the .exe's code still references itself as "electrum.exe".

**Comment by triorr** [comment] 2015-09-04 04:42
Could be something related to py2exe , I don't know.

**Comment by Marokovan** [comment] 2015-09-04 04:58
Thank you Triorr, renaming to the file to "electrum.exe" WORKS.

**Comment by ecdsa** [comment] 2016-10-10 07:57
I have a Windows10 computer, and I cannot reproduce this issue with the 2.7 builds.
Can someone test with the latest builds?

**Comment by protonn** [comment] 2016-10-12 18:44
I get the error message with Electrum portable, but it will startup after I click ok. If I rename to electrum.exe the error message does not appear.

I can run Electrum-LTC 2.6.4.2 portable on the same machine with no error message, without changing the filename (electrum-ltc-2.6.4.2.exe). 

Running Windows 10.

**Comment by ecdsa** [comment] 2016-10-13 05:02
@pooler can you explain how the building method differs with LTC ?

**Comment by pooler** [comment] 2016-10-13 10:19
As far as I can tell the building method is the same. What appears to be different is the version of the dependencies, and probably the building environment itself. For what it's worth, Electrum-LTC 2.6.4.2 was built using Python 2.7.11 running under Wine 1.6.2. The various packages such as PyQt4 are probably a different version than what specified in `prepare-wine.sh` as well, since I remember I installed them manually.

**Comment by ecdsa** [comment] 2016-10-13 11:34
ok, thanks for sharing the info

**Comment by patrikr** [comment] 2016-12-23 20:22
Same startup error message with Electrum 2.7.12 in Windows 8.1 64-bit. (With both standalone and portable.)

Renaming the binary to electrum.exe fixed it.

**Comment by 0rkaM** [comment] 2017-01-10 08:39
Same problem on electrum-2.7.16-portable.exe... renaming without the "-2.7.16-portable" fixes the problem.
Kind of bad that a bitcoin wallet is not properly tested.
(I do have Python 3.3.5 standard installation)

**Comment by Moongazer** [comment] 2017-03-03 16:03
Problem still exists. I used the "Standalone Executable" `electrum-2.7.18.exe` and this error shows up. After clicking "OK", it seems to work fine. And its true, renaming the file to `electrum.exe` fixes the problem (thanks @0rkaM)

System: Windows 8.1 64bit, no Python installed

**Comment by ecdsa** [comment] 2017-03-09 18:23
this should be fixed in 2.8.0 builds. please confirm.

**Closed by ecdsa** 2017-03-09 18:23 UTC
Labels: Windows

**Comment by Moongazer** [comment] 2017-03-10 10:32
Can confirm, issue is solved in 2.8.0, thanks
