### ISSUE TITLE
Address input widget icons position

### ISSUE THREAD

**Issue by snoopcatt** [spesmilo/electrum#6610] opened 2020-09-21 20:50 UTC
**Version**
Electrum 4.0.3 

**Summary**
In **Send** tab, icons of «Read QR code» and «Read file» actions are shifted to the top. 
Sometimes icons even does not fit in the address bar.

**Steps to reproduce**
1. Open **Send** tab
2. Look at the input bar

GNU/Linux:
![Screenshot_2020-09-21_23-49-51](https://user-images.githubusercontent.com/2917322/93819988-26bc6a00-fc65-11ea-8d88-dedae658d78a.png)

Windows:
![Screenshot_2020-09-21_23-48-08](https://user-images.githubusercontent.com/2917322/93820053-42277500-fc65-11ea-8a88-6685bda1dc33.png)

**Expected behaviour**
Icons should be centered and fit into input bar (or appear after the input bar)

**Comment by SomberNight** [comment] 2020-10-14 15:44
duplicate of https://github.com/spesmilo/electrum/issues/5047

**Closed by SomberNight** 2020-10-14 15:44 UTC
