### ISSUE TITLE
16: mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation). Code:-26

### ISSUE THREAD

**Issue by princehuios** [spesmilo/electrum#6117] opened 2020-04-26 16:43 UTC
16: mandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation). Code:-26
i created a wallet and wanted to do a transaction.
but when it was time to broadcast the transaction i got the above

**Comment by SomberNight** [comment] 2020-04-27 01:08
dupe of https://github.com/spesmilo/electrum/issues/6118
and https://github.com/spesmilo/electrum/issues/6116

**Closed by SomberNight** 2020-04-27 01:08 UTC
