### ISSUE TITLE
when electrum is run for the first time without headers, display in the GUI that download activity is undergo

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum#3966] opened 2018-02-24 17:35 UTC
When starting Electrum for the first time, without any blockchain headers, it needs to download them. This is not a huge amount of data but on slow connections or behind custom setups (like slow proxies, Tor network, etc.) it can take quite a few minutes. During this time, there is nothing shown in the GUI to indicate it. 

For example, I just started on Tails an Electrum 3.0.6 instance from scratch, with a brand new wallet. It immediately shown 0 mBTC in bottom left side, like this was the balance in fully synced mode. In bottom right side there is a blue icon at network settings (ok, since i am using localhost:9050 socks5 proxy) and only if I click on that to further open the network dialog i can see the blockchain: x blocks increasing gradually as more headers are downloaded.  The background activity (headers download) works good.

Users who don't know how this works might have a bad experience. I think it would be useful to display something that will let the user know that something is happening and that electrum needs more time to catch-up with blockchain headers.

Related is #2650, might check if we find useful implementing something from there as well.

**Comment by SomberNight** [comment] 2018-02-24 17:54
Note that the slow startup referred to in this issue will be a lot less serious in 3.1 due to checkpointing
https://github.com/spesmilo/electrum/blob/f1b757821838ec4496e9e978cca70cee222f98e9/RELEASE-NOTES#L24-L27

**Comment by gits7r** [comment] 2018-02-24 18:30
@SomberNight still i think it would be useful to fix this from now, because even with checkpoints it is useful in case users restore older seeds that go back before multiple checkpoints.

Also, I can see in 3.1 the coin selection privacy and priority was merged into a single one. I am happy with this change as well, just I make sure electrum 3.1 remains compatible with config files created with previous versions. There was some mess for users with persistence enabled when in 2.7.x the config file format changed. Basically if electrum 3.1 reads in config file coin selection: privacy or priority it should just go on with the default merged method and remove this line from the config file, without reporting any errors. Can you confirm this is the case?

**Comment by SomberNight** [comment] 2018-02-24 19:27
> it should just go on with the default merged method and remove this line from the config file, without reporting any errors. Can you confirm this is the case?

The preference in the config for a coin chooser policy is kept. If it refers to a policy that does not exist in the current code, it is simply ignored, and the default is used.

-----

Back to the issue, I agree that the GUI could indicate that header download is ongoing.
Even with checkpoints, even if not a progress indicator, just simply the status saying "initial headers download" or similar.

(actually this seems to be a duplicate of https://github.com/spesmilo/electrum/issues/3473)

**Comment by ecdsa** [comment] 2018-02-26 11:03
I disagree, I think checkpoints make this feature unnecessary. In addition, since chunks can be downloaded in random order, it is actually misleading to consider only local height to determine if we are downloading headers. The current GUI shows unverified transactions as unverified, I think that is sufficient.

**Closed by ecdsa** 2018-02-26 11:03 UTC
Labels: enhancement, user-interface

**Comment by SomberNight** [comment] 2018-02-26 16:07
> GUI shows unverified transactions as unverified

Well yes. However, the GUI status is shown as synchronised. There is no way to distinguish if a tx is unverified because the verification failed or if the verifier just hasn't gotten to it yet.

> since chunks can be downloaded in random order, it is actually misleading to consider only local height

Yes, indeed. :/

**Comment by SomberNight** [comment] 2018-02-27 01:29
@ecdsa 
I agree that my previous idea was less than perfect.
However I believe this feature, specifically letting the user know that sync is on-going after the synchronizer has found all used addresses within gap limit, would still be useful.
I also agree that with checkpoints this feature is no longer that important.

I think if we can find a solution that is easy to implement, we should consider implementing it.

What is your opinion of doing something along these lines:

```patch
diff --git a/gui/qt/main_window.py b/gui/qt/main_window.py
index ddaafc4b..a84d0224 100644
--- a/gui/qt/main_window.py
+++ b/gui/qt/main_window.py
@@ -701,6 +701,10 @@ class ElectrumWindow(QMainWindow, MessageBoxMixin, PrintError):
             if not self.wallet.up_to_date or server_height == 0:
                 text = _("Synchronizing...")
                 icon = QIcon(":icons/status_waiting.png")
+            elif len(self.network.requested_chunks) > 0:
+                chunks = sorted(self.network.requested_chunks)[:2]
+                text = _("Downloading headers... {}").format(chunks)
+                icon = QIcon(":icons/status_waiting.png")
             elif server_lag > 1:
                 text = _("Server is lagging ({} blocks)").format(server_lag)
                 icon = QIcon(":icons/status_lagging.png")
```

- this is easy/clean
- it shows the user that something is going on. the aim of the indicator is just to show "change" (some sort of progress)
- however it does not show how much to download is left. the numbers shown are not necessarily increasing

**Comment by gits7r** [comment] 2018-02-27 09:41
I endorse this, because it's good for user experience at no cost for us. We must think from the perspective that we advertise electrum as instant on / lightning fast to sync. An user turning it on for the first time on a slow connection (maybe behind Tor, from a censored country with a slow bridge) might not have the patience to wait without having a clue of what is going on.

We who are familiar with the terminology and software,  have no problem in seeing unverified while it appears to be fully synced because we know what needs to happen, others may not. 

Even if it does not show how much download is left, it still shows that something is going on and patience is required, which is the purpose anyway.
