### ISSUE TITLE
Once electrum goes offline due to lost Internet - it stays offline

### ISSUE THREAD

**Issue by 2pac1** [spesmilo/electrum#7079] opened 2021-03-01 19:03 UTC
Hey guys,
 
 If one loses Internet connectivity, Electrum goes to offline mode and once the Internet connectivity is restored, Electrum will stay offline (red globe) and it will not reconnect and you cannot reconnect intuitively.

Now the fix is: 
-to close it and start it again. 
or
-Go to - Network - Servers and click to connect to a server again

**Comment by SomberNight** [comment] 2021-03-01 21:05
This is a regression from https://github.com/spesmilo/electrum/commit/e83f0dd3fc4e19c8845fc21f344400f1b0a7eebf
It is already fixed on master by https://github.com/spesmilo/electrum/commit/60792dc8081467db0384fe9842f6729cd77cf48f
However there hasn't been a release yet since the fix.

**Closed by SomberNight** 2021-03-01 21:05 UTC
Labels: bug 🐞, topic-network 🕸

**Comment by 2pac1** [comment] 2021-03-01 21:07
Cool. Tnx.
Sorry for double posting.
Keep it up.
