### ISSUE TITLE
Cannot create a new wallet with a Ledger Nano S

### ISSUE THREAD

**Issue by TravelingTechGuy** [spesmilo/electrum#3508] opened 2017-12-12 21:35 UTC
Version: 3.0.2
OS: Windows 10
Ledger Nano S

Trying to create a new wallet:

1. Standard Wallet
2. Use Hardware Device
3. An unnamed ledger [ledger, initialized]
4. **Read Error**

Ledger is in the Bitcoin app, with "Browser Support" turned to "No".

Any other details or logs I can provide?

**Comment by SomberNight** [comment] 2017-12-12 22:42
Have you tried
- unplugging/reconnecting the Ledger
- restarting Electrum
- upgrading the Bitcoin app or fw on the Ledger
- with Electrum 3.0.3
- using different usb port/cable

It works for me here with a similar config, so not sure...

**Comment by TravelingTechGuy** [comment] 2017-12-12 22:53
Just downloaded 3.0.3, and tried again:

- unplugged/plugged Ledger
- tried a different port
- Bitcoin app on Ledger is the latest, as is the FW

Here's what seems to work eventually, but I'm not sure if it's as planned:

1. Try as above, get 'Read Error'
2. Switch Browser Support to 'yes' on Ledger
3. Try again, get first error about channel
4. Close the error box, switch Browser Support to 'No'
5. Try again, get to the next screen ('Derivation')

Tried the sequence several times. It seems that it doesn't read the Browser Support bit (or whatever data structure it's in) until you actively change to 'Yes', try-fail, change to 'No' and try again.

Hopefully that gives enough information on what to fix in the code.

**Comment by lukem512** [comment] 2017-12-18 17:35
I'm having the same issue with my Nano S. Exactly the same as @TravelingTechGuy describes

**Comment by galaxydoctor** [comment] 2017-12-21 20:49
Same issue also

**Comment by willyloman** [comment] 2017-12-22 01:40
I ran into this same issue initially but was able to set-up a multisignature hardware wallet using @TravelingTechGuy's workaround.

**Comment by lukem512** [comment] 2017-12-22 10:18
It does indeed seem to be an issue with the Browser Support bit.

**Comment by SomberNight** [comment] 2017-12-25 17:49
Ok, I can reproduce this, but for me, closing and reopening Electrum fixes it; so no need for the [convoluted workaround](https://github.com/spesmilo/electrum/issues/3508#issuecomment-351222172).
The problem seems to happen if you move in/out of apps on the Ledger.

**Comment by twinhype** [comment] 2017-12-29 08:35
I had the same issue as @TravelingTechGuy and had to use his workaround.

**Comment by Onefox** [comment] 2018-01-09 23:16
have the same problem with 3.0.5 I couldn't get @TravelingTechGuy  workaround to work..

**Comment by daniel-cohen** [comment] 2018-01-20 08:13
Had the same problem with 3.0.2
Bitcoin app 1.1.18
and Firmware 1.3.1

@TravelingTechGuy 's  workaround worked. Thanks dude!

**Comment by ecdsa** [comment] 2018-01-20 08:38
@daniel-cohen please do not post comments about old versions of electrum

**Comment by aribo** [comment] 2018-01-28 22:49
Same problem here Mac with 3.0.3

**Comment by SomberNight** [comment] 2018-02-04 21:04
Please test https://github.com/spesmilo/electrum/pull/3842

**Closed** 2018-02-05 08:05 UTC
Labels: btchip, bug
