### ISSUE TITLE
could not sign tx on android

### ISSUE THREAD

**Issue by tim-le** [spesmilo/electrum#2033] opened 2016-11-10 16:06 UTC
I use two android devices, one is online , second one is offline, 
the offline phone exports the master public key to the online phone,
now let the online phone make an unsigned tx and show the qrcode, 
then I try to sign this tx use the offline phone, but then I see no "sign" buttons on the offline phone.

**Comment by tim-le** [comment] 2016-11-11 13:06
sorry, I was not importing the master public key,  instead a watching-only btc address which is from the online phone wallet was imported.

**Comment by JazzTp** [comment] 2016-11-13 18:35
tim-le, I would also be interested in using my old smartphone offline as cold storage, while having the more recent one online (I'll need to flash the old one to some Cyanogenmod, although it's working perfectly fine, because the latest Electrum Android version is not compatible with Android 2.2).

Do you please have the link to any tutorial handy on how the two phones would co-operate? Are the two Electrum Android instances able to perform all communications through QRcodes and camera? Were you able to export your master public key and sign ongoing transactions etc. all through screen-to-camera communications?

Thank you.

**Comment by tim-le** [comment] 2016-11-13 22:05
Sihi JazzTp,
  yes,  by qrcode, all through screen-to-camera communications.
1, once you made a unsigned tx and tap the qrcode button
2, use your offline phone,  goto Send tab, scan the qrcode
3, you should be able to see the button "Sign" , tap it, then tap the qrcode button.
4, close the qrcode on online phone , goto Send, camera,  scan the offline phone
5, finally,  tap the button "broadcast".

**Comment by JazzTp** [comment] 2016-11-14 02:28
Hi tim-le,

**Thank you very much**, that's great news, I am now _highly_ motivated into flashing my old smartphone to a newer Android version.

What if I wanted to _also_ be able to sign outgoing transactions from a second cold storage which I'd only keep on an offline Electrum-on-desktop-Linux instance with no working webcam? Would that be possible too?

**Comment by tim-le** [comment] 2016-11-14 04:42
yes,  instead of using qrcode, a unsigned tx can be saved to a file,  then you copy it to your offline device,  maybe a usbdisk is needed,  then copy the signed tx file back to the online device and broadcast it.

**Comment by JazzTp** [comment] 2016-11-15 02:18
Thanks again tim-le, but that's the step I can't figure out when it comes to Electrum-on-Android online communicating with Electrum-on-Linux-desktop cold storage. On Android Electrum, *how* do you save to a file an unsigned tx? If you press the floppy disk icon it saves an "invoice"... I used a file manager to search for the file with no success.

**Comment by JazzTp** [comment] 2016-11-15 19:33
Hi tim-le, I see you have a good knowledge of the Electrum console usage, congrutulations. I've generally been able to find my way also in not very intuitive User Interfaces, so now I'm glad to see that I haven't turned so dumb as not to see something that might have been just there in good evidence on the Android version of Electrum.

I think _for now_ the easy choice is to use Electrum-on-Android on both the online and offline cold storage instances, _OR_ Electrum-on-desktop on both sides, and not assume, _for now_, that the two versions of Electrum can easily talk to each another.

**Thank you again.**

**Comment by ecdsa** [comment] 2016-11-18 08:47
This is not related to android. It is caused by the way you use cold storage.

If your watching only wallet does not have the master public key, then it cannot know the address derivation.
In that case, the cold storage will not be able to sign, (unless the address is in the cold wallet)

The following combinations should work: 
1. Watching-only wallet: xpub. Cold storage: seed or xprv
2. Watching-only wallet: imported address. Cold storage: imported privkey

However, this does not work:
3. watching-only wallet: imported address, cold storage: seed

**Comment by tim-le** [comment] 2016-11-18 08:53
got it, and will consider giving a option "use change addresses"?

**Comment by ecdsa** [comment] 2016-11-18 09:08
yes we can add that option

**Comment by ecdsa** [comment] 2017-03-06 05:41
this should be fixed by 
5ee4cf41a83cb429f7f95094932076705a847cfd

**Comment by seanc-1** [comment] 2017-03-06 05:42
image1.GIFimage1.GIF

**Closed by ecdsa** 2017-03-06 05:41 UTC

**Comment by seanc-1** [comment] 2017-03-06 05:42
image1.GIFimage2.JPGimage1.GIFimage2.JPG
