### ISSUE TITLE
add DroidSansFallback font on Android

### ISSUE THREAD

**Issue by shuaiLiWang** [spesmilo/electrum#5703] opened 2019-10-15 09:59 UTC
1.download DroidSansFallback.ttf to electrum/gui/kivy/data/fonts/
2.add code in  kivy/main_windows.py(__init__ function) 
        (kivy.resources.resource_add_path('electrum/gui/kivy/data/fonts/')
        self.font_cn = kivy.resources.resource_find('DroidSansFallback.ttf'))
3.add code in *.kv
    Label:
            text: _('设置')
            font_name: root.font_cn
            bold: True
            font_size: 30
            pos_hint: {'x':.02, 'y':.8}
            size_hint: .8, .1
            text_size: self.width - dp(100), self.height
            color:  [0.098, 0.098, 0.439, 1]

result: also show Garbled
![111](https://user-images.githubusercontent.com/9347690/66821644-57842180-ef75-11e9-9122-82440a95e4d8.png)

**Comment by SomberNight** [comment] 2019-10-15 14:08
Could you clarify what the issue is about?
Is it that you have selected `zh_CH` as language in the Android app, and characters don't show properly?
And the rest of your comment is just how you tried to fix it without success?

**Comment by shuaiLiWang** [comment] 2019-10-16 01:54
> Could you clarify what the issue is about?
> Is it that you have selected `zh_CH` as language in the Android app, and characters don't show properly?
> And the rest of your comment is just how you tried to fix it without success?

yes，you are right

**Comment by shuaiLiWang** [comment] 2019-10-16 02:29
now it ok， thank you！！ because DroidSansFallback.ttf is bad file

**Comment by shuaiLiWang** [comment] 2019-10-16 02:43
multi-language not support now, right ?
it only support default(en_UK)

**Comment by shuaiLiWang** [comment] 2019-10-16 07:23
> Could you clarify what the issue is about?
> Is it that you have selected `zh_CH` as language in the Android app, and characters don't show properly?
> And the rest of your comment is just how you tried to fix it without success?

yes, " Is it that you have selected `zh_CH` as language in the Android app, and characters don't show properly?" this is my issue!

**Comment by ecdsa** [comment] 2019-10-16 11:42
@shuaiLiWang could you write a pull request please?

**Comment by andronoob** [comment] 2019-11-08 11:07
@shuaiLiWang Would you like to have a look at #2575 and #2032?

**Comment by shuaiLiWang** [comment] 2019-11-15 03:34
＠ecdsa @andronoob  
First, I am very sorry, I am busy with other projects recently.
my app can work normally on android by add DroidSansFallback.ttf

**Comment by shuaiLiWang** [comment] 2019-11-15 03:54
I did these to solve this problem:
1.add the code "Label.register('Roboto','electrum/gui/kivy/data/fonts/DroidSansFallback.ttf',)" in main_window.py
2.download DroidSansFallback.ttf to electrum/gui/kivy/data/fonts
I found that many languages are normal, but there are also a few that are not normal.
I am not testing enough

**Comment by SomberNight** [comment] 2022-03-22 03:27
AFAICT `DroidSansFallback.ttf`/`DroidSansFallbackFull.ttf` do not contain latin glyphs (so e.g. cannot be used to display English) ([downloaded from AOSP](https://android.googlesource.com/platform/frameworks/base.git/+/refs/heads/android12-release/data/fonts/)).
Or at least, when I tried the approach you outlined, e.g. Japanese characters seem to be displayed correctly, but English text and numbers (Arabic numerals) do not work.

Anyway, I will close this in favour of https://github.com/spesmilo/electrum/issues/2032.

**Closed by SomberNight** 2022-03-22 03:27 UTC
Labels: OS-android🤖, localization 🌍
