### ISSUE TITLE
Can't start electrum anymore (on ubuntu)

### ISSUE THREAD

**Issue by jangos** [spesmilo/electrum#1501] opened 2015-10-19 14:18 UTC
I use electrum installed on Ubuntu for years now without any hassle.
From one day to another, my wallet simply does not start anymore.
I did apt-get upgrade & update & restart before submitting that issue.
do you need more info, I am happy to provide. I really dunno what to do...

**Comment by mightyiam** [comment] 2015-10-19 17:07
What version are you using, @jangos ?

**Comment by jangos** [comment] 2015-10-19 17:31
ubuntu 14.04 LTS, 64 bit @mightyiam

**Comment by ecdsa** [comment] 2015-10-19 17:48
download Electrum from electrum.org, or report this bug to ubuntu

**Comment by jangos** [comment] 2015-10-19 18:36
I downloaded Electrum from electrum.org - why is it an ubuntu bug and why I don't get help here?

**Comment by jangos** [comment] 2015-10-19 18:45
Okay, I did installation again. Now comes:

> Error: Cannot read config file.

**Comment by mightyiam** [comment] 2015-10-19 19:09
@jangos please, what file did you download exactly, and how did you install it?

**Comment by jangos** [comment] 2015-10-19 19:11
> Install dependencies:
sudo apt-get install python-qt4 python-pip
Install Electrum:
sudo pip install https://download.electrum.org/Electrum-2.5.1.tar.gz

**Comment by ecdsa** [comment] 2015-10-19 21:43
sorry I thought you installed Electrum using apt.
is there a traceback?

**Comment by jangos** [comment] 2015-10-20 06:39
Sorry, what is a traceback.

**Comment by ecdsa** [comment] 2015-10-20 06:47
https://www.google.de/search?client=ubuntu&channel=fs&q=what+is+a+traceback.&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=X-MlVqW6GauK8Qf5lbuYAg

**Comment by jangos** [comment] 2015-10-20 06:59
Sorry, but doesn't really help. What can I do? I am a Ubuntu beginner - how to use or provide a traceback? My alternative would be installing Multibit to import the back up keys, right?

**Comment by ecdsa** [comment] 2015-10-20 07:04
sorry but I cannot work with vague statements such as "my wallet does not start anymore".
please copy paste what you see when you start electrum from the terminal. (besides "Error: Cannot read config file.")

**Comment by jangos** [comment] 2015-10-20 11:07
sorry, a screenshot makes sense for sure:

![selection_0459](https://cloud.githubusercontent.com/assets/5238142/10605397/4f0f1134-772b-11e5-8983-b0c51602b219.png)

**Comment by ecdsa** [comment] 2015-10-20 11:19
well, it cannot read your wallet file, not just the config file.
you probably need to rstore your wallet from seed.
first check the content of that file, to see if it is corrupted or empty. please report here.
then move that file to another location, and restore from seed.

**Comment by jangos** [comment] 2015-10-20 12:12
much thx for the hints! the file is empty, I will restore from seed and report.

**Comment by ecdsa** [comment] 2015-10-20 17:39
ok, closing this issue; it's not a bug in the current version.
please still report about the restore operation.

**Closed** 2015-10-20 17:39 UTC

**Comment by jangos** [comment] 2015-10-21 09:56
okay. how the wallet file can vanish?

**Comment by jangos** [comment] 2015-10-21 11:00
I guess all label descriptions for each transaction are gone now and there isn't any way to restore them, right?

**Comment by ecdsa** [comment] 2015-10-21 13:41
did the restore succeed? if yes, what do you mean by "I can't install electrum anymore" ?

**Comment by ecdsa** [comment] 2015-10-21 13:45
Note: the decryption key is not required anymore in recent versions. so I guess you are still running an old version. Please update to 2.5.1

**Comment by jangos** [comment] 2015-10-21 14:21
Is there a manual for the seed restore? I can't open or upgrade electrum due that screen error mentioned above. can't I open e.g. another (dummy) wallet? 

( Thanks for the hint with the decryption key, that is pretty useful)

**Comment by ecdsa** [comment] 2015-10-21 14:48
I do not understand your situation.
Did you restore the wallet or no?
if no, remove the empty wallet file, and restart Electrum

**Comment by jangos** [comment] 2015-10-21 15:21
No, I didn't restored by using the seed yet. I could do it on another device and report here.
I recognized that I can't find either the directory nor the wallet file.

**Comment by ecdsa** [comment] 2015-10-21 15:24
the path is shown in the popup window (screenshot)
the .electrum directory is a hidden directory (it starts with a . )

**Comment by jangos** [comment] 2015-10-21 18:05
Restored successfully using the private keys. Thank you for your help and patience!
Last question: Is there a way to get back the edited description (notes) of all transfers?

**Comment by ecdsa** [comment] 2015-10-21 18:07
Good to hear that. 
Do not forget to update Electrum to the latest version (2.5.1.)
You can get the descriptions back only if you used the Label Sync plugin.

**Comment by jangos** [comment] 2015-10-21 18:23
How to update?

I used the plugin before (with the old version), will try and report here.

**Comment by ecdsa** [comment] 2015-10-21 18:25
just install the new version, it will replace the older one

**Comment by jangos** [comment] 2015-10-21 18:26
Done: Version 2.5.1

**Comment by jangos** [comment] 2015-10-21 18:27
When I activate LabelSync on Plugins and press settings and "force download" there comes an error pop up message: 

> <electrum.wallet.Imported_Wallet object at 0x7ff2e155d210>

**Comment by ecdsa** [comment] 2015-10-21 18:59
maybe @maran knows about that

**Comment by jangos** [comment] 2015-10-23 13:39
@ecdsa can you please give me his email address, I would like to clarify that issue. to summarize my case: it would be awesome to be able to restore all wallet transaction descriptions.

**Comment by jangos** [comment] 2015-11-02 13:41
@ecdsa @maran Hi dudes, I still have my original wallet file. it would be very helpful if I could restore my transaction labels (pretty important due tax and accounting reasons). as I updated electrum now I can't access the authorization key for the label synchronization plugin anymore. can you may instruct how to proceed?

**Comment by ecdsa** [comment] 2015-11-02 14:38
@jangos open your original wallet files, and in the menu, choose "Wallet -> Labels -> Export"
this will save them to a file. You can then import them

**Comment by jangos** [comment] 2015-11-02 15:56
Open already does not work :(

> Cannot read wallet file '/home/johnny/Desktop/biz/default_wallet_x'

**Comment by ecdsa** [comment] 2015-11-02 16:02
is it that file empty, as above, or is it a different file?

**Comment by jangos** [comment] 2015-11-03 12:49
which application to use for opening instead / how to check whether it is empty? the file has 758,0 kB

**Comment by ecdsa** [comment] 2015-11-03 13:52
well, if it's 758kb, then it's not empty :)
maybe the file was somehow corrupted.
you can email it to me if you want me to have a look.
