### ISSUE TITLE
🛠 Error handling for Windows binaries

### ISSUE THREAD

**Issue by bauerj** [spesmilo/electrum#2258] opened 2017-03-08 20:59 UTC
As far as I know there is no way to get tracebacks when running the Windows binaries (or is there :open_mouth: ).

I think it would make sense to enable the user to see them as that would make it easier to investigate bugs.

There are a basically three possible solutions for that:

 - Use the Console tab to print tracebacks
 - Save tracebacks to a log file in the electrum directory
 - Do both.

What do you think? It's trivial to code but maybe there already is a (better) way.

**Comment by ecdsa** [comment] 2017-03-08 21:36
duplicate of #2009

**Closed** 2017-03-08 21:56 UTC
