### ISSUE TITLE
When i send coin from one electrum wallet to a new wallet i created, the coin goes to someone else according to blockchain

### ISSUE THREAD

**Issue by notinsync** [spesmilo/electrum#1941] opened 2016-09-30 15:56 UTC
When my coin from helix lite never showed up in a new electrum wallet I'd just created, I ran test moving a small amount from an old wallet to the new one. It never showed up either, so I check the blockchain and found that the coin went to a wallet with a large balance, much larger than I've ever had. That wallet has multiple transactions starting Aug 20. Electrum page said to report bugs here. Not sure if this is a bug or not. I no longer have enough coin to post as a new member on bitcointalk. Is it possible someone hijacked this wallet? It's never been used for any purchases. It was created new. Now my coin is in someone else's wallet! This is the wallet the coin went to: 1AT3GWokyVtekLZfF5G5bnNUXcYvWHwiPE
What happened???????

**Comment by ecdsa** [comment] 2016-09-30 16:47
what is helix lite?

**Comment by notinsync** [comment] 2016-09-30 20:22
Helix is a popular coin mixing service. I've used it a few times. http://helixlight.org/

**Comment by ecdsa** [comment] 2016-10-01 05:09
what is your OS and version?
did you copy-paste the recipient address in Electrum?

**Comment by notinsync** [comment] 2016-10-01 14:51
win 7 64 bit
Yes, copy and pasted my wallet address

**Comment by ecdsa** [comment] 2016-10-01 18:52
maybe you have a virus that replaces bitcoin addresses in the clipboard with that one.
try to copy-paste more bitcoin addresses, and see if they are modified.

**Comment by usezfsyo** [comment] 2016-10-01 19:01
Do you have the pgp-signed 'Helix Verify String'? Does it show the proper payment address?

**Comment by notinsync** [comment] 2016-10-02 14:41
ecdsa - I did two small test transactions. I created a new wallet and the coin transferred fine. I was also able to send coin to the wallet in question here. It hasn't completed but I see it in blockchain with the correct receive address. If it completes, this will be my first success with this wallet.
usezfsyo - since helix light doesn't require log in I don't think I can go back and find out anything about the transaction. I read this article b/c I don't know anything about the "helix verify string" https://www.reddit.com/r/grams/comments/4sesu5/grams_new_features/ 
but i still don't understand how to access it for my transaction. please advise.
Thank you both for your help.

**Comment by notinsync** [comment] 2016-10-02 14:53
After reading the article it is possible a scam helix page was used to send the coin to me. My friend was paying me back in BC and we ran it from his coinbase acct thru helix. But that still doesn't explain why the coin I sent from one of my own wallets went somewhere else. 
usezfsyo if he checks his coinbase account, can i use info on the transaction to find the helix verify string?

**Comment by ecdsa** [comment] 2016-10-05 09:51
closing this; I don't think it's a bug, and you cannot reproduce it.
either you've been victim of a scam, or you were confused.

**Closed by ecdsa** 2016-10-05 09:51 UTC
