### ISSUE TITLE
Electrum -3.3.2 - Windows 8.1 - Bluetooth API issue and cannot open wallet

### ISSUE THREAD

**Issue by SuBPaR42** [spesmilo/electrum#4960] opened 2018-12-22 17:30 UTC
Tried to open a Ledger Wallet that worked fine under 3.2.3 and now receive the following error.

https://i.imgur.com/2rjBZF7.png

> This Windows version (6.3.9600) does not support the required Bluetooth API. Consider updating to a more recent Windows (10.0.10586 or above).

**Comment by ecdsa** [comment] 2018-12-23 08:54
this is probably a change in the Ledger library. @btchip ?

**Comment by SuBPaR42** [comment] 2018-12-23 22:19
Thanks Thomas - will wait for more info...

**Comment by SomberNight** [comment] 2018-12-24 23:39
When exactly do you get the error? I've tried in a Windows 7 VM with both a hw.1 and a Nano S; could not reproduce so far.

**Comment by SuBPaR42** [comment] 2018-12-25 23:01
File -- Open -- Select File -- Next

Then get the error display message.  Only happens with a ledger wallet file (either Nano S or HW.1 wallet).

**Comment by SomberNight** [comment] 2018-12-26 01:53
Trezor does not work either.

**Comment by SomberNight** [comment] 2018-12-26 02:56
Ahh, it's most likely because python-trezor (and clones) do the same :(
https://github.com/trezor/python-trezor/blob/a9f39b94a53a51ebc4fd3c7490e07feaddfc6f5e/trezorlib/qt/pinmatrix.py#L34

**Comment by SomberNight** [comment] 2018-12-26 04:08
I've built a binary without trezor/keepkey/safet, and now ledger at least works.

https://github.com/spesmilo/electrum/issues/4815 also looks related.
Pyinstaller is pulling in all of Qt because of these import statements.

**Comment by SomberNight** [comment] 2018-12-26 04:14
Opened PR for Trezor. https://github.com/trezor/python-trezor/pull/349
Going to ask KeepKey/SafeT to pull upstream commit after it's merged.

I don't see how to work around this "bluetooth" issue in python land..... Qt is crashing the whole process which is horrible.

**Comment by SuBPaR42** [comment] 2018-12-26 14:43
I owe you a beer (or 6).  Thanks for your diligence in tracking this down!

**Closed** 2019-01-31 19:58 UTC
Labels: OS-windows, Qt, bug
