### ISSUE TITLE
Bitdefender detected a virus in the uninstaller

### ISSUE THREAD

**Issue by MrGoatsy** [spesmilo/electrum#3399] opened 2017-11-28 00:15 UTC
I downloaded Electrum from the official website:
https://electrum.org/#home

I download it 20-11-2017 and 23-11-217.

This is what it showed:
https://i.imgur.com/tzsRVEZ.png

**Comment by SomberNight** [comment] 2017-11-28 00:18
duplicate of https://github.com/spesmilo/electrum/issues/3386

Please check other issues before opening a new one.

**Closed** 2017-11-28 05:15 UTC
