### ISSUE TITLE
Incorrectly shown balance for P2PK "addresses"

### ISSUE THREAD

**Issue by goblin** [spesmilo/electrum#1836] opened 2016-06-17 19:17 UTC
Some watching-only addresses show incorrect balance. Example address: 
16U7ppNSpuNNjZCUnF4s17UU7mKBL6Zjib

In Electrum 2.6.4 on Linux, I do:
1. File | New/Restore
2. (enter a name)
3. choose "Restore a wallet or import keys", "Standard wallet", [Next]
4. enter 16U7ppNSpuNNjZCUnF4s17UU7mKBL6Zjib (many other addresses are affected too), [Next]

You can see there are two transactions: a generation +50 from 2012-09-22, and then a "+0" transaction from 2013-01-03, which in fact was spending all coins from that input. Blockchain [dot] info correctly shows the available balance as 0, whereas Electrum shows 50 BTC available.

**Comment by gits7r** [comment] 2016-06-18 08:49
The transaction in 2013-01-03 as shown on bc.i shows spending a coinjoin from 3 different addresses 50 btc from each. Anyway,we should look into this and see why/how this affects electrum.

Can you please provide a screenshot after you add the address as watch only while fully synchronized?

**Comment by ecdsa** [comment] 2016-06-18 10:09
closing; I believe the wallet was not fully synchronized

**Comment by ecdsa** [comment] 2016-06-18 10:13
ack, I can reproduce that

**Comment by goblin** [comment] 2016-06-19 21:39
You're right, in this small example it fixes itself when the wallet is reopened.

However I have a different test case where I loaded ~1000 watch-only public addresses, and it still shows incorrect balance on them even when the wallet is reopened. I tried to make it into a smaller test case with 2 or 3 addresses but I haven't succeeded yet (the ones I've tried seem to fix themselves after reopening). I'll try some more later.

**Comment by goblin** [comment] 2016-06-19 21:41
Here's the screenshot as requested by @gits7r :

![ss](https://cloud.githubusercontent.com/assets/2834/16180006/4cf0ab18-3677-11e6-8b58-052018cc915e.png)

**Comment by ecdsa** [comment] 2016-09-22 10:00
this issue is caused by the fact that it's a pay-to-pubkey transaction

**Comment by ecdsa** [comment] 2017-01-02 09:55
The problem is that wallet.find_pay_to_pubkey_address() works only if transactions are added in chronological order, using wallet.add_transaction(). While that is the case on wallet startup, it cannot be guaranteed when a wallet is being restored, because add_transaction is called upon reception of the transaction.

**Comment by KeefeJ** [comment] 2017-01-29 07:38
I managed to replicate the more serious version of the issue, where reopening the wallet does *not* fix the balances, with just two particular pay-to-pubkey "addresses" together. For privacy however, I have pm'd ecdsa the addresses.

So even at wallet startup, for certain combinations of addresses, the balances are not tracked correctly. Interestingly, this pair of coinbases were both spent in the same transaction. Also, it makes a difference in which order the two addresses are input into the import dialog. When entered in the reverse order, the balances are correct after reopening the wallet.

**Comment by ecdsa** [comment] 2017-01-29 07:43
Note: it might be possible to recover the public key from sole transaction data, using MyVerifyingKey.from_signature
This would probably fix the issue.

**Comment by SomberNight** [comment] 2018-02-06 20:09
Note: we now use scripthashes to query the server, not addresses; and since ElectrumX 1.2, p2pk and p2pkh scripts are properly separated (https://github.com/kyuupichan/electrumx/commit/e039ba4b15c3750a2c83aab651cfa97986e672e4). Hence, atm, you can't watch p2pk scripts by importing an address (there is no "address" anyway).

**Comment by ecdsa** [comment] 2018-02-06 22:45
@SomberNight so I guess we can close this issue. 
block explorers, not electrum, should be blamed for displaying an incorrect balance.

**Closed** 2018-02-06 22:46 UTC
Labels: bug
