### ISSUE TITLE
Deposit frozen 

### ISSUE THREAD

**Issue by QualityInvest** [spesmilo/electrum#6509] opened 2020-08-14 18:45 UTC
In my wallet electrum my deposit btc id transaction 77cca64b9a2302cf150c4a5f5ac8ef5e7a413c36f08034831ed6554480db7b07 more 1 week, why?

**Comment by lucasmoten** [comment] 2020-08-14 21:43
Looks like it was confirmed awhile ago

```
{
  "txid": "77cca64b9a2302cf150c4a5f5ac8ef5e7a413c36f08034831ed6554480db7b07",
  "hash": "f147d7cf5f1fbcfc93922b36c3f4431e87f3231cb1d3f13f46345cc452a2d866",
  "version": 2,
  "size": 249,
  "vsize": 168,
  "weight": 669,
  "locktime": 642606,
  "vin": [
    {
      "txid": "52ed09c2de9193fa887095a5a00976bd23dbb12d52907f0a0f70a77e65b2c53b",
      "vout": 1,
      "scriptSig": {
        "asm": "0014f61779417ada41a8b76ff87f0d0bcfcb6a364109",
        "hex": "160014f61779417ada41a8b76ff87f0d0bcfcb6a364109"
      },
      "txinwitness": [
        "304402202029f5d95c83c855b46a5bc2391c1fb4aff72f950f68a7f9870b69764672131002205244acc2b74dd8bcff8e5243bdfbd74a20345a1137bdbe7f56f1e67f21bce0ab01",
        "03431a28fb943245e1c9f9d56cbfede88f5a200aa2eff85ab3ddd810843a240556"
      ],
      "sequence": 4294967293
    }
  ],
  "vout": [
    {
      "value": 0.00396400,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 8d2ff3b1f2c04d875911323acdbf3427c194639b OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a9148d2ff3b1f2c04d875911323acdbf3427c194639b88ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "1DsXiooKyB4X8YbWnHrx631ytHi9798dtP"
        ]
      }
    },
    {
      "value": 0.01395033,
      "n": 1,
      "scriptPubKey": {
        "asm": "OP_HASH160 bfe7b67e1e48eab7053b95e042880b5d4deb3f2b OP_EQUAL",
        "hex": "a914bfe7b67e1e48eab7053b95e042880b5d4deb3f2b87",
        "reqSigs": 1,
        "type": "scripthash",
        "addresses": [
          "3KBiZsicePx8FfnDqP8Ue9XKruYuzpkQiV"
        ]
      }
    }
  ]
}
```

**Comment by SomberNight** [comment] 2020-08-26 18:05
I don't see the problem. Please clarify. Closing for now.

**Closed by SomberNight** 2020-08-26 18:05 UTC
