### ISSUE TITLE
Win10: electrum crashes at generating keys when appdata path contains special characters

### ISSUE THREAD

**Issue by radonthetyrant** [spesmilo/electrum#2541] opened 2017-06-20 22:34 UTC
Electrum Version: 2.8.3
Windows 10

Observation:

On the same machine, the program crashes during first key-generation if the full path to the appdata dir contains special characters.
When renaming the directory or creating a new user account without special characters, it works as intended.

Reproduction:

- Create user account with special characters, for example "Frapée"
- Install Electrum
- Generate new Wallet
- Program crashes during key generation

Search didn't turn up any related issues, so I thought this could be new, altough I found it to be unlikely the issue hasn't brought to attention yet. I might be missing something but whatever.

cheers

**Comment by ecdsa** [comment] 2017-06-21 06:43
dduplicate of #2376 
please check existing issues before you create new ones

**Closed by ecdsa** 2017-06-21 06:43 UTC
