### ISSUE TITLE
Electrum 3.0 zombie after quit

### ISSUE THREAD

**Issue by makishart** [spesmilo/electrum#3217] opened 2017-11-04 18:24 UTC
Hi, I upgraded in electrum 3.0 I started a new wallet because the wallet update wasn't successful. Whenever I try to shutdown the window disappears but the app hangs in the background until I kill it from the task manager. I am running it on opensuse tumbleweed.
I also tried deleting the wallet and start a new empty one but the result was the same.

**Comment by AbdussamadA** [comment] 2017-11-07 18:07
duplicate of #3023

**Comment by makishart** [comment] 2017-11-08 09:28
I actually didn't have the same issue in previews versions..
Shall I close this issue?

**Comment by ecdsa** [comment] 2017-11-08 13:15
not sure if that really is a duplicate of #3023 .. the descriptions seem to differ

**Comment by makishart** [comment] 2017-11-08 14:33
Ok.. Let me know if I can help with any specific info or if it is a common issue for opensuse tumbleweed..

**Comment by ecdsa** [comment] 2017-11-08 14:39
@makishart it would be useful to kknow if this issue occurs when you run electrum from a terminal

**Comment by makishart** [comment] 2017-11-08 15:26
Yes, since that happened the first few times, I only run it from the terminal now. When I quit electrum then the terminal hangs until I Ctrl+c or close the terminal to force close electrum. During the hang the tray icon is active and the menu pop up on right click but nothing happens. Can't quit or retrieve the application.

**Comment by ecdsa** [comment] 2017-11-08 15:39
do you quit it using the menu?

**Comment by makishart** [comment] 2017-11-08 17:01
Both ways.. Clicking the x button or using quit from the menu has the same effect..

**Comment by AbdussamadA** [comment] 2017-11-10 17:07
The systray issue also started with version 3.

**Comment by fr3aker** [comment] 2017-11-20 23:53
It looks like `self.app` started in `ElectrumGui.main()` is never stopped which causes the stall. Calling `self.app.quit()` in `ElectrumWindow.clean_up()` seems to fix the problem but I'm not familiar with QT and Electrum's GUI code and don't know if this is the proper fix.

**Comment by JackDinn** [comment] 2017-11-22 11:19
hmm, just updated to electrum 3.0.2 because i would have thought this would have been fixed but no its still there. Looks like i still have to use killall electrum to shut it down, maybe next update ???

**Comment by SomberNight** [comment] 2017-12-30 01:31
I've reproduced this. More specifically,
- using a config based on @AbdussamadA's description (from https://github.com/spesmilo/electrum/issues/3023#issuecomment-342535476): OpenSUSE Leap 42.3 with KDE
- when using Electrum with the QT GUI, after closing all the windows, the process does not quit

I'm unsure if #3023 is the same problem (duplicate or not).

Even more specifically, the main thread of the app runs
https://github.com/spesmilo/electrum/blob/9d4dd20b239c975e99aef4254160732c5031997b/gui/qt/__init__.py#L252
and the `exec_` call will never return.

To be fair, the [QT docs mention](https://doc.qt.io/qt-5/qapplication.html#exec) that `exec` might not return on some platforms, but the docs looks (to me) to be concerned with OS shutdown and similar cases. They suggest to connect to the `QCoreApplication::aboutToQuit` signal instead of expecting `exec` to return.

In this specific case, not even `aboutToQuit` is emitted.

`QGuiApplication::lastWindowClosed` is emitted however, and `QGuiApplication::quitOnLastWindowClosed()` is `True`, which based on the same docs, should result in the app quitting, but this does not happen for some reason. We can however connect our own slot to `lastWindowClosed` to fix this.

**Closed** 2017-12-30 15:50 UTC

**Comment by JackDinn** [comment] 2017-12-31 08:39
does not seem to have been fixed. Built from master, 

Closing the main GUI via window close button kills the tray icon.
File/Quit or Tray/Exit Electrum leaves the /usr/local/bin/electrum running (but does kill the tray icon).

Kernel: 4.10.0-42-generic x86_64 (64 bit) Desktop: KDE Plasma 5.11.4 Distro: neon 16.04 xenial

**Comment by SomberNight** [comment] 2018-01-02 11:09
@JackDinn I've now tested with latest LTS (5.8) and latest non-LTS (5.11) KDE neon, and haven't been able to reproduce the issue. The Electrum process properly quits for me.

**Comment by JackDinn** [comment] 2018-01-02 12:54
@SomberNight yea , it could be related to my neon Dev OS, Iv had a lot of trouble with it recently and yesterday i decided to drop it. Im using Manjaro KDE now but learning a completely new package management system means i was out of my depth trying to build Electrum from source so i shall just stick with the AUR package for now (3.0.3-1). Thank you for taking a look though and the excellent work you do too.

**Comment by AbdussamadA** [comment] 2018-01-03 10:58
@SomberNight I tested git master on openSUSE and it works fine. Thanks!
