### ISSUE TITLE
Unable to send / restore

### ISSUE THREAD

**Issue by TomYeoman** [spesmilo/electrum#2998] opened 2017-10-05 18:23 UTC
Hi all

I've recently tried to send BTC from my walllet using electrum-2.8.3-portable. After repeatedly getting "invalid otp" errors ( i'm certain that the correct private key is used for my authenticator )

I then decided to try a wallet restore using my seed, where it has got stuck hanging on "please wait"

I've tried:

- updating to the latest desktop version of electrum ( electrum-2.9.3 )
- changing servers ( Which I can sucessfully ping ) but i'm still unable to get past the "please wait" screen when restoring!

- ![image](https://user-images.githubusercontent.com/14075632/31245490-6eb95362-aa02-11e7-96c2-0165760fae3f.png)

**Comment by ecdsa** [comment] 2017-10-06 05:50
what is the file name?
I believe there was a similar issue caused by utf-8 characters in the wallet name or path.

**Comment by ecdsa** [comment] 2017-10-07 07:53
closing, no answer

**Closed by ecdsa** 2017-10-07 07:53 UTC
