### ISSUE TITLE
Bug with non-dynamic fee slider

### ISSUE THREAD

**Issue by Engelberg** [spesmilo/electrum#3369] opened 2017-11-24 06:23 UTC
In 3.0.2, I have my fee set to non-dynamic mode.  When I initially create a transaction in the SEND tab, the slider is in the second position from the left and shows that I have it set to 10 sat/byte.  But when I actually go to the preview, it shows that it has only included 5 sat/byte.  I have to go to the SEND tab and drag the slider right and left, back to the 10 sat/byte position for it to actually compute the transaction as 10 sat/byte.

I've figured out the workaround (always drag the slider before creating a transaction) but it's a nuisance that if I forget, it creates a transaction with the wrong fee.

Perhaps the problem is that in a prior version, the second position from the left was in fact 5 sat/byte, not 10 sat/byte?

**Comment by SomberNight** [comment] 2017-11-24 13:51
I can't reproduce this...
Does this happen with all transactions?

What kind of wallet do you have? If you go into `Wallet`>`Information` in the menubar, what is wallet type and script type?
Also, what type is the keystore? Enter `wallet.keystore` into the in-app console to see.

**Comment by Engelberg** [comment] 2017-11-25 07:21
standard, p2pkh, electrum.keystore.BIP32_KeyStore

Yes, every transaction (although I don't make a ton of transactions).  This is a watching wallet that is creating the transaction, and the broadcasting out a signed transaction loaded from a file.

My hunch is that it has something to do with the fact that this is a 3.0.2 installed on top of 2.9.3, and somehow the old slider values are being used in the computation until the slider is actually dragged, even though the UI shows the new value.  It appears that Electrum remembers the last fee setting used each time you start it up; since the wallet was created by 2.9.x, maybe that remembered fee setting is getting misinterpreted by 3.0.2?  Just a guess.

**Comment by ejose19** [comment] 2017-11-25 23:03
At least yours fixes when dragging. If I set to 50 sat/byte when I go to preview it shows 42 sat/byte, and there's no way to get the same value that's displayed on the slider to be the one on the real transactions. Honestly it would be better to let the user input the sat/byte they want, as stated in #3365

**Comment by SomberNight** [comment] 2017-11-25 23:52
@ejose19 that's probably because of #3347. And if it is, #3365 would not have fixed it.

**Comment by SomberNight** [comment] 2018-02-07 21:04
Does this still happen in 3.0.6 or master?

**Comment by SomberNight** [comment] 2018-04-26 23:27
Closing as I could not reproduce back when the issue was opened and it is now even less likely current master would be affected.

**Closed by SomberNight** 2018-04-26 23:27 UTC
Labels: bug, user-interface
