### ISSUE TITLE
quickstart guide doesn't work, how to open the wallet, no DB file is mentioned

### ISSUE THREAD

**Issue by frogeyedpeas** [spesmilo/electrum#6491] opened 2020-08-09 05:49 UTC
The file https://github.com/spesmilo/electrum/blob/master/electrum/scripts/quick_start.py

crashes when run with python 3.7.7 with an error "AssertionError: event loop not running"

This can be mitigated by importing electrum utils and including the line "loop, stopping_fut, loop_thread = create_and_start_event_loop()" BEFORE the daemon gets created. Such as follows 

    from electrum.util import json_encode, print_msg, create_and_start_event_loop, log_exceptions

    loop, stopping_fut, loop_thread = create_and_start_event_loop()

    config = SimpleConfig() 
    daemon = Daemon(config, listen_jsonrpc=False)

After making this patch the same quick start unfortunately fails due to errors later down the line, the "wallet DB" is never referenced in the quickstart so an error of the form:

    wallet = Wallet(storage, config=config)
    TypeError: __new__() missing 1 required positional argument: 'storage' 

occurs due to the expected "DB" argument initially. It's _unclear_ what this should be set to, as setting it to None also kills the program since methods are called against the DB object if it is not None. 

Documentation note: the quickstart guide doesn't reveal how to open wallets with a password, at best users can guess after reading the _all of the source code_ for Walletstorage that the WalletStorage.decrypt() command should be used prior to supplying the storage to the Wallet class but it's _unclear_ if this is correct usage.

**Comment by frogeyedpeas** [comment] 2020-08-09 05:58
I made a branch to keep track of these bugs and eventual fixes but i'm don't have permissions to push new branches to the repository. If you could grant me permissions ill make PR's whenever I can fix an issue that I find.

**Comment by frogeyedpeas** [comment] 2020-08-09 06:18
https://github.com/spesmilo/electrum/pull/6492

**Comment by frogeyedpeas** [comment] 2020-08-09 17:28
SOLUTION include the following lines in the get started script:

    database = WalletDB(storage.read(), manual_upgrades=False)
    wallet = Wallet(database,storage, config=config)

**Comment by joemags-apps** [comment] 2020-08-10 12:55
> SOLUTION include the following lines in the get started script:
> 
> ```
> database = WalletDB(storage.read(), manual_upgrades=False)
> wallet = Wallet(database,storage, config=config)
> ```
I'm getting this Error
```
database = WalletDB(storage.read(), manual_upgrades=False)
NameError: name 'WalletDB' is not defined
```

Forgive me I don't have much experience with python
Do I need to import WalletDB , will you please show me how. Thanks

**Comment by SomberNight** [comment] 2020-08-25 17:20
duplicate of https://github.com/spesmilo/electrum/issues/6453

fixed by https://github.com/spesmilo/electrum/commit/42da407ee16784eb6e2d1f1c644f77d97d7c3007

**Closed by SomberNight** 2020-08-25 17:20 UTC
