### ISSUE TITLE
CLI: electrum broadcast 

### ISSUE THREAD

**Issue by Satevg** [spesmilo/electrum#1742] opened 2016-03-29 15:15 UTC
`electrum broadcast 010000000133068481838dae15e1a9157a26592eb30df3ee96f7f19779901f6e0dcbdfa7df000000006a473044022061cb2448809ffd7d7b599bfc282d3135e4bb4e1989224a433a7ddea096f396170220401e2ae6a82856016c775cb6d2f82d5707ecf0d07dbacff882938a507fd8294501210353cbee668249132b849c3f0ac1af9c7c61f916cc66f2405c18a80c007298b5e8ffffffff0150c30000000000001976a9143aeb35606e30a06a3b127569270185fa1e07b24988ac00000000`

Returns for me following:

```
Traceback (most recent call last):
  File "/usr/local/bin/electrum", line 371, in <module>
    result = server.run_cmdline(config_options)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 288, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 238, in _request
    check_for_errors(response)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 567, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32700, u'Request {"jsonrpc": "2.0", "params": [{"verbose": false, "tx": {"raw": "010000000133068481838dae15e1a9157a26592eb30df3ee96f7f19779901f6e0dcbdfa7df000000006a473044022061cb2448809ffd7d7b599bfc282d3135e4bb4e1989224a433a7ddea096f396170220401e2ae6a82856016c775cb6d2f82d5707ecf0d07dbacff882938a507fd8294501210353cbee668249132b849c3f0ac1af9c7c61f916cc66f2405c18a80c007298b5e8ffffffff0150c30000000000001976a9143aeb35606e30a06a3b127569270185fa1e07b24988ac00000000", "_inputs": null, "_outputs": null, "__jsonclass__": ["electrum.transaction.Transaction", []]}, "cmd": "broadcast", "timeout": 30, "password": null, "cwd": "/root/.electrum", "portable": false}], "id": "5wcw1z8s", "method": "run_cmdline"} invalid. (__init__() takes exactly 2 arguments (1 given))')
```

**Comment by ecdsa** [comment] 2016-03-29 21:31
dupe of #1728

**Closed** 2016-04-04 15:01 UTC

**Comment by shaman** [comment] 2016-10-24 17:58
Fixed for me with python-qt4 and python-pip reinstallation
