### ISSUE TITLE
History updates unreliable

### ISSUE THREAD

**Issue by sup2X** [spesmilo/electrum#1921] opened 2016-09-06 01:09 UTC
I know that Electrum is primary used as desktop client, but the presence of API and payment requests suggest that it can be used as server backend for receiving payments.

The problem is that the synchronization with electrum servers breaks too often. I use it for this purpose almost one year, but I have to restart the daemon from time to time to make sure it is in sync (otherwise the customers don't see the payments and are pissed off).

I thought that auto-connect should solve the issue but it is probably somehow broken. If an server intentionally (or because of a bug) ignores some subscribe request then the client just don't know about a new transaction to that address.

Maybe the option to subscribe to multiple servers in parallel instead of just one would solve the issue. Another solution could be adding an option to define custom set of reliable servers...

**Comment by ser** [comment] 2016-09-27 01:28
Hi, I volunteer to work on this problem, but we must find a way to simulate that behaviour on demand :) Do you have any hints how to reproduce that error?

**Comment by sup2X** [comment] 2016-09-30 18:43
Hi, I'm not sure how to reproduce this error, but it happens also with desktop client. Sometimes, the electrum client just stops updating the transaction history. You have to restart the client in order to get recent history.

It also happens to my friend, so it probably isn't related to my OS or settings.

**Comment by bauerj** [comment] 2018-01-15 11:31
Maybe this will be solved when the asyncio branch is merged.

**Comment by ecdsa** [comment] 2018-01-15 11:34
@bauerj I think this can be closed. there is no reproducible description in this report, and a number of synchronization issues have been fixed since it was submitted.
also, the asyncio branch does is not more stable than master...

**Closed by ecdsa** 2018-01-15 11:34 UTC
Labels: bug
