### ISSUE TITLE
Password/pincode protection and BIP39 seed mnemonic support (android)

### ISSUE THREAD

**Issue by babaiants** [spesmilo/electrum#4552] opened 2018-07-15 17:58 UTC
<!-- Note: This website is for bug reports, not general questions.
Do not post issues about non-bitcoin versions 

1. The adnroid version of a watch-only wallet cannot be password/pincode protected, this option is greyed out.
2. The android version doesn't support a BIP39 seed mnemonic for restore a wallet.

**Comment by SomberNight** [comment] 2018-07-16 15:54
Re BIP39 seeds on Android, duplicate of https://github.com/spesmilo/electrum/issues/3388
Re passwords on Android, duplicate of https://github.com/spesmilo/electrum/issues/2417

**Closed by SomberNight** 2018-07-16 15:54 UTC
