### ISSUE TITLE
Crash on OS X upon completing wallet initialization

### ISSUE THREAD

**Issue by jlopp** [spesmilo/electrum#4805] opened 2018-10-27 14:42 UTC
After importing a 3-of-5 p2sh wrapped segwit wallet on OS X with Electrum 3.2.3, Electrum crashes every time with this stack trace:

```
/Electrum.app/Contents/MacOS/Electrum --testnet
Traceback (most recent call last):
  File "electrum/gui/qt/util.py", line 661, in run
  File "/var/folders/lr/57jkmj0s11v3y364dy6sw7wr0000gp/T/_MEIVyk2Ti/electrum/plugins/trezor/trezor.py", line 150, in get_client
    client = devmgr.client_for_keystore(self, handler, keystore, force_pair)
  File "electrum/plugin.py", line 409, in client_for_keystore
  File "electrum/plugin.py", line 454, in force_pair_xpub
electrum.plugin.DeviceUnpairableError: Electrum cannot pair with your TREZOR.

Before you request bitcoins to be sent to addresses in this wallet, ensure you can pair with your device, or that you have its seed (and passphrase, if any).  Otherwise all bitcoins you receive will be unspendable.
```

To be more specific, the wallet is created from one Ledger Nano S, two Trezor Ones, and two master upubs.

After the Electrum crash I am able to run Electrum and the wallet loads as expected.

**Comment by SomberNight** [comment] 2018-10-28 19:14
Crash as in the whole app dies?
Could you see if you can reproduce with simpler wallet setups? For instance, with 2-of-2 ledger+trezor; and trezor+trezor?
Also, run Electrum with the `-v` flag, as the surrounding log lines might be helpful.

**Comment by SomberNight** [comment] 2018-11-16 17:11
Ok, I've reproduced this.
It's a duplicate of https://github.com/spesmilo/electrum/issues/4348
Should be fixed now.

**Closed by SomberNight** 2018-11-16 17:11 UTC

**Comment by jlopp** [comment] 2018-11-16 17:18
Ah, great! I haven't forgotten about the other issues either - I just normally don't have access to a Mac. Testing more is still on my to-do list.
