### ISSUE TITLE
Exception in labels plugin: no attribute 'wallet_id'

### ISSUE THREAD

**Issue by molecular** [spesmilo/electrum#863] opened 2014-09-21 11:11 UTC
```
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/mnt/maui/home/nick/bitcoin/electrum/plugins/labels.py", line 219, in do_full_pull
    connection.request("GET", ("/api/wallets/%s/labels.json?auth_token=%s" % (self.wallet_id, self.auth_token())),"", {'Content-Type': 'application/json'})
AttributeError: Plugin instance has no attribute 'wallet_id'
```

Lable upload/download (using label sync plugin settings buttons) works. But 'normal' label upload (just entering an address label) doesn't seem to work. Maybe it's related to above error which I just discovered on the console.

**Comment by ecdsa** [comment] 2015-03-13 16:04
I guess it is fixed now; cannot reproduce, and wallet_id is set in load_wallet

**Closed by ecdsa** 2015-03-13 16:04 UTC
