### ISSUE TITLE
Problem with Electrum wrongly recognizing a transactions input address

### ISSUE THREAD

**Issue by Onkovat** [spesmilo/electrum#2247] opened 2017-03-06 23:14 UTC
This is for electrum 2.7.18.

The problem is with a 2 of 2 multisig. Creating and signing a transaction works fine. When checking this transaction online then the real input address is recognized. Though when loading it into the other electrum then it shows a different input address that was never used. So electrum has some error in recognizing.

This happens when the transaction is created on the first electrum the same like it happens on the second electrum.

I can give the transaction and details though I would not want to post it here publicly.

**Comment by ecdsa** [comment] 2017-03-07 04:31
regenerate both wallets from seed.
some recent versions misordered the public keys of multisig inputs. the issue is fixed in master.

**Closed by ecdsa** 2017-03-07 04:31 UTC

**Comment by Onkovat** [comment] 2017-03-07 19:22
Well, for now I only could recreate my own wallet. I then imported the transaction I previously received from the cosigner. It again parsed it wrongly on electrum 2.7.18. Even though the transaction should be correct since https://blockchain.info/de/decode-tx shows it correctly. Also the input searched with https://blockchain.info/unspent?active=[address] is correct also.
Is there a way to send the transaction to you without revealing it to the public?

**Comment by Onkovat** [comment] 2017-03-07 19:23
Should I open a new ticket?

**Comment by ecdsa** [comment] 2017-03-08 00:20
you have to regenerate both cosigners, then do transactions

**Comment by Onkovat** [comment] 2017-03-11 12:15
Thank you, it worked and we could take out the coins from the wallet.
