### ISSUE TITLE
ProtocolError(-32600, 'ill-formed response error object: cannot estimate fee for 25 blocks')

### ISSUE THREAD

**Issue by alexander-koval** [spesmilo/electrum#7397] opened 2021-07-08 12:59 UTC
Hi guys. I was connected to endurance node. But suddenly it disconnect. In logs I see that 
```
20210708T112845.698878Z |     INFO | lnpeer.Peer.[LNGossip, 13.248.222.197:9735] | Disconnecting: GracefulDisconnect("initialize failed: HandshakeFailed('Lightning handshake act 1 response has bad length, are y\
ou sure this is the right pubkey? 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134@13.248.222.197:9735')")
```
Also when I start wallet I see 

```
E/i | interface.[blockstream.info:993] | Exception in run: ProtocolError(-32600, 'ill-formed response error object: cannot estimate fee for 25 blocks')
Traceback (most recent call last):
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/util.py", line 1093, in wrapper
    return await func(*args, **kwargs)
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/interface.py", line 487, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/interface.py", line 510, in run
    await self.open_session(ssl_context)
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/interface.py", line 657, in open_session
    await group.spawn(self.monitor_connection)
  File "/usr/lib/python3.9/site-packages/aiorpcx/curio.py", line 255, in __aexit__
    await self.join()
  File "/usr/lib/python3.9/site-packages/aiorpcx/curio.py", line 213, in join
    raise task.exception()
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/interface.py", line 682, in request_fee_estimates
    fee_tasks.append((i, await group.spawn(self.get_estimatefee(i))))
  File "/usr/lib/python3.9/site-packages/aiorpcx/curio.py", line 255, in __aexit__
    await self.join()
  File "/usr/lib/python3.9/site-packages/aiorpcx/curio.py", line 213, in join
    raise task.exception()
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/interface.py", line 1080, in get_estimatefee
    res = await self.session.send_request('blockchain.estimatefee', [num_blocks])
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/interface.py", line 172, in send_request
    response = await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/lib/python3.9/site-packages/aiorpcx/session.py", line 537, in send_request
    return await self._send_concurrent(message, future, 1)
  File "/usr/lib/python3.9/site-packages/aiorpcx/session.py", line 507, in _send_concurrent
    return await future
  File "/usr/lib/python3.9/site-packages/aiorpcx/jsonrpc.py", line 721, in receive_message
    item, request_id = self._protocol.message_to_item(message)
  File "/usr/lib/python3.9/site-packages/aiorpcx/jsonrpc.py", line 273, in message_to_item
    return cls._process_response(payload)
  File "/usr/lib/python3.9/site-packages/aiorpcx/jsonrpc.py", line 220, in _process_response
    raise cls._error(code, message, False, request_id)
aiorpcx.jsonrpc.ProtocolError: (-32600, 'ill-formed response error object: cannot estimate fee for 25 blocks')

```
[electrum_log_20210708T112844Z_504068.log](https://github.com/spesmilo/electrum/files/6784671/electrum_log_20210708T112844Z_504068.log)
[electrum_log_20210708T125040Z_519138.log](https://github.com/spesmilo/electrum/files/6784673/electrum_log_20210708T125040Z_519138.log)

**Comment by SomberNight** [comment] 2021-07-08 15:14
> Also when I start wallet I see
>
> `E/i | interface.[blockstream.info:993] | Exception in run: ProtocolError(-32600, 'ill-formed response error object: cannot estimate fee for 25 blocks')`

This is unrelated to the LN issue. I suppose that server recently restarted and that's why it does not have those feerate estimates, but it does not matter. The trace in the log is so long and the exception itself is a bit weird because electrs sends protocol errors in a weird way (not following the jsonrpc spec):
https://github.com/romanz/electrs/issues/313

> Hi guys. I was connected to endurance node. But suddenly it disconnect. In logs I see that
> ```
> 20210708T112845.698878Z |     INFO | lnpeer.Peer.[LNGossip, 13.248.222.197:9735] | Disconnecting: GracefulDisconnect("initialize failed: HandshakeFailed('Lightning handshake act 1 response has bad length, are y\
> ou sure this is the right pubkey? 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134@13.248.222.197:9735')")
> ```

Can you still reproduce this issue? I have tried to connect to that node now and it works for me.

**Comment by alexander-koval** [comment] 2021-07-08 16:21
No. I've reopen channel and it's work normally.

**Comment by SomberNight** [comment] 2021-07-08 23:06
I don't think closing/opening a new channel had anything to do with this.
Given this is a testnet, I think the node in question might have been doing something weird for a few hours.

**Closed by SomberNight** 2021-07-08 23:06 UTC
