### ISSUE TITLE
unconfirmed transaction

### ISSUE THREAD

**Issue by PaulNorthern** [spesmilo/electrum#3533] opened 2017-12-16 12:59 UTC
How can I cancel an unconfirmed transaction that has been hanging for 3 days already? I tried to increase the tax, but it did not help.

**Comment by PaulNorthern** [comment] 2017-12-16 13:13
https://www.blocktrail.com/BTC/tx/b820a54b58b9c42fffd7f5f0de038a6b3b071234260bd4f42720fb3fae7d5b9e

**Comment by SomberNight** [comment] 2017-12-16 14:30
That tx has a 9 sat/vbyte fee, [which is really low at the moment](https://core.jochen-hoenicke.de/queue/#24h). If you want it to confirm in reasonable time, you should probably bump the fee to ~10 times that.

http://docs.electrum.org/en/latest/faq.html#my-transaction-has-been-unconfirmed-for-a-long-time-what-can-i-do
https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do

Anyway, this is not a bug, it's just how bitcoin works, so closing this.

**Closed by SomberNight** 2017-12-16 14:30 UTC

**Comment by PaulNorthern** [comment] 2017-12-16 14:38
Thank you very much, comrade. U really helped me)
