### ISSUE TITLE
Increase fee (bump fee, RBF) should respect coin selection

### ISSUE THREAD

**Issue by ziggamon** [spesmilo/electrum#5719] opened 2019-10-22 14:55 UTC
Transactions that have only one output are "send all" transactions. It should be a reasonable assumption that when increasing fee on those the sender intends the fee to come out of the amount sent, not to introduce another input into the mix and create change.

**Comment by SomberNight** [comment] 2019-10-22 15:31
The RBF logic is now getting quite complex; namely I would rather not write down the whole list of decisions taken in a comment anymore. So let's only consider your example of "only one output".

If there is only one output, and it is
- a receive address of the wallet ("green"), then the bump_fee logic will decrease the output amount
- a change address of the wallet ("yellow"), same as above (now that https://github.com/spesmilo/electrum/issues/5718 is fixed)
- an external address, then
    1. we will first try to add new inputs and create change, or if this fails, then
    2. we will decrease the output amount

So it seems you are interested in the "external address" case, as the others already behave as you describe.

Note that if the transaction is spending all the UTXOs in the wallet, then we will end up decreasing the output amount.

> Transactions that have only one output are "send all" transactions.

I assume by "send all" you mean the user clicked "Max" in the GUI; hence spending all selected UTXOs (which might not be all the UTXOs in the wallet if coin selection is being performed).

The issue is that sometimes we end up creating a transaction without change "just by chance". And if this transaction is paying an exact amount to a merchant, than that amount should not be decreased.

**Comment by SomberNight** [comment] 2019-10-22 15:40
I guess only the user knows what he wants (or if he does not know, then they should not care what arbitrary but reasonable decisions we take), so this can only really be resolved by extending the GUI somehow letting the user choose.

For example, it would be nice to have a GUI where coin selection can be used for bumping the fee.

**Comment by ziggamon** [comment] 2019-10-22 15:47
Right. I see the issue. 

How about if you simply keep track of clicks on the "send max" button or "spend" menuitem, and if it's the case you go for the `ii` mode first.

**Comment by SomberNight** [comment] 2019-10-22 16:03
> How about if you simply keep track of clicks on the "send max" button or "spend" menuitem, and if it's the case you go for the ii mode first.

Well... but what if the user restarts the application while the tx in unconfirmed and wants to do RBF after? Clicking "send max" while creating a tx is not something we should persist on disk; that seems ugly. (Even if we did, then what about the case where the user restored from seed while the tx is unconfirmed and tries to bump fee then? :D -- kind of joking but still)

![electrum_4_0_0_bump_fee](https://user-images.githubusercontent.com/29142493/67305639-2c558100-f4e5-11e9-9e32-d036afbfc8b8.PNG)

Maybe we could add a new checkbox, "allow adding inputs", to the "bump fee" dialog, enabled by default. Maybe it could be hidden by default, only visible if "Edit fees manually" is enabled in Preferences.

**Comment by ziggamon** [comment] 2019-10-22 16:11
Yeah, we're far in the deep edge case territory. Can't blame you if you want to just close this ticket as not important enough to focus on right now.

But I'd make one less argument for the less wrong approach and that is to reduce the sent amount first. Merchants who require an exact amount of BTC probably don't want you to be using RBF anyway (RBF breaks their commitment to a fiat value, which was the reason for a fixed btc amount in the first place), so I'd say chances are veery low of that happening at the same time as an utxo by sheer luck having the exact right bitcoin amount as desired. Could change the default and reopen the ticket if anyone complains.

**Comment by SomberNight** [comment] 2019-10-22 16:17
The ideal solution would be to optionally expose coin selection to "bump_fee". The user would be able to select some coins and then we would decide which of those to use; or if none was selected then no new inputs would be added.

**Comment by SomberNight** [comment] 2019-10-22 16:37
I would rather not change the default order because at the same time this more powerful bump_fee method was added (that can now add new inputs), we also made it more likely that "no change" txns are created.

see https://github.com/spesmilo/electrum/blob/d9b5ab30860bd2180e2b7b5592c0229bfc73bff0/RELEASE-NOTES#L19-L29
https://github.com/spesmilo/electrum/commit/e864fa50882db90df50e6e0240f55197b28097ed

So effectively, if you have lots of UTXOs, there is now a decent chance we find some combination that results in the ~exact output value (and we allow around ~546 sats to be burned as fees as leeway; related: https://github.com/spesmilo/electrum/issues/5359).

**Comment by SomberNight** [comment] 2019-11-20 17:50
With https://github.com/spesmilo/electrum/commit/49284f716b90a266b4664b364d7c0303ac4ba123 "bump fee" now respects the global coin selection.

> How about if you simply keep track of clicks on the "send max" button or "spend" menuitem, and if it's the case you go for the `ii` mode first.

This issue is still not fully resolved however, as there is still no way to force "bump fee" not to add new inputs (but rather to decrease output amounts).

There are two options I can see now:
1. allow the global coin selection to select an empty set of coins (which would force the "bump fee" logic to choose method `ii`)
2. add a checkbox in the "bump fee" dialog "allow adding new inputs" or similar (checked by default)

Atm I like option (1.) better. Although selecting an empty set seems only useful in the "bump fee" case (other users of coin selection currently include: "new tx"; and "channel open").

**Closed** 2019-11-21 16:46 UTC
Labels: topic-fees, topic-wallet
