### ISSUE TITLE
Feature request: Password protected hardware wallets

### ISSUE THREAD

**Issue by eugenesan** [spesmilo/electrum#7856] opened 2022-06-15 04:37 UTC
Currently there is only an option to encrypt hardware wallet using hardware device.
It would be extremely useful to be able to create a password protected hardware wallets.
The use case is to be able to monitor the wallet and require hardware device only for creating transactions.

**Comment by ecdsa** [comment] 2022-06-15 06:08
this is a duplicate of an existing issue, see #5561 
please do a minimum of research before posting

**Closed by ecdsa** 2022-06-15 06:08 UTC

**Comment by eugenesan** [comment] 2022-06-15 07:58
@ecdsa 
My bad.
I failed to find it.
Thanks.
