### ISSUE TITLE
is there a probleme with fees

### ISSUE THREAD

**Issue by mikamour** [spesmilo/electrum#1776] opened 2016-04-30 09:07 UTC
is a electrum wallet a scam
1MkMJhEXZoCF9sKxpfjXL48m7GUBwS6AXz	     0.00020259
...au3u....DthbnbT...8wYdy6u.....	     0.0005    

the fees cost 50% of my send 
i have set transaction fees at 0
the second probleme is about **double spend**
look what they says on blockchain : Warning! this transaction is a double spend. You should be extremely careful when trusting any transactions to/from this sender.
because of this my transaction are blocked.
i am using electrum 2.5.2

**Comment by dabura667** [comment] 2016-04-30 10:49
> the fees cost 50% of my send 
> i have set transaction fees at 0

fees increase as data requirements increase. So if you receive a lot of small amounts of bitcoin frequently, you will spend more fees to move those bitcoins. (This is why faucets will cost you more money than you make, and are usually a bad idea)

0 fees on a transaction will cause your transaction to be rejected by multiple nodes.

> the second probleme is about double spend
> look what they says on blockchain...

This problem is likely caused by your transaction having 0 fees. Most nodes on the network will not relay your transaction without any fees, so a site like blockchain.info would see your transaction, and by reconnecting and sending through another server you could possibly have run into this problem.

If you could post the actual transaction ID, then we can help.

Also, Electrum is not a scam.

**Comment by ecdsa** [comment] 2016-05-16 15:26
closing, OP not providing txid.

**Closed by ecdsa** 2016-05-16 15:26 UTC
