### ISSUE TITLE
Some headers displayed on first column of the Channels tab

### ISSUE THREAD

**Issue by dario-spagnolo** [spesmilo/electrum#7158] opened 2021-03-31 21:16 UTC
After updating to 4.1.0 (AppImage / Linux), the first column header of the Channels tab contains some raw headers. A screenshot is worth a thousand words: 

![Sélection_320](https://user-images.githubusercontent.com/8155871/113212145-ac554e00-9276-11eb-9a0f-88fe62c02774.png)

It might be limited to the French locale.

**Comment by dario-spagnolo** [comment] 2021-03-31 21:24
Also, this bug made me notice that the locale preference is not consistent. Although "English" is selected in the language, some texts are displayed in French inside the Channels tab ("Capacité", "Peut envoyer", etc.).

**Comment by SomberNight** [comment] 2021-04-01 00:48
Weird.
Do other strings besides these in the Channels tab look normal?

**Comment by SomberNight** [comment] 2021-04-01 01:03
Hmm I cannot reproduce so far...
Does this reliably happen for you?
Could you try changing the language to something other than English or French; e.g. German, and taking a screenshot like that?

**Comment by SomberNight** [comment] 2021-04-01 01:23
> this bug made me notice that the locale preference is not consistent. Although "English" is selected in the language, some texts are displayed in French 

Is your OS language set to French?

**Comment by SomberNight** [comment] 2021-04-02 15:23
I think this is mostly fixed by https://github.com/spesmilo/electrum/commit/210ff647fa65aa5756304f8ae7ef0b6e45ccad40 and https://github.com/spesmilo/electrum/commit/a2ed95340ce941acb4cc6f9181c78637dcbdc61a
but I am still interested in answers for above questions :)

**Closed by SomberNight** 2021-04-02 15:23 UTC
Labels: bug 🐞, localization 🌍
