### ISSUE TITLE
A json-rpc port to Electrum daemon refuses a connection from a client.

### ISSUE THREAD

**Issue by JdeveloperAcc** [spesmilo/electrum#5501] opened 2019-07-10 09:56 UTC
We use a json-rpc connection to Electum daemon on a localhost on Windows Server 2016.
Sometimes a new http request with a new rpc command is replied with the http error: 
"No connection could be made because the target machine actively refused it 127.0.0.1:xxxxx."

After some while the connection is established again and the daemon receives and processes next json-rpc commands.

We use Electrum Windows app in version 3.3.6 (32 bits) from a win installer officially downloaded from Electrum.org repository.

A run configuration:
electrum-3.3.6.exe app ... a run under an admin user
electrum-3.3.6.exe daemon start ... an admin shell command I
electrum-3.3.6.exe daemon load_wallet ... an admin shell command II
a client is a web application on IIS, 
it utilizes the lib EdjCase.JsonRpc.Client in version 3.0.2. 

The log file exception:
- 7/9/2019 3:07:58 AM - GetPaymentRequest : Exception = EdjCase.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send rpc requests(s) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:xxxxx.

**Comment by badhitman** [comment] 2019-08-11 02:24
Electrum daemon does not work on Windows. Works on Linux. Mac don't know.

**Comment by ecdsa** [comment] 2019-08-14 12:46
I don't think this is caused by an issue in the Electrum code.
what do you mean by "sometimes". does that happen randomly?

**Comment by ecdsa** [comment] 2019-08-19 12:20
closing, no answer

**Closed by ecdsa** 2019-08-19 12:20 UTC
