### ISSUE TITLE
Allow "oneserver" to be configured from GUI.

### ISSUE THREAD

**Issue by cantilope** [spesmilo/electrum#6577] opened 2020-09-12 01:44 UTC
Please can you add an option to configure`"oneserver": true` in the GUI rather than having to specify on the command line or manually edit the config file?

**Comment by SomberNight** [comment] 2020-09-12 01:59
please search for existing issues before opening new ones.
duplicate of https://github.com/spesmilo/electrum/issues/6574

**Closed by SomberNight** 2020-09-12 01:59 UTC
