### ISSUE TITLE
Do not allow wallets to be created without encrypting keys

### ISSUE THREAD

**Issue by jingxi285** [spesmilo/electrum#6883] opened 2020-12-26 12:39 UTC
v4.0.9
When importing some seed words, noticed this:
 "Leave this field empty if you want to disable encryption", bad idea not require a password to encrypt private keys on disk!

**Comment by ecdsa** [comment] 2020-12-27 11:14
there are use cases where encryption is not wanted.
I am not sure if we should allow them from the GUI, though.

**Comment by jingxi285** [comment] 2020-12-27 17:29
Maybe even change to "Leave this field empty if you want to disable encryption - at your own risk!"

**Comment by Transisto** [comment] 2020-12-30 21:36
There are for sure many use-case,  Believe it or not some desktop are secure enough for a hot spending wallet.

I agree though there could be a stronger warning. Could even show a relative password strenght meter but would never require a minimum length otherwise people are more likely to lose funds from forgetting longer than they want passwords.

**Comment by ecdsa** [comment] 2020-12-31 11:31
closing as duplicate of #2143
please check existing issues before you open new ones.

**Closed by ecdsa** 2020-12-31 11:31 UTC
