### ISSUE TITLE
Scaling issue of icons inside TextEdits. Icons in "Pay to" and "Receiving address" inputs mis-aligned (incorrect size). qt icons too large/cropped (widget position shifted)

### ISSUE THREAD

**Issue by bolatovumar** [spesmilo/electrum#5047] opened 2019-01-31 02:34 UTC
Electrum 3.3.3 on Windows 10 (also happens on MacOS X Mojave).

Sorry if this bug has been raised already, I couldn't find it among existing bugs.
![capture2](https://user-images.githubusercontent.com/1934678/52026688-9e041f80-24bd-11e9-8716-c2cc55c65bd0.PNG)

![capture](https://user-images.githubusercontent.com/1934678/52026675-8f1d6d00-24bd-11e9-9e44-ea000e6f3c25.PNG)

**Comment by luggs-co** [comment] 2019-01-31 02:46
Confirmed here on Win10.

**Comment by luggs-co** [comment] 2019-01-31 02:47
Also QR code in transaction details - Transaction ID text field. I going to assume it's any icon inside a text field.

- Yep, Address details also has this issue.

**Comment by SomberNight** [comment] 2019-01-31 11:41
introduced in https://github.com/spesmilo/electrum/commit/7a4270f5a4441c708556432a45f2b553129ae84e
due to the hardcoded "25" pixels

**Comment by bolatovumar** [comment] 2019-01-31 15:03
@SomberNight so the fix could be as simple as removing the line with hardcoded values?

Unfortunately I am not experienced with PyQt or else I would try it and test it myself.

**Comment by SomberNight** [comment] 2019-01-31 22:12
@ecdsa do you remember why you added that line?

**Comment by SomberNight** [comment] 2019-02-01 20:54
Note: positioning and size of icons in this case seems to be very much dependent on OS/Qt/dark-light mode...
It was set to 25 because on some combos, the icons were small.

**Comment by bolatovumar** [comment] 2019-02-02 00:35
The "Pay to" field icons are aligned correctly in light mode on Mac OS:
![screen shot 2019-02-01 at 4 31 39 pm](https://user-images.githubusercontent.com/1934678/52156763-1e05c300-263f-11e9-80d3-2696ac53e704.png)

However, the "Receiving address" field icon is not:
![screen shot 2019-02-01 at 4 32 10 pm](https://user-images.githubusercontent.com/1934678/52156808-56a59c80-263f-11e9-945e-af7d0a2bad2b.png)

**Comment by bolatovumar** [comment] 2019-02-02 00:39
Same as above observed on Windows 10

**Comment by bolatovumar** [comment] 2019-02-02 19:08
Just out of curiosity, how would one go about trying to fix a bug like this (or any other bug) in Electrum? Would I have make the code change and re-build the app from scratch and then verify that the issue is fixed or not? Or is there an alternative development workflow which would allow for quickly testing the changes?

**Comment by SomberNight** [comment] 2019-02-28 19:41
@bolatovumar you would typically run from source; see e.g. https://github.com/spesmilo/electrum/blob/master/README.rst#development-version

However, it is a bit trickier if the problem is platform-specific. You can either (1) set up a development environment and run from source on all affected platforms; or (2) only do it on one, and build binaries there for the other platforms.

**Comment by rt121212121** [comment] 2019-02-28 20:23
I would say they are not correctly aligned in the light mode in MacOS as shown above, they should be down 1 or 2 pixels.

One thing I found for ElectrumSV was that the buttons did some complicated calculation to vertically align the images, which I removed, then just shifted them left into the field. It's possible that we do not handle well the wide variety of different cases, but it might be something to check if it can be simplified.

**Comment by bolatovumar** [comment] 2019-03-03 22:57
@rt121212121 you are right about them not being aligned correctly in MacOS in light mode but it's not anywhere as bad as the dark mode. I would says it's OK.

**Comment by Daijobou** [comment] 2019-05-12 10:48
Issue still exists in version 3.3.5 for windows 10.

**Comment by SomberNight** [comment] 2022-06-01 17:23
fixed in https://github.com/spesmilo/electrum/commit/2d1727520fb9a4a768adb4f261c29b15c12a3fa9

**Closed by SomberNight** 2022-06-01 17:23 UTC
Labels: bug 🐞, user-interface 🔲, Qt ✨
