### ISSUE TITLE
Electrum 3.0.3 does not exit on linux

### ISSUE THREAD

**Issue by zorn-v** [spesmilo/electrum#3616] opened 2017-12-28 00:43 UTC
Kubuntu 17.10
After closing it remains hanging in KDE tray. Context menu is there (but without wallet menu item), but "Close" menu item does not work anyway.

**Comment by AbdussamadA** [comment] 2017-12-28 16:01
duplicate of #3023

**Closed** 2017-12-28 17:40 UTC
