### ISSUE TITLE
Does not build on MacOS

### ISSUE THREAD

**Issue by nitinsurana** [spesmilo/electrum#3743] opened 2018-01-19 18:22 UTC
1. Create setup.cfg within the contrib directory
2. https://stackoverflow.com/a/44728772/566092
3. Execute ./make_packages (it'll install the dependencies)
4. pip install btchip-python
5. Copy /lib/python3.6/site-packages/btchip to contrib/packages
4. Execute ./make_osx

I followed the above setups, but it gives the following error :

```
➜  electrum git:(master) ✗ ./contrib/make_osx 
186 INFO: PyInstaller: 3.3.1
186 INFO: Python: 3.6.3
192 INFO: Platform: Darwin-17.3.0-x86_64-i386-64bit
194 INFO: UPX is not available.
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'btchip'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/utils/hooks/__init__.py", line 326, in get_module_file_attribute
    attr = loader.get_filename(package)
AttributeError: 'NoneType' object has no attribute 'get_filename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 30, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/utils/hooks/__init__.py", line 720, in collect_data_files
    pkg_base, pkg_dir = get_package_paths(package)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/utils/hooks/__init__.py", line 530, in get_package_paths
    file_attr = get_module_file_attribute(package)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/utils/hooks/__init__.py", line 336, in get_module_file_attribute
    raise ImportError
ImportError
hdiutil: create failed - No such file or directory

```
Any pointers ? Or is there an up-to-date guide for building on MacOS with Homebrew python install ?

**Comment by nitinsurana** [comment] 2018-01-19 18:31
Next got an error for `keepkeylib`. Fixed that as well and now the error is 

`ValueError: script '/Users/voegtlin/electrum/electrum' not found` - something somewhere is hardcoded I believe. Following is the complete error 

```
190 INFO: PyInstaller: 3.3.1
190 INFO: Python: 3.6.3
196 INFO: Platform: Darwin-17.3.0-x86_64-i386-64bit
199 INFO: UPX is not available.
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 52, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 162, in __init__
    raise ValueError("script '%s' not found" % script)
ValueError: script '/Users/voegtlin/electrum/electrum' not found
hdiutil: create failed - No such file or directory
```

**Comment by nitinsurana** [comment] 2018-01-19 18:36
Fixed the hard-coded location in `osx.spec`, now the next error is

**Comment by nitinsurana** [comment] 2018-01-19 18:46
Fixed, using the following set of commands 
```
./contrib/make_locale
brew install gettext; brew link gettext --force
./contrib/make_locale (gives fatal errors, ignore)
./contrib/make_osx
```

I guess the readme needs to be updated for the same or a new readme for macOS should be created. Shall I send a pull-request ?

**Comment by nitinsurana** [comment] 2018-01-19 18:48
`Electrum.app` doesn't work, just dies. Any pointers now ?

**Comment by nitinsurana** [comment] 2018-01-19 18:53
There is something seriously wrong, the .dmg file created using the above process is only 8.6MB but the one located on the site - https://electrum.org/#download is around 20MB.

**Comment by KaboomFox** [comment] 2018-01-19 21:22
it cannot import bitcoin or any other file in the lib directory because of the `package_dir` in the setup.py file. If you look back at the repo there use to be a setup-release.py file.

**Comment by nitinsurana** [comment] 2018-01-19 21:35
Thanks. Any pointers on how to build it on macOS now ?

**Comment by bauerj** [comment] 2018-01-19 22:28
Do you have an `Electrum-3.0.5-py3.6.egg` (or .wheel) in your dist folder? If not, you can generate it using `setup.py install`.

**Comment by nitinsurana** [comment] 2018-01-19 23:49
Yes, I have the .egg file.

**Comment by bauerj** [comment] 2018-01-21 14:36
Duplicate of #3746.

**Closed by bauerj** 2018-01-21 14:36 UTC
Labels: bug, duplicate, macOS
