### ISSUE TITLE
KeyError in addr_history_response

### ISSUE THREAD

**Issue by sup2X** [spesmilo/electrum#1931] opened 2016-09-19 19:56 UTC
Hello,

sometimes i get this error when Electrum daemon is starting:

```
[Network] <-- {'method': 'blockchain.address.get_history', 'params': [u'1J...'], u'id': 407, u'result': []}
[Synchronizer] receiving history 1J... 0
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/electrum/network.py", line 794, in run
    self.wait_on_sockets()
  File "/usr/local/lib/python2.7/dist-packages/electrum/network.py", line 788, in wait_on_sockets
    self.process_responses(interface)
  File "/usr/local/lib/python2.7/dist-packages/electrum/network.py", line 578, in process_responses
    self.process_response(interface, response, callbacks)
  File "/usr/local/lib/python2.7/dist-packages/electrum/network.py", line 530, in process_response
    callback(response)
  File "/usr/local/lib/python2.7/dist-packages/electrum/synchronizer.py", line 102, in addr_history_response
    server_status = self.requested_histories[addr]
KeyError: u'1J...'
```

Afterwards, it is not possible to send any bitcoins:
`'transaction declined: %s', 'error: Server did not answer'`

Recovering the wallet from backup helps, but it is very annoying doing it almost every day.

Regards
sup2X

**Comment by ecdsa** [comment] 2016-09-20 14:04
is this a duplicate of #1919 ?

**Comment by sup2X** [comment] 2016-09-20 17:44
No, the exception occurs in a different place. This issue is probably caused by the wallet corruption.

I was periodically restarting my python script that uses Electrum as a Library with SIGKILL. I used SIGTERM instead, called wallet.stop_threads() and it is working good so far (I will test it for a few days and report the result here). Still, I think that this exception should be caught and let the user know that the wallet is probably corrupted.

**Comment by ecdsa** [comment] 2016-09-21 09:35
first I need to ba able to reproduce your issue.
can it be reproduced if you create a new wallet? how is the wallet created?
also, does it occur if you use ecdsa.net as the server?

**Comment by sup2X** [comment] 2016-09-22 15:32
It could be probably reproduced by killing (not closing but sending SIGKILL) the Electrum client during synchronization. My server was doing this every hour with cron. Unfortunately, I don't have the corrupted wallet file anymore. It is the standard wallet from 2.6.4.

Yes, it occurred on ecdsa.net also. I think that the real reason of 'error: Server did not answer' is that the exception occurred in network thread and the main thread continues to run. I use the old customized merchant.py script, so it works a little different then GUI client.

Since I added SIGTERM handler and wallet.stop_threads() into merchant.py the wallet is saved properly during restarts and the issues does not occur anymore.

I will send you the wallet file if it happens again.

**Comment by sup2X** [comment] 2016-10-12 23:34
Unfortunately, wallet.stop_threads() actually didn't help. The issue appeared again after few days.

**Comment by bauerj** [comment] 2018-01-15 12:25
I think this issue is solved now. Please reopen if that's not the case.

**Closed by bauerj** 2018-01-15 12:25 UTC
