### ISSUE TITLE
History is not updated when a new transaction is sent.

### ISSUE THREAD

**Issue by neocogent** [spesmilo/electrum#1740] opened 2016-03-25 23:05 UTC
I've had this happen since way back - it has never worked as far as I can recall. When I send a trx I expect it to show up in the history list as pending but this never happens. Electrum does not sync after a new transaction. I always have to manually exit the program and start it again to see the pending transaction and the now current balance.

Or are we expected to wait for some time period for a new sync to update? If so, then that is really a poor user experience.

**Comment by ecdsa** [comment] 2016-03-26 06:14
history is updated once the server you are talking to has updated its memory pool.
it typically takes about 10 seconds

**Comment by neocogent** [comment] 2016-03-26 15:06
I've waited several minutes before restarting. Is that something the server can configure or perhaps some servers have a problem with? Next trx I'll switch servers before and then see if it's any different. I've been using electrum.no-ip.org for a long time.

**Comment by neocogent** [comment] 2016-04-03 17:50
I've tried this now with other servers on new trxs. Either many servers aren't updating, or it just doesn't work. I've never seen this work properly. I'm watching my wallet now well over 2 minutes after sending a trx and still it has not done anything. Even if I switch servers it will sync but not show any new activity. Yet, if I immediately after this close the program and start again (still on same server) it will sync and show the pending trx. So it would see that even if right after the trx, it did sync, then it would be shown on screen, perhaps due to some form of caching that is cleared during a restart.

**Comment by ecdsa** [comment] 2016-04-03 18:54
if it's never worked properly, I guess the issue is client side, not server side

**Comment by neocogent** [comment] 2016-04-03 18:56
I'd be interested if many others see this behavior or if it's just me, or a few of us out here.

**Comment by ElectrumUserExp** [comment] 2016-04-09 16:08
Same issue at me. Using Portable Edition of Electrum for Windows. Waited about 30 Minutes. In Blockchain there were more than 6 confirmation for the transaction. Electrum client was not showing the transaction. Change the servers doesnt help. After closing and starting electrum again the transactions showed up. This is not user friendly...

**Comment by EagleTM** [comment] 2016-04-12 11:49
For me I believe it used to be a lot more prominent with older clients than with the current 2.6.x branch. It works 7/10 times, need to restart for the remaining 30% to see the tx. When it does work, it usually takes like 5-10 seconds to show up after the tx is sent (which is probably because of mempool updates on the server).

I believe the client only queries the server once with the tx id of the new tx and writes it to the wallet file (that's by changing servers doesn't do anything). Pure theory: If it gets an negative answer for the new tx id or no answer at all (timeout) the tx won't show up in the client.  There might be a difference depending on whether the server is currently processing a new block (which keeps it from freshing the memory pool) or how long memory pool updates take on the server for the tx query to either be answered negatively or to time out...

**Comment by badzso** [comment] 2016-04-13 19:10
[](url)

**Comment by ecdsa** [comment] 2017-07-03 09:14
closing: probably not relevant anymore

**Closed by ecdsa** 2017-07-03 09:14 UTC

**Comment by casper** [comment] 2017-08-02 12:47
This just happened to me on 2.8.3. Seems it is still be an open bug. Waited 15 minutes, two confirmations. Still nothing. Close Electrum + restart, and the transaction shows up after "Synchronizing" is done in the status bar.
