### ISSUE TITLE
Persisting 'window permanent in background' bug on OS X, ever since Electrum-2.5.1

### ISSUE THREAD

**Issue by zanglebert** [spesmilo/electrum#1497] opened 2015-10-18 20:02 UTC
Electrum-2.5.1
OS X 10.11

Two problems, perhaps related:

(1) New windows opened inside Electrum (e.g. "Details" of a transaction in history, "Sign/Broadcast" in Send) don't open in the foreground anymore.

(2) After opening a new window (i.e. (1) above), after cmd-tabbing away from Electrum, I cannot cmd-tab back to Electrum. To go back to Electrum, I need to use Dock or Mission control.

Note: After going back to Electrum as described in (2), the newly opened window (details, sign tx) is in the foreground now, and can be used e.g. to sign a tx.

**Comment by kyuupichan** [comment] 2015-10-19 03:39
I can reproduce this.  Unfortunately I don't have a dev env setup on my Mac; I will try to get that working.

**Comment by kyuupichan** [comment] 2015-10-24 14:00
I can reproduce this running the binary from electrum.org.  However it does not happen, and works correctly, when running from source (which I finally managed to get working).  So this appears to be something to do with the packaging on the official site....

**Comment by kyuupichan** [comment] 2015-11-07 08:55
I've just upgraded to El Capitan, and this still happens with the official binary.  I notice however that when opening e.g. the tx details window, and it doesn't appear, that clicking on the dock icon causes it to appear, and then the issue no longer occurs for that session.  I have no idea what is causing this.

**Comment by kriznik** [comment] 2015-12-13 16:35
same problem here, even if I'm trying to close that window (eg. tx, second wallet) it is still on desktop. Hitting cmd+o brings up open dialog and also "closes" that already closed window. But weirdly sometimes it is working normally.

I was trying few scenarios, and it looks like that it never working when you open electrum and immediately open for example tx detail.
On the other hand, if you open electrum and if you switch focus to another window (eg. safari) and then bring back electrum then it is working like normal, details windows, open wallets, closing, everything is working.

So issue should be related somehow on focus after start or something like that.
Hopefully it helps.

**Comment by skaht** [comment] 2015-12-14 04:58
Seem to run into the same problem giving [Encompass v0.6.0rc1](https://github.com/mazaclub/encompass/releases/tag/v0.6.0rc1) a test drive on Yosemite. Encompass supports a number of altcoins that is built on top of Electrum with Trezor support.  Specifically, while trying to import import a few Dash, very well aware of sweeps being much safer.  (Saw [Encompass v0.6.0rc2](https://github.com/mazaclub/encompass/issues/150) is what is really supporting Trezor functionality.)  

Trying to build v0.6.0rc2 forced me down the path of trying to build Electrum from ```brew``` details (not using MacPorts) posted at [Build Electrum on Mac OS X](http://docs.electrum.org/en/latest/build.html#build-electrum-on-mac-os-x).  Ended up running down the rabbit hole of there being brew issues with [qt](https://github.com/Homebrew/homebrew/issues/46974#issuecomment-164329599) from a ```% brew install python pyqt``` package dependencies mentioned by Electrum. In short, building Electrum using brew seems to be on hold.

**Comment by kriznik** [comment] 2015-12-14 19:14
update: it's necessary to loose focus with window, which will completely overlay electrum window. Then when I bring back electrum it is working normally (details tx, closing etc.). 
If focus is on different program but electrum is still visible to your eyes, eg. it is not hidded under another window, it has mentioned bugs.

**Comment by zanglebert** [comment] 2016-02-14 21:46
Reporting back on this issue:

UI bug is still present as of Electrum version 2.5.4 on OSX.

Changing windows ("losing focus", as kriznik above described it) still is a valid work-around, but I'm wondering if there are any plans to look into an actual fix for the next release?

**Comment by kriznik** [comment] 2016-03-14 21:11
Hello, update
in electrum 2.6.2 for OSX is still this annoying bug in place :(

**Comment by tommcintyre** [comment] 2016-08-23 18:43
This is still present in 2.6.4, and after various OS reinstalls :/

**Comment by zanglebert** [comment] 2016-09-09 16:17
I updated the title, to be more clear about the topic/content of the bug, but also to mention how long it has been around.

Frankly, I would really appreciate at least some feedback from one of the regular contributors. Anything, from "it's being looked at", to "too low priority, deal with it". In either case, some acknowledgement would be nice, that the bug persists. 

And while it's not a showstopper admittedly, it does make using Electrum on OS X a lot less convenient, and might even scare off new users, since the trick/workaround described above, to "unhide"/bring back into focus the missing window by invoking Mission Control is perhaps not something *everyone* tries, so new users might just conclude the window (transaction, details, whatever) is entirely missing.

**Comment by ecdsa** [comment] 2016-10-06 10:38
@zanglebert it's been looked at

**Comment by ecdsa** [comment] 2017-03-09 18:24
this should be fixed in 2.8.0 builds.
please confirm.

**Closed by ecdsa** 2017-03-09 18:24 UTC
Labels: OSX

**Comment by zanglebert** [comment] 2017-03-21 16:14
Sorry for missing the notification earlier.

Just tried to reproduce the bug, but strangely I wasn't able to reproduce already in a previous version, 2.7.18. Was the relevant fix only applied now?

In any case, tested 2.8.1 as well, and cannot replicate it there either anymore. Previous windows that got stuck in the background (e.g. Transaction: Details , Send: Preview) are now correctly opened in  foreground, and switching between different Electrum windows by shortcut works as well.

Thanks!
