### ISSUE TITLE
After 1 month, I still unable to cosign transaction with Hardware wallet Safe-T (Linux+Mac)

### ISSUE THREAD

**Issue by passio777x** [spesmilo/electrum#5516] opened 2019-07-18 08:04 UTC
Hi everyone. I am feel really bad about this. I am unable to cosign transaction with Archos Safe-T and Electrum. I tryed on Lubuntu and on Mac OS X 10.14.5

I always got the sames error. I tryed to sign in many ways :
If i put my seed + my Archos safe-T on same Elecrum Wallet (I should be able to co-sign immediately with my Wallet Password + Safe-T confirmation. Wallet password works, not Safe-T confirmation.
I made a video -> https://www.youtube.com/watch?v=lVTAk6GquXI

Other case, I restore wallet with Hardware Public Master Key + a Seed, then I can "send for cosign"... But I got error: 

**[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)**

I also tried to export manually the .txt, but no way to sign it with archos Safe-T.... Same issues on Mac OS X and Linux for 1 month. I am even NOT ABLE to get back the bitcoin I sent on this wallet test.

Please, let me know if you can help. What should I do ? Use other hard wallet ? Use other software ?

**Comment by passio777x** [comment] 2019-07-18 22:28
Never in my whole life I have felt so alone in Forums.

**Comment by SomberNight** [comment] 2019-07-18 23:40
Please don't open multiple issues for the same problem.
Duplicate of https://github.com/spesmilo/electrum/issues/5446

**Closed by SomberNight** 2019-07-18 23:40 UTC

**Comment by passio777x** [comment] 2019-07-19 00:57
[electrum_log_20190719T005722Z_4164.log](https://github.com/spesmilo/electrum/files/3408936/electrum_log_20190719T005722Z_4164.log)

**Comment by passio777x** [comment] 2019-07-19 01:16
Log file of the Youtube video process issue : 
[electrum_log_20190719T011429Z_4412.log](https://github.com/spesmilo/electrum/files/3408970/electrum_log_20190719T011429Z_4412.log)
