### ISSUE TITLE
Segwit Transactions don t work

### ISSUE THREAD

**Issue by munichhilton** [spesmilo/electrum#3524] opened 2017-12-14 13:31 UTC
Hello, 

I am not sure:
I tried to send from a segwit wallet with Electrum 3.0.3:

https://btc.com/401252994e58436160940e60f5fb06c453b1b1d108d4bc645557bc9eea7e80d7
&
https://btc.com/731f6391b2395ee596a21d90d6ffbb1250a11b0bbeb3fd2027d809b6c89686a3

Never ever had this kind of problems with a normal wallet (same fees in the last days Electrum 3.0.2)

Is there something I can do or are my coins lost forever.

Any help is appreciated.

Regards

**Comment by AbdussamadA** [comment] 2017-12-14 13:43
The fee is too low. See here: https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do

And in future ask for help in the places listed [here](https://electrum.org/#community) and not on github.

**Comment by munichhilton** [comment] 2017-12-14 13:47
Thanks really sure about the fees ? I tried to bump the first trans. with the 2nd.

What will happen if they both are stuked ?

Regards

**Comment by dabura667** [comment] 2017-12-14 13:55
Currently your two transactions are dependant on each other, and the parent transaction is only 70 satoshis per byte.

Using CPFP, the two transactions combined are 231 satoshis per byte.

Currently there are about 1.5 MB of transactions above you... and it looks like the fees are moving downward.

I would say both transactions will confirm maybe within 30 minutes - 3 hours time.

**Comment by SomberNight** [comment] 2017-12-14 13:57
There is no bug here; closing.

**Closed by SomberNight** 2017-12-14 13:57 UTC

**Comment by munichhilton** [comment] 2017-12-14 14:01
Sorry I have messed up the transactions - so no bug - didn t know better.

Thanks for the help.

**Comment by dabura667** [comment] 2017-12-14 15:07
Just as a resolution:
49 minutes after my post your transactions were confirmed. My estimate was accurate.
