### ISSUE TITLE
my wallet is blocked what is happening?

### ISSUE THREAD

**Issue by popotin** [spesmilo/electrum#2006] opened 2016-10-26 19:52 UTC
Hello, can someone help me i've got a bug with my wallet.  It's connected but all my transactions are blocked.

Please help if possible.

**Comment by sup2X** [comment] 2016-10-27 00:20
https://bitcointalk.org/index.php?topic=1661792.100

**Comment by ecdsa** [comment] 2016-12-31 15:45
looks like an unconfirmed tx issue, closing

**Closed by ecdsa** 2016-12-31 15:45 UTC
