### ISSUE TITLE
IOError: Cannot read wallet file [Electrum 1.9.8]

### ISSUE THREAD

**Issue by grepface** [spesmilo/electrum#2743] opened 2017-08-13 11:25 UTC
Somehow it happend that my wallet file was corrupted.

I was using electrum long that's why version is so old.

Now I'd like to send bitcoins from wallet, but can't open it.

Normal wallet filetype is: ASCII text, with very long lines
But corrupted wallet is: data

Also I even can't open it in text editor due to encoding error.

**Comment by dabura667** [comment] 2017-08-13 11:47
iirc <2.0.0 wallets need to be converted to the new wallet file type, and this has broken a few times in the past.

If your labels are super important, please await further assistance, if not, please use your old 12 word phrase (pre-2.0.0) as they are still backwards compatible.

**Comment by grepface** [comment] 2017-08-13 11:48
unfortunately seed is lost

**Comment by dabura667** [comment] 2017-08-13 11:58
Try downloading 2.0 from the electrum download server (it's where the current downloads are stored)

https://download.electrum.org/2.0/

1. Make a copy of your backed up wallet file (in case it gets corrupted again)
2. Try opening the copy using 2.0.
3. If it opens fine, check the wallet file, it should be ASCII text, but in a different format than the original.
4. Open the new ASCII wallet file using the latest version.

**Comment by grepface** [comment] 2017-08-13 12:12
I made as you advised and got error message: Cannot read wallet file.

I guess there is something I should do with that wallet file. But what - I Dont Know.

**Comment by dabura667** [comment] 2017-08-13 12:18
#1085 Seems related.

Try 2.0.3 instead.

https://download.electrum.org/2.0.3/

**Comment by grepface** [comment] 2017-08-13 12:25
got same error

**Comment by dabura667** [comment] 2017-08-13 12:34
Just to check: you are trying to open the ASCII text wallet file from 1.9.8, correct?

One of the versions will properly convert your <2.0 wallet to a proper >=2.0 wallet file.

You could always just download the 1.9.8 client, open the wallet (don't use it to send money though) and click "Show seed" then enter your seed into the newest client.

https://download.electrum.org/1.9.8/

**Comment by grepface** [comment] 2017-08-13 12:35
$ file -bi default_wallet
application/octet-stream; charset=binary

That file is corrupted and not ASCII, but binary. That somehow happend in Electrum 1.9.8.
I've tried this version to open file, but I guess it won't ever open

**Comment by ecdsa** [comment] 2017-08-13 17:50
@dabura667 if he cannot open the file in a text editor, then it means the file is corrupted; it is not caused by the wallet format.
@grepface did you save your seed? restoring from seed is probably the only option

**Comment by ecdsa** [comment] 2017-08-16 13:43
closing, no answer

**Closed by ecdsa** 2017-08-16 13:43 UTC
