### ISSUE TITLE
TypeError: bool object is not callable

### ISSUE THREAD

**Issue by PortDaveA** [spesmilo/electrum#8383] opened 2023-05-03 19:09 UTC
I got the following error on my android electrum app. I don't have the pass phrase keys for this particular wallet. It
is a two factor authenticated wallet. I got this error after entering my two factor authentication code while trying to send
my bitcoin to another wallet. 

What can I do? Is there anyway to role back this version? Would it fix the issue? 

Traceback (most recent call last):

File "/home/user/wspace/

electrum/.buildozer/android/app/ electrum/ util.py", line 1224, in run_with_excep t_hook

File "/home/user/wspace/ electrum/.buildozer/android/platform/ build-arm64-v8a/build/python-installs/ Electrum/jnius/

_init__.py", line 84, in jnius_thread _hook

File "/home/user/wspace/ electrum/.buildozer/android/platform/ build-arm64-v8a/build/other_builds/ python3/arm64-v8a_ndk_target_21/ python3/Lib/

electrum/.buildozer/android/app/ electrum/gui/qml/

threading.py", line 870, in run File "/home/user/wspace/ qewallet.py", line 553, in submit_otp_ task

File "/home/user/wspace/ electrum/.buildozer/android/app/ electrum/plugins/trustedcoin/ qml.py", line 425, in on_otp

File "/home/user/wspace/ electrum/.buildozer/android/app/

electrum/gui/qml/ qewallet.py", line 537, in on_sign_com plete TypeError: bool object is not callable

**Comment by accumulator** [comment] 2023-05-03 19:15
duplicate of #8368

**Closed by accumulator** 2023-05-03 19:15 UTC
