### ISSUE TITLE
the wrong balance

### ISSUE THREAD

**Issue by bo761** [spesmilo/electrum#4248] opened 2018-04-10 08:42 UTC
![2018-04-09 17-23-28](https://user-images.githubusercontent.com/38181469/38546004-fbe19ed6-3c9a-11e8-8f12-97b901e172cd.png)

**Comment by SomberNight** [comment] 2018-04-10 08:46
dupe of:
https://github.com/spesmilo/electrum/issues/4243
https://github.com/spesmilo/electrum/issues/4244
https://github.com/spesmilo/electrum/issues/4245

Please refrain from opening any more issues regarding this.
You need to update Electrum. That is an old version. We have already told you this.

**Closed by SomberNight** 2018-04-10 08:46 UTC

**Comment by bo761** [comment] 2018-04-10 08:51
well I'll update - if I finally lose money you will compensate the damage

**Comment by SomberNight** [comment] 2018-04-10 08:57
This is an open source project. 
https://github.com/spesmilo/electrum/blob/305843999eabdb4276109e3dc6b70bf21dbbc29a/LICENCE#L14-L20

Please make sure you have a backup of your seed words; again, as I've already said.

**Comment by bo761** [comment] 2018-04-10 09:01
of course there is how can I updated
