### ISSUE TITLE
Python Console - time.sleep(n) causes client to hang for n duration

### ISSUE THREAD

**Issue by breakfixrepeat** [spesmilo/electrum#5018] opened 2019-01-20 22:46 UTC
Discovered this behavior while playing with a script I ran from within the electrum console gui that periodically checks for unspent funds.

import time

def hang(n):
        print('Electrum will hang for %d seconds', %n)
        time.sleep(n)
        print('Electrum is now responsive to input again')

hang(10)

**Comment by SomberNight** [comment] 2019-01-20 23:18
You can create a thread yourself and run your custom code in that.

The code in the console runs in the GUI thread. One advantage of this is that you can interact with GUI elements from the console.
If you sleep in the GUI thread, the GUI will hang. No surprise there.

**Comment by breakfixrepeat** [comment] 2019-01-20 23:38
Shouldn't the console and any code runs in it run in their own independent sub-processes anyway?

I'd say this behavior is unusual given that IDLE or any other console-like program wouldn't cause the main thread to wait so as to cause the entire GUI to hang.

**Comment by SomberNight** [comment] 2019-01-21 00:14
One use case for the console is to debug Electrum itself, which would not be possible if the code ran in another process.

**Comment by SomberNight** [comment] 2019-01-21 16:42
Closing; "it's not a bug, it's a feature"

**Closed by SomberNight** 2019-01-21 16:42 UTC
Labels: Qt
