### ISSUE TITLE
Accessibility with a screen reader

### ISSUE THREAD

**Issue by pzajda** [spesmilo/electrum#1643] opened 2016-01-23 18:35 UTC
Hi,

I would like to use Electrum, because it is the simplest wallet to migrate from Bitcoin QT.
I'm blind, and use NVDA as screen reader.

At this time, Electrum is unusable by screen reader users.
I can only confirm that under Windows.
I know QT has accessibility support especially in QT 5. Before that version, accessibility has to be set because it was not automatically enabled.
Would it be possible to make Electrum accessible please?

**Comment by kyuupichan** [comment] 2016-01-24 11:17
Closing as duplicate of https://github.com/spesmilo/electrum/issues/1036

**Closed by kyuupichan** 2016-01-24 11:17 UTC
Labels: duplicate
