### ISSUE TITLE
Electrum 3.1 conversion from NoneType to Decimal is not supported

### ISSUE THREAD

**Issue by goodProjects** [spesmilo/electrum#3944] opened 2018-02-21 03:13 UTC
Python Version : Python 3.6.4 
OS: mac sierra 10.13.1

**python3 electrum --testnet**
```

Traceback (most recent call last):
  File "/Users/userName/Downloads/electrum-master/gui/qt/__init__.py", line 217, in start_new_window
    w = self.create_window_for_wallet(wallet)
  File "/Users/userName/Downloads/electrum-master/gui/qt/__init__.py", line 179, in create_window_for_wallet
    w = ElectrumWindow(self, wallet)
  File "/Users/userName/Downloads/electrum-master/gui/qt/main_window.py", line 201, in __init__
    self.load_wallet(wallet)
  File "/Users/userName/Downloads/electrum-master/lib/util.py", line 275, in <lambda>
    return lambda *args, **kw_args: do_profile(func, args, kw_args)
  File "/Users/userName/Downloads/electrum-master/lib/util.py", line 271, in do_profile
    o = func(*args, **kw_args)
  File "/Users/userName/Downloads/electrum-master/gui/qt/main_window.py", line 344, in load_wallet
    self.history_list.update()
  File "/Users/userName/Downloads/electrum-master/gui/qt/util.py", line 484, in update
    self.on_update()
  File "/Users/userName/Downloads/electrum-master/lib/util.py", line 275, in <lambda>
    return lambda *args, **kw_args: do_profile(func, args, kw_args)
  File "/Users/userName/Downloads/electrum-master/lib/util.py", line 271, in do_profile
    o = func(*args, **kw_args)
  File "/Users/userName/Downloads/electrum-master/gui/qt/history_list.py", line 202, in on_update
    r = self.wallet.get_full_history(domain=self.get_domain(), from_timestamp=self.start_timestamp, to_timestamp=self.end_timestamp, fx=fx)
  File "/Users/userName/Downloads/electrum-master/lib/util.py", line 275, in <lambda>
    return lambda *args, **kw_args: do_profile(func, args, kw_args)
  File "/Users/userName/Downloads/electrum-master/lib/util.py", line 271, in do_profile
    o = func(*args, **kw_args)
  File "/Users/userName/Downloads/electrum-master/lib/wallet.py", line 1044, in get_full_history
    summary['start_fiat_balance'] = Fiat(fx.historical_value(init_balance, start_date), fx.ccy)
  File "/Users/userName/Downloads/electrum-master/lib/exchange_rate.py", line 539, in historical_value
    return Decimal(satoshis) / COIN * Decimal(rate)
TypeError: conversion from NoneType to Decimal is not supported

```

**Comment by SomberNight** [comment] 2018-02-21 03:16
duplicate of https://github.com/spesmilo/electrum/issues/3939

**Closed by SomberNight** 2018-02-21 03:16 UTC
Labels: duplicate
