### ISSUE TITLE
Trezor Cosigner Wallet Setup Issue

### ISSUE THREAD

**Issue by Rspigler** [spesmilo/electrum#3573] opened 2017-12-20 21:22 UTC
I am trying to create a multisig setup where a trezor device is one of the cosigners (among other hardware devices).  During the very initial setup everything works fine, but at the end when Electrum asks for each device to be plugged in one more final time, I keep receiving the error 'Unexpected Magic Characters' for the Trezor device.  All other devices show up green while Trezor shows up red.

Appreciate any help!

Thanks for a great wallet and happy holidays to everyone

Robert

**Comment by bjmicai** [comment] 2017-12-26 02:36
I have the same problem, hope it would be fixed soon.

**Comment by bjmicai** [comment] 2017-12-26 02:37
trezor firmware version: 1.6
electrum version: 3.0.3

**Comment by Rspigler** [comment] 2017-12-26 03:03
Hi @bjmicai, thanks for the comment.  Realized I didn't post my software.  I am running the same system as you.

**Comment by bjmicai** [comment] 2017-12-26 03:30
Some debug info below:

python3 electrum
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
Traceback (most recent call last):
  File "/Users/micai/Electrum-3.0.3/gui/qt/util.py", line 587, in run
    result = task.task()
  File "/Users/micai/Electrum-3.0.3/plugins/trezor/plugin.py", line 133, in get_client
    client = devmgr.client_for_keystore(self, handler, keystore, force_pair)
  File "/Users/micai/Electrum-3.0.3/lib/plugins.py", line 403, in client_for_keystore
    info = self.select_device(plugin, handler, keystore, devices)
  File "/Users/micai/Electrum-3.0.3/lib/plugins.py", line 472, in select_device
    infos = self.unpaired_device_infos(handler, plugin, devices)
  File "/Users/micai/Electrum-3.0.3/lib/plugins.py", line 461, in unpaired_device_infos
    client = self.create_client(device, handler, plugin)
  File "/Users/micai/Electrum-3.0.3/lib/plugins.py", line 342, in create_client
    client = plugin.create_client(device, handler)
  File "/Users/micai/Electrum-3.0.3/plugins/trezor/plugin.py", line 110, in create_client
    client = self.client_class(transport, handler, self)
  File "/Users/micai/Electrum-3.0.3/plugins/trezor/client.py", line 7, in __init__
    ProtocolMixin.__init__(self, transport)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 451, in __init__
    self.init_device()
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 458, in init_device
    self.features = expect(proto.Features)(self.call)(proto.Initialize())
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 144, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 158, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 196, in call
    resp = self.call_raw(msg)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 158, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 192, in call_raw
    return self.transport.read_blocking()
  File "/usr/local/lib/python3.6/site-packages/trezorlib/transport.py", line 89, in read_blocking
    data = self._read()
  File "/usr/local/lib/python3.6/site-packages/trezorlib/transport.py", line 150, in _read
    (msg_type, datalen, data) = self.parse_first(chunk)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/transport.py", line 162, in parse_first
    raise Exception("Unexpected magic characters")
Exception: Unexpected magic characters

**Comment by SomberNight** [comment] 2017-12-26 04:36
Does it also happen in a standard (non-multisig) wallet with Trezor?

Is this a duplicate of https://github.com/spesmilo/electrum/issues/3131 ?

> but at the end when Electrum asks for each device to be plugged in one more final time

What do you mean by this? Is this when the wallet is fully created, so when you see the main window, and not the wizard?

**Comment by bjmicai** [comment] 2017-12-26 06:32
Both standard and multisig wallet with Trezor has the same problem. After a wallet is created, and then unplug -> plug Trezor, the error shows up. Not sure if it's a duplicate of #3131.
I checked lots of referenced tickets, they points to hidapi library, I checked the one on my MaxOS, the version is:

`hidapi==0.7.99.post21`

and the result of hid.enumerate() shows: 

 ```
{'interface_number': -1,
  'manufacturer_string': 'SatoshiLabs',
  'path': b'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/X'
          b'HC1@14000000/HS01@14100000/TREZOR@14100000/U2F Interface@1/IOUSB'
          b'HostHIDDevice@14100000,1',
  'product_id': 1,
  'product_string': 'TREZOR',
  'release_number': 256,
  'serial_number': 'BC09496F56F8BBD1CC14C0CB',
  'usage': 1,
  'usage_page': 61904,
  'vendor_id': 21324},
 {'interface_number': -1,
  'manufacturer_string': 'SatoshiLabs',
  'path': b'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/X'
          b'HC1@14000000/HS01@14100000/TREZOR@14100000/TREZOR Interface@0/IO'
          b'USBHostHIDDevice@14100000,0',
  'product_id': 1,
  'product_string': 'TREZOR',
  'release_number': 256,
  'serial_number': 'BC09496F56F8BBD1CC14C0CB',
  'usage': 1,
  'usage_page': 65280,
  'vendor_id': 21324},
```

Seems hidapi is not the cause.

**Comment by bjmicai** [comment] 2017-12-26 06:34
By the way, what's the difference between trezor-agent and python-trezor, do I need to install both of them?

**Comment by SomberNight** [comment] 2018-05-09 12:13
Is this problem still present on current master?

**Comment by SomberNight** [comment] 2018-08-03 18:04
I think this might have been fixed when we started using the enumeration methods from python-trezor

**Closed by SomberNight** 2018-08-03 18:04 UTC
Labels: awaiting-response, bug, hw-trezor
