### ISSUE TITLE
Segwit fees are set wrong

### ISSUE THREAD

**Issue by Dreamsorcerer** [spesmilo/electrum#3372] opened 2017-11-24 21:48 UTC
Tested on 3.0, but can't see anything in the release notes/issues that suggest it has been reported and fixed already.

I created a segwit transaction at 100 sat/byte, then looking at the transaction details it says it is 82 sat/byte. This appears to be because the fee estimate was based on the actual transaction size (ignoring witness) of 116 bytes, while the transaction details must use the virtual size of 143.25 bytes.

This obviously results in transactions with fees too low.

**Comment by SomberNight** [comment] 2017-11-24 22:03
Duplicate of #3347
Will be fixed in next minor release.

**Closed** 2017-11-25 16:21 UTC
