### ISSUE TITLE
Recovered seed (BIP39) generates unspendable addresses

### ISSUE THREAD

**Issue by MrTschi** [spesmilo/electrum#4891] opened 2018-12-01 12:51 UTC
Hi,

I generated a new walled with CoPay (iOS App) and noted down the BIP39 recovery seed.
With this seed I restored my brand new wallet in electrum 3.2.3 with "legacy addresses" selected.
After that, I checked the master public key of both apps and they are identically.
I generated a new address within electrum and moved all my funds to this address.
The payment arrived and is visible in my electrum wallet.
Switching to CoPay app, there is no transaction within this wallet, so I wanted to move funds back to bitstamp.net but when I'm trying to send a transaction within electrum I get the following error:
`

error: {'code': 1, 'message': 'the transaction was rejected by network rules.\n\nmandatory-script-verify-flag-failed (Script failed an OP_EQUALVERIFY operation) (code 16)\n[0100000002436331a829f208723d53091b7b8b06a4277d00c156e34ead9c154f9514241cd9000000006a47304402204e4d1c687f83be1480119e5fa347b482296ce4d2fb042852eacbdee4b91ba1fa02206500d4b4dcf836acc8d924a4b2073eb0362440a7b4908b4b2ff841026beeebf60121037eb62028b4b773e957fedb6e8375154e7c70b40d84ea6df79a87e610b0d9ec45feffffff511ec4751c1098e171117ccb6634f7747b51cdfdad71965ef6e07c1097cda2f1160000006a4730440220153a0f5d59b7fdf66cc7dcf1e08cb845a6d8188aadedc11e75096632e6834ae202200a3e3d36f01ec2998489d0bb5fd16e6864fced292d80e7bf8250fc0fa7125a500121037eb62028b4b773e957fedb6e8375154e7c70b40d84ea6df79a87e610b0d9ec45feffffff012e049e040000000017a9148482620e9cbe2f35624e72c91718d71e5718fc5587d66c0800]'}`

I tried to re-import the wallet within electrum using my seed, but after that the newly imported wallet does not have any transactions.

What happened here? Is it possible to recover my funds?

Thanks,
Max

**Comment by MrTschi** [comment] 2018-12-01 13:03
I tried the following without success:

- Exported the bitcoin address private keys out of my wallet where the funds get displayed
- New / restore wallet
- Import Bitcoin addresses / private keys
- Entered the private key "p2pkh:K......z"
- Finished importing
- Imported wallet have a different address than in the original wallet
-- Address which has the funds: 15hfPj8aR2vsFTw34zFkiCxbAhdxWAvcJZ
-- Imported private key results in address: 1LZk9Zz9n6KugSScNsGc8FiRrt27f5GgNR

Dont know how to get my funds back :/

Has this something to do with a wrong address derivation path somewhere?

**Comment by dabura667** [comment] 2018-12-01 13:44
copay won't see it until you click "generate new address" a few times and show the address.

**Comment by MrTschi** [comment] 2018-12-01 13:50
Thanks for your reply @dabura667 !

> copay won't see it until you click "generate new address" a few times and show the address.
Tried this, copay stated "checking wallet for new balances" but I still have a zero-balance
Also cleared transaction cache without success

> if you got the same xpub you should be fine
xpub is identically, yes.

> but in general mixing multiple wallet software because "BIP39 should be compatible" is usually a bad idea
OK did not know this.

Any other idea?

**Comment by dabura667** [comment] 2018-12-01 14:41
How many times did you tap the circular arrow next to your Copay address? (Below the QR code on the right)

Try tapping it 19 times.

**Comment by AbdussamadA** [comment] 2018-12-01 14:49
can you check your browser history and tell us where you downloaded electrum from?

**Comment by AbdussamadA** [comment] 2018-12-01 14:53
also is that ismine check on the console of the wallet with the imported private keys or the bip39 restored wallet?

**Comment by MrTschi** [comment] 2018-12-01 15:06
> can you check your browser history and tell us where you downloaded electrum from?

From the official electrum website, im going to create a checksum later to ensure integrety

> also is that ismine check on the console of the wallet with the imported private keys or the bip39 restored wallet?

check was of the bip restored wallet

> Try tapping it 19 times.

Balance still zero ..

> you know you can just dump that address' private key

I exported it through the GUI and imported it ending up with a zero balance

**Comment by AbdussamadA** [comment] 2018-12-01 15:12
You can see a list of all your addresses on the addresses tab. View menu > show addresses if you can't see that. You can also search the list with ctrl+f. Make sure the address in question is there in the latest wallet you created (the one with the single imported private key). 

Also what color orb icon do you see in the bottom right?

**Comment by AbdussamadA** [comment] 2018-12-01 15:13
oh and can you confirm the download url from the browser history?

**Comment by SomberNight** [comment] 2018-12-01 17:01
- What OS?

- > can you confirm the download url from the browser history?

- > im going to create a checksum later to ensure integrety

    please share full filename along with checksum

**Comment by MrTschi** [comment] 2018-12-01 19:35
OS: MacOS 10.13.6

I've tried the following steps:

- `getprivatekeys("15hfPj8aR2vsFTw34zFkiCxbAhdxWAvcJZ")`
- Used this private key to create a new electrum wallet
- Evaluated this command in the console of the "private key only" wallet
```
>> ismine("15hfPj8aR2vsFTw34zFkiCxbAhdxWAvcJZ")
false
```
- "Addresses" tab does only show this address: 1LZk9Zz9n6KugSScNsGc8FiRrt27f5GgNR

Regarding the Checksum: I do not have the dmg anymore as I have electron installed for a longer time but I'm sure that I've downloaded it from electrum.org

**Comment by MrTschi** [comment] 2018-12-02 10:09
@AbdussamadA 
> Also what color orb icon do you see in the bottom right?

It is green, clicking on it states connected to 10 nodes.

## Checksum
@AbdussamadA 
> can you check your browser history and tell us where you downloaded electrum from?

Its not in the browser history anymore but I think due to the checksums below this might be the proof for the official app.

@SomberNight I found a way to generate the requested checksum:

The Mac-App "Electrum.app" (folder located in /Applications) does have only a few files:
- MD5 (/Applications/Electrum.app/Contents/MacOS/Electrum) = 270e8e32a8d91f25daa36382b1f4c722
- MD5 (/Applications/Electrum.app/Contents/Resources/electrum.icns) = 2b8025b601932267d73f0575fbaa300e
- MD5 (/Applications/Electrum.app/Contents/Info.plist) = 6d327e2b41e3919d53b14a0a68141778

Now checking against official 3.2.3 of electrum: 
- https://download.electrum.org/3.2.3/electrum-3.2.3.dmg
- Mounted dmg and copied Electrum.app folder to ~/Downloads
- MD5 (/Users/max/Downloads/Electrum.app/Contents/MacOS/Electrum) = 270e8e32a8d91f25daa36382b1f4c722
- MD5 (/Users/max/Downloads/Electrum.app/Contents/Resources/electrum.icns) = 2b8025b601932267d73f0575fbaa300e
- MD5 (/Users/max/Downloads/Electrum.app/Contents/Info.plist) = 6d327e2b41e3919d53b14a0a68141778

I used md5 system command in terminal to generate checksums (md5 <file>).

## Comparing wallet-xpub / addresses in different recovery scenarios:
ℹ️ All wallets below were created/recovered using the same BIP39 seed

### Wallet 1: wallet which has the unspendable address
![image](https://user-images.githubusercontent.com/9491895/49338441-54b06480-f621-11e8-831a-06cb7bdfa412.png)
- Wallet-XPub
```
xpub6CJsJ1bjs7RwDx1jBmfSkqHfkQJvxgdLaiJsaqoR5qn2WeoXrweNc6NNNHyqijX163MG4ShyuhE4UqLRTyFRUsWwgr5i1aG9rLJpQ8P6HJb
```
- Wallet master private
```
>> getmasterprivate()
"xpr...pM2"
```
- The affected address which has the funds
```
>> ismine("15hfPj8aR2vsFTw34zFkiCxbAhdxWAvcJZ")
true
```
- Retrieve address private key
```
>> getprivatekeys("15hfPj8aR2vsFTw34zFkiCxbAhdxWAvcJZ")
"p2pkh:KzL...iKz"
```
- Various address of wallet 2 (below) having no funds
```
>> ismine("14zrCTTKYVYZ7A4EUwu7w53u9WLwLENuqu")
false
```

### Wallet 2: Default derivation path m/44'/0'/0'
![image](https://user-images.githubusercontent.com/9491895/49338454-87f2f380-f621-11e8-8919-08f5e4489892.png)
- Wallet-XPub
```
xpub6CJsJ1bjs7RwDx1jBmfSkqHfkQJvxgdLaiJsaqoR5qn2WeoXrweNc6NNNHyqijX163MG4ShyuhE4UqLRTyFRUsWwgr5i1aG9rLJpQ8P6HJb
```
➡️ Its the same as of wallet 1
- Wallet master private
```
>> getmasterprivate()
"xpr...pM2"
```
➡️ Its the same as of wallet 1
- The affected address which has the funds
```
>> ismine("15hfPj8aR2vsFTw34zFkiCxbAhdxWAvcJZ")
false
```
- Retrieved private key for the first address item in "addresses" list
```
>> getprivatekeys("1LZk9Zz9n6KugSScNsGc8FiRrt27f5GgNR")
"p2pkh:KzL...iKz"
```
⚠️ This private key is identically to the private key of wallet 1's address 15hfPj8aR2vsFTw34zFkiCxbAhdxWAvcJZ but has a different public address
- Test another various address of wallet 1
```
>> ismine("1N4xPoWJjAnseBfJeMRkBRARwVpSdSddGm")
false
```

### Wallet 3: Same steps and config as wallet 2 to see if it will result in same behavior when recovering multiple times
![image](https://user-images.githubusercontent.com/9491895/49338473-c5578100-f621-11e8-9ce3-3f59649b2e5e.png)
- Wallet-XPub
```
xpub6CJsJ1bjs7RwDx1jBmfSkqHfkQJvxgdLaiJsaqoR5qn2WeoXrweNc6NNNHyqijX163MG4ShyuhE4UqLRTyFRUsWwgr5i1aG9rLJpQ8P6HJb
```
- Wallet master private
```
>> getmasterprivate()
"xpr...pM2"
```
- Check first item of wallet 2 "addresses" list
```
>> ismine("1LZk9Zz9n6KugSScNsGc8FiRrt27f5GgNR")
true
```
- Retrieve private key for this address
```
>> getprivatekeys("1LZk9Zz9n6KugSScNsGc8FiRrt27f5GgNR")
"p2pkh:KzL...iKz"
```
➡️ Same behavior as wallet 2

### Wallet 4: Different derivation path: m/49'/0'/0'
![image](https://user-images.githubusercontent.com/9491895/49338482-d99b7e00-f621-11e8-8795-c15020a95f44.png)
- Wallet-XPub
```
xpub6Bxtfz2Sx9GDJzBNN34mGgP31bR6S9DRi9LxiWqys48AyUpLaumhuJKKT6Lok1ZawzASsaXSHGMvcV76D4eAGxUpryYXYyu5yqjDAmnhWrw
```
The public key is different to wallet 1 and 2
- Wallet master private
```
>> getmasterprivate()
"xprv...xk8"
```
➡️ Is different to wallet 1,2+3
- Exported addresses with private keys
Neither an addresses nor a private key equals to wallet 1 or 2. So I think the default derivation path is correct as other derivation paths end up in different wallet xpub keys

----

## Conclusion
So the the question I'm asking me is what happend that electrum generated a different public address (15hfPj8aR2vsFTw34zFkiCxbAhdxWAvcJZ and 1LZk9Zz9n6KugSScNsGc8FiRrt27f5GgNR) for the identical key-pairs (wallet-keypair & address private key)?

**Comment by SomberNight** [comment] 2018-12-02 16:12
When you created the original wallet file that had the incorrect address, did you enable full wallet file encryption? It's a checkbox in the password dialog.

**Comment by MrTschi** [comment] 2018-12-02 17:18
@SomberNight
> When you created the original wallet file that had the incorrect address, did you enable full wallet file encryption?

Yes first wallet is fully encrypted with a password

> if you do, the file on disk is a text file with base64 encoded ciphertext

Yes this is the case

**Comment by AbdussamadA** [comment] 2018-12-03 10:46
This is like the 5th or 6th incident of what looks like malware modifying addresses in electrum wallets. Another recent one was reported on [reddit](https://www.reddit.com/r/Electrum/comments/a19k47/4000_lost_in_electrum_imported_address_wallet/). 

There was another reported [here](https://github.com/spesmilo/electrum/issues/4462) on github. This person was using portable version on Windows.

The one @MrTschi posted above is by a user Hexacolyte and he made a number of threads including [one](https://bitcointalk.org/index.php?topic=4992211.0) on the forum. Over there he says he used the portable version so he was on Windows and not MacOSx. What sort of malware targets different operating systems?

**Comment by AbdussamadA** [comment] 2018-12-03 11:33
What browser are you using and did you install any crypto related extensions/add ons at the time of creating your original wallet?

**Comment by MrTschi** [comment] 2018-12-03 11:50
@AbdussamadA
> What browser are you using 

Latest Safari

> did you install any crypto related extensions/add ons at the time of creating your original wallet?

No, only have AdBlockPlus Safari Extension from the Mac AppStore. 

I‘m a software developer so I think I usually know what I‘m doing ;)
I think if it would be a malware the issue would not appear once. I couldnt reproduce this so far...

**Comment by SomberNight** [comment] 2018-12-03 14:14
Can you confirm that
- wallet1 and wallet2 have the same xpub
- wallet1 and wallet2 have NO addresses in common

**Comment by SomberNight** [comment] 2018-12-03 14:33
Make a copy/backup of the wallet file for wallet1 (and for wallet2) if you haven't already.

Then open both wallets, go to the `Console` tab (`View`>`Show Console`), and generate two new addresses:
```
wallet.create_new_address(False)
wallet.create_new_address(False)
```

Make new screenshots for wallet1 and wallet2 in  the `Addresses` tab that show the newly generated addresses (these should be the last "receiving" addresses, probably colored in red).

**Comment by MrTschi** [comment] 2018-12-03 18:16
@SomberNight 
> Can you confirm that wallet1 and wallet2 have the same xpub

Yes they are identically (as described here: https://github.com/spesmilo/electrum/issues/4891#issuecomment-443495955)

> Can you confirm that wallet1 and wallet2 have NO addresses in common
(please also check change addresses)

Wallet1 has 1 more address than wallet2, i could image that this is because 1 address has funds so electrum had generated a new one after I had send my bitcoins to the wallet..
```
$ git diff wallet1 wallet2
diff --git a/wallet1 b/wallet2
index 56b2e66..cdc551d 100644
--- a/wallet1
+++ b/wallet2
@@ -1,27 +1,26 @@
-15hfPj8aR2vsFTw34zFkiCxbAhdxWAvcJZ
-1L9wPcsuMe9b1oNsXE7z6wT8aLpgAHRSZL
-171sTWx8WKGaekSRteP8hJaNVu4xeAyWa7
-1Pu7dgQ551oMDZGLAHdQhvL65a66gMfkjG
-1PVZjm5w48thHwxsrDWCXoAYrKtUfAXgrw
-1DKxC2xmRityzt3ASYG3GPff3Uh2Qv2N2X
-1GK2b2GbZMjyJ2iW88dCX1rQgN4Z4tVT8k
-18WHGXUHdBHNKQ5HBYDGzzsDcBhSHEnn9e
-18u1gNBwV38v3fzq1rT9GPSWAxAZ71Rv3r
-1Gwe61JKNsfi9VsFC1dQ9E3rEUfz8cxp9t
-1N4xPoWJjAnseBfJeMRkBRARwVpSdSddGm
-16VSZ8GFeJP4cL7aWhr3EJ2FDD8Ds9LeTK
-1ETrtGNh7JvUeqFVME68qNaFZN25YF64XA
-1GymPCz7ujhWDBBhFGsBAMEBfSjGDsUKnc
-1M67eopB3s1PZsd5k9E3vigKcZnwJzJrpB
-1MnN4tAA6wgvjL4Z4dYkQdx6Jox63sV16x
-17P5DykzEy8pQ4MgDtGaVn4AEBs7FciBWF
-1Pcg8cxPS4eueBRcLd2eG9dDCt3cxpkNnn
-1E6twzkSxfqPrDE4azLWZpj5gAFecZGkYZ
-1NayCpZf2D6iprVxyNp9PHHU2cWDBmw1DP
-1GkfX5HQV7jCmZrvvEru8dmWiPova1riWx
-14jzwvRncPhTZ9MbtmixPxEur5mn3Ciprj
-1Jn3qyLo2oC3wWeXkbgoRXBKeN23cUEr6v
-12GdaQUeCVPHgQixThfC7UhWa1XTSRxfih
-16e4kKn2aFRBycomxmdEeX5SsBNYpnca45
-1PmDz6bLcNayAe9vG8i9UiLwsS8r5edJyx
-1E7Yg6TCEEttVfqBzb6nZCjDuDDfPBTGak
+1LZk9Zz9n6KugSScNsGc8FiRrt27f5GgNR
+1A3Hh48pd6aU1zchitKiFTQTbCB9pyJrnM
+1M78FMyD7GKrjewwFwjcZrHNB9yDTvtR7k
+1SA1aVMLq2REcJBZuTc1GsHhfvg8tYmCQ
+1HvjXrsysUwb6WntMgdhjk9WuAVYQ7tPUj
+18FHak86uKQzn2U8agkQJEngnQ6hbB9FiX
+18S8VdMuVcDEkqNMhZQc9WqbW9ATGsiaPX
+14zrCTTKYVYZ7A4EUwu7w53u9WLwLENuqu
+1JcgAoPBJNMUpHXFy83tS5PZjUUucat5Zt
+17fu5qudFsicigR44dUJxEjr79po4eZk4r
+17J9AJtFWeZdFedfkPbwub9sph6SwYN2G7
+1HwTFGvW8uADsLCjwpZmRRaDRuo86XDNMp
+19PpVQNjq6fRTZpdtKQZqKCJXCctj9wRz9
+1DstAyMNMPGcNwG43qcgn5jv7EJXTsPiqR
+1LAaaBqG7Gg8myV8cPubzszNB2BsVA4whS
+1JevoDdweNZuh2hdsM2UC7qc4GdavHLWn4
+1GcgpbYmNwdDVhM8hjLeDYuPwzEkZCSvGr
+1G1GgThSdTcfv33SRyVKEejJw2oqqRmLfw
+13fXWbqBfzLCmX89t7MvxPWATGbYbugNhd
+1hTkY4AJmb3yR2VYsFZPyqpeexFVrTAQQ
+1HbdEBiM5gEsqR2WEZErmieKtuZ3kLRuwu
+1NNGiYLyj633jQtKukZzyUwJUUGpUT9PPk
+1PTY9AVu4uUxXaKWajihDsQfKWuYwqFqdg
+1Cqt1L5zKmFkVi7RZzpS6uXc4RwHZN3N6
+1FwFxvgVp255uYbF5V4x1224LbkNY4iQH3
+1H3tfG1GRAwftwN6KjQJRJ7VhcsJoTWxWP
```
➡️ All addresses (including change addresses) are different

----
Answer to post https://github.com/spesmilo/electrum/issues/4891#issuecomment-443730076:

### wallet1
```
>> wallet.create_new_address(False)
'1PQzdaMMiCmKGQFA2g3X3wH9qCUQvhxPx7'
>> wallet.create_new_address(False)
'18kBPVeFUPf4emiNhfF6VacrmjzRedfBcc'
```

### wallet2
```
>> wallet.create_new_address(False)
'1GkfX5HQV7jCmZrvvEru8dmWiPova1riWx'
>> wallet.create_new_address(False)
'1PQzdaMMiCmKGQFA2g3X3wH9qCUQvhxPx7'
```

### Screenshot
I scrolled completely to the bottom:

![image](https://user-images.githubusercontent.com/9491895/49392586-2b7dfa00-f72f-11e8-877b-1776b1a3763f.png)

➡️ Address 1GkfX5HQV7jCmZrvvEru8dmWiPova1riWx is now present in both wallets

**Comment by SomberNight** [comment] 2018-12-03 18:36
So all the initially generated addresses seem to be incorrect (not from xpub), but newly generated addresses are derived from xpub.

**Comment by MrTschi** [comment] 2018-12-03 18:46
# To sum things up:
- It could not have been changed from the outside (other than electrum) as the wallet file was encrypted
- The checksum of the binary matches the distributed version (3.2.3) from the official website
- Public addresses which were generated directly after seed recovery were wrong but the keys are correct
- Trying many different restore scenarios I wouldn't be able to reproduce the issue

---

As I didn't know how it is implemented: Could this be a race condition (e.g. shared variables)? That moment when I recover a wallet, at least one wallet must be open. If I close the last open wallet, the whole program exits.

**Comment by MrTschi** [comment] 2018-12-03 19:36
When and how are the address' private keys beeing generated in code?

**Comment by SomberNight** [comment] 2018-12-03 20:04
Private keys are basically not interesting for this issue.
- user enters bip39 seed
- calculate bip32 root seed
- set keystore.xprv based on bip32 root seed
- set keystore.xpub based on keystore.xprv
- from keystore.xpub, calculate individual pubkeys, from which calculate addresses
- store xprv, xpub, and list of addresses into wallet
- pubkey and privkeys can be recalculated on demand from xpub and xprv and position of address in list

-----

Wallet creation goes as below.

Create keystore.
https://github.com/spesmilo/electrum/blob/e9f18883211cf823815580df9dfa8ac254ab43f7/electrum/base_wizard.py#L410-L412
https://github.com/spesmilo/electrum/blob/e9f18883211cf823815580df9dfa8ac254ab43f7/electrum/keystore.py#L592-L598

Set xprv and xpub.
https://github.com/spesmilo/electrum/blob/e9f18883211cf823815580df9dfa8ac254ab43f7/electrum/keystore.py#L321-L328
https://github.com/spesmilo/electrum/blob/e9f18883211cf823815580df9dfa8ac254ab43f7/electrum/base_wizard.py#L424-L425
https://github.com/spesmilo/electrum/blob/e9f18883211cf823815580df9dfa8ac254ab43f7/electrum/base_wizard.py#L478-L485

Dump keystore into wallet storage.
https://github.com/spesmilo/electrum/blob/e9f18883211cf823815580df9dfa8ac254ab43f7/electrum/base_wizard.py#L495-L500
https://github.com/spesmilo/electrum/blob/e9f18883211cf823815580df9dfa8ac254ab43f7/electrum/keystore.py#L289-L294

Generate addresses, save them into wallet storage, and write wallet storage to disk.
https://github.com/spesmilo/electrum/blob/e9f18883211cf823815580df9dfa8ac254ab43f7/electrum/base_wizard.py#L566-L572


-----

Addresses are generated as below.

https://github.com/spesmilo/electrum/blob/e9f18883211cf823815580df9dfa8ac254ab43f7/electrum/wallet.py#L1455-L1458
https://github.com/spesmilo/electrum/blob/e9f18883211cf823815580df9dfa8ac254ab43f7/electrum/wallet.py#L1443-L1453
https://github.com/spesmilo/electrum/blob/e9f18883211cf823815580df9dfa8ac254ab43f7/electrum/wallet.py#L1427-L1441
https://github.com/spesmilo/electrum/blob/e9f18883211cf823815580df9dfa8ac254ab43f7/electrum/wallet.py#L1518-L1519
https://github.com/spesmilo/electrum/blob/e9f18883211cf823815580df9dfa8ac254ab43f7/electrum/keystore.py#L233-L241
https://github.com/spesmilo/electrum/blob/e9f18883211cf823815580df9dfa8ac254ab43f7/electrum/wallet.py#L1529-L1530
https://github.com/spesmilo/electrum/blob/e9f18883211cf823815580df9dfa8ac254ab43f7/electrum/bitcoin.py#L240-L249
https://github.com/spesmilo/electrum/blob/e9f18883211cf823815580df9dfa8ac254ab43f7/electrum/wallet.py#L212-L213

**Comment by AbdussamadA** [comment] 2018-12-03 21:32
@MrTschi
> I think if it would be a malware the issue would not appear once. I couldnt reproduce this so far...

Ah maybe the malware only cares about the default wallet file? How about you [find your wallets directory](http://docs.electrum.org/en/latest/faq.html#where-is-my-wallet-file-located) and make a backup copy of it. Then nuke the original and run electrum. Go through the process of creating a standard wallet making sure you write down the seed words. Then close electrum and restore from seed in a new wallet file. See if the addresses in the two wallets vary.

**Comment by ecdsa** [comment] 2018-12-04 05:29
> So all the initially generated addresses seem to be incorrect (not from xpub), but newly generated addresses are derived from xpub.

This suggests that keystore.xpub_receive was corrupted in memory during the initial address generation.
it is interesting to see that change addresses are different too. This suggests that the corruption hit keystore.xpub, before keystore.xpub_receive was generated.

Random memory corruption (a bit flip) could possibly corrupt the method that derives xpub_receive from xpub, because intermediate variables are not checksummed. However, such a scenario would only affect receiving addresses or change addresses, not both. Here it seems that keystore.xpub was corrupted. 
I do not think that random memory corruption could have done that, because xpubs are checksummed.

**Comment by MrTschi** [comment] 2018-12-04 06:30
@SomberNight thanks for picking the code snippets. Now I have a better understanding of what electrum does during recovery. 
@AbdussamadA 
> Ah maybe the malware only cares about the default wallet file?

I have no wallet called „default_wallet“. I have an older wallet file called „Max“ which is not fully encrypted. This one was my first BTC wallet (2017 till now) without facing any issues. 
At 1th of december I recovered a new wallet from seed as described. This wallet file is called „bitcoin“ but is now fully encrypted.

> Maybe open it with electrum once or twice and then compare the addresses to see if it any were injected by the malware.

As we figured out is that the bad addresses were only generated during wallet recovery. After I recovered the wallet, I clicked on „receive“ and send my BTC to this address without restarting electrum. After electrum registered the payment a new address was generated. This new address was derived correctly

Please correct me if I got something wrong. 

@ecdsa
A memory failure could explain why it only happend once. 

——

How do you guys think about an automatic wallet address integrecity check in the „receive“ tab before an address is going to be displayed using sign/encrypt message?
- Sign or encrypt a message using **stored** address private key
- Validate using **stored** address

**Comment by ecdsa** [comment] 2018-12-04 08:56
@MrTschi No, the point I am trying to make is that this corruption is not likely to result from a memory failure (aka bit flip). I asked you to include the change addresses (in yellow) in your screenshot precisely for that reason: I wanted to know if they were corrupted too.

Since both change and receiving addresses are corrupted, it is likely that the keystore xpub in your memory was corrupted **before** addresses were derived. And since the correct xpub was saved to disk, we have to conclude that the xpub was corrupted in your computer's memory **after** it was derived and saved to disk.

Such a modification is unlikely to result from memory failure, because xpubs have a checksum. I believe it is more likely to be a bug or malware.

**Comment by ecdsa** [comment] 2018-12-04 09:03
clarification: a memory failure could affect the process that derives xpub_receive from xpub, or xpub_change from xpub. however, I think it is unlikely that it would affect both derivations independently. that's why I think it is more likely that the main xpub was corrupted.

**Comment by ecdsa** [comment] 2018-12-04 09:53
Please also note that malware can change the xpub in memory, even if the file is encrypted. 
Wallet encryption only encrypts the file on disk; the xpub remains unencrypted in memory.

**Comment by SomberNight** [comment] 2018-12-04 12:05
> a memory failure could affect the process that derives xpub_receive from xpub, or xpub_change from xpub

Actually those intermediate xpubs are also stored (in memory) in xpub format, including 4 byte checksum, and when used to derive further keys, the checksum is checked. In case of corruption of those, an exception propagates out to the crash reporter.

**Comment by ecdsa** [comment] 2018-12-04 13:10
> > a memory failure could affect the process that derives xpub_receive from xpub, or xpub_change from xpub
> 
> Actually those intermediate xpubs are also stored (in memory) in xpub format, including 4 byte checksum, and when used to derive further keys, the checksum is checked. In case of corruption of those, an exception propagates out to the crash reporter.

no, I am referring to _CKD_pub ; the variables used during the derivation are not checksummed (and they cannot be).

**Comment by MrTschi** [comment] 2018-12-04 17:43
@ecdsa 
>  I asked you to include the change addresses (in yellow) in your screenshot [...]

I've already posted a detailed answer to this question including screenshots in this comment: https://github.com/spesmilo/electrum/issues/4891#issuecomment-443811681
To make it short: All addresses, including change addresses are corrupted.

@ecdsa 
> I believe it is more likely to be a bug or malware.

Fun fact: Before I decided to move my funds to a new wallet I also used electrum with my previous wallet (2016 till 01.12.2018). I upgraded to latest electrum (3.2.3) some weeks ago. Only the private key of this wallet is encrypted (not the whole wallet file so this is a json file). I checked this wallet for corrupted addresses but every address keypair is OK, including change addresses.
IMHO: If there is a "malware" on my mac, it should had infected this wallet too. Infecting this old wallet would have been much easier than shifting bits / manipulating of my memory 🤣 

----

Another interesting point which might be the issue:
I typed the recovery seed into a rich text editor (default TextEdit app on mac) to print it out. I changed the font, font size and so on.
To 100% ensure that I print out the correct seed I copy&pasted the seed from that rich text app into electrum seed textfield.
Maybe I copied a control character (0x0, \n, \r or other shit) which leads to the issue.

Could this be the case or does non-alphanumeric chars get filtered?

**Comment by AbdussamadA** [comment] 2018-12-04 17:51
>Maybe I copied a control character (0x0, \n, \r or other shit) which leads to the issue.

Trailing and leading control characters get filtered out. If they are between other characters then they don't get removed. However, the xpubs are the same so it doesn't matter exactly what you used as seed. xpub comes from the seed so if its the same then the seed is the same as well.

**Comment by ecdsa** [comment] 2018-12-13 10:11
@MrTschi when you created the wallet for the very first time, was the wallet file encrypted?

**Comment by MrTschi** [comment] 2018-12-13 11:42
@ecdsa yes it was encrypted during creation (import process). It never was stored unencrypted.

**Comment by SomberNight** [comment] 2018-12-20 20:32
Have you used a fork/altcoin version of Electrum that could have accessed this wallet file?

**Comment by MrTschi** [comment] 2018-12-21 05:06
Hi @SomberNight , thank you for your answer. I did not use a fork or unofficial version. I only have BTC so I have no need for an altcoin wallet.

Please also check this post where I calculated checksums and compared them with the ofiicial release:
https://github.com/spesmilo/electrum/issues/4891#issuecomment-443495955

**Comment by max-grosch** [comment] 2019-01-04 22:36
Any news here?

**Comment by MrTschi** [comment] 2019-01-04 22:37
Any news here?

**Comment by MrSoapDealer** [comment] 2019-01-21 08:47
Unfortunately looks like I'm in the same boat. All I did was make a new Electrum wallet via Tails (3.11) Funds transferred right in, but same exact error trying to send out.

**Comment by AbdussamadA** [comment] 2019-01-21 10:45
@MrSoapDealer you should mention that your seed is an electrum seed and not bip39. Also it's a legacy p2pkh wallet with addresses that begin with 1. [Reddit thread](https://www.reddit.com/r/Electrum/comments/ai6ip8/please_send_help_unrecognizable_tails_electrum/) for those interested.

**Comment by MrSoapDealer** [comment] 2019-01-24 07:04
@SomberNight realized I misread what you asked. The error I get sweeping my key is just "no input values" when trying to broadcast. No error codes just that text.

I did some playing around in the meantime aswell. I created another new standard Electrum wallet via Tails OS, everything went normal. I sent funds to this wallet, went through balance shows correctly. Just so happens I'm running into the same error as my post above with wallet 1 unable to send out. Once again tried to recover via Windows, it opened a wallet with all new addresses, no balance nor history. The xpubs match. Sweep fails, Import shows different address.

Very odd, it's weird that my older wallets still run fine. I also tried creating a wallet 3 via Tails to try sweeping into that which didnt work either.

**Comment by AbdussamadA** [comment] 2019-01-24 08:45
>I sent funds to this wallet

Wow that was a waste of money. Your tails distro is somehow infected with malware. That's why you keep getting different addresses. Where did you download tails from? Do you have persistence enabled?

**Comment by SomberNight** [comment] 2019-01-24 11:51
> I did some playing around in the meantime aswell. I created another new standard Electrum wallet via Tails OS, everything went normal. I sent funds to this wallet, went through balance shows correctly. Just so happens I'm running into the same error as my post above with wallet 1 unable to send out

So you have created a malfunctioning wallet file twice now, both on Tails?

Instead of sending coins to an address and trying to spend them, you should be able to test the wallet file by signing a message and verifying it. (in `Addresses` tab right click address > `Sign/verify message`)
Test that this fails with "wallet 1" and "wallet 2", as a sanity check.

Please carry out the message signing test on "wallet 3", and also another newly created wallet; as it would be valuable to know if all newly created wallets are malfunctioning or not.

**Comment by MrSoapDealer** [comment] 2019-01-30 05:08
@SomberNight sorry for the late update. I tested all 3 wallets via Tails with the sign/verify.

First 20 addresses give wrong signature when verifying
The last 16 addresses all check out and verify 

-This is the case with all 3 wallets
- All the sent addresses with recieved coins are within the first 20 addresses which give wrong signature.

**Comment by MrSoapDealer** [comment] 2019-01-31 23:06
@SomberNight did some more investigating looking up transactions on blockchain.info.. I can look up each individual recieved address, balance is confirmed. When I search using my xpub from either Wallet 1 or 2, two options are found for the same code. The 1st option I click gives me a blank page with zero info. The 2nd options brings me to a page with wallet info but says zero balance nor transactions.

**Comment by SomberNight** [comment] 2019-02-06 19:27
Please take a look at https://github.com/spesmilo/electrum/issues/5082
@MrTschi can that possibly explain your issue? What file system and storage media were the wallet files stored on?

**Comment by MrTschi** [comment] 2019-02-06 20:28
@SomberNight thanks for investigation!
The corrupted wallet was created at the internal ssd of my mac (Samsung 850 Pro MZ-7KE256BW).

Before creating the corrupt wallet I experimented different types of seed recovery (different BIP derivation paths) and different new wallet creations. So i‘m not sure if I have the previous wallet file...
Maybe this is related but never had file corruptions on my SSD drive before. Age of storage device is round about 3years.

You mentioned that the previous opened wallet seed may could recover the funds. Would the mentioned address which has the funds be the #1 derived address of the previous opened wallet or may i have to create more addresses so that it comes up?

**Comment by SomberNight** [comment] 2019-02-06 23:25
The theory is that there was a previous wallet file ("old"), that got opened, and certain parts of this file were overwritten ("new"). So the wallet file what you ended up with is an amalgamation of two. The seed words and xpub is for the new one; the addresses for the old.

If you've received coins to the "old" addresses; you would need to get the "old" seed. Unless you have e.g. written down the "old" seed on paper, your chances are grim :/

**Comment by MrTschi** [comment] 2019-02-07 05:40
@SomberNight 
> you would need to get the "old" seed.
I've checked this, I do not have the "old" seed nor a wallet file of the previous created test wallets. So my funds are permanently gone.

Let me know if theres something I could help in order to get this bug fixed soon.

**Comment by ecdsa** [comment] 2019-02-08 08:48
closing this, because the issue is explained.  please follow-up in #5082

**Closed by ecdsa** 2019-02-08 08:48 UTC
Labels: maybe-malware
