### ISSUE TITLE
Crashes at Mac OS X

### ISSUE THREAD

**Issue by sean0010** [spesmilo/electrum#2332] opened 2017-03-26 06:41 UTC
2.7.18 was ok. I was able to use without any problem.
2.8.0 and 2.8.2 crashes right after running.

macOS Sierra 10.12.3
Mac mini (Mid 2010)

http://i.imgsafe.org/760fe4165d.png
http://i.imgsafe.org/760ff9c606.png
http://i.imgsafe.org/76100e7b6d.png
http://i.imgsafe.org/76101d0b8e.png
http://i.imgsafe.org/76100c1095.png
http://i.imgsafe.org/761036ee0a.png
http://i.imgsafe.org/761033fb24.png
http://i.imgsafe.org/7610258999.png
http://i.imgsafe.org/76102b9337.png

I can provide more details if needed, let me know how to.

**Comment by shsmith** [comment] 2017-04-01 17:29
Could be caused by this: https://github.com/spesmilo/electrum/issues/2326

**Comment by aglyzov** [comment] 2017-05-02 10:06
I confirm, the same issue here on my mac.

**Comment by aglyzov** [comment] 2017-05-02 10:19
```
default	12:49:23.340377 +0300	Electrum	Traceback (most recent call last):
default	12:49:23.340471 +0300	Electrum	  File "/Applications/Electrum.app/Contents/Resources/__boot__.py", line 77, in <module>
default	12:49:23.340525 +0300	Electrum	    _run()
default	12:49:23.340574 +0300	Electrum	  File "/Applications/Electrum.app/Contents/Resources/__boot__.py", line 62, in _run
default	12:49:23.340623 +0300	Electrum	    exec(compile(source, path, 'exec'), globals(), globals())
default	12:49:23.340675 +0300	Electrum	  File "/Applications/Electrum.app/Contents/Resources/electrum.py", line 379, in <module>
default	12:49:23.340723 +0300	Electrum	    d.init_gui(config, plugins)
default	12:49:23.340773 +0300	Electrum	  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/daemon.py", line 283, in init_gui
default	12:49:23.340826 +0300	Electrum	    self.gui.main()
default	12:49:23.340877 +0300	Electrum	  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/gui/qt/__init__.py", line 200, in main
default	12:49:23.340927 +0300	Electrum	    if not self.start_new_window(path, self.config.get('url')):
default	12:49:23.340978 +0300	Electrum	  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/gui/qt/__init__.py", line 157, in start_new_window
default	12:49:23.341027 +0300	Electrum	    wallet = self.daemon.load_wallet(path, None)
default	12:49:23.341090 +0300	Electrum	  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/daemon.py", line 220, in load_wallet
default	12:49:23.341248 +0300	Electrum	    wallet = Wallet(storage)
default	12:49:23.341324 +0300	Electrum	  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/wallet.py", line 1757, in __new__
default	12:49:23.341476 +0300	Electrum	    wallet = WalletClass(storage)
default	12:49:23.341620 +0300	Electrum	  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/wallet.py", line 1564, in __init__
default	12:49:23.341942 +0300	Electrum	    Deterministic_Wallet.__init__(self, storage)
default	12:49:23.342008 +0300	Electrum	  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/wallet.py", line 1409, in __init__
default	12:49:23.342317 +0300	Electrum	    Abstract_Wallet.__init__(self, storage)
default	12:49:23.342479 +0300	Electrum	  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/wallet.py", line 134, in __init__
default	12:49:23.342542 +0300	Electrum	    self.contacts = Contacts(self.storage)
default	12:49:23.342639 +0300	Electrum	  File "/Applications/Electrum.app/Contents/Resources/lib/python2.7/lib/contacts.py", line 41, in __init__
default	12:49:23.342690 +0300	Electrum	    self.update(d)
default	12:49:23.342771 +0300	Electrum	ValueError: dictionary update sequence element #0 has length 34; 2 is required
default	12:49:23.352396 +0300	Electrum	2017-05-02 12:49:23.352 Electrum[42214:4028018] Electrum Error
```

**Comment by aglyzov** [comment] 2017-05-02 10:20
2.7.18 works fine

**Comment by aglyzov** [comment] 2017-06-11 20:18
Okay, today I fixed my issue with OSX by removing ~/.electrum and restoring a wallet from the seed.

This exception:
`ValueError: dictionary update sequence element #0 has length 34; 2 is required`
and the fact that the restored wallet works fine without crashes suggests there is a bug in the wallet upgrading/importing code. Perhaps my wallet was too old and had an outdated field or whatever in it.

Anyway, this is a workaround that worked for me on OSX.

**Comment by ecdsa** [comment] 2017-07-27 07:38
closing as duplicate of #2326

**Closed by ecdsa** 2017-07-27 07:38 UTC
