### ISSUE TITLE
Setting Submarine Swap to 'Max' crashes Electrum

### ISSUE THREAD

**Issue by Liongrass** [spesmilo/electrum#6770] opened 2020-11-24 10:10 UTC
REPRO:
I am running Electrum 4.0.5 on Ubuntu 20.04.1
I have one Lightning channel open.
Lightning is synced
Under Channel I select Swap

ACTUAL:
- Upon clicking Max
- The fields 'you send' and 'you receive' fill up with my available balance
- Electrum crashes without an error notice

Additional information:
When first clicking on the Lightning symbol (you send on-chain, you receive lightning), then clicking Max, Electrum does not crash. When clicking on the blue Bitcoin symbol again (you send lightning, you receive on-chain), Electrum crashes without error notice.

**Comment by SomberNight** [comment] 2020-11-25 07:32
There are probably more conditions that need to be fulfilled to reproduce. No crash here.

Could you clarify what you mean by "crash"? Is there a "Sorry" crash reporter window, or is it a segfault?
Also, is there anything in the [debug logs](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging)?

**Comment by Liongrass** [comment] 2020-11-25 08:31
Hi, thanks for the link to the debug log info, I was looking for logs, didn't realize I have to edit the settings. This might be useful:

```
20201125T083016.145187Z |    ERROR | gui.qt.exception_window.Exception_Hook | exception caught by crash reporter
Traceback (most recent call last):
  File "/tmp/.mount_electrS67lXv/usr/lib/python3.7/site-packages/electrum/gui/qt/swap_dialog.py", line 138, in on_send_edited
    if self.is_reverse and send_amount and send_amount > self.lnworker.num_sats_can_send():
  File "/tmp/.mount_electrS67lXv/usr/lib/python3.7/site-packages/electrum/lnworker.py", line 1369, in num_sats_can_send
    for chan in self.channels.values()))/1000 if self.channels else 0
  File "/tmp/.mount_electrS67lXv/usr/lib/python3.7/site-packages/electrum/lnworker.py", line 1369, in <genexpr>
    for chan in self.channels.values()))/1000 if self.channels else 0
  File "/tmp/.mount_electrS67lXv/usr/lib/python3.7/site-packages/electrum/lnchannel.py", line 1132, in available_to_spend
    consider_ctx(ctx_owner=receiver, is_htlc_dust=True),
  File "/tmp/.mount_electrS67lXv/usr/lib/python3.7/site-packages/electrum/lnchannel.py", line 1093, in consider_ctx
    ctn = self.get_next_ctn(ctx_owner)
  File "/tmp/.mount_electrS67lXv/usr/lib/python3.7/site-packages/electrum/lnchannel.py", line 1218, in get_next_ctn
    return self.hm.ctn_latest(subject) + 1
  File "/tmp/.mount_electrS67lXv/usr/lib/python3.7/site-packages/electrum/lnhtlc.py", line 50, in func_wrapper
    return func(self, *args, **kwargs)
  File "/tmp/.mount_electrS67lXv/usr/lib/python3.7/site-packages/electrum/lnhtlc.py", line 56, in ctn_latest
    return self.ctn_oldest_unrevoked(sub) + int(self.is_revack_pending(sub))
  File "/tmp/.mount_electrS67lXv/usr/lib/python3.7/site-packages/electrum/lnhtlc.py", line 60, in ctn_oldest_unrevoked
    return self.log[sub]['ctn']
  File "/tmp/.mount_electrS67lXv/usr/lib/python3.7/site-packages/electrum/json_db.py", line 44, in wrapper
    return func(self, *args, **kwargs)
  File "/tmp/.mount_electrS67lXv/usr/lib/python3.7/site-packages/electrum/json_db.py", line 129, in __getitem__
    key = self.convert_key(key)
  File "/tmp/.mount_electrS67lXv/usr/lib/python3.7/site-packages/electrum/json_db.py", line 86, in convert_key
    return str(int(key)) if isinstance(key, int) else key
RecursionError: maximum recursion depth exceeded while getting the str of an object
```

**Comment by Liongrass** [comment] 2020-11-25 08:58
Somehow this bug seemed to have also caused my only channel to close.

**Comment by ecdsa** [comment] 2020-11-26 08:49
@bitromortac you mentioned a crash caused by the swap dialog, is that the same as here?

**Comment by ecdsa** [comment] 2020-11-26 09:17
@Liongrass has your channel been working normally before? were you able to send/receive lightning payments?

**Comment by ecdsa** [comment] 2020-11-26 09:47
I see a possible infinite recursion in the `follows` boolean field we use to return early from on_send_edited, on_recv_edited:
https://github.com/spesmilo/electrum/blob/master/electrum/gui/qt/swap_dialog.py#L140

there is no guarantee that the callback will be called within the time window where `follows` is set to false

**Comment by ecdsa** [comment] 2020-11-26 09:53
probable duplicate of #6295

**Comment by ecdsa** [comment] 2020-11-26 10:12
Note: the same `follows` boolean mechanism is used for exchange rates in the main window.

**Comment by bitromortac** [comment] 2020-11-26 19:05
I can reproduce it. @ecdsa, I could take a look.

**Comment by ecdsa** [comment] 2020-11-26 19:27
@bitromortac when you reproduce it, do you get exactly the same traceback, or does it vary? (such as in #6295)

**Comment by Liongrass** [comment] 2020-11-27 03:30
@ecdsa The channel was working well before, I was able to receive and send. The channel was closed cooperatively. Can I find out which side initiated the closure? Both nodes are mine and there was no action taken on my side.

**Comment by bitromortac** [comment] 2020-11-27 06:47
On a second look it looks more like #6295, I posted my traceback there.

**Comment by ecdsa** [comment] 2020-11-27 09:08
@Liongrass which implementation is the other node running? Electrum will not initiate a cooperative close without user action. It will, however, force close the channel in various cases.

@bitromortac I still think this issue is the same as #6295. The traceback is different because the recursion max has been reached at a different line in the code. 

The issue depends on the timing of execution Qt signals, that is why it is not reproducible for everyone.

**Comment by Liongrass** [comment] 2020-11-27 09:10
The other side is running `lncli version 0.11.0-beta commit=v0.11.0-beta`

**Comment by ecdsa** [comment] 2020-11-27 09:14
@Liongrass you should check in your logs, look for SHUTDOWN

**Comment by ecdsa** [comment] 2020-11-27 09:32
@bitromortac to get rid of the infinite recursion, I think we need to connect `on_send_edited`, `on_recv_edited` to `textEdited` instead of `textChanged`:

```diff
-        self.send_amount_e.textChanged.connect(self.on_send_edited)
-        self.recv_amount_e.textChanged.connect(self.on_recv_edited)
+        self.send_amount_e.textEdited.connect(self.on_send_edited)
+        self.recv_amount_e.textEdited.connect(self.on_recv_edited)
```

Unfortunately a fix will requires more work than changing those two lines, because the logic of the max button and fee settings is affectced.

**Comment by bitromortac** [comment] 2020-11-27 17:35
> @bitromortac to get rid of the infinite recursion, I think we need to connect `on_send_edited`, `on_recv_edited` to `textEdited` instead of `textChanged`:
> 
> ```diff
> -        self.send_amount_e.textChanged.connect(self.on_send_edited)
> -        self.recv_amount_e.textChanged.connect(self.on_recv_edited)
> +        self.send_amount_e.textEdited.connect(self.on_send_edited)
> +        self.recv_amount_e.textEdited.connect(self.on_recv_edited)
> ```
> 
> That way, the callbacks will not be triggered by `setAmount`.
> 
> Unfortunately a fix will requires more work than changing those two lines, because the logic of the max button and fee settings is affected.

Tested it and it seems to fix it! :grinning:

**Closed** 2020-12-04 10:03 UTC
Labels: bug 🐞
