### ISSUE TITLE
Unresponsive buttons in multiple instances of wallet creation wizard (modal dialogs not updating/refreshing if there is more than one)

### ISSUE THREAD

**Issue by AbdussamadA** [spesmilo/electrum#3286] opened 2017-11-13 05:03 UTC
When you run more than one instance of electrum's wallet creation wizard all but one of the instances will have unresponsive back and next buttons. For example in order to create multisig wallets. This has been observed on linux but may be apparent on other OS too.

Started happening with electrum 3.0. Persists with electrum 3.0.1 too.

Linux specs are given below:

![versions](https://user-images.githubusercontent.com/3611810/32710422-ddb27580-c859-11e7-9880-7f65754a2143.png)

**Comment by sunnyville01** [comment] 2017-11-20 14:12
Could this be a feature? Why are you running multiple instances of the wallet creating wizard?

**Comment by SomberNight** [comment] 2018-03-16 23:50
Similarly if you have a main window open with e.g. a seed dialog in it; and another InstallWizard window; then the wizard will have unresponsive next/back buttons. So it seems that window modal dialogs for different window are actually blocking each other.

Looks related: https://bugreports.qt.io/browse/QTBUG-37202

**Comment by SomberNight** [comment] 2019-06-03 16:58
Note: I've tested using an Electrum 2.9.3 binary on Windows 7, and could reproduce the problem of the wizards blocking each other. That version of Electrum used Qt4, so this is not related to the qt4-qt5 transition. I think this issue has always existed.

**Comment by fresheneesz** [comment] 2019-12-24 04:39
I'd like to comment @sunnyville01. No this is not a feature. I was running multiple instances of the wallet in order to interface between a normal wallet and a multisig.

**Comment by accumulator** [comment] 2023-09-22 09:02
seems to be fixed with new wizard (#8560)

**Closed by accumulator** 2023-09-22 09:02 UTC
Labels: bug 🐞, user-interface 🔲, Qt ✨, topic-wizard 🧙‍♂️
