### ISSUE TITLE
Crash in mode text Linux

### ISSUE THREAD

**Issue by Thedemon007** [spesmilo/electrum#2014] opened 2016-10-31 19:20 UTC
Reproduce:

create a wallet

`electrum create`

lauch armony in console mode:

`electrum -g text`

Try move to Receive and crash:

```
Traceback (most recent call last):
File "/usr/local/bin/electrum", line 338, in <module>  d.init_gui(config, plugins)
File "/usr/local/lib/python2.7/dist-packages/electrum/daemon.py", line 253, in init_gui self.gui.main()
File "/usr/local/lib/python2.7/dist-packages/electrum_gui/text.py", line 291, in main self.run_tab(2, self.print_receive, self.run_receive_tab)
File "/usr/local/lib/python2.7/dist-packages/electrum_gui/text.py", line 229, in run_tab  print_func()
File "/usr/local/lib/python2.7/dist-packages/electrum_gui/text.py", line 149, in print_receive addr = self.wallet.get_unused_address(None)
TypeError: get_unused_address() takes exactly 1 argument (2 given)
Exception in thread Thread-11 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
File "/usr/lib/python2.7/threading.py", line 763, in run
File "/usr/local/lib/python2.7/dist-packages/electrum/blockchain.py", line 47, in init
File "/usr/local/lib/python2.7/dist-packages/electrum/blockchain.py", line 115, in init_headers_file
File "/usr/lib/python2.7/urllib.py", line 94, in urlretrieve
File "/usr/lib/python2.7/urllib.py", line 279, in retrieve
File "/usr/lib/python2.7/urllib.py", line 975, in close
File "/usr/lib/python2.7/socket.py", line 282, in close
File "/usr/lib/python2.7/ssl.py", line 397, in close
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'close'
```

**Comment by ecdsa** [comment] 2016-11-02 06:38
duplicate of #2002

**Closed by ecdsa** 2016-11-02 06:38 UTC

**Comment by Thedemon007** [comment] 2016-11-02 10:28
Ok thanks fixed in https://github.com/spesmilo/electrum/commit/2ca043789837a3635a3532fc8ed9f515af049154
