### ISSUE TITLE
network taskgroup dies when disconnected

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#7677] opened 2022-02-21 09:24 UTC
I have not checked, but this might be related to the recent `aiorpc` changes

```
W/i | interface.[skbxmit.coinjoined.com:50002] | disconnecting due to GracefulDisconnect(RPCError(-101, 'excessive resource usage'))
W/i | interface.[stavver.dyshek.org:50002] | disconnecting due to GracefulDisconnect(RPCError(-101, 'excessive resource usage'))
E | asyncio | Task exception was never retrieved
future: <Task finished name='Task-118929' coro=<Interface.get_estimatefee() done, defined at /opt/electrum/electrum/interface.py:1071> exception=RequestTimedOut("request timed out: ('blockchain.estimatefee', [5]) (id: 84)")>
Traceback (most recent call last):
  File "/opt/electrum/electrum/interface.py", line 171, in send_request
    response = await asyncio.wait_for(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/session.py", line 540, in send_request
    return await self._send_concurrent(message, future, 1)
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/session.py", line 512, in _send_concurrent
    return await future
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 382, in __aexit__
    raise TaskTimeout(self._secs) from None
aiorpcx.curio.TaskTimeout: task timed out after 30s

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/electrum/electrum/interface.py", line 1078, in get_estimatefee
    res = await self.session.send_request('blockchain.estimatefee', [num_blocks])
  File "/opt/electrum/electrum/interface.py", line 175, in send_request
    raise RequestTimedOut(f'request timed out: {args} (id: {msg_id})') from e
electrum.interface.RequestTimedOut: Network request timed out.
E/n | network | taskgroup died.
Traceback (most recent call last):
  File "/opt/electrum/electrum/network.py", line 1204, in main
    [await group.spawn(job) for job in self._jobs]
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 297, in __aexit__
    await self.join()
  File "/opt/electrum/electrum/util.py", line 1255, in join
    task.result()
  File "/opt/electrum/electrum/network.py", line 1277, in _maintain_sessions
    await maintain_main_interface()
  File "/opt/electrum/electrum/network.py", line 1268, in maintain_main_interface
    await self._ensure_there_is_a_main_interface()
  File "/opt/electrum/electrum/network.py", line 1245, in _ensure_there_is_a_main_interface
    await self._switch_to_random_interface()
  File "/opt/electrum/electrum/network.py", line 648, in _switch_to_random_interface
    await self.switch_to_interface(random.choice(servers))
  File "/opt/electrum/electrum/network.py", line 714, in switch_to_interface
    await i.taskgroup.spawn(self._request_server_info(i))
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 204, in spawn
    self._add_task(task)
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 150, in _add_task
    raise RuntimeError('task group terminated')
RuntimeError: task group terminated
E/n | network | Exception in set_parameters: RuntimeError('task group terminated')
Traceback (most recent call last):
  File "/opt/electrum/electrum/util.py", line 1160, in wrapper
    return await func(*args, **kwargs)
  File "/opt/electrum/electrum/network.py", line 632, in set_parameters
    await self.switch_to_interface(server)
  File "/opt/electrum/electrum/network.py", line 705, in switch_to_interface
    await self.taskgroup.spawn(self._run_new_interface(server))
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 204, in spawn
    self._add_task(task)
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 150, in _add_task
    raise RuntimeError('task group terminated')
RuntimeError: task group terminated
Traceback (most recent call last):
  File "/opt/electrum/electrum/gui/qt/network_dialog.py", line 121, in func
    self.parent.set_server()
  File "/opt/electrum/electrum/gui/qt/network_dialog.py", line 411, in set_server
    self.network.run_from_another_thread(self.network.set_parameters(net_params))
  File "/opt/electrum/electrum/network.py", line 387, in run_from_another_thread
    return fut.result(timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/opt/electrum/electrum/util.py", line 1160, in wrapper
    return await func(*args, **kwargs)
  File "/opt/electrum/electrum/network.py", line 632, in set_parameters
    await self.switch_to_interface(server)
  File "/opt/electrum/electrum/network.py", line 705, in switch_to_interface
    await self.taskgroup.spawn(self._run_new_interface(server))
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 204, in spawn
    self._add_task(task)
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 150, in _add_task
    raise RuntimeError('task group terminated')
RuntimeError: task group terminated
E/n | network | Exception in set_parameters: RuntimeError('task group terminated')
Traceback (most recent call last):
  File "/opt/electrum/electrum/util.py", line 1160, in wrapper
    return await func(*args, **kwargs)
  File "/opt/electrum/electrum/network.py", line 632, in set_parameters
    await self.switch_to_interface(server)
  File "/opt/electrum/electrum/network.py", line 705, in switch_to_interface
    await self.taskgroup.spawn(self._run_new_interface(server))
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 204, in spawn
    self._add_task(task)
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 150, in _add_task
    raise RuntimeError('task group terminated')
RuntimeError: task group terminated
Traceback (most recent call last):
  File "/opt/electrum/electrum/gui/qt/network_dialog.py", line 121, in func
    self.parent.set_server()
  File "/opt/electrum/electrum/gui/qt/network_dialog.py", line 411, in set_server
    self.network.run_from_another_thread(self.network.set_parameters(net_params))
  File "/opt/electrum/electrum/network.py", line 387, in run_from_another_thread
    return fut.result(timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/opt/electrum/electrum/util.py", line 1160, in wrapper
    return await func(*args, **kwargs)
  File "/opt/electrum/electrum/network.py", line 632, in set_parameters
    await self.switch_to_interface(server)
  File "/opt/electrum/electrum/network.py", line 705, in switch_to_interface
    await self.taskgroup.spawn(self._run_new_interface(server))
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 204, in spawn
    self._add_task(task)
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 150, in _add_task
    raise RuntimeError('task group terminated')
RuntimeError: task group terminated




```

**Comment by SomberNight** [comment] 2022-02-21 18:59
This is the interesting exception that killed the network taskgroup:
> ```
>  E/n | network | taskgroup died.
>  Traceback (most recent call last):
>    File "/opt/electrum/electrum/network.py", line 1204, in main
>      [await group.spawn(job) for job in self._jobs]
>    File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 297, in __aexit__
>      await self.join()
>    File "/opt/electrum/electrum/util.py", line 1255, in join
>      task.result()
>    File "/opt/electrum/electrum/network.py", line 1277, in _maintain_sessions
>      await maintain_main_interface()
>    File "/opt/electrum/electrum/network.py", line 1268, in maintain_main_interface
>      await self._ensure_there_is_a_main_interface()
>    File "/opt/electrum/electrum/network.py", line 1245, in _ensure_there_is_a_main_interface
>      await self._switch_to_random_interface()
>    File "/opt/electrum/electrum/network.py", line 648, in _switch_to_random_interface
>      await self.switch_to_interface(random.choice(servers))
>    File "/opt/electrum/electrum/network.py", line 714, in switch_to_interface
>      await i.taskgroup.spawn(self._request_server_info(i))
>    File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 204, in spawn
>      self._add_task(task)
>    File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 150, in _add_task
>      raise RuntimeError('task group terminated')
>  RuntimeError: task group terminated
>  ```

In `network.switch_to_interface`, looks like the interface we are switching to is already ~dying: `i.taskgroup` has already terminated. This results in `taskgroup.spawn` raising this `RuntimeError`.
https://github.com/spesmilo/electrum/blob/d8d2c180aafaec1ae9bc68c27a7d780df8de4348/electrum/network.py#L708-L714

Before https://github.com/spesmilo/electrum/pull/7661, interface.taskgroup used to be a `SilentTaskGroup`:
https://github.com/spesmilo/electrum/blob/d8d2c180aafaec1ae9bc68c27a7d780df8de4348/electrum/interface.py#L379
https://github.com/spesmilo/electrum/blob/d8d2c180aafaec1ae9bc68c27a7d780df8de4348/electrum/util.py#L1189-L1195
So instead of `RuntimeError`, only an `asyncio.CancelledError` would have been raised.

Such a `CancelledError` would have been caught here -- I believe such an exception might have been the reason why I added this block of catching "spurious cancellations" in https://github.com/spesmilo/electrum/commit/62e352a2a8e61ae930b6a09b1457d5419afea35c:
https://github.com/spesmilo/electrum/blob/d8d2c180aafaec1ae9bc68c27a7d780df8de4348/electrum/network.py#L1199-L1200
https://github.com/spesmilo/electrum/blob/d8d2c180aafaec1ae9bc68c27a7d780df8de4348/electrum/network.py#L1273-L1281

I think that try-except (without using SilentTaskGroup) is now useless.

The root cause here is that we should not be spawning tasks onto interface.taskgroup if the interface is already ~dying.

**Comment by SomberNight** [comment] 2022-02-21 19:06
I can only see two places where we call `interface.taskgroup.spawn` outside the taskgroup's context manager:
https://github.com/spesmilo/electrum/blob/d8d2c180aafaec1ae9bc68c27a7d780df8de4348/electrum/network.py#L714
https://github.com/spesmilo/electrum/blob/d8d2c180aafaec1ae9bc68c27a7d780df8de4348/electrum/network.py#L1270

**Comment by ecdsa** [comment] 2022-02-22 05:54
the issue is still there.
the client remains disconnected.
```
I/i | interface.[188.230.155.0:50002] | disconnecting due to: CancelledError()
I/i | interface.[dxm.no-ip.biz:50002] | disconnecting due to: CancelledError()
I/i | interface.[node.degga.net:50002] | disconnecting due to: CancelledError()
I/i | interface.[167.172.42.31:50002] | disconnecting due to: CancelledError()
I/i | interface.[37.205.9.165:50002] | disconnecting due to: CancelledError()
I/i | interface.[142.93.6.38:50002] | disconnecting due to: CancelledError()
I/i | interface.[tardis.bauerj.eu:50002] | disconnecting due to: CancelledError()
I/n | network | couldn't launch iface kittycp2gatrqhlwpmbczk5rblw62enrpo2rzwtkfrrr27hq435d4vid.onion:50002:s -- CancelledError()
I/i | interface.[kittycp2gatrqhlwpmbczk5rblw62enrpo2rzwtkfrrr27hq435d4vid.onion:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(-2, 'Name or service not known')))
I/i | interface.[electrumx.ultracloud.tk:50002] | disconnecting due to: CancelledError()
E/n | network | taskgroup died (0x7f9274f98e50).
Traceback (most recent call last):
  File "/opt/electrum/electrum/network.py", line 1205, in main
    [await group.spawn(job) for job in self._jobs]
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 297, in __aexit__
    await self.join()
  File "/opt/electrum/electrum/util.py", line 1255, in join
    task.result()
  File "/opt/electrum/electrum/network.py", line 1277, in _maintain_sessions
    await maintain_main_interface()
  File "/opt/electrum/electrum/network.py", line 1269, in maintain_main_interface
    await self._ensure_there_is_a_main_interface()
  File "/opt/electrum/electrum/network.py", line 1246, in _ensure_there_is_a_main_interface
    await self._switch_to_random_interface()
  File "/opt/electrum/electrum/network.py", line 648, in _switch_to_random_interface
    await self.switch_to_interface(random.choice(servers))
  File "/opt/electrum/electrum/network.py", line 715, in switch_to_interface
    await i.taskgroup.spawn(self._request_server_info(i))
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 204, in spawn
    self._add_task(task)
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 150, in _add_task
    raise RuntimeError('task group terminated')
RuntimeError: task group terminated
I/n | network | taskgroup stopped (0x7f9274f98e50).
```

**Comment by SomberNight** [comment] 2022-02-22 14:30
Ok, so this commit explains why the previous "fix" (https://github.com/spesmilo/electrum/commit/d7af868ed8c4dd94e332d3af9dc0cd15c479f306) does not work: https://github.com/spesmilo/electrum/commit/2acecc5859e2d3cf44493e82ed99343deb8f4398

and I believe this commit should now fix it: https://github.com/spesmilo/electrum/commit/f4cfc6c7c332c987957914afb6e6b9000f841e6a

**Comment by SomberNight** [comment] 2022-02-23 17:47
so I think this is fixed now... please reopen if you can reproduce again :)

**Comment by ecdsa** [comment] 2022-02-23 22:44
indeed, it is fixed

**Comment by ecdsa** [comment] 2022-02-25 09:23
it happened again. this time I have the log with timestamps

```
20220224T183129.490761Z |    DEBUG | util.profiler | AddressList.update 0.0000
20220224T183131.882777Z |     INFO | network | fee_histogram [[3.4, 109986], [3.2, 73957], [3.1, 789690], [3.0, 185418], [2.4, 201327], [2.0, 406026], [1.1, 269428], [1.0, 799010]]
20220224T183231.920210Z |     INFO | network | fee_histogram [[5.2, 107717], [3.5, 128382], [3.2, 103436], [3.1, 846155], [3.0, 189807], [2.4, 202916], [2.0, 406256], [1.1, 270791], [1.0, 820501]]
20220224T210909.225249Z |     INFO | interface.[electrum.stippy.com:50002] | disconnecting due to RequestTimedOut("request timed out: ('mempool.get_fee_histogram',) (id: 740)")
20220224T210909.236325Z |     INFO | network | switching to ex03.axalgo.com:50002:s
20220224T210909.239667Z |     INFO | interface.[guichet.centure.cc:50002] | disconnecting due to: CancelledError()
20220224T210909.240493Z |     INFO | interface.[btc.ocf.sh:50002] | disconnecting due to: CancelledError()
20220224T210909.241698Z |     INFO | interface.[electrum3.hodlister.co:50002] | disconnecting due to: CancelledError()
20220224T210909.242545Z |     INFO | interface.[bitcoins.sk:56002] | disconnecting due to: CancelledError()
20220224T210909.243217Z |     INFO | interface.[2AZZARITA.hopto.org:50002] | disconnecting due to: CancelledError()
20220224T210909.244091Z |     INFO | interface.[fortress.qtornado.com:443] | disconnecting due to: CancelledError()
20220224T210909.244875Z |     INFO | interface.[ex03.axalgo.com:50002] | disconnecting due to: CancelledError()
20220224T210909.245776Z |     INFO | interface.[electrum.brainshome.de:50002] | disconnecting due to: CancelledError()
20220224T210909.270995Z |     INFO | network | couldn't launch iface electrumx.alexridevski.net:50002:s -- CancelledError()
20220224T210909.666976Z |     INFO | interface.[electrumx.alexridevski.net:50002] | disconnecting due to: ConnectError(ConnectionResetError(104, 'Connection reset by peer'))
20220224T210939.272247Z |     INFO | interface.[188.165.211.112:50002] | disconnecting due to: CancelledError()
20220224T210940.274038Z |    ERROR | network | taskgroup died (0x7fbe4a0afdf0).
Traceback (most recent call last):
  File "/opt/electrum/electrum/network.py", line 1205, in main
    [await group.spawn(job) for job in self._jobs]
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 297, in __aexit__
    await self.join()
  File "/opt/electrum/electrum/util.py", line 1255, in join
    task.result()
  File "/opt/electrum/electrum/network.py", line 1277, in _maintain_sessions
    await maintain_main_interface()
  File "/opt/electrum/electrum/network.py", line 1269, in maintain_main_interface
    await self._ensure_there_is_a_main_interface()
  File "/opt/electrum/electrum/network.py", line 1246, in _ensure_there_is_a_main_interface
    await self._switch_to_random_interface()
  File "/opt/electrum/electrum/network.py", line 648, in _switch_to_random_interface
    await self.switch_to_interface(random.choice(servers))
  File "/opt/electrum/electrum/network.py", line 715, in switch_to_interface
    await i.taskgroup.spawn(self._request_server_info(i))
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 204, in spawn
    self._add_task(task)
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 150, in _add_task
    raise RuntimeError('task group terminated')
RuntimeError: task group terminated
20220224T210940.277786Z |     INFO | network | taskgroup stopped (0x7fbe4a0afdf0).
20220224T212408.696831Z |     INFO | lnpeer.Peer.[LNWallet, 03864ef025-4b9d6bd1] | Disconnecting: LightningPeerConnectionClosed()
20220224T212409.220644Z |     INFO | lnworker.LNWallet.[wallet_2021.new] | adding peer 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f@node.acinq.co:9735
20220224T212409.527996Z |     INFO | lnpeer.Peer.[LNWallet, 03864ef025-0f7f369e] | handshake done for 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f@node.acinq.co:9735
20220224T212409.528260Z |    DEBUG | lnpeer.Peer.[LNWallet, 03864ef025-0f7f369e] | Sending INIT
20220224T212409.670224Z |    DEBUG | lnpeer.Peer.[LNWallet, 03864ef025-0f7f369e] | Received INIT
20220224T212409.701170Z |    DEBUG | lnpeer.Peer.[LNWallet, 03864ef025-0f7f369e] | Received CHANNEL_REESTABLISH
20220224T212409.701795Z |     INFO | lnpeer.Peer.[LNWallet, 03864ef025-0f7f369e] | channel_r
```

**Comment by SomberNight** [comment] 2022-03-11 14:35
```
20220224T210909.236325Z |     INFO | network | switching to ex03.axalgo.com:50002:s
20220224T210909.244875Z |     INFO | interface.[ex03.axalgo.com:50002] | disconnecting due to: CancelledError()
20220224T210940.274038Z |    ERROR | network | taskgroup died (0x7fbe4a0afdf0).
Traceback (most recent call last):
[...]
  File "/opt/electrum/electrum/network.py", line 715, in switch_to_interface
    await i.taskgroup.spawn(self._request_server_info(i))
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 204, in spawn
    self._add_task(task)
  File "/home/voegtlin/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 150, in _add_task
    raise RuntimeError('task group terminated')
RuntimeError: task group terminated
```
https://github.com/spesmilo/electrum/blob/67c386c39a3831b16f89f272f765c54feb47434f/electrum/network.py#L710-L715

Not sure what is going on there during that 30 second pause... Looks like the event loop is bogged down with something.
Regardless, the interesting bit is that when `switching to ...` is printed, we have already checked that interface.taskgroup is still alive, and the next await is already the taskgroup.spawn, but during the spawn there are multiple awaits going on before it reaches the internal check to see if the taskgroup is still alive, and during that time the interface is killed and the taskgroup terminates. To me this looks like an issue with the aiorpcx taskgroup.spawn API itself... the caller cannot be expected to ensure the taskgroup stays alive for the multiple event loop iterations spawn takes before it itself checks it...

https://github.com/kyuupichan/aiorpcX/blob/e55950fed903b63e82b87c7b6ca93ab50e18ce08/aiorpcx/curio.py#L198
https://github.com/kyuupichan/aiorpcX/blob/e55950fed903b63e82b87c7b6ca93ab50e18ce08/aiorpcx/curio.py#L150

Not even the `SilentTaskGroup` approach we used to do would fix this...
https://github.com/spesmilo/electrum/blob/d8d2c180aafaec1ae9bc68c27a7d780df8de4348/electrum/util.py#L1189-L1195

**Closed** 2022-03-11 14:39 UTC
Labels: bug 🐞, topic-network 🕸
