### ISSUE TITLE
Use blockchain.estimatefee in client within some bound range

### ISSUE THREAD

**Issue by EagleTM** [spesmilo/electrum#1382] opened 2015-07-30 19:12 UTC
Server has blockchain.estimatefee for a while. The default fee of 0.1 mBTC set by the client can be too low. With the spam attacks on the network I'd suggest making use of it, so that the client queries the server for blockchain.estimatefee and uses it as a default fee.

Obviously there are security implications with this, as the fee could be faked by the server. I'd recommend to apply at least one of two countermeasures:

a) set an upper bound of 0.00050000 (0.5 mBTC) to be set by estimatefee in the client. If the server reports a higher one, still of 0.5 mBTC. The user can still change it up / down in the GUI 
b) query multiple servers (2-3? or all the ones it uses for headers if that's easy)

**Comment by ecdsa** [comment] 2015-07-31 22:21
I agree,but that's a duplicate of #208

**Closed by ecdsa** 2015-07-31 22:21 UTC
Labels: enhancement
