### ISSUE TITLE
Android app not accepting valid BIP39 Seed words

### ISSUE THREAD

**Issue by ioogithub** [spesmilo/electrum#5827] opened 2019-12-08 16:55 UTC
Install a fresh version of Electrum for Android (version 3.3.8.0-release), select Standard Wallet, I already have a seed.

I type in my 24 seed word however Electrum will never accept it. The Next button at the bottom never turns clickable.

The seed is currently being used with Electrum Desktop v 3.38 and Mycellium. I have also tested it with a Trezor. All of these devices accept the seed and it works as expected but Electrum Android will not accept it. I have tried this multiple times.

**Comment by SomberNight** [comment] 2019-12-08 17:00
duplicate of https://github.com/spesmilo/electrum/issues/3388

BIP39 seeds cannot be restored in Android app on latest release but it has already been implemented on master

**Closed by SomberNight** 2019-12-08 17:00 UTC

**Comment by ioogithub** [comment] 2019-12-08 17:05
Does this mean it will be supported in a future release?

Also, will the "Extend your seed with custom words" feature also be added to Android with using BIP39 seeds?

Is there any workaround in the meantime so I can start using Electrum for Android?

**Comment by SomberNight** [comment] 2019-12-08 17:11
> Does this mean it will be supported in a future release?

Yes, next release will have it.

> Also, will the "Extend your seed with custom words" feature also be added to Android with using BIP39 seeds?

Yes, that is also implemented.

> is there any workaround in the meantime so I can start using Electrum for Android?

You can build an Android APK yourself; it is not that difficult. See the [README](https://github.com/spesmilo/electrum/blob/master/electrum/gui/kivy/Readme.md)
