### ISSUE TITLE
Getting Antivirus warnings: "OSX.ElectrumStealer"

### ISSUE THREAD

**Issue by Adelino88** [spesmilo/electrum#5956] opened 2020-02-14 05:56 UTC
By Downloading the .DMG or .ZIP files (for MacOS) from the https://electrum.org/#download, I am getting warnings from my Antivirus. Affected version Electrum 3.3.8. 

Example Logs from Antivirus:
14.02.20, 06:26:04 | Scan - Malware Found (1 scanned, 1 infected, 1 repaired): Home ▸ Downloads ▸ Electrum-3.3.8.zip.download ▸ VAjS3x ▸ Electrum-3.3.8 ▸ electrum ▸ gui ▸ qt ▸ .BC.T_7UIlSF
14.02.20, 06:26:03 | Real-Time Scan - Malware Found (1 scanned, 1 infected, 0 repaired): Home ▸ Downloads ▸ Electrum-3.3.8.zip.download ▸ VAjS3x ▸ Electrum-3.3.8 ▸ electrum ▸ gui ▸ qt ▸ .BC.T_7UIlSF
14.02.20, 06:26:02 | Scan - Malware Found (1 scanned, 1 infected, 1 repaired): Home ▸ Downloads ▸ Electrum-3.3.8.zip.download ▸ VAjS3x ▸ Electrum-3.3.8 ▸ electrum ▸ .BC.T_IYLOxq
14.02.20, 06:26:01 | Real-Time Scan - Malware Found (1 scanned, 1 infected, 0 repaired): Home ▸ Downloads ▸ Electrum-3.3.8.zip.download ▸ VAjS3x ▸ Electrum-3.3.8 ▸ electrum ▸ .BC.T_IYLOxq
14.02.20, 06:26:01 | Scan - Malware Found (1 scanned, 1 infected, 1 repaired): Home ▸ Downloads ▸ Electrum-3.3.8.zip.download ▸ VAjS3x ▸ Electrum-3.3.8 ▸ electrum ▸ .BC.T_u6OQjq
14.02.20, 06:26:00 | Real-Time Scan - Malware Found (1 scanned, 1 infected, 0 repaired): Home ▸ Downloads ▸ Electrum-3.3.8.zip.download ▸ VAjS3x ▸ Electrum-3.3.8 ▸ electrum ▸ .BC.T_u6OQjq
14.02.20, 06:25:59 | Scan - Malware Found (1 scanned, 1 infected, 1 repaired): Home ▸ Downloads ▸ Electrum-3.3.8.zip.download ▸ VAjS3x ▸ Electrum-3.3.8 ▸ electrum ▸ .BC.T_YWMmKw
14.02.20, 06:25:48 | Real-Time Scan - Malware Found (1 scanned, 1 infected, 0 repaired): Home ▸ Downloads ▸ Electrum-3.3.8.zip.download ▸ VAjS3x ▸ Electrum-3.3.8 ▸ electrum ▸ .BC.T_YWMmKw
14.02.20, 06:24:03 | File added to quarantine (OSX/ElectrumStealer): Home ▸ Downloads ▸ electrum-3.3.8.dmg
14.02.20, 06:24:00 | Scan - Partial (1 scanned, 0 infected, 0 repaired): Home ▸ Downloads ▸ electrum-3.3.8.dmg
14.02.20, 06:23:29 | Scan - Malware Found (5 scanned, 1 infected, 0 repaired): Home ▸ Downloads ▸ electrum-3.3.8.dmg
14.02.20, 06:21:27 | Scan - Malware Found (1 scanned, 1 infected, 0 repaired): Macintosh_SSD ▸ Applications ▸ Electrum.app ▸ Contents ▸ MacOS ▸ Electrum

**Comment by SomberNight** [comment] 2020-02-14 19:04
What antivirus do you use?

Please verify the GPG signature of the downloaded files -- as a sanity check, I expect it will pass.

**Comment by helpau** [comment] 2023-10-16 18:20
Looks like [Intego VirusBarrier](https://www.macupdate.com/app/mac/46644/lazesoft-mac-data-recovery#:~:text=the%20following%20warnings-,from%20Virus%20Barrier,-10.8.7.%20Now%2C%20I%27m) , this company doesn't have antiviruses on virustotal, but they have Windows version(probably with exactly the same database). I'll try to rescan electrum binaries this week.

**Comment by helpau** [comment] 2023-10-18 17:09
Intego Antivirus 3.0.0.1, Windows 10, Definition version 8.20.10.154, custom scan, files scanned:5
electrum-3.3.8.dmg
electrum-3.3.8.exe
Electrum-3.3.8.zip
electrum-4.4.6.dmg
electrum-4.4.6.exe
No issues detected, so I can't reproduce

**Comment by SomberNight** [comment] 2023-10-19 16:47
Thanks, we can close this.

**Closed by SomberNight** 2023-10-19 16:47 UTC
Labels: OS-mac, antivirus-false-positive ❎
