### ISSUE TITLE
On Mac OS X, importing ALL CAPS BIP39 recovery SEED does NOT result in checksum error as in Windows version

### ISSUE THREAD

**Issue by ybuadmin** [spesmilo/electrum#3298] opened 2017-11-14 00:12 UTC
On Mac OS X version of Electrum, importing a valid BIP39 recovery SEED that has been converted into ALL CAPS, does NOT result in checksum error as in Windows version.  Instead, the Mac version seems to create new wallet with 0.0 balance.

TO REPRODUCE, On the Mac version, enter a BIP39 recovery seed that has been converted to ALL CAPS.  Notice that a new wallet seems to have been created.  Enter the same ALL CAPS recovery seed in the Windows version, notice that a checksum error is displayed.

EXPECTED BEHAVIOR: Either match the Windows user experience OR fix both versions to convert case to lowercase before recovering wallet.

**Comment by JustinTArthur** [comment] 2017-11-15 07:02
I was not able to reproduce this checksum error on Windows. On both platforms in Electrum 3.0.2, I entered the following BIP39 seed in all caps:
`LEGAL WINNER THANK YEAR WAVE SAUSAGE WORTH USEFUL LEGAL WINNER THANK YELLOW`

On both platforms, the dialog warned that the seed was using an unknown wordlist but allowed me to create a new wallet using the custom capitalized words.

Make sure you have checked the BIP39 option on both platforms.

**Comment by ecdsa** [comment] 2017-11-15 09:56
I guess the user saw bug #3299 and misinterpreted it.
closing

**Closed by ecdsa** 2017-11-15 09:56 UTC

**Comment by ybuadmin** [comment] 2017-11-15 15:50
User here.  @Thomas, I think that must have been what happen.
When will the following bug fix appear in a release?  Thanks!

fix: bip39 checksum sometimes not calculated #3299
