### ISSUE TITLE
password with enter code

### ISSUE THREAD

**Issue by b4zz4** [spesmilo/electrum#6733] opened 2020-11-14 18:01 UTC
Long ago I used an "enter code" as part of the password and now it does not accept it anymore...
This was a mistake on my part, but now version 3.4 of the wallet don't work

Could you help me fix this in the latest version of Electrum ?
Thanks

**Comment by SomberNight** [comment] 2020-11-14 18:42
I don't understand.
Do you mean you used a seed extension ("passphrase") for your seed?
Where did you originally generate the seed? Was it using Electrum?

Also, what do you mean by version 3.4? There is no Electrum 3.4

**Comment by b4zz4** [comment] 2020-11-14 19:15
Sorry, I use the translator is difficult to explain. 
I generated a complex key, copied and pasted it adding a newline. 
This worked like this per year, but now updating the program I realized that it doesn't work anymore.

![I speak of this password](https://user-images.githubusercontent.com/643833/99155199-8c8d0700-2694-11eb-8146-264cc0380f15.png)
I speak of this password

**Comment by SomberNight** [comment] 2020-11-14 19:24
So your password is not accepted anymore?
Are you sure you have the correct password?
When did it last work? (what version of Electrum?)
Do you have special characters in your password? Or is it alphanumeric (only letters and numbers)?

**Comment by b4zz4** [comment] 2020-11-14 19:50
I am sure password is the correct. 
 It is in the old version but not in the new version.
The old version no longer connects to nodes.
The characters are alphanumeric, without accents or strange characters.

**Comment by SomberNight** [comment] 2020-11-14 23:53
> The old version no longer connects to nodes.

What do you mean? Do you get "invalid password" error or not?

**Comment by ecdsa** [comment] 2020-12-18 10:37
I can reproduce the issue. I believe the user created a password that contains a "newline" character.

It is possible to copy and paste such a password in the password field, with the current version (4.0.8)
It is however not possible to type it. Not sure if that was possible with older versions, though.

**Comment by ecdsa** [comment] 2020-12-18 10:46
@b4zz4 I do not think it was ever possible to type a newline in the password field.
Maybe you used to copy and paste your password from a password manager, and now you are trying to type it?
In that case, this is not caused by a change in Electrum, but by a change in the way you enter your password.

**Comment by ecdsa** [comment] 2021-01-02 11:39
Closing this issue. In the absence of an answer, I guess my explanation is correct
In that case there is nothing we can do about it.

**Closed by ecdsa** 2021-01-02 11:39 UTC
Labels: question ❓
