### ISSUE TITLE
BUG: Fee slider is based on stripped size while details tab uses virtual size

### ISSUE THREAD

**Issue by ejose19** [spesmilo/electrum#3480] opened 2017-12-09 03:06 UTC
I've noticed inconsistencies with the fee regarding the one shown in the fee slider and the one shown in the preview/details window, and finally concluded the problem is that the former is using the stripped size while the latter uses the virtual size.

This simple problem can be solved with using the same size for both, either stripped size or virtual size, based on which one is the better candidate.

**Comment by SomberNight** [comment] 2017-12-09 19:30
Is this a duplicate of https://github.com/spesmilo/electrum/issues/3347 ?
Can you test on master?

**Comment by ecdsa** [comment] 2017-12-12 16:05
if it is a duplicate, it is fixed in 3.0.3
if not, reopen

**Closed by ecdsa** 2017-12-12 16:05 UTC
