### ISSUE TITLE
Error on payment from ledger HW.1

### ISSUE THREAD

**Issue by ericlau792** [spesmilo/electrum#7420] opened 2021-07-20 09:59 UTC
I created a wallet based on the old HW.1 ledger wallet.
I can open it and see the funds.
When I try to send money to a legacy address (the only possible), after being verified, I have a "read error" and the transaction is not done.

I can see a quick message :"validate your transaction on your ledger wallet" which cannont be done because it is a simple one...

Eric
![Error electrum](https://user-images.githubusercontent.com/46556676/126304558-ed788e64-6def-4a4a-aadb-003d3bf854d7.png)

**Comment by SomberNight** [comment] 2021-07-21 01:01
possibly duplicate of https://github.com/spesmilo/electrum/issues/7022

Do you know what version of firmware you have on the device?
You can get the firmware version using the "Console" tab (`View`>`Show Console`), e.g.:
```
>>> wallet.keystore.get_client().getFirmwareVersion()
{'compressedKeys': True, 'version': '1.0.4', 'specialVersion': 32}
```

**Closed** 2021-07-21 13:39 UTC
Labels: hw-ledger
