### ISSUE TITLE
Sending BTC failed with "trailing junk after DER sig: 01" message

### ISSUE THREAD

**Issue by KleeTaurus** [spesmilo/electrum#2722] opened 2017-08-10 16:15 UTC
I setup a multisig wallet with electrum and TREZOR hardware wallet, but when I transfer my BTC into another address, I got an error in the last step. A dialog is poped up with "trailing junk after DER sig: 01". It looks like something wrong with following code.

    rs_strings, empty = der.remove_sequence(sig_der)
    if empty != b(""):
        raise der.UnexpectedDER("trailing junk after DER sig: %s" %
                                binascii.hexlify(empty))

**Comment by fireduck64** [comment] 2017-08-10 16:20
I was getting that error as well.  It went away when I ran electrum from source rather than from the 2.9.2 package.

**Comment by bauerj** [comment] 2017-08-10 16:21
See #2718 for more information.

**Comment by ecdsa** [comment] 2017-08-10 16:24
@fireduck64 which package are you referring to?

**Comment by ecdsa** [comment] 2017-08-10 16:30
@KleeTaurus what's your OS and how did you install electrum?

**Comment by fireduck64** [comment] 2017-08-10 16:33
@ecdsa I got that error when running with https://download.electrum.org/2.9.2/Electrum-2.9.2.tar.gz and it went away when running with latest source.

**Comment by ecdsa** [comment] 2017-08-10 16:35
@fireduck64 in that tarball, lib/transaction.py, line 559 has the patch
so the issue does not come from the tarball.
I would really like to know where it comes from, if you have the time to investigate

**Comment by ecdsa** [comment] 2017-08-10 16:36
@fireduck64 can you retry to run from the tarball, to see if the problem is still there?

**Comment by fireduck64** [comment] 2017-08-10 16:36
@ecdsa yeah, will do

**Comment by KleeTaurus** [comment] 2017-08-10 16:45
@ecdsa I got this issue both on windows 10 and macos with the version electrum 2.9.2. I'll try it tomorrow with the tarball.
I also add some debug info in util.py which located in ecdsa.
    sig_der: MEUCIQCHRM9icZGS8/uxu2tQoEpYxG7sXRObvgh6n1AljrWkEgIgGQrhk5KSkaN/AFSZC1F0sbQXyXs29fKMuUl3nus0rhA=
    rs_strings: AiEAh0TPYnGRkvP7sbtrUKBKWMRu7F0Tm74Iep9QJY61pBICIBkK4ZOSkpGjfwBUmQtRdLG0F8l7NvXyjLlJd57rNK4Q
    empty: 
    sig_der: MEUCIQCHRM9icZGS8/uxu2tQoEpYxG7sXRObvgh6n1AljrWkEgIgGQrhk5KSkaN/AFSZC1F0sbQXyXs29fKMuUl3nus0rhAB
    rs_strings: AiEAh0TPYnGRkvP7sbtrUKBKWMRu7F0Tm74Iep9QJY61pBICIBkK4ZOSkpGjfwBUmQtRdLG0F8l7NvXyjLlJd57rNK4Q
    empty: AQ==
I found the function was executed twice with little difference in the last character in sig_der variable.

**Comment by ecdsa** [comment] 2017-08-10 16:46
@KleeTaurus which version of electrum was used by your cosigner?

**Comment by fireduck64** [comment] 2017-08-10 16:50
I was unable to reproduce with just using trezor to sign things (no multisig or transaction).  I'll setup a multisig and see if I can do it.

**Comment by KleeTaurus** [comment] 2017-08-10 16:57
@ecdsa my cosigner version 2.9.2

**Comment by fireduck64** [comment] 2017-08-10 17:00
Reproduced.  Signs fine from source, not from installed package

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/util.py", line 582, in run
    result = task.task()
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1141, in sign_transaction
    k.sign_transaction(tx, password)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/trezor/plugin.py", line 66, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/trezor/plugin.py", line 244, in sign_transaction
    tx.update_signatures(raw)
  File "/usr/local/lib/python2.7/dist-packages/electrum/transaction.py", line 559, in update_signatures
    r, s = ecdsa.util.sigdecode_der(sig.decode('hex')[:-1], order)
  File "/usr/local/lib/python2.7/dist-packages/ecdsa/util.py", line 240, in sigdecode_der
    binascii.hexlify(empty))
UnexpectedDER: trailing junk after DER sig: 01

**Comment by fireduck64** [comment] 2017-08-10 17:02
Comparing source with what I have installed:

$ diff ./plugins/trezor/plugin.py /usr/local/lib/python2.7/dist-packages/electrum_plugins/trezor/plugin.py284c284
<                             signatures=map(lambda x: x.decode('hex')[:-1] if x else '', txin.get('signatures')),
---
>                             signatures=map(lambda x: x.decode('hex') if x else '', txin.get('signatures')),

$ diff ./lib/wallet.py /usr/local/lib/python2.7/dist-packages/electrum/wallet.py
539c539
<         confirmed_only = config.get('confirmed_only', False)
---
>         confirmed_only = config.get('confirmed_only', True)

**Comment by ecdsa** [comment] 2017-08-10 17:06
oh right, this as fixed in e991722d9cb81dea5568c9cdf4a4e94c44df9fff
use version 2.9.3

**Closed** 2017-08-10 17:06 UTC

**Comment by KleeTaurus** [comment] 2017-08-11 00:53
First I uninstall 2.9.2 from my windows 10 and reinstall 2.9.3, when I sign the transaction I got "sign_tx() got an unexpected keyword argument 'lock_time'"

**Comment by ecdsa** [comment] 2017-08-11 03:02
@KleeTaurus binaries were packaged with the wrong version of trezorlib. 
I made new binaries, please redownload

**Comment by KleeTaurus** [comment] 2017-08-11 03:04
Got it.

**Comment by KleeTaurus** [comment] 2017-08-11 15:18
@ecdsa Great job, it works :)
