### ISSUE TITLE
0 BTC transaction received instead of correct amount [BUG]

### ISSUE THREAD

**Issue by Gardenstudio** [spesmilo/electrum#3798] opened 2018-01-29 18:35 UTC
Dear Electrum developers,
there is a bug that blocks the syncronization of electrum (windows and android are affected) and users receive transactions with 0 BTC instead of the right amount.
We did several tests on different platforms and somebody (great man!) probably found also the possible reason.
Please have a look on this thread for any detail (screenshots and other info)
https://bitcointalk.org/index.php?topic=2829027.0

Seems like the problem affects users who received a BTC transaction from bitpanda, but not 100% sure about it.

![electrum_crash](https://user-images.githubusercontent.com/35932561/35527486-25348a7a-052b-11e8-8fe0-ff06111f223c.png)

**Comment by SomberNight** [comment] 2018-01-29 18:44
duplicate of https://github.com/spesmilo/electrum/issues/3788
Thanks for telling who made the txn.

**Closed by SomberNight** 2018-01-29 18:44 UTC
Labels: bug, duplicate

**Comment by tudorconstantin** [comment] 2018-01-29 18:58
this might not be a duplicate of #3788 because there, the tx is completely ignored by Electrum, so it doesn't appear in the History

**Comment by SomberNight** [comment] 2018-01-29 19:03
@tudorconstantin both b18a38be693a5dca1aae2326351cb80c3ca64616559f0c4c5c9b6d2d8841d9cb (from this issue) and e9933221a150f78f9f224899f8568ff6422ffcc28ca3d53d87936368ff7c4b1d (from https://github.com/spesmilo/electrum/issues/3788) seems to be spending from p2wsh-p2sh txins that have a witnessScript with 3 stack items: sig, pubkey, script.

**Comment by SomberNight** [comment] 2018-01-29 19:04
@tudorconstantin could you confirm whether your txn was created by Bitpanda too?

**Comment by SomberNight** [comment] 2018-01-29 19:09
The crash shown in the screenshot in OP can be reproduced via importing 16wXcHfyBuaVnyGdArKjTrjx6HqdhmUrVK into an Imported Wallet and trying to look up txn details.

**Comment by tudorconstantin** [comment] 2018-01-29 19:19
I try to find out some details about that tx, but I might not be able to get them.

**Comment by Gardenstudio** [comment] 2018-01-29 19:20
Three users in the bitcointalk thread confirmed to have done a bitpanda -> electrum transaction.

Can be bitpanda changed something in their system that creates this problem.
Thank you for working on it... this is a problem about not having the possibility to spend own money.
Good job guys :-)

**Comment by SomberNight** [comment] 2018-02-04 18:28
@Gardenstudio 3.0.6 was released yesterday, and that should include the relevant fix.
