### ISSUE TITLE
There are a lot of transactions in the bitcoin mempool atm and it sounds like you might be using low fees.

### ISSUE THREAD

**Issue by Yarkndr** [spesmilo/electrum#8754] opened 2023-12-16 19:24 UTC
There are a lot of transactions in the bitcoin mempool atm and it sounds like you might be using low fees.
Try bumping the fee.
See https://bitcoinelectrum.com/frequently-asked-questions/#my-bitcoin-transaction-is-not-confirming-what-can-i-do

The absolute value of the fee, especially in fiat terms, (e.g. "4 USD" is irrelevant to the system). Only fee/byte (sat/vbyte) matters.

_Originally posted by @SomberNight in https://github.com/spesmilo/electrum/issues/8749#issuecomment-1858308194_
            

I was able to delete the transaction because it was not processed by the miners and showed up local in electrum.
I created a new transaction again, specified an ETA of $30 commission. 
No changes, the transaction is ignored and pulled further back in the queue just the same. Previously with such a commission the transaction was processed within 2-3 hours.
What else can be connected with ?

**Comment by accumulator** [comment] 2023-12-17 12:31
duplicate of https://github.com/spesmilo/electrum/issues/8749

**Closed by accumulator** 2023-12-17 12:31 UTC
