### ISSUE TITLE
MultiSig "The change path is unusual" issue is possibly due to Ledger setup?

### ISSUE THREAD

**Issue by craig5999** [spesmilo/electrum#5914] opened 2020-01-27 02:49 UTC
I've set up a multi-sig using OSX (Catalina 10.15.2) Electrum 3.3.8 with a Trezor and Ledger (both up-to-date firmware), using the default m/48'/0'/0'/2' path. Both public keys are available when I check the wallet information via the Electrum menu.

I get the message "The change path is unusual" 48'/0'/0'/2'/1/3 on my Ledger when attempting to sign a tx. Accepting the change path allows me to complete the tx successfully. The change comes back to my multi-sig wallet as expected. I checked the option "Use change addresses". It is checked. Above it was stated that the issue should be fixed if the option is checked. But this does not fix it for me.

I tried unchecking "Use change addresses" and restarting Electrum. I still got the warning, but this time with change path 48'/0'/0'/2'/1/2. I considered this unusual - why is it asking this if I disabled change addresses? Because it still needs to use a change path to send back to the same wallet?

Would it be safe for me to manually select any other derivation path supported by Ledger?

Anyway, it would be great if you could give me some clarity on this. My guess is that Ledger does not yet recognize this multi-sig derivation path, so a warning is thrown. I read the reddit threads and saw that it is safe to continue, so I guess it's not a big issue. I've contacted Ledger support and will update when I receive an answer.

Thank you!

----

UPDATE!

On the Ledger I'm using, there is also some BTC stored in m/49'/0'/0'. So I thought, how about trying from scratch with a different set of addresses? I set a temp passphrase and set up a new multi-sig wallet with everything kept the same except the ledger passphrase.

Transactions went through without any change address warning.

Could it be that the use of the m/49'/0'/0' path in the original Ledger is somehow conflicting with the multi-sig setup, and giving me a warning when I try to use 48'/0'/0'/2'/1/3? It seems the case to me.

Thoughts?

_Originally posted by @craig5999 in https://github.com/spesmilo/electrum/issues/5271#issuecomment-578569780_

**Comment by relativisticelectron** [comment] 2020-02-01 18:48
I have also had the "The change path is unusual" warning from Ledger. I attribute it to the lacking support (by Ledger) of multisig.

**Comment by SomberNight** [comment] 2020-02-03 17:01
This is essentially a duplicate of https://github.com/spesmilo/electrum/issues/5271 (or at least OP's comments there).

**Closed by SomberNight** 2020-02-03 17:01 UTC
Labels: hw-ledger

**Comment by craig5999** [comment] 2020-02-05 07:19
Sorry for double posting. Since this thread has been closed, would you be able to re-open the other one? I would like to find out why this is occurring.
