### ISSUE TITLE
seed phrase not verifying

### ISSUE THREAD

**Issue by EurekaIgnem** [spesmilo/electrum#8904] opened 2024-02-20 13:40 UTC
I could not get the electrum wallet to load onto my Android. it failed multiple times (> 4) when I attempted to confirm my 12 word seed phrase. Electrum simply closed and I was required to restart/relaunch the app but without memory of the wallet that previously was about to be created.   On my first attempt, I choose "2FA wallet" not "standard".  I choose to "extend with pass phrase"; I used non BIP39 words.  On attempting to confirm the 12 word seed phrase a small window (green or yellow) appeared at bottom right of the seed phase confirmation window with writing (I think it was "xx - segwit") in this yellow or green window.

If you want to pursue this anomalous behavior, notify me and I will get more data, as of now, I gave up on Electrum-android and went to Aqua.

Here are details I recall:

Xiaomi Redmi 7 Android
MIUI version 11.0.2
Android ver. 10.QK.Q1
Android Patch:  2021.03.01

I copied the seed phrase down accurately. I know because i repeated confirmation of first seed phrase 4 times, with and without extended pass phrase.  I tried new seed phrases multiple times thereafter. The internet connection might be an explanation, but only a 40% likelihood, as the device I am writing to you now, was opening fine this entire time. Low storage is not the issue, because the phone was just factory reset. Only a few apps were loaded (i.e. 3 other apps) before loading electrum. And yes, I did a uninstall and re-install of Electrum for Android... it manifest the same glitch with confirming the seed phrase.

The first seed phrase I obtained from Electrum itself. I tried confirming this ~ 4 times. Then I generated another new seed phrase from Electrum, and the same glitch on confirmation occurred. Then I tried recreating or giving Electrum the first seed phrase it gave to me, and that did not get confirmed either.

One thing that I did which was akward, I tried entering extended pass phrase words after the 12 seed words on first go. This did not work. I stopped trying to add extended pass phrases phrases after 2 failures at confirming the seed phrase ensemble.

**Comment by accumulator** [comment] 2024-02-20 15:10
Can you try again with the option 'Always allow screenshots' enabled in Preferences?

**Comment by accumulator** [comment] 2024-02-21 16:32
I suspect this is caused by the removal of the `FLAG_SECURE`. Also, there are a number of play store reports that point to the same issue.

Maybe it's better to not remove the flag after adding..

**Comment by SomberNight** [comment] 2024-02-21 17:17
> I suspect this is caused by the removal of the `FLAG_SECURE`

(related https://github.com/spesmilo/electrum/issues/8522)

It would be nice if OP could confirm by testing with the mentioned config setting.

**Comment by SomberNight** [comment] 2024-02-23 13:05
Note: if this is really related to `FLAG_SECURE`, it might now be fixed on version 4.5.3. So it would be great if you could test with that @EurekaIgnem

**Closed** 2024-10-09 13:28 UTC
Labels: bug 🐞, OS-android🤖, awaiting-response 💤
