### ISSUE TITLE
Wallet balance is shown in the Windows 10 system tray settings

### ISSUE THREAD

**Issue by Erty444** [spesmilo/electrum#7564] opened 2021-11-15 04:36 UTC
Windows 10:
go to Taskbar settings - Select which icons appear on the taskbar.
here we can see list of apps and switches on/off for them which allows to always show app icon in the tray. 
in the list you can find Electrum app.
at the 2nd text string you'll see the same text as in the bottom of main window of Electrum, for example "Balance: 1.23456 BTC...."
so your balance is compromised and it is stored (this text string) somewhere in the Windows

**Comment by SomberNight** [comment] 2021-11-15 15:55
duplicate of https://github.com/spesmilo/electrum/issues/5665

**Closed by SomberNight** 2021-11-15 15:55 UTC
