### ISSUE TITLE
[Windows] v2.6.4 throw a Visual C++ Runtime Error

### ISSUE THREAD

**Issue by MarcoPon** [spesmilo/electrum#1762] opened 2016-04-13 16:37 UTC
The portable edition show it right after launching:

![electrum-error](https://cloud.githubusercontent.com/assets/10859367/14501355/2a282d32-01a6-11e6-8b9c-4f0b87ebcacf.png)

And then it goes on working like normal.

**Comment by ecdsa** [comment] 2016-05-16 15:28
duplicate of #1000

**Closed by ecdsa** 2016-05-16 15:28 UTC
