### ISSUE TITLE
QR code with seed is left behind after creating new wallet

### ISSUE THREAD

**Issue by atychyna** [spesmilo/electrum#3688] opened 2018-01-10 04:54 UTC
On a Mac while creating new wallet and selecting "copy to clipboard" option for QR barcode with seed Electrum creates `~/.electrum/qrcode.png` that never gets deleted. This is a potential security violation.

**Comment by AbdussamadA** [comment] 2018-01-10 04:57
duplicate of #3663 . it's been fixed. use git master or wait for the next release.

**Closed** 2018-01-10 05:10 UTC
