### ISSUE TITLE
[UI/UX Request] Users should be able to create a wallet using their preferred language since the beginning 

### ISSUE THREAD

**Issue by kiocosta** [spesmilo/electrum#7494] opened 2021-09-10 01:54 UTC
I believe the best possible option in terms of UX would be to set the language automatically based on the user's device's language or location, but I'm not sure if Electrum has access to these information nor if it would be safe for it to have. 

If that's not possible,  I guess selecting a language should be the first thing the user sees, at least on the mobile version. Kinda in the same way Apple does when you use iPhone for the first time.

The reason is: **many people don't understand english**. They don't understand what "standard wallet" or "seed" means. And this initial part is one of the most important parts. The option of changing the language **after** the wallet has been created isn't very useful since the harder part was already done in a language they don't understand (or not done at all and the user simply went to try another wallet because he couldn't understand what he had to do due to the language).

I'm trying to teach people about Bitcoin and I generally suggest using the Electrum wallet, but I see that the language is generally something that makes the process even more confusing for those who don't understand it.

**Comment by SomberNight** [comment] 2021-09-15 18:00
> I believe the best possible option in terms of UX would be to set the language automatically based on the user's device's language or location, but I'm not sure if Electrum has access to these information nor if it would be safe for it to have.
> If that's not possible, I guess selecting a language should be the first thing the user sees, at least on the mobile version. 

This is mostly a duplicate of https://github.com/spesmilo/electrum/issues/4618.

Since version 3.3.0 (https://github.com/spesmilo/electrum/pull/4724), in Qt (desktop) we have been setting the default language based on the OS language.
I have now implemented the same for the kivy GUI (used on Android) (https://github.com/spesmilo/electrum/commit/7cb11ceda4d0191ca3e91be22812d967f46b85ec). So the next release will have this (set default lang to OS lang).

Re the a first screen where the user can select the language, I think that's overkill but nevertheless it is already asked for in https://github.com/spesmilo/electrum/issues/4618, so I will leave that issue open, and close this one.

**Closed by SomberNight** 2021-09-15 18:00 UTC
Labels: user-interface 🔲, localization 🌍
