### ISSUE TITLE
Incoming transactions not appearing everywhere

### ISSUE THREAD

**Issue by ziggamon** [spesmilo/electrum#7954] opened 2022-08-24 13:01 UTC
Minor UI issue in the 4.3 branch on desktop Mac (possibly others too, haven't tested). To reproduce:

* Receive a bitcoin payment
* Push notification shows up
* It shows up in History tab

Does not show up in:
* Coins tab
* Balance in the footer

After restarting electrum it shows up in Coins tab, but not in Balance in the footer. 
After transactions confirms it shows up everywhere

**Comment by SomberNight** [comment] 2022-08-24 14:09
I think I've seen a similar refresh bug recently but failed to reproduce it a second time then.
I cannot reproduce this either now :/

I've tried on macOS 10.15 and win10.  Either create a receive request or without, have the History tab open, and get paid onchain. OS notification appears, History tab is refreshed, Coins tab is refreshed, Addresses tab is refreshed, Balance in footer is updated...

**Comment by ziggamon** [comment] 2022-08-24 14:47
Yeah it seems to have some randomness. But it's weird cause the notification is showing up reliably. And (I think) clicking the notification makes it show up in all places.

Let me know if there are some things I can do to help reproduce the bug more reliably.

**Comment by ziggamon** [comment] 2022-08-25 09:30
Seems it's not just incoming. Just did an outgoing transaction and saw a similar issue. The Balance updated, transaction shows up in History, but the utxo was still there in Coins. Looking back after some time it seems to have disappeared, so time seems to resolve it somehow.

**Comment by ecdsa** [comment] 2022-08-30 10:14
maybe related: #7940 (seems to be caused by `utxo_list` not updated when it should)

**Comment by SomberNight** [comment] 2022-09-26 16:35
Commits https://github.com/spesmilo/electrum/commit/444dc7fb7f6792450ce2ad89df26cca89d46940e and https://github.com/spesmilo/electrum/commit/60e2ad43161a39607276a76695f6628175b46fd3 fix a similar refresh bug, although it does not match exactly the description in the OP.

> After restarting electrum it shows up in Coins tab, but not in Balance in the footer.
> After transactions confirms it shows up everywhere

it's weird that restarting electrum would not fix the refresh issue...
apart from that bit, the reported bug could be what is being fixed in above commits

closing... but can reopen if someone reports this again

**Closed by SomberNight** 2022-09-26 16:35 UTC
