### ISSUE TITLE
my payment has been stuck all day i cancelled payment i sent payment forward ,all failed to return coin or complete payment still stuck 

### ISSUE THREAD

**Issue by hopjopper** [spesmilo/electrum#9019] opened 2024-04-20 05:09 UTC
my payment has been stuck all day i cancelled payment i sent payment forward ,all failed to return coin or complete payment still stuck

**Comment by hopjopper** [comment] 2024-04-20 05:10
says unconfirmed parent whilst parent is confirmed

**Comment by hopjopper** [comment] 2024-04-20 05:12
i sent 137 aud now i have 63 aud which stil isnt confirmed

**Comment by hopjopper** [comment] 2024-04-20 05:12
this is the worst wallet i have ever used always has some weird problem

**Comment by ecdsa** [comment] 2024-04-20 10:09
sorry, but this kind of report is useless. 
you could at least give a txid, and learn a bit how transaction fees work.
closing this; will reopen only if you give us useful info.

**Closed by ecdsa** 2024-04-20 10:09 UTC

**Comment by hopjopper** [comment] 2024-04-20 10:31
https://blockstream.info/tx/a2e31cb5159293b14d4f4f0c8a18dad480e65835fa7f722f7299b891e43a9af9
https://blockstream.info/tx/103001836d7265ae386929c3800d1e3884f40fda00b185f903986eecfdacbe5f

**Comment by hopjopper** [comment] 2024-04-20 10:34
[url=https://ibb.co/Nn9bMGd][img]https://i.ibb.co/qFNVv23/Screenshot-from-2024-04-20-20-32-46.png[/img][/url]

here is a photo as well so you can see, this has been like this since this morning and i have increased fee multiple times to the point that my initial 137 is now only worth 69 aud

**Comment by ecdsa** [comment] 2024-04-20 10:34
I closed this because this website is an issue tracker for developers. there is no issue for us to solve. 
you just need to increase the fee of your transaction.

**Comment by hopjopper** [comment] 2024-04-20 10:34
https://ibb.co/Nn9bMGd

**Comment by hopjopper** [comment] 2024-04-20 10:35
> I closed this because this website is an issue tracker for developers. there is no issue for us to solve. you just need to increase the fee of your transaction.

mate i have increased it at least 10 times i know how fees work this is an issue i have never seen before

**Comment by hopjopper** [comment] 2024-04-20 10:36
i had sent 137 aud now its down to 69 aud talk about increasing fees? this is some other bullshit your wallet is doing

**Comment by hopjopper** [comment] 2024-04-20 11:22
https://pay.coingate.com/invoice/ff516331-7f0e-43cd-b4d8-71a1981efe7b

this is still waiting for payment which i have cancelled since after increasing fee multiple times until the point the wallet doesnt allow increase of fee 

ur wallet has buckled and i had sent 137 aud the transaction was around 40 aud with 90 left over which i tried to send elsewhere 
nothing worked everything got stuck for 12 hours now i have cancelled payment i have increased fee i have done every option available multiple of times and nothing works and now i dont trust your wallet anymore it seems any bitcoin u send to it gets devoured by your bad coding

**Comment by KeefeJ** [comment] 2024-04-20 17:56
Those two transactions are currently offering only 106.3 sat/vB and 93.7 sat/vB in fees currently. Unfortunately that's far too little today, probably due to the Runes launch flooding mempools.

You can see how bad bitcoin fees are today by looking at one of these two sites:
https://jochen-hoenicke.de/queue
https://mempool.space

**Comment by hopjopper** [comment] 2024-04-20 18:00
so ur saying i need to increase fee again? the wallet isnt even allowing
that , its not allowing double spend cancel or increase fee

**Comment by KeefeJ** [comment] 2024-04-20 18:00
At the moment, you'd have to pay about 50 AUD per transaction to compete with these new NFTs-on-bitcoin.

**Comment by hopjopper** [comment] 2024-04-20 18:02
on both transactions? how the wallet isnt allowing it even if i wanted to
blow all the funds on the transaction

**Comment by KeefeJ** [comment] 2024-04-20 18:05
Yes, 50 AUD on each, because the second is spending the first. It's not Electrum's fault that the fee market is nuts today. But if Electrum is not letting you bump the fees that high, and you actually have enough in your wallet to cover such high fees, please show us a screenshot of that fee-bump screen.

**Comment by hopjopper** [comment] 2024-04-20 18:11
i increased fee multiple times in fact probably 10 times or until it didnt
allow anymore increase fee

**Comment by KeefeJ** [comment] 2024-04-20 18:55
Canceling the Coingate invoice on Coingate's website is irrelevant to Electrum or the bitcoin blockchain.

If you want further help, show us your Coins tab in Electrum (you might need to check the box for it under the View menu to get the tab to show), and also the bump-fee dialog where you say it won't let you increase the fee any further.

**Comment by KeefeJ** [comment] 2024-04-20 19:35
FYI, if you leave things as is, if the fee market eventually calms down such that your transactions confirm:
- 0.00026965 BTC (~27 AUD) will go to Coingate (I assume 3PjpaTL4fbD2gXnjztAGqMcAiHfFqwikwf is them)
- 0.00062202 BTC (~62 AUD) will return to your wallet's confirmed balance (at bc1q3yucmveqqw6uj423zzt6udfcqep2mx0r64gpm2)
- 0.00024850 BTC (~25 AUD) will go to the miners as fees (0.00013234 for the first txn and 0.00011616 for the second txn)

If you have canceled the Coingate invoice (or it has expired), you'll need Coingate to then send you back that 0.00026965 BTC (~27 AUD), but to do so they would have to pay miner fees as well, which could very well wipe out all of that amount.

I realize now that Electrum has a "cancel" (actually double-spend) feature, that you were probably trying to use also. You would want to double-spend the first transaction, not the second one. And unfortunately you'd have to pay about 50 AUD in fees to do so, even if Electrum let you (it might not let you anymore now that there's a second transaction spending the first one.

**Comment by KeefeJ** [comment] 2024-04-20 20:14
I do hope you share a screenshot of the Increase Fee dialog for the second transaction. I can't think of any technical reason why it wouldn't let you increase the fee any further on that one (it does makes sense that the first transaction's fee can no longer be increased though).

So _maybe_ there's a bug in Electrum, that could warrant reopening this git issue, but I'd like to see what you're seeing first.

**Comment by hopjopper** [comment] 2024-04-20 20:38
Will do.

**Comment by hopjopper** [comment] 2024-04-20 22:26
il get back to you its 8am sunday here had a few drinks with friends cant
do any of those things atm abit drunk and sleepy

**Comment by hopjopper** [comment] 2024-04-21 06:51
while i was sleeping both have processed and completed both transactions
are completed even nord vpn sent me a email saying payment complete
https://ibb.co/JK2FPhb
