### ISSUE TITLE
Wont detect Trezor

### ISSUE THREAD

**Issue by stefment** [spesmilo/electrum#1957] opened 2016-10-07 09:44 UTC
Hello there. I was wondering if anyone have any suggestions for how to get Electrum 2.7 to detect my Trezor? Ive tried 2.7.1 and 2.7.2 but it wont detect it :) Anyone else have a similar Issue?

I am using Windows 10 64bit and i have installed Electrum with the installer. I did try to reboot, turn of anti-virus, and different USB ports. Any help is much appreciated. Thanks.

**Comment by ecdsa** [comment] 2016-10-07 15:11
ok, I can reproduce that on a win10 computer.

**Comment by stefment** [comment] 2016-10-08 08:47
can or cant?

**Comment by ecdsa** [comment] 2016-10-08 12:10
@slush0  is there a particular version of python-trezor that should be used ?

**Comment by slush0** [comment] 2016-10-08 13:14
@prusnak is looking at it, I'm AFK. Which version did you use for the build?

**Comment by slush0** [comment] 2016-10-08 13:18
Do you see any specific error? Or the TREZOR is simply not detected?

**Comment by slush0** [comment] 2016-10-08 13:28
Can you please find out what usb interfaces Windows see for the USB? Do they have filled "usage page"? There's possibility that Electrum (python-rezor) is trying to talk with U2F interface instead of Trezor's main HID interface...

**Comment by slush0** [comment] 2016-10-08 13:30
Generally we expect the trouble at enumerate() function: https://github.com/trezor/python-trezor/blob/master/trezorlib/transport_hid.py#L7, unfortunately we're both without Windows machines now.

**Comment by ecdsa** [comment] 2016-10-08 13:33
I'm not a Windows expert..
trezor is not recognized, while Ledger and Keepkey work with my latest builds.

**Comment by slush0** [comment] 2016-10-08 13:36
Just please add some debugging into enumerate() and tell us what you see. It will be somehow related to adding U2F (and reworking of enumerate() to use "usage page" because of it). Keepkey does not have U2F and Ledger use completely different stack, so we're comparing apples and oranges.

**Comment by ecdsa** [comment] 2016-10-08 13:48
@slush0 I think it could take some time to debug this properly. do you remember which version of python-trezor was used with electrum 2.6.4 ? I would like to have a quick fix before

**Comment by slush0** [comment] 2016-10-08 14:33
That's also irrelevant. In times of release 2.6.4, the firmware didn't contain more USB interfaces like in TREZOR since 1.4.0. Although I don't have hard data, I suppose it is somehow related. Nothing other really changed.

Please send here result of hid.enumerate(0, 0), I can quickly tell you if that's the problem.

**Comment by ecdsa** [comment] 2016-10-08 14:41
here it is. run from the console. (another usb stick was plugged)
```
[{'usage_page': 1, 'product_id': 257, 'interface_number': -1, 'manufacturer_string': u'Microsoft', 'vendor_id': 2821, 'release_number': 14, 'serial_number': u'9999', 'usage': 2, 'path': '\\\\?\\hid#fte1000&col01#5&2ee1c9c6&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}', 'product_string': u'HIDI2C Device'}, {'usage_page': 65280, 'product_id': 257, 'interface_number': -1, 'manufacturer_string': u'Microsoft', 'vendor_id': 2821, 'release_number': 14, 'serial_number': u'9999', 'usage': 197, 'path': '\\\\?\\hid#fte1000&col02#5&2ee1c9c6&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}', 'product_string': u'HIDI2C Device'}, {'usage_page': 12, 'product_id': 34181, 'interface_number': -1, 'manufacturer_string': u'Microsoft', 'vendor_id': 2821, 'release_number': 1, 'serial_number': u'9999', 'usage': 1, 'path': '\\\\?\\hid#pdec3393&col02#5&b9e4761&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}', 'product_string': u'HIDI2C Device'}, {'usage_page': 1, 'product_id': 0, 'interface_number': -1, 'manufacturer_string': u'Microsoft', 'vendor_id': 0, 'release_number': 0, 'serial_number': u'1.0', 'usage': 6, 'path': '\\\\?\\hid#intcfd9&col01#3&2b7a34a4&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}', 'product_string': u'GPIO Button Driver'}, {'usage_page': 12, 'product_id': 0, 'interface_number': -1, 'manufacturer_string': u'Microsoft', 'vendor_id': 0, 'release_number': 0, 'serial_number': u'1.0', 'usage': 1, 'path': '\\\\?\\hid#intcfd9&col02#3&2b7a34a4&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}', 'product_string': u'GPIO Button Driver'}, {'usage_page': 1, 'product_id': 0, 'interface_number': -1, 'manufacturer_string': u'Microsoft', 'vendor_id': 0, 'release_number': 0, 'serial_number': u'1.0', 'usage': 128, 'path': '\\\\?\\hid#intcfd9&col03#3&2b7a34a4&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}', 'product_string': u'GPIO Button Driver'}, {'usage_page': 65280, 'product_id': 34181, 'interface_number': -1, 'manufacturer_string': u'Microsoft', 'vendor_id': 2821, 'release_number': 1, 'serial_number': u'9999', 'usage': 1, 'path': '\\\\?\\hid#pdec3393&col03#5&b9e4761&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}', 'product_string': u'HIDI2C Device'}, {'usage_page': 1, 'product_id': 0, 'interface_number': -1, 'manufacturer_string': '', 'vendor_id': 0, 'release_number': 1, 'serial_number': '', 'usage': 12, 'path': '\\\\?\\hid#atk4002#3&2f32b022&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}', 'product_string': ''}, {'usage_page': 65329, 'product_id': 34181, 'interface_number': -1, 'manufacturer_string': u'Microsoft', 'vendor_id': 2821, 'release_number': 1, 'serial_number': u'9999', 'usage': 118, 'path': '\\\\?\\hid#pdec3393&col04#5&b9e4761&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}', 'product_string': u'HIDI2C Device'}, {'usage_page': 1, 'product_id': 34181, 'interface_number': -1, 'manufacturer_string': u'Microsoft', 'vendor_id': 2821, 'release_number': 1, 'serial_number': u'9999', 'usage': 6, 'path': '\\\\?\\hid#pdec3393&col01#5&b9e4761&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}', 'product_string': u'HIDI2C Device'}, {'usage_page': 65280, 'product_id': 1, 'interface_number': -1, 'manufacturer_string': u'SatoshiLabs', 'vendor_id': 21324, 'release_number': 256, 'serial_number': u'C1A090238C62E9ADBAF9AB46', 'usage': 1, 'path': '\\\\?\\hid#vid_534c&pid_0001#6&17f09dbe&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}', 'product_string': u'TREZOR'}]
```

**Comment by slush0** [comment] 2016-10-08 14:45
Looks like the TREZOR is not even listed. Can you please check Device manager in Windows to check if there's some collision/issue with HID drivers? If so, please try "Detect new hardware", it should get fixed. Then please send the enumerate again.

**Comment by prusnak** [comment] 2016-10-08 14:46
It is listed, at the end. But this is not U2F enabled TREZOR (pre-1.4.0 FW). Do you say you have problem even with this one? Then it is unrelated to recent changes in FW.

**Comment by ecdsa** [comment] 2016-10-08 14:47
yes it is listed, the last item

**Comment by slush0** [comment] 2016-10-08 14:49
Yes, I noticed after the comment and delete it. Now I'm checking if everything match here.

**Comment by slush0** [comment] 2016-10-08 14:53
Everything seems ok. vendor, product_id, usage page, everything seems just fine. So I expect Electrum see the device, but cannot connect? That should trigger some exception, at least here: https://github.com/trezor/python-trezor/blob/master/trezorlib/transport_hid.py#L64

**Comment by ecdsa** [comment] 2016-10-08 15:48
it looks like an issue caused by pyinstaller
from the console I can import trezorlib, but it does not find trezorlib.client

**Comment by ecdsa** [comment] 2016-10-08 16:03
fixed in c5a591123dd223ffc253cb403a3b0928d7d0af5f
I will close the issue after I release new binaries

**Comment by ecdsa** [comment] 2016-10-08 17:11
2.7.3 binaries are there

**Closed by ecdsa** 2016-10-08 17:11 UTC

**Comment by slush0** [comment] 2016-10-09 14:02
Thank you very much!
