### ISSUE TITLE
Electrum offline with Ledger HW is unable to sign transactions

### ISSUE THREAD

**Issue by gianlucamazza** [spesmilo/electrum#4017] opened 2018-03-04 16:08 UTC
i've a problem signing a transaction using the following setup:

scenario 1: (working as expected)
created an electrum testnet wallet using a standard seed in --offline mode
created an electrum testnet watchonly wallet using xpub
created n transactions from watchonly and saved to file several times
I had no problems also signing transactions for addresses that i didn't have in first 20 addresses on my offline wallet

scenario 2: (not working, ledger is unable to sign offline transactions)
created an electrum testnet wallet using a ledger hardware wallet in --offline mode
created an electrum testnet watchonly wallet using xpub
If i try to sign an offline transaction I always get an error:
'NoneType' object has no attribute 'raw'

<img width="862" alt="schermata 2018-03-04 alle 16 53 51" src="https://user-images.githubusercontent.com/25006045/36947586-90d38b92-1fce-11e8-8c99-07515aed5d38.png">

**Comment by SomberNight** [comment] 2018-03-04 19:44
dupe of https://github.com/spesmilo/electrum/issues/3302

**Closed by SomberNight** 2018-03-04 19:45 UTC
Labels: bug, duplicate
