### ISSUE TITLE
Problems signing Transactions with Ledgers in 2.9.3

### ISSUE THREAD

**Issue by derHase85** [spesmilo/electrum#2822] opened 2017-08-30 14:03 UTC
I got following error, when signing with ledger and trying to transfer a transaction with 2.9.3

error: The transaction was rejected by network rules.  (16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation))

In 2.8.3 it's working without problems.

If I save the transaction in 2.9.3 and try to sign it in 2.8.3 with the ledger I got following output in the console:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/ledger/ledger.py", line 353, in sign_transaction
    format_satoshis_plain(tx.get_fee()), changePath, bytearray(rawTx.decode('hex')))
  File "/usr/local/lib/python2.7/dist-packages/electrum/transaction.py", line 780, in get_fee
    return self.input_value() - self.output_value()
  File "/usr/local/lib/python2.7/dist-packages/electrum/transaction.py", line 774, in input_value
    return sum(x['value'] for x in self.inputs())
  File "/usr/local/lib/python2.7/dist-packages/electrum/transaction.py", line 774, in <genexpr>
    return sum(x['value'] for x in self.inputs())
KeyError: 'value'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/util.py", line 582, in run
    result = task.task()
  File "/usr/local/lib/python2.7/dist-packages/electrum/wallet.py", line 1118, in sign_transaction
    k.sign_transaction(tx, password)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/ledger/ledger.py", line 382, in sign_transaction
    self.give_error(e, True)
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/ledger/ledger.py", line 197, in give_error
    raise Exception(message)
Exception: 'value

[signed_365c3b2b_2.8.3.txt](https://github.com/spesmilo/electrum/files/1263822/signed_365c3b2b_2.8.3.txt)
[signed_ebf08e20_2.9.3.txt](https://github.com/spesmilo/electrum/files/1263821/signed_ebf08e20_2.9.3.txt)

**Comment by ecdsa** [comment] 2017-08-30 15:22
duplicate of #2645

**Closed by ecdsa** 2017-08-30 15:22 UTC
