### ISSUE TITLE
With no hardware wallet connected, attempting to use one causes tracebacks and hung GUI.

### ISSUE THREAD

**Issue by fortran77** [spesmilo/electrum#1772] opened 2016-04-25 00:26 UTC
Electrum 2.6.4, Ubuntu 14.04.4 LTS.

With no hardware wallet connected, attempting to use one causes two tracebacks and a hung GUI.

After invoking electrum from the shell command-line, I use the menu commands shown below.

    File => New/Restore => (accept default filename 'wallet_1') OK =>
      select "Create a new wallet"
      and also select "Hardware wallet" =>
    Next =>
      select any of the three visible options (see Note 1), e.g.,
        "Restore Electrum wallet from device seed words" =>
    Next

A traceback occurs, and I see a small pop-up window with the error message "Error list index out of range" and an OK button.  After I click on the OK button I see a window that says "Please wait..." and the second traceback occurs and the GUI then hangs. I have to hit ^C on the command line to make electrum exit.

I have no hardware wallet connected to this machine nor any software driver for any hardware wallet.

Note 1. The screen does not list any hardware wallets to choose from.

    % electrum
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/installwizard.py", line 165, in run
        wallet = WizardBase.run(self, *args)
      File "/usr/local/lib/python2.7/dist-packages/electrum/wizard.py", line 151, in run
        cr, wallet = self.create_or_restore(storage)
      File "/usr/local/lib/python2.7/dist-packages/electrum/wizard.py", line 225, in create_or_restore
        wallet_type = hw_wallet_types[choice]
    IndexError: list index out of range
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/main_window.py", line 399, in new_wallet
        self.gui_object.start_new_window(full_path, None)
      File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/__init__.py", line 163, in start_new_window
        wallet = self.daemon.load_wallet(path, self.get_wizard)
      File "/usr/local/lib/python2.7/dist-packages/electrum/daemon.py", line 188, in load_wallet
        wallet = wizard.run(self.network, storage)
      File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/installwizard.py", line 165, in run
        wallet = WizardBase.run(self, *args)
      File "/usr/local/lib/python2.7/dist-packages/electrum/wizard.py", line 151, in run
        cr, wallet = self.create_or_restore(storage)
      File "/usr/local/lib/python2.7/dist-packages/electrum/wizard.py", line 225, in create_or_restore
        wallet_type = hw_wallet_types[choice]
    IndexError: list index out of range
    ^C%

**Comment by ecdsa** [comment] 2016-05-19 05:26
closing, duplicate of #1793

**Closed by ecdsa** 2016-05-19 05:26 UTC
