### ISSUE TITLE
Android: Something went wrong while executing Electrum

### ISSUE THREAD

**Issue by IgnacioGioia** [spesmilo/electrum#8375] opened 2023-05-02 14:01 UTC
I'm trying to send some bitcoin to another wallet I own. Everything goes normally, I enter the amount and the wallet address and after I enter the code from trustedcoin a screen pops off saying: Sorry! Something went wrong while executing Electrum. If I check the report contents it lists a bunch of python files and ends with TypeError: bool object is not callable

**Comment by accumulator** [comment] 2023-05-02 14:39
duplicate of #8368.
Fixed in 4.4.2, which we are planning to release this week.
Sorry for the inconvenience.

**Closed as completed by accumulator** 2023-05-02 14:39 UTC
