### ISSUE TITLE
Starting problem

### ISSUE THREAD

**Issue by mlauronen** [spesmilo/electrum#2863] opened 2017-09-12 11:16 UTC
Yesterday I installed the latest version of Electrum application into my Windows 10 and it worked ok. Today I am trying to start the app by the icon on my desktop. The app starts and the "ELectrum - Install Wizard" window is opened asking my password for the chosen wallet. I type in the password. After pressing "Next" button the window will disappear and the app process dies. The application does not start. 

What could be the reason for this, what to do next and how to fix ?

**Comment by ecdsa** [comment] 2017-09-12 12:19
do you have funds in this wallet? if yes, you should restore it from seed.

the reason for your issue cannot be determined without having a look at the wallet file.
if you send me the file and the password I can have a closer look. 
(remove all your funds from your wallet before you send it to me)

**Comment by mlauronen** [comment] 2017-09-12 12:36
There is no funds in it. To what email you need me to send the stuff ?

**Comment by ecdsa** [comment] 2017-09-12 12:37
electrumdev@gmail.com

**Comment by mlauronen** [comment] 2017-09-12 12:44
btw. If I backup the wallet file and years after when Electrum dosn't exists anymore how can I decrypt the wallet file to see the private key(s) ?

I of course know my password and seed.

**Comment by ecdsa** [comment] 2017-09-13 06:49
issue was caused by utf8 in the path
it is fixed in git master

**Closed by ecdsa** 2017-09-13 06:49 UTC
