### ISSUE TITLE
Electrum will olny let me send 1/3 of balance

### ISSUE THREAD

**Issue by jsylvers** [spesmilo/electrum#2066] opened 2016-12-06 01:39 UTC
Balance says it is .0015... and when I go to sweep it to another wallet I can only send .00046...I know there are fees involved, but I have yet to pay over .001 to send bitcoin and this is just to transfer to another wallet I've been using.

**Comment by dabura667** [comment] 2016-12-06 01:50
Currently the network is shitting itself and fees are high.

It looks like your 0.0015 was not given to you in one transaction, but it was given to you over the span of 4-5 transactions. This also increases your fees, as every transaction's ID must be referenced in the spending transaction.

**Comment by jsylvers** [comment] 2016-12-06 02:19
6 but yes I see that now. should I use ! to get them to combine? And as I forgot to add the version # it is 2.7.9

**Comment by ecdsa** [comment] 2016-12-06 05:50
the 'sweep' function does not include unconfirmed coins, maybe that's your issue?

**Comment by jsylvers** [comment] 2016-12-06 07:34
The only unconfirmed transaction is the one where I sent it to another wallet to see what would happen and now it won't let me send any of the remaining balance.

https://blockchain.info/address/1FiXZtUgGC5uA4r3WrokytpWqiiSkPXQDk

Not much in there to worry about, but I don't like unfinished business so to speak.

**Comment by ecdsa** [comment] 2016-12-07 12:52
please provide more information.
there's no way we can help you with this level of detail.
what are the addresses/balances involved?
which server are you using?

**Comment by ecdsa** [comment] 2016-12-07 12:57
well, I think this post is just about miner fees being too high, not about some bug. 
closing.

**Closed by ecdsa** 2016-12-07 12:57 UTC
