### ISSUE TITLE
Electrum R6034 error

### ISSUE THREAD

**Issue by HarrySkySon** [spesmilo/electrum#1880] opened 2016-07-28 06:07 UTC
I run 64bit Windows operating system. Every time I open Electrum it I get this error message: R6034 An application has made an attempt to load the C runtime library incorrectly. 

How can I fix it?

**Comment by ecdsa** [comment] 2016-08-02 08:02
closing, because duplicate of #1000
some users reported that renaming the file as 'electrum.exe' fixes it

**Closed by ecdsa** 2016-08-02 08:02 UTC
