### ISSUE TITLE
Android version 2.8.2 force close when filling in Description field

### ISSUE THREAD

**Issue by darwusch** [spesmilo/electrum#2624] opened 2017-07-22 12:29 UTC
Hi,
When I pay with Electrum (android version 2.8.2) and scan a QR-code, it fills in the address and amount correctly.
However, when I add a description in the Description field, it force closes.
Please fix.

**Comment by darwusch** [comment] 2017-07-22 23:25
Update:
I used the Gboard keyboard, and after switching to the standard android keyboard it worked fine.
Wonder why the Gboard isn't working with Electricum though.

**Comment by randyperkins** [comment] 2017-07-31 09:50
Similar issue with newer version.  **Google play store says 2.9.0.1 while the app itself states 2.9.0**
Phone Nexus 6.  Android 7.1.1 with security patches thru July 5, 2017.
The Standard Keyboard is Gboard.  There is no option for 'standard android keyboard' on phone.  Additional keyboards installed are 'Hackers Keyboard' and 'Google Voice Typing"

Issue:
I was filling out a description field to change the Server.  This is under Network...Server.  The app would force close when filling out the 'Port' field.  Interestingly, If Iput a letter in the field it did not force close.  when I tried to put a number in the 'Port" field , the app force closed.  This occcured using 'The Hackers Keyboard' and 'Gboard'.

**I was able to work around this issue by selecting 'Google Voice Typing' as my keyboard and speaking the 'port'**.  If I recall the 'Host' field worked fine but my host does not have any numbers in it.

**Thanks for all the work on electrum**.  I hope I dont muddle things up by mentioning here that being able to select the --oneserver option from within the GUI would be great although I dont expect a lot of users would be needing that option.

Many thanks to the OP for opening this issue as it narrowed the problem down for me an I was able to find a workaround.

**Comment by ecdsa** [comment] 2017-07-31 22:41
duplicate of #2333

**Comment by ecdsa** [comment] 2017-08-04 10:35
should be fixed with APK 2.9.2.1
Please confirm

**Closed** 2017-08-04 10:39 UTC

**Comment by darwusch** [comment] 2017-08-04 10:49
Confirmed, thanks for fixing!

**Comment by randyperkins** [comment] 2017-08-04 12:02
confirmed.  working now with 
Phone Nexus 6. Android 7.1.1 with security patches thru July 5, 2017.
Thanks for the quick response
