### ISSUE TITLE
Error "No module named websocket" When Signing Transaction With Ledger/Electrum

### ISSUE THREAD

**Issue by jwbats** [spesmilo/electrum#3542] opened 2017-12-17 14:21 UTC
I've restored one of my Ledger accounts, which has confirmed balanced, but which has unconfirmed parent accounts.

When I want to transfer this balance into another account and it's time to sign the transaction, it will show a popup saying "No module named websocket".

People running Linux have been able to solve this by installing the websocket python library. However, nobody seems to have a solution for Win10 users.

**Comment by bauerj** [comment] 2017-12-17 14:28
Hmm, this should probably be included in the binary then.

Just to confirm, you use Electrum 3.0.3? The installer version?

**Comment by SomberNight** [comment] 2017-12-17 18:36
Is this with a Ledger HW.1?

And if so, is this issue a duplicate of https://github.com/spesmilo/electrum/issues/2433 ?

**Comment by jwbats** [comment] 2017-12-17 20:35
I'm using Electrum 3.0.3 (installer version) with a Ledger Nano S on Win10.

**Comment by ecdsa** [comment] 2017-12-18 09:23
definitely a duplicate of #2433

**Closed by ecdsa** 2017-12-18 09:23 UTC
