### ISSUE TITLE
jus ton other bug

### ISSUE THREAD

**Issue by stanch3vv** [spesmilo/electrum#2419] opened 2017-05-18 08:18 UTC
After i waitet 7 days for confirmations, the trasaction just disapeared from my wallet but the coins are frozne....so i cna not check my trasaction ID anymore cause there is no info about in my wallet.The coins are still there but i can not use them, its super sick.Really working with your wallet id very slow and difficult sometimes

**Comment by EagleTM** [comment] 2017-05-18 08:22
This is less an issue with Electrum but more of an issue with scaling the Bitcoin network. There are currently hundredthousand transactions to be included in the blockchain, however we have a 1 MB limit per ~10 minutes. Transactions which pay less fees (and I wouldn't even say "low" because we have high fees on the network currently) are not being mined and will eventually fall out of the memorypool meaning no server you use will have a record for it. You can try spending coins again using a higer fee. Use fee estimates and replace by fee to be able to bump the fee further.

This is not a bug in Electrum but the way Bitcoin is currently designed, so I'm closing.

**Closed by EagleTM** 2017-05-18 08:22 UTC

**Comment by stanch3vv** [comment] 2017-05-18 13:42
how can i pay hier tax using your wallet electrum?>
