### ISSUE TITLE
Conversion plug-in stopped working

### ISSUE THREAD

**Issue by zanglebert** [spesmilo/electrum#1161] opened 2015-04-26 22:26 UTC
New installation of Electrum on OS X 10.10.3, via Electrum executable for OS X, version 2.1.1

Previously the conversion feature via plugin worked, but not anymore. Neither total wallet value in USD is displayed, nor is the BTC amount in the 'send' window converted to USD (or another currency).

Already tried disabling and re-enabling the plugin, as well as picking a different conversion rate source - none of which helped.

**Comment by ecdsa** [comment] 2015-04-27 08:14
it works for me

**Comment by ecdsa** [comment] 2015-04-27 10:03
bug confirmed by my officemate, running osx binary

**Comment by ecdsa** [comment] 2015-04-28 10:21
it should be fixed by 77648c284f069b743edd5df38f7bbee85be00a2d
I'll wait until it's tested on binaries before closing this.

**Comment by maran** [comment] 2015-05-20 19:17
Confirmed working now, closing.

**Closed by maran** 2015-05-20 19:17 UTC
