### ISSUE TITLE
Modify Unconfirmed Transactions

### ISSUE THREAD

**Issue by jeffersoncarpenter** [spesmilo/electrum#2371] opened 2017-04-25 23:40 UTC
There are lots of modifications that you might want to make to unconfirmed transactions, such as:

* Change destination address
* Increase or decrease fee
* Change payment amount
* Add or remove availability criteria

Double-spending attacks can achieve all of those easily.  I think you should implement those, and fall back on nicer features such as RBF when possible.

**Comment by EagleTM** [comment] 2017-07-08 10:59
RBF is supported, just enable in config and mark your transaction as "replaceable" before sending.

"Change destination address" / "Change payment amount" requires full RBF which only a low percentage of bitcoind and even fewer electrum servers support. I'm aware there are miners supporting full RBF so there is a good chance for to succeed, but there is also a political component whether to offer this.  At most it requires detection whether the server supports it, which needs to be implemented server side first.

**Comment by gaillard** [comment] 2017-12-27 00:31
I just ran across this today and would love to be able to create new transactions that use unconfirmed inputs to a prior RBF transaction. You say the backend would need support, but at least if we can get a raw signed tx out of electrum, we could then find a miner ourselves or broadcast to a different set of peers. How does that sound?

**Comment by ecdsa** [comment] 2019-09-13 06:56
closing, duplicate of #2228.

**Closed by ecdsa** 2019-09-13 06:56 UTC
Labels: enhancement
