### ISSUE TITLE
No USD price while on TOR network

### ISSUE THREAD

**Issue by annaparker** [spesmilo/electrum#7820] opened 2022-05-19 10:32 UTC
When I am connected through proxy SOCKS5 TOR the USD price next to BTC amount won't show up. When I disable proxy it works. I am using latest win 4.2.1 version.

**Comment by SomberNight** [comment] 2022-05-19 11:54
duplicate of https://github.com/spesmilo/electrum/issues/6738 and https://github.com/spesmilo/electrum/issues/6407

**Closed by SomberNight** 2022-05-19 11:54 UTC
