### ISSUE TITLE
Labels broken in 2.3.2

### ISSUE THREAD

**Issue by aussiehash** [spesmilo/electrum#1299] opened 2015-06-17 03:16 UTC
Using the latest `git pull` on OSX

The "labels" function is completely broken (not using the label sync plugin)

* opening an existing wallet created with Electrum 2.x *initially* displays the correct account names
  - changing electrum server wipes all account names
  - closing electrum and reopening wipes all account names
  - opening another wallet file wipes all account names

* creating a new wallet > hardware wallet > trezor
  - all BIP32/39/44 wallets are listed with correct balances
  - renaming the "Main account" label, then renaming "Account 1" reverts the first label change
  - renaming any account label reverts the previous rename
  - closing electrum and reopening, no label changes are recorded.

* the wallet file's has "labels" field is wiped by 2.3.2
    `"labels": {}, `

**Comment by CyberLizard** [comment] 2015-07-20 22:36
I do have labels but they are A causing lag on busy wallets with syncing and I guess checking vs label sync if they are up to date and clicking on force up-/download in the plugin settings returns http://prntscr.com/7v13bp

**Comment by RustyNomad** [comment] 2015-08-14 16:06
I found a solution to the problems with the labels.

Please see the post I made on bitcointalk.org

https://bitcointalk.org/index.php?topic=1152932.msg12140527#msg12140527

**Comment by aussiehash** [comment] 2015-08-15 10:22
Still broken, @RustyNomad I see you've closed your issue submission

**Comment by ecdsa** [comment] 2015-08-15 11:45
isn't this a dupe of #1158 ?

**Comment by aussiehash** [comment] 2015-08-16 12:02
Well I'm not sure when the bug snuck in, it does not exist in the 2.0 beta releases. For example I think "seed 7" works fine.

**Closed** 2015-08-17 10:49 UTC

**Comment by aussiehash** [comment] 2015-08-18 10:41
Thanks ! Works perfectly.

**Comment by CyberLizard** [comment] 2015-08-22 16:22
I was referencing tx labels not account labels. However this seems to be resolved, labels are now syncing fine for me. http://prntscr.com/87mwc2
