### ISSUE TITLE
Android cannot export backup wallet

### ISSUE THREAD

**Issue by dnsdev9** [spesmilo/electrum#7327] opened 2021-06-01 08:42 UTC
When click on backup it is showed failed to shave wallet backup error no1 operations no permitted.

**Comment by SomberNight** [comment] 2024-02-07 11:31
This was likely a duplicate of https://github.com/spesmilo/electrum/issues/6774.
There is a newer issue to re-implement this functionality in the qml gui: https://github.com/spesmilo/electrum/issues/8851

**Closed by SomberNight** 2024-02-07 11:31 UTC
