### ISSUE TITLE
Unable to choose language at first start

### ISSUE THREAD

**Issue by un1t** [spesmilo/electrum#4618] opened 2018-08-08 20:18 UTC
I showed how to use Electrum to my not english speeking friends. 
Language of operating system was russian, but all texts was in english. Even settings unavailable until you create a first wallet.
I think at first launch language should be the same as OS language. And maybe there should be dropdown where user can change language.

**Comment by un1t** [comment] 2018-09-19 08:17
This issue could be split into two parts.
1. Use system language by default
2. Allow user to chose other language at first launch

I've made PR for the first part https://github.com/spesmilo/electrum/pull/4724

**Comment by SomberNight** [comment] 2021-09-15 17:55
> 1. Use system language by default
>     b. for Kivy GUI

1/b is now done in https://github.com/spesmilo/electrum/commit/7cb11ceda4d0191ca3e91be22812d967f46b85ec

**Comment by SomberNight** [comment] 2022-03-22 16:25
>> 1. Use system language by default
>>     b. for Kivy GUI
>
> 1/b is now done in https://github.com/spesmilo/electrum/commit/7cb11ceda4d0191ca3e91be22812d967f46b85ec

I had to revert the kivy change (https://github.com/spesmilo/electrum/commit/25fee6a6be7e8e4bb8a0a62ef6737f6019d372e4) as some languages we have translations for cannot be displayed at all in kivy due to font issues (https://github.com/spesmilo/electrum/issues/2032), so those cannot be defaulted to...

**Comment by lionkmp** [comment] 2023-04-09 18:21
I have the same problem on **Android**. It would be excellent if the program could use the operating system's language at start. Thanks in advance.

(I'm trying to teach Electrum to friends, but only 28% of Hungarians know any second language. Only a quarter of that on "usable" level - according to some stats. Thus I'm working on completing the translation.)

**Comment by accumulator** [comment] 2023-04-11 14:32
The QML Android version now defaults to the system locale. 4d5be450d9aec7078112af2428bbf7fa1d428c6e

@lionkmp: This new version is not completely translated yet, it would be great if you can help out translating hungarian before 4.4.0 gets released!

https://crowdin.com/project/electrum/hu

**Comment by lionkmp** [comment] 2023-04-12 20:32
@accumulator Thank you, that's great news. Yes, I'm working on the Hungarian translation since days. It's a lot of work because I verify everything - and don't know some of the features, so I read a lot of howto-s. What's the 4.4 deadline? Thanks.

**Comment by accumulator** [comment] 2023-04-13 07:34
> What's the 4.4 deadline?

Soon ™

**Comment by accumulator** [comment] 2023-11-14 12:37
I verified that Electrum uses system locale by default on both Android and Linux. 
Haven't tested on Windows or MacOS.

**Comment by lionkmp** [comment] 2023-11-17 22:37
Tested on Windows with deleting the Electrum App_Data folder and the "how to connect" first dialog comes up well in the UI language (tested with Hungarian). So I think this is OK.

**Comment by accumulator** [comment] 2023-11-20 10:29
@SomberNight if you can confirm MacOS, we can probably close this..

**Comment by lionkmp** [comment] 2023-11-20 22:09
Mac correct language startup confirmed. Danish, poorly translated, 7%, but the OS language is picked by the program:

![electrum_mac](https://github.com/spesmilo/electrum/assets/5088657/d3681b2e-10b2-4c1d-9c03-bc956ede09b7)

**Comment by accumulator** [comment] 2023-11-21 08:50
Ok, thanks! 

Closing.

**Closed by accumulator** 2023-11-21 08:50 UTC
Labels: enhancement ✨, user-interface 🔲, localization 🌍
