### ISSUE TITLE
Electrum 2.6.4 issue with TREZOR

### ISSUE THREAD

**Issue by peca23** [spesmilo/electrum#1786] opened 2016-05-04 14:58 UTC
I try to set up Electrum with Trezor for Ubuntu but failed. First, I went to https://electrum.org/#download 
and install the latest Electrum 2.6.4. with easy installation option:

sudo apt-get install python-qt4 python-pip sudo pip install https://download.electrum.org/2.6.4/Electrum-2.6.4.tar.gz 

Then I connected previously pre-set Trezor and in Electrum checked "Create a New Wallet" and chose "Hardware Wallet" and on the next page checked "Use the device you have already set up". And then every time I push Next button, I receive "list index out range" error and Electrum collapses. Please, help.

Source: https://www.reddit.com/r/Bitcoin/comments/4hq6i9/intall_electrum_264_with_trezor_support_for/

**Comment by slush0** [comment] 2016-05-06 13:00
Cannot replicate / worksforme (Ubuntu/Mint).

**Comment by kyuupichan** [comment] 2016-05-07 01:43
Please can you run from the command line with -v and paste the back trace.
Is the device plugged in?

**Comment by peca23** [comment] 2016-05-10 13:16
[Plugins] registering wallet keepkey: ('hardware', 'keepkey', u'KeepKey wallet')
[Plugins] registering wallet ledger: ('hardware', 'btchip', u'Ledger wallet')
[Plugins] registering wallet trezor: ('hardware', 'trezor', u'TREZOR wallet')
[Plugins] registering wallet trustedcoin: ('twofactor', '2fa', u'Wallet with two-factor authentication')
[profiler] __init__ 0.0033
[Network] starting network
[Network] connecting to electrum.thwg.org:50002:s as new interface
[WalletStorage] wallet path /home/xxx/.electrum/wallets/default_wallet
[Blockchain] 411160 blocks
[electrum.thwg.org] cannot resolve hostname
[Plugins] loaded trezor
[profiler] load_transactions 0.0001
[profiler] build_reverse_history 0.0000
[profiler] check_history 0.0001
[ilikehuskies.no-ip.org] connected
[Network] switching to ilikehuskies.no-ip.org:50002:s
[Network] sending subscriptions to ilikehuskies.no-ip.org:50002:s 0 0
[electrum3.hachre.de] connected
[electrum.no-ip.org] connected
[erbium1.sytes.net] connected
[Network] recommended fee 30043
[bitcoins.sk] saving certificate
[bitcoins.sk] connected
[ElectrumWindow/default_wallet] Notifying GUI
[46.166.162.163] connected
[Network] relayfee 1000
[electrum.dragonzone.net] connected
[btc.smsys.me] connected
[profiler] save_transactions 0.0001
[WalletStorage] wallet path /home/xxx/.electrum/wallets/wallet_1

(python:5311): Gtk-CRITICAL **: IA__gtk_widget_get_direction: assertion 'GTK_IS_WIDGET (widget)' failed

(python:5311): Gtk-CRITICAL **: IA__gtk_widget_get_direction: assertion 'GTK_IS_WIDGET (widget)' failed
[Plugins] loaded ledger
[Plugins] loaded keepkey
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum_gui/qt/installwizard.py", line 165, in run
    wallet = WizardBase.run(self, *args)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wizard.py", line 151, in run
    cr, wallet = self.create_or_restore(storage)
  File "/usr/local/lib/python2.7/dist-packages/electrum/wizard.py", line 225, in create_or_restore
    wallet_type = hw_wallet_types[choice]
IndexError: list index out of range

**Comment by peca23** [comment] 2016-05-10 13:18
It happens in both cases when I have wiped TREZOR or even one which is set up already

**Comment by kyuupichan** [comment] 2016-05-10 22:49
@peca23 Thanks for this.  I cannot understand how this happens though.  Can you add some lines to print information?

IN wizard.py:

            hw_wallet_types, choices = self.plugins.hardware_wallets(action)
            msg = _('Select the type of hardware wallet: ')
            action, choice = self.query_hw_wallet_choice(msg, action, choices)
            wallet_type = hw_wallet_types[choice]

the first line can only return arrays of the same size.  It crashes on the last line.  It'd be good to know, just before that line, what "choice", "choices" and "hw_wallet_types" are.

**Comment by ecdsa** [comment] 2016-05-18 16:53
closing as duplicate of #1807

**Closed by ecdsa** 2016-05-18 16:53 UTC

**Comment by kyuupichan** [comment] 2016-05-18 22:43
https://github.com/spesmilo/electrum/commit/11ef0f5489f0df8812cc2e9cad1d70aab2a72fbe fixes this I believe
