### ISSUE TITLE
Electrum detects two Trezor devices instead of 1

### ISSUE THREAD

**Issue by jonaszaheda** [spesmilo/electrum#5284] opened 2019-04-23 18:03 UTC
Electrum detects two Trezor devices but I have only 1 device pluged in. 

It happend after 3.3.4 update
running on windiws 7

attached printscreen.
![electrum_bug](https://user-images.githubusercontent.com/19964772/56604933-5fd15480-6603-11e9-9deb-65e29fdcdd55.png)

**Comment by jonaszaheda** [comment] 2019-04-23 18:57
btw. before opening this I have found this https://www.reddit.com/r/TREZOR/comments/6ix3qs/trezor_with_electrum_two_devices_detected/

seems like somebody had this issue before but i couldn´t find it here

**Comment by SomberNight** [comment] 2019-04-23 19:27
You can see that the two options are not identical.
The same device is detected through the Trezor Bridge software which apparently you have installed; and also directly as a low level USB device (through hidapi). In some cases one might work, the other might not; or one might not even show up (like if you don't have Trezor Bridge installed).

I agree that all this machinery could be hidden from the user and the software could detect that these interfaces resolve to the same device, and intelligently try both of them if one fails; however this is not implemented and I would consider it really low priority.

**Comment by jonaszaheda** [comment] 2019-04-23 20:03
Thank you for explanation,
as a non-technical user I was worried this could be dangerous.

Can we tell which option is better/safer or is it ambiguous?

.

**Comment by SomberNight** [comment] 2019-04-23 20:35
You can choose either, and you don't even have to remember which one you chose, it does not matter. In some (probably rare) cases one might not work, then just choose the other.

**Comment by jonaszaheda** [comment] 2019-04-23 20:40
Ok, thank you

**Comment by ecdsa** [comment] 2019-04-25 12:34
not sure if we want to "fix" this.

**Comment by sandrokensan** [comment] 2019-05-05 20:57
I have the same issue, I have installed a low level USB device (through hidapi) and also the bridge for install the firmware, so I have the two options. The bridge option works but the second option has timeout and the display on the trezor's screen of the words seed don't reset the timeout coundown.
So after some minutes Electrum show a message that Trezor is off line.

**Comment by prusnak** [comment] 2020-06-25 12:35
I tested this with Electrum 4.0.0b0 and the issue is no longer present. This can be closed.

The issue was fixed via the change in https://github.com/spesmilo/electrum/commit/fb76fcc886b7c999387a6676f479678df742fdaa#diff-d340122daff15ed7703f584dd191bc92R141-R150

**Closed** 2020-06-25 13:34 UTC
Labels: enhancement, hw-trezor, priority-low
