### ISSUE TITLE
lost transaction

### ISSUE THREAD

**Issue by ghost** [spesmilo/electrum#2404] opened 2017-05-14 16:54 UTC
I just bought 0.1 bitcoin. I have seen the transaction in the history list and updated balance. But then after reloading transaction disappeared and balance became an old one. What has happened?

**Comment by bauerj** [comment] 2017-05-14 16:56
Not sure. Was the transaction marked as confirmed?

**Comment by Vova1979** [comment] 2017-05-14 17:01
Yes, and history you can see on https://blockchain.info/address/1PqjQnvbt2SUZouz97p1SksL4CN4vKj7uV for wallet address 1PqjQnvbt2SUZouz97p1SksL4CN4vKj7uV 
Outgoing transactions I have for 0.005 and 0.041931 but just lost incoming 0.1 BTC. How could it happen?

**Comment by bauerj** [comment] 2017-05-14 17:03
Are you sure that address is part of the wallet you opened? What happens when you restart Electrum?

**Comment by Vova1979** [comment] 2017-05-14 17:06
I have seen transaction. I have only one wallet and pretty sure about address. When I restart Electrum I saw updated amount for a second but the it just changed for an old one and transaction disappeared from the history list.

**Comment by Vova1979** [comment] 2017-05-14 17:42
and previously I received another amount on the same wallet

**Comment by ConTrast77** [comment] 2017-05-27 09:04
A similar situation.
The transaction "unconfirmed" appears. Disappears, appears after 15 seconds. Re-entry into the program. 2 times. Then it's fine. But several times changed the status between "unconfirmed" and "unconfirmed parent".

**Comment by EagleTM** [comment] 2017-06-13 11:28
Unconfirmed transactions are not on the blockchain yet. 

They are checked against the server you are using and it depends whether it's in the mempool of that server. If it's not it's dropped from the history GUI. This can change if you switch servers (or if electrum does it automatically because of lag / connection errors).

I don't see this a bug, it's intended behaviour so you can resend a transaction which has not propagated the network or if the transaction fell out of the memory pool of a server.

**Closed by EagleTM** 2017-06-13 11:28 UTC
