### ISSUE TITLE
Cannot connect to a server - history too long 

### ISSUE THREAD

**Issue by dvelchev1** [spesmilo/electrum#7407] opened 2021-07-14 14:07 UTC
Cannot connect to any server, the log keeps returning the same error "history too long".

Error log:

> 20210714T134827.113035Z |     INFO | network | switching to electrum-btc.leblancnet.us:50002:s
> 20210714T134827.197684Z |     INFO | interface.[electrum.villocq.com:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed')))
> 20210714T134827.197684Z |     INFO | network | couldn't launch iface electrum.villocq.com:50002:s -- CancelledError()
> 20210714T134827.629724Z |     INFO | network | fee_histogram [[66, 102322], [27, 123126], [20, 108334], [3, 147937], [1, 197013]]
> 20210714T134828.285050Z |    ERROR | interface.[electrum-btc.leblancnet.us:50002] | disconnecting due to GracefulDisconnect(RPCError(1, 'history too large'))
> 20210714T134828.385118Z |     INFO | network | switching to 188.230.155.0:50002:s
> 20210714T134828.469799Z |     INFO | network | fee_histogram [[66.6, 100151], [27.3, 118152], [15.5, 121180], [3.0, 133656], [1.0, 194940]]
> 20210714T134828.839279Z |     INFO | interface.[109.248.206.13:50002] | connection established. version: ['ElectrumX 1.16.0', '1.4']
> 20210714T134829.004259Z |     INFO | interface.[109.248.206.13:50002] | set blockchain with height 690992
> 20210714T134829.004259Z |     INFO | interface.[109.248.206.13:50002] | skipping header 690992
> 20210714T134829.004259Z |    ERROR | interface.[188.230.155.0:50002] | disconnecting due to GracefulDisconnect(RPCError(1, 'history too large'))
> 20210714T134829.117854Z |     INFO | network | switching to hodlers.beer:50002:s
> 20210714T134829.255997Z |     INFO | interface.[electrum.leblancnet.us:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed')))
> 20210714T134829.255997Z |     INFO | network | couldn't launch iface electrum.leblancnet.us:50002:s -- CancelledError()
> 20210714T134829.387817Z |     INFO | interface.[bitcoin.corgi.party:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(gaierror(11001, 'getaddrinfo failed')))
> 20210714T134829.387817Z |     INFO | network | couldn't launch iface bitcoin.corgi.party:50002:s -- CancelledError()
> 20210714T134829.434710Z |     INFO | network | fee_histogram [[66, 101280], [21, 130993], [9, 123481], [1, 245438]]
> 20210714T134829.835907Z |     INFO | interface.[electrum.emzy.de:50002] | connection established. version: ['ElectrumX 1.16.0', '1.4']
> 20210714T134829.905498Z |     INFO | interface.[electrum.emzy.de:50002] | set blockchain with height 690992
> 20210714T134829.920868Z |     INFO | interface.[electrum.emzy.de:50002] | skipping header 690992
> 20210714T134829.920868Z |    ERROR | interface.[hodlers.beer:50002] | disconnecting due to GracefulDisconnect(RPCError(1, 'history too large'))
> 20210714T134830.005590Z |     INFO | network | switching to electrum.emzy.de:50002:s
> 20210714T134830.159462Z |     INFO | network | fee_histogram [[79.3, 100436], [27.3, 126570], [20.1, 126424], [5.0, 148845], [1.0, 255906]]
> 20210714T134830.291091Z |    ERROR | interface.[electrum.emzy.de:50002] | disconnecting due to GracefulDisconnect(RPCError(1, 'history too large'))
> 20210714T134830.322337Z |     INFO | network | switching to 109.248.206.13:50002:s
> 20210714T134830.444861Z |     INFO | interface.[bitcoin.dermichi.com:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(OSError(22, 'The network location cannot be reached. For information about network troubleshooting, see Windows Help', None, 1231, None)))
> 20210714T134830.460535Z |     INFO | network | couldn't launch iface bitcoin.dermichi.com:50002:s -- CancelledError()
> 20210714T134830.460535Z |     INFO | interface.[VPS.hsmiths.com:50002] | connection established. version: ['ElectrumX 1.10.0', '1.4']
> 20210714T134830.476161Z |     INFO | network | fee_histogram [[69.1, 100005], [27.3, 124235], [17.9, 123127], [5.0, 142304], [1.0, 247307]]
> 20210714T134830.560887Z |     INFO | interface.[VPS.hsmiths.com:50002] | set blockchain with height 690992
> 20210714T134830.560887Z |     INFO | interface.[VPS.hsmiths.com:50002] | skipping header 690992
> 20210714T134830.777030Z |    ERROR | interface.[109.248.206.13:50002] | disconnecting due to GracefulDisconnect(RPCError(1, 'history too large'))
>

**Comment by SomberNight** [comment] 2021-07-15 15:00
duplicate of https://github.com/spesmilo/electrum/issues/4315
see that thread.

**Closed by SomberNight** 2021-07-15 15:00 UTC
