### ISSUE TITLE
2.6.4 -w switch does not work?

### ISSUE THREAD

**Issue by nikslab** [spesmilo/electrum#2161] opened 2017-02-11 04:09 UTC
_niks@niks-vostro:~/.electrum/wallets$_ **ls -al my_wallet**
-rw-r--r-- 1 niks niks 183544 Feb 11 11:55 my_wallet
_niks@niks-vostro:~/.electrum/wallets$_ **pwd**
/home/niks/.electrum/wallets
_niks@niks-vostro:~/.electrum/wallets$_ **electrum -v -w /home/niks/.electrum/wallets/my_wallet listaddresses**
Error: Wallet file not found.
Type 'electrum create' to create a new wallet, or provide a path to a wallet with the -w option
_niks@niks-vostro:~/.electrum/wallets$_ **ls -al /home/niks/.electrum/wallets/my_wallet**
-rw-r--r-- 1 niks niks 183544 Feb 11 11:55 /home/niks/.electrum/wallets/my_wallet
_niks@niks-vostro:~/.electrum/wallets$_ **electrum version**
2.6.4
_niks@niks-vostro:~/.electrum/wallets$_ **uname -a**
Linux niks-vostro 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:09:55 UTC 2017 i686 i686 i686 GNU/Linux

BTW if I just let it open GUI it will magically find the wallet and open it properly.

**Comment by nikslab** [comment] 2017-02-11 05:29
Update: upgraded to 2.8.0, problem fixed, but started again on the machine where I issued wallet.change_gap_limit(500) in the console.  Two machines, on one I did this and have the same problem, on another I didn't do it and don't have that problem.  Somehow issuing this console command screws up -w switch ?!?!?!?

**Comment by ecdsa** [comment] 2017-02-11 07:53
are you using symlinks?

**Comment by kyuupichan** [comment] 2017-02-11 07:54
sounds like it might be that python argparser bug

**Comment by nikslab** [comment] 2017-02-11 07:56
I don't think so.  Not on the wallet file and not on electrum executable.

**Comment by nikslab** [comment] 2017-02-11 07:58
It definitely started happening after I issued wallet.change_gap_limit(500) command in GUI console.  Not sure why that is related but 99% sure that caused it.  Fresh install fixes it.

**Comment by ecdsa** [comment] 2017-02-11 19:37
@kyuupichan can you reproduce it on your system?

**Comment by ecdsa** [comment] 2017-02-14 11:37
@nikslab is there a way to reproduce this ?

**Comment by ecdsa** [comment] 2017-02-16 14:51
closing, cannot reproduce.
from the report, it is unclear whether the bug occured with 2.8.0 or not

**Closed by ecdsa** 2017-02-16 14:51 UTC

**Comment by nikslab** [comment] 2017-02-18 03:53
It does happen in 2.8.0.  Not sure why it was unclear how to reproduce.  Issue wallet.change_gap_limit(500) in GUI console.  Shut down GUI.  Then try the -w switch. GUI continues to work fine and find wallets.

**Comment by ecdsa** [comment] 2017-02-18 17:55
can you check if it works with the following order:
`electrum listaddresses -v -w /home/niks/.electrum/wallets/my_wallet`

**Comment by nikslab** [comment] 2017-02-19 02:10
Yup!  That's it!  In that order it works!  When listaddresses command is at the end it doesn't.  Reminder: this is not a problem after a fresh install.  It only starts happening after I issue the wallet.change_gap_limit(500)  command (or maybe others I don't know).  Also reminder this is Ubuntu, it could be environmental. In any case, hopefully you are on to something....

**Comment by ecdsa** [comment] 2017-02-19 02:23
no, it has nothing to do with wallet.change_gap_limit().
it's a known issue, caused by some versions of argparse

**Comment by nikslab** [comment] 2017-02-19 02:40
Well it seems that somehow issuing wallet.change_gap_limit() (perhaps other things too) triggers it because there isn't a problem with fresh install.  Would it help then to change the official syntax to that order?  Command first, parameters later.  Tried it on another machine which I didn't break and where command-last works.  command-first also works on that machine.

**Comment by ecdsa** [comment] 2017-02-21 11:50
the argparse issue was fixed in aad8b4377ca09cee4c21864894a378dca8fdab75
