### ISSUE TITLE
Closing Lightning channel: "Funding transaction not found." & "Failed to close channel: TxBroadcastServerReturnedError"

### ISSUE THREAD

**Issue by Geremia** [spesmilo/electrum#7583] opened 2021-12-03 20:32 UTC
When I try to close a Lightning channel with master (Electrum 0df05dd), I get this error:
>Failed to close channel:
>TxBroadcastServerReturnedError('bad-txns-inputs-missingorspent\nYou might have a local transaction in your wallet that this transaction builds on top. You need to either broadcast or remove the local tx.')

[!["Failed to close channel" screenshot][1]][2]

I don't think I have any pending local transactions, so I'm not sure why it thinks I "might have a local transaction in your wallet that this transaction builds on top".

The channels I'm trying to force-close have been stuck on REESTABLISHING.

"Funding transaction not found."
[!["Funding transaction not found" screenshot][3]][2]

[A solution](https://bitcointalk.org/index.php?topic=5352784.msg57618089#msg57618089) in the BitcoinTalk.org post "[Electrum funds stuck in lightning. Unable to force close channel][2]" mentions correcting the funding_outpoint in my wallet, but in my case the funding transaction doesn't appear in my wallet.

Closing the channel with `close_channel` in the console makes Electrum hang.

  [1]: https://i.imgur.com/LmwJsU4.png
  [3]: https://i.imgur.com/62mSwpV.png
  [2]: https://bitcointalk.org/index.php?topic=5352784

**Comment by bitromortac** [comment] 2021-12-16 10:44
With latest master it is not possible to cooperatively close channels, which did not send lots of payments due to a regression, which should be fixed by #7588.

**Comment by SomberNight** [comment] 2022-11-06 05:24
so I guess this can be closed

**Closed by SomberNight** 2022-11-06 05:24 UTC
