### ISSUE TITLE
Electrum 4.5.2 Desktop - Invoices stuck on "unpaid" status

### ISSUE THREAD

**Issue by paboum** [spesmilo/electrum#8890] opened 2024-02-12 23:42 UTC
I don't use invoices, just manually input my transaction data as I want them.
Since 4.5.2 update, I have the following issue.
After I send the transaction, it shouldn't even appear on invoices list, but it does.
In "history", the "description" field is empty for transactions made after 4.5.2 (the older ones still display properly).
Instead, the description appears in the invoice. The transactions have cleared days ago, but still appear as unpaid invoices.

**Comment by SomberNight** [comment] 2024-02-22 10:44
I think this is probably a duplicate of https://github.com/spesmilo/electrum/issues/8842
Does your wallet file have a password and file-encryption enabled?

**Comment by paboum** [comment] 2024-02-22 14:47
Nope, I use full disk encryption.

**Comment by SomberNight** [comment] 2024-02-22 15:14
Ok, then I think it is a duplicate -- the bug is related to partial writes with jsonpatch, and if you have file-encryption enabled then jsonpatch is disabled. (though for existing already paid invoices/requests, simply enabling encryption is not sufficient to get them unstuck)
Should be fixed including for already "stuck" invoices in version 4.5.3, hopefully released very soon.
Please comment and reopen after that if still not fixed.

**Closed by SomberNight** 2024-02-22 15:14 UTC

**Comment by paboum** [comment] 2024-02-26 14:33
Yup, fixed in 4.5.3, thanks.
