### ISSUE TITLE
Electrum stop working on my Arch Linux

### ISSUE THREAD

**Issue by Jzarecta** [spesmilo/electrum#1779] opened 2016-05-01 19:18 UTC
I am having an issue on Arch Linux using python 2.7.11 after some update (I pressume) I get the following message:
`Error: cannot import name DependencyWarning. Try 'sudo pip install <module-name>'
`

**Comment by magicvodi** [comment] 2016-05-12 12:45
I just installed Electrum on Arch on my PC and got the same error.
On my Laptop with Arch everything works as expected. Can I help investigating somehow?

**Comment by Jzarecta** [comment] 2016-05-12 18:02
I solved it, it seems the issue was from a module that came from pip instead from the repo. Cant remember which module. Uninstall the module from pip and re-install it from pacman.

**Comment by cstewart90** [comment] 2016-05-25 10:35
The problem module for me was pillow.

**Comment by ecdsa** [comment] 2016-10-21 11:39
closing, the issue is not with electrum.

**Closed by ecdsa** 2016-10-21 11:39 UTC
