### ISSUE TITLE
History display issue - Transactions stuck in pending stage if spent from another wallet

### ISSUE THREAD

**Issue by Thireus** [spesmilo/electrum#1379] opened 2015-07-29 09:18 UTC
If coins are spent from another wallet that is controlling the coins, the behavior of all other electrum wallets that are watching or controlling these coins as well are to display a new pending transaction in the history as soon as the transaction is broadcasted.

However, if these other wallets are not online, and if the transaction already received all confirmations on the network, these wallets when they'll be back online will be stuck on "pending" for the transaction that was already processed and confirmed. The user will have to close these electrum wallets and re-open them again to finally have this new transaction displayed correctly with the correct number of confirmation (and not pending).

I assume this is an issue when a new transaction history element is created that receives the "pending" status by default and then waits for some sort of update for its 1st confirmations, while in fact the transaction has already been confirmed in full.

**Comment by ecdsa** [comment] 2015-07-29 10:01
this seems to be an old bug. 
I thought it had been fixed by @kyuupichan

**Comment by ecdsa** [comment] 2015-07-29 10:01
were you using electrum with a daemon?

**Comment by Thireus** [comment] 2015-07-29 10:12
My Electrum clients are connected to a single Electrum-server. This happens when I proceed a transaction with one of my wallets and when the others are offline. When I bring them back online (i.e. a few hours later, once the transaction is confirmed on the main wallet) it seems they don't catch up correctly with the number of confirmations and stay stuck on "pending", until I close them and re-open them. I think it is is just a display issue, or maybe it's the client that does not properly update the transaction status (maybe it's waiting until the next block processed by electrum-server to update the confirmation status).

**Comment by thokon00** [comment] 2015-07-29 13:44
I can confirm this issue. You have to re-open the wallet or wait until the next block is found.

**Comment by ecdsa** [comment] 2015-08-06 13:23
are you sure it is "pending" and not "unverified" ?

**Comment by kyuupichan** [comment] 2015-08-12 08:07
I just had this having come back from vacation and received a couple of payments whilst away.  They remain unverified.  I think there are at least 2 issues here.

1) No merkle root is requested until the network finds a block.  I've not looked into this yet.
2) Once the merkle roots are requested, they are never verified.  network_proxy.py has a large number of unanswered requested but network.py has none.  I can only think this is because we completely drop the request at line 490 of network.py:

        if not self.is_connected():
            return False

The proxy then thinks it's requested the data, but the network chucked it away.  We should queue the request and send it when connectivity is achieved rather than forgetting about it.

**Comment by ecdsa** [comment] 2015-08-13 06:59
@Thireus is it "pending" or "unverified" ?

**Comment by Thireus** [comment] 2015-08-13 07:14
@ecdsa I don't have the screenshots with me now, but I remember the transaction's icon were two gears and in the date field it was displayed "pending".

**Comment by kyuupichan** [comment] 2015-08-25 04:36
I can reproduce this issue at will now, but the transactions are unverified.  You need both 1) an old wallet file, and 2) an old block_headers file  (where "old" means prior to the transaction).  Just one or the other won't do it.

Now I can reproduce I will try and figure out what's happening and fix it.

**Comment by kyuupichan** [comment] 2015-08-25 05:30
Can someone who suffered from this confirm it is now fixed?  I realize testing may involve a 24-hour or more wait.

**Comment by kyuupichan** [comment] 2015-08-27 14:27
I'm going to close this as I believe it is fixed.  If something similar recurs, please open a new issue and give as many details as possible (unverified vs pending etc.) that you think would help to reproduce.  Thanks.

**Closed by kyuupichan** 2015-08-27 14:27 UTC
