### ISSUE TITLE
pyaes is slow

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#3778] opened 2018-01-27 04:05 UTC
Can we make pycryptodomex a dependency? We already use it if it is available, but do not require it atm.

I've created a 3.6 MB wallet file, encrypted with a pw. (standard wallet with 50k addresses and no txns)

Log (with extra profiling) when opening the wallet:
```
[WalletStorage] wallet path /home/user/.electrum/testnet/wallets/test_large_wallet
[profiler] aes_decrypt_with_iv 46.8952
[profiler] decrypt 47.1146
[profiler] load_transactions 0.0000
[profiler] build_reverse_history 0.0067
[profiler] save_transactions 0.0671
[profiler] check_history 59.0495
[profiler] on_update 0.0963
[profiler] on_update 0.1026
```

Log after running `python3 -m pip install pycryptodomex`:

```
[WalletStorage] wallet path /home/user/.electrum/testnet/wallets/test_large_wallet
[profiler] aes_decrypt_with_iv 0.0046
[profiler] decrypt 0.2278
[profiler] load_transactions 0.0000
[profiler] build_reverse_history 0.0069
[profiler] save_transactions 0.0644
[profiler] check_history 54.1222
[profiler] on_update 0.0976
[profiler] on_update 0.0955
```

It seems decrypting a wallet is ~200 times faster with pycryptodomex than with pyaes; and encryption is similar.
(Ignore `check_history`, that is being dealt with in https://github.com/spesmilo/electrum/pull/3777)

**Comment by bauerj** [comment] 2018-01-27 09:33
Is there any advantage in using pyaes? It seems like both should be available on any system.

**Comment by ecdsa** [comment] 2018-01-27 10:51
pyaes is pure python. I doubt pycryptodomex will be available on any system.

One thing worth investigating is whether we can replace python-ecdsa with pycryptodomex too.

**Comment by bauerj** [comment] 2018-01-27 10:57
> PyCryptodome is not a wrapper to a separate C library like OpenSSL. To the largest possible extent, algorithms are implemented in pure Python. Only the pieces that are extremely critical to performance (e.g. block ciphers) are implemented as C extensions.

So it *should* be possible to use it on any system that can run Python - maybe even our Android builds.

**Comment by ecdsa** [comment] 2018-03-08 10:57
closing, duplicate of #3927

**Closed by ecdsa** 2018-03-08 10:57 UTC
Labels: enhancement
