### ISSUE TITLE
delete wallet file error

### ISSUE THREAD

**Issue by plextoriano** [spesmilo/electrum#4660] opened 2018-08-24 14:48 UTC
Steps:

1.- imported a only one private key
2.- delete private key
3.- delete wallet file
4.- on accept confirmation and after enter password show error **"list index out of range"**

**Comment by plextoriano** [comment] 2018-08-28 17:50
Where is log?
The steps are:
1.- Create new wallet.
![image](https://user-images.githubusercontent.com/2480960/44740191-17a47580-aafa-11e8-81a9-11ed77ed18bd.png)

2.- In the wizard **"import Bitcoin address or private keys"** _(It only happens if the imported address is private)_
![image](https://user-images.githubusercontent.com/2480960/44740226-2f7bf980-aafa-11e8-8fed-88a8b9b41665.png)

3.- On label Addresses, select the only one address imported and select
![image](https://user-images.githubusercontent.com/2480960/44740336-81bd1a80-aafa-11e8-989d-07f44558e317.png)

4.- Last, Select File > Delete wallet
![image](https://user-images.githubusercontent.com/2480960/44740642-466f1b80-aafb-11e8-9713-e31230a2c9bc.png)

after this:

![image](https://user-images.githubusercontent.com/2480960/44740528-f728eb00-aafa-11e8-9449-95b35db829f5.png)

**Comment by SomberNight** [comment] 2018-08-28 18:44
Thanks for the report.
Looks like it is a duplicate of https://github.com/spesmilo/electrum/issues/3254

**Closed by SomberNight** 2018-08-28 18:44 UTC
