### ISSUE TITLE
some language doesn't work on android

### ISSUE THREAD

**Issue by asuka431** [spesmilo/electrum#7711] opened 2022-03-13 08:42 UTC
not only google play version, but all.
arabic chinese japaese and more language doesn't work. changing language from setting will only to lead all words which is defined at locale replacing empty.
what is interesting, i set docker to use ja.JP_UTF-8, it has no error to build. but it also happens at all time.

**Comment by asuka431** [comment] 2022-03-13 08:49
https://stackoverflow.com/questions/55521932/android-locale-changer/58777775#58777775
kind of this?

**Comment by SomberNight** [comment] 2022-03-21 19:12
duplicate of https://github.com/spesmilo/electrum/issues/2032
The issue is with kivy :/

**Closed by SomberNight** 2022-03-21 19:12 UTC
