### ISSUE TITLE
qml network settings: `oneserver` implied from `auto_connect`

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#8250] opened 2023-03-16 20:30 UTC
In the qml gui, in network->server settings, `oneserver` is implicitly set based on `auto_connect`.
https://github.com/spesmilo/electrum/blob/3574c99275662179fece647972ecb8a534bd48e2/electrum/gui/qml/qenetwork.py#L164

I think we should not do this. `oneserver` defaults to off of course, and `auto_connect` should be settable ~independently.

If we want to allow setting `oneserver` (just like in the kivy gui), it can be another checkbox.
In that case, there should be soft-dependance between the two checkboxes:
```
auto_connect => not oneserver
```
i.e. if auto_connect is enabled, we should disable oneserver and not let the user enable it.
(but if `auto_connect` is disabled, any state for `oneserver` is permitted)

-----

In general I think `oneserver` is a niche-setting, and there is little point in enabling it, but I acknowledge that some users keep asking for it. I personally disable `auto_connect` but don't use `oneserver`, (outside testing). Lagging-detection and chain-split detection are more useful than the miniscule privacy loss of connecting to more servers for just headers.

**Comment by accumulator** [comment] 2023-03-16 23:45
From a user's perspective, I think the `auto_connect` option might be confusing. I'm not sure if I understand the exact behavior myself :) I assume `auto_connect` determines if the primary/default server can switch between public servers automatically? If so, this is probably not something a user cares about, except maybe in chain-split situations, where a user might want to pick one of the tips (via server selection) and stick with it.

The `oneserver` option is useful for privacy reasons, users might want to connect to their private electrum server. I think that's a valid use-case.

**Comment by SomberNight** [comment] 2023-03-17 00:05
> I assume `auto_connect` determines if the primary/default server can switch between public servers automatically?

Yes, it determines whether the network is allowed to change the selected primary server. That is, iff the user cares about which server they are connected to, they are expected to disable `auto_connect`.

> The `oneserver` option is useful for privacy reasons, users might want to connect to their private electrum server. I think that's a valid use-case.

What specific privacy concerns are there when not using `oneserver` (but assuming `auto_connect is False`)?
I guess you are leaking that your IP address is using Electrum. Anything else?

**Comment by SomberNight** [comment] 2023-03-17 00:17
> I think the auto_connect option might be confusing. I'm not sure if I understand the exact behavior myself :)

But yes, you are correct that there are some subtle implied behaviour changes. Along the lines of "the user likely trusts this server they selected".

see https://github.com/spesmilo/electrum-docs/blob/213fd697c0c0cdeb396ed13186416e3c020b93f0/faq.rst#does-electrum-trust-servers
For example
> With "auto-connect" disabled, only the fee estimates sent by the main server are used.

Possible attack: main server sends very high estimatefee values, the client clamps it to 1500 sat/vb, but otherwise accepts them, the client now sends update_fee messages for its LN channels to the LN peers, who then force-close the respective channels. That is, if you have `auto_connect=false`, the server can get all your channels force-closed.

**Comment by ecdsa** [comment] 2023-03-17 08:23
`oneserver` should be off by default.  If we decide to enable it, it should be through a checkbox in the network dialog. Enabling it is a security regression, because it means you trust blindly the server you are connected to. It should only be used if the server is your own private server. (maybe we can work that out with the next version of the protocol)

quick-fix in 49683d6ff11cc72d74830e8133ff4f1a75ed390e

**Comment by ecdsa** [comment] 2023-03-17 09:34
closing this; not going to add that checkbox now

**Closed by ecdsa** 2023-03-17 09:34 UTC
Labels: gui-qml
