### ISSUE TITLE
electrum 2.0.2 erases wallet file

### ISSUE THREAD

**Issue by jontis** [spesmilo/electrum#1108] opened 2015-03-25 11:10 UTC
When I use electrum, it sometimes starts up with the error message "can't read wallet file", and sure, the wallet file is then 0 bytes so sure enough, it's an empty file. I'm not sure when this happens.
I've studied the behavior and it seems like each time I start electrum, the wallet file goes from xx bytes, to 0 and back to xx bytes. This also happens when I shut down electrum. I have not been able to tell when the 0 byte file is left. The file where I have observed the behavior is residing on a symlinked luks spin partition if that affects things, but I'm not sure it's exclusive for this file. Pasting in an old copy of the wallet file and starting electrum again makes it work but it is somewhat unsettling. Recreating from Seed also works but the wallet file get's lost later again.

**Comment by maran** [comment] 2015-03-25 11:13
I believe this is a duplicate of #1085. Please upgrade to Electrum 2.0.3 and let us know if that works.

**Comment by ecdsa** [comment] 2015-03-25 13:27
yes, please upgrade to 2.0.3

**Closed by ecdsa** 2015-03-25 13:27 UTC

**Comment by jontis** [comment] 2015-04-05 18:11
I have upgraded. Since then I have not seen the problem.
