### ISSUE TITLE
btchip and send 

### ISSUE THREAD

**Issue by ziomik** [spesmilo/electrum#1302] opened 2015-06-17 21:59 UTC
OSX: When I try to send I get this error: "finalizeinput() takes exactly 5 arguments (6 given)"

**Comment by ecdsa** [comment] 2015-06-23 12:28
@btchip please comment

**Comment by btchip** [comment] 2015-06-23 15:39
Can you check if you're using btchip-python version 0.1.15 ? (https://github.com/LedgerHQ/btchip-python/tree/v0.1.15)

**Comment by ziomik** [comment] 2015-06-23 16:19
Use these versions, thanks
Electrum 2.3.2
btchip-python 0.1.15
cython-hidapi master
Cython 0.22.1
PyUSB 1.0

**Comment by btchip** [comment] 2015-06-23 16:21
Can't figure why that would happen with 0.1.15. Are you sure you reinstalled it over the previous one ?

**Comment by ziomik** [comment] 2015-06-23 16:28
Tried to reinstall, same problem:

MacBook-Pro-di-Ziomik:btchip-python ziomik$ python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to btchip_python.egg-info/requires.txt
writing btchip_python.egg-info/PKG-INFO
writing top-level names to btchip_python.egg-info/top_level.txt
writing dependency_links to btchip_python.egg-info/dependency_links.txt
reading manifest file 'btchip_python.egg-info/SOURCES.txt'
writing manifest file 'btchip_python.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.10-x86_64/egg
running install_lib
running build_py
creating build/bdist.macosx-10.10-x86_64/egg
creating build/bdist.macosx-10.10-x86_64/egg/btchip
copying build/lib/btchip/__init__.py -> build/bdist.macosx-10.10-x86_64/egg/btchip
copying build/lib/btchip/bitcoinTransaction.py -> build/bdist.macosx-10.10-x86_64/egg/btchip
copying build/lib/btchip/bitcoinVarint.py -> build/bdist.macosx-10.10-x86_64/egg/btchip
copying build/lib/btchip/btchip.py -> build/bdist.macosx-10.10-x86_64/egg/btchip
copying build/lib/btchip/btchipComm.py -> build/bdist.macosx-10.10-x86_64/egg/btchip
copying build/lib/btchip/btchipException.py -> build/bdist.macosx-10.10-x86_64/egg/btchip
copying build/lib/btchip/btchipFirmwareWizard.py -> build/bdist.macosx-10.10-x86_64/egg/btchip
copying build/lib/btchip/btchipHelpers.py -> build/bdist.macosx-10.10-x86_64/egg/btchip
copying build/lib/btchip/btchipKeyRecovery.py -> build/bdist.macosx-10.10-x86_64/egg/btchip
copying build/lib/btchip/btchipPersoWizard.py -> build/bdist.macosx-10.10-x86_64/egg/btchip
copying build/lib/btchip/btchipUtils.py -> build/bdist.macosx-10.10-x86_64/egg/btchip
copying build/lib/btchip/ledgerWrapper.py -> build/bdist.macosx-10.10-x86_64/egg/btchip
copying build/lib/btchip/msqr.py -> build/bdist.macosx-10.10-x86_64/egg/btchip
creating build/bdist.macosx-10.10-x86_64/egg/btchip/ui
copying build/lib/btchip/ui/__init__.py -> build/bdist.macosx-10.10-x86_64/egg/btchip/ui
copying build/lib/btchip/ui/personalization00start.py -> build/bdist.macosx-10.10-x86_64/egg/btchip/ui
copying build/lib/btchip/ui/personalization01seed.py -> build/bdist.macosx-10.10-x86_64/egg/btchip/ui
copying build/lib/btchip/ui/personalization02security.py -> build/bdist.macosx-10.10-x86_64/egg/btchip/ui
copying build/lib/btchip/ui/personalization03config.py -> build/bdist.macosx-10.10-x86_64/egg/btchip/ui
copying build/lib/btchip/ui/personalization04finalize.py -> build/bdist.macosx-10.10-x86_64/egg/btchip/ui
copying build/lib/btchip/ui/personalizationseedbackup01.py -> build/bdist.macosx-10.10-x86_64/egg/btchip/ui
copying build/lib/btchip/ui/personalizationseedbackup02.py -> build/bdist.macosx-10.10-x86_64/egg/btchip/ui
copying build/lib/btchip/ui/personalizationseedbackup03.py -> build/bdist.macosx-10.10-x86_64/egg/btchip/ui
copying build/lib/btchip/ui/personalizationseedbackup04.py -> build/bdist.macosx-10.10-x86_64/egg/btchip/ui
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/bitcoinTransaction.py to bitcoinTransaction.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/bitcoinVarint.py to bitcoinVarint.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/btchip.py to btchip.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/btchipComm.py to btchipComm.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/btchipException.py to btchipException.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/btchipFirmwareWizard.py to btchipFirmwareWizard.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/btchipHelpers.py to btchipHelpers.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/btchipKeyRecovery.py to btchipKeyRecovery.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/btchipPersoWizard.py to btchipPersoWizard.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/btchipUtils.py to btchipUtils.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/ledgerWrapper.py to ledgerWrapper.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/msqr.py to msqr.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/ui/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/ui/personalization00start.py to personalization00start.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/ui/personalization01seed.py to personalization01seed.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/ui/personalization02security.py to personalization02security.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/ui/personalization03config.py to personalization03config.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/ui/personalization04finalize.py to personalization04finalize.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/ui/personalizationseedbackup01.py to personalizationseedbackup01.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/ui/personalizationseedbackup02.py to personalizationseedbackup02.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/ui/personalizationseedbackup03.py to personalizationseedbackup03.pyc
byte-compiling build/bdist.macosx-10.10-x86_64/egg/btchip/ui/personalizationseedbackup04.py to personalizationseedbackup04.pyc
creating build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
copying btchip_python.egg-info/PKG-INFO -> build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
copying btchip_python.egg-info/SOURCES.txt -> build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
copying btchip_python.egg-info/dependency_links.txt -> build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
copying btchip_python.egg-info/not-zip-safe -> build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
copying btchip_python.egg-info/requires.txt -> build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
copying btchip_python.egg-info/top_level.txt -> build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
creating 'dist/btchip_python-0.1.15-py2.7.egg' and adding 'build/bdist.macosx-10.10-x86_64/egg' to it
removing 'build/bdist.macosx-10.10-x86_64/egg' (and everything under it)
Processing btchip_python-0.1.15-py2.7.egg
removing '/usr/local/lib/python2.7/site-packages/btchip_python-0.1.15-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/site-packages/btchip_python-0.1.15-py2.7.egg
Extracting btchip_python-0.1.15-py2.7.egg to /usr/local/lib/python2.7/site-packages
btchip-python 0.1.15 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/site-packages/btchip_python-0.1.15-py2.7.egg
Processing dependencies for btchip-python==0.1.15
Searching for hidapi==0.7.99.post6
Best match: hidapi 0.7.99.post6
Adding hidapi 0.7.99.post6 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Finished processing dependencies for btchip-python==0.1.15

**Comment by btchip** [comment] 2015-06-23 16:39
Then sorry I have no idea. I'll wait for someone more experienced with Python package management issues to chime in, but that should work correctly with the latest version of the module.

**Comment by ziomik** [comment] 2015-06-23 16:42
Ok, any help is accepted .. keep open Issues. For now, thanks

**Comment by ecdsa** [comment] 2015-06-29 11:04
I suggest to remove all existing installations of btchip-python before reinstalling

**Comment by ecdsa** [comment] 2015-07-03 07:57
closing, duplicate of #1341

**Closed by ecdsa** 2015-07-03 07:57 UTC
