### ISSUE TITLE
Electrum-2.3.3: manual connection fails on restart

### ISSUE THREAD

**Issue by rapodaca** [spesmilo/electrum#1330] opened 2015-06-30 23:02 UTC
Connect to server using auto-connect (click red button). Open Network configuration again, uncheck auto-connect, and choose a server. Server connects without a problem.

Shut down electrum and restart. Click red button, and choose the same server that worked during previous session.

Electrum does not connect.

I expected Electrum to connect to the server from the last session. Instead, it doesn't connect at all.

This method does work reliably on Electrum-2.2. I haven't tried any versions in-between.

Running Tails 1.4, using Tor.

**Comment by ecdsa** [comment] 2015-07-01 03:43
the server code was upgraded yesterday, because of the 'stress test'
I guess that's why you had trouble connecting.
in any wase, I cannot reproduce your issue

**Comment by rapodaca** [comment] 2015-07-01 04:55
It does not appear to be a server issue, at least not entirely. The two clients (2.2 and 2.3.3) clearly show different behavior, with all other factors held constant.

**Comment by ecdsa** [comment] 2015-07-01 04:58
ok, reopening. can you test on ecdsa.net?

**Comment by rapodaca** [comment] 2015-07-01 05:19
Yes - I get exactly the same behavior on ecdsa.net. 2.2 works as expected and 2.3.3 fails to connect on startup.

Other params include SSL (checked) SOCKS5, localhost:9050. Network params set identically on both version of client.

**Comment by ecdsa** [comment] 2015-07-01 06:25
ok I can reproducee it now; only with proxy

**Comment by ecdsa** [comment] 2015-07-01 06:46
fixed in 0ac3aebb8840967c4bd9598191e96050e3e54218

**Closed by ecdsa** 2015-07-01 06:46 UTC
