### ISSUE TITLE
Seg faulting, error report

### ISSUE THREAD

**Issue by andiejs** [spesmilo/electrum#6789] opened 2020-11-27 19:30 UTC
My Electrum (on linux mint) keeps dumping core. Usually there's no error message, but the last time there was (pasted below). Not sure what action caused this -- I think it was running in the background at this point.

E/i | interface.[blockstream.info:700] | Exception in wrapper_func: RequestCorrupted('fees must be in decreasing order',)
Traceback (most recent call last):
  File "/home/monster/Electrum-4.0.5/electrum/util.py", line 1039, in wrapper
    return await func(*args, **kwargs)
  File "/home/monster/Electrum-4.0.5/electrum/interface.py", line 480, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/home/monster/Electrum-4.0.5/electrum/interface.py", line 504, in run
    await self.open_session(ssl_context)
  File "/home/monster/Electrum-4.0.5/electrum/interface.py", line 647, in open_session
    await group.spawn(self.monitor_connection)
  File "/home/monster/Electrum-4.0.5/packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/home/monster/Electrum-4.0.5/packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/home/monster/Electrum-4.0.5/electrum/network.py", line 456, in _request_fee_estimates
    histogram = await interface.get_fee_histogram()
  File "/home/monster/Electrum-4.0.5/electrum/interface.py", line 1004, in get_fee_histogram
    raise RequestCorrupted(f'fees must be in decreasing order')
electrum.interface.RequestCorrupted: fees must be in decreasing order
Segmentation fault (core dumped)

**Comment by bitromortac** [comment] 2020-11-28 07:51
See https://github.com/romanz/electrs/issues/331, it's an issue with the blockstream server presumably. I don't know if they have patched their https://github.com/Blockstream/electrs.

**Comment by ecdsa** [comment] 2020-11-28 11:27
closing as duplicate of #6772

**Closed by ecdsa** 2020-11-28 11:27 UTC

**Comment by shesek** [comment] 2020-11-29 09:05
This [was fixed](https://github.com/Blockstream/electrs/commit/1e69fa6376037deab19cb6fc6254f280c57bafc7) in blockstream/electrs a few weeks ago, but did not get deployed on the live servers yet. A deployment should happen in the next few days and resolve this.

**Comment by SomberNight** [comment] 2020-12-07 16:22
I find it extremely weird that this would cause a segfault. That must be a separate issue.
