### ISSUE TITLE
Error loading Python DLL

### ISSUE THREAD

**Issue by ElecM8** [spesmilo/electrum#3171] opened 2017-11-02 00:17 UTC
Just updated to the version 3.0 and I got this error after starting Electrum.
Does anyone know how to fix that? Tried reinstalling and restarting, but after quickly looking on google the only result I found is [this github issue](https://github.com/pyinstaller/pyinstaller/issues/2495), which doesn't help me much...
Edit: Windows 7 x64, in case that matters.

![Electrum](https://i.imgur.com/VMPFudB.png)

**Comment by SomberNight** [comment] 2017-11-02 00:24
So I take it you've used the "Windows Installer" exe?
What version of Windows? Trying to reproduce.

**Comment by ElecM8** [comment] 2017-11-02 00:35
> So I take it you've used the "Windows Installer" exe?
Yeah. I did try the standalone version though, same issue.

**Comment by SomberNight** [comment] 2017-11-02 01:06
Ok. I can reproduce on Win7 x64 [Version 6.1.7601], with all three Windows binaries.

**Comment by keystrike** [comment] 2017-11-02 01:34
Reproduced on Windows 8.1 x64 [6.3.9600] with standalone and "Windows installer" exe.

However when using the "Windows installer" exe version the error is "LoadLibrary: Invalid access to memory location."

**Comment by SomberNight** [comment] 2017-11-02 01:37
Correct behaviour / can't reproduce on:
- Windows 10 x64 [Version 10.0.14393]
- Windows 10 x64 [Version 10.0.15063]

**Comment by trotskylenin** [comment] 2017-11-02 02:04
Same issue here on Windows 7 Ultimate x64 SP1 with Standalone Executable and Installer.
![python_dll_error](https://user-images.githubusercontent.com/6507464/32306241-f9457cf2-bf58-11e7-9c22-62469ba3c055.png)

**Comment by RattitudeMining** [comment] 2017-11-02 02:50
I am also getting the same problem when updating.
Tried installing a-new on two other Windows 7 Pro SP1 machines and the same thing happens.
Though I have rolled back to 2.9.3... I don't like not-seeing my coin; creepy.
I have not tried sending anything... I'm too scared to even move.
Error messages are aggravating... but here is mine: https://www.screencast.com/t/ZluA5TrmL

Hopefully a fix will be in soon, likely a problem with Win7/8 OS issue.

**Comment by ebliever** [comment] 2017-11-02 02:59
I'm having the same issue on Win7 64b, also installed over 2.9.3.

**Comment by amarett0** [comment] 2017-11-02 12:18
I have the same problem

**Comment by underhood** [comment] 2017-11-02 12:48
Issue confirmed here as well.... Win 7 64 bit.... same issue for installer and standalone exe.

> Error loading Python DLL
>'C:\Users\Myusername\AppData\Local\Temp\_MEI49562\python35.dll'. LoadLibrary: An attempt to set the process default activation context failed because the process default activation context was already set.

**Comment by Kalumets** [comment] 2017-11-02 17:35
Same here on Win 7 64bit

**Comment by blais1064** [comment] 2017-11-03 00:08
Having the same issue Win 7 64 bit,  I tried what is recommended in hotfix referenced above but getting same Errors

**Comment by SomberNight** [comment] 2017-11-03 06:09
@blais1064 of course you're getting the same errors. That is a pull request... The instructions for end-users there are only relevant with that change merged into the code, for newly built binaries.

Please don't comment here if you have no new info to add.
To be clear, if you are using Windows 7 or 8.1, we now know 3.0.0 does NOT work for you.

Some related links (for devs):
https://github.com/pyinstaller/pyinstaller/issues/1566#issuecomment-328808382
https://pyinstaller.readthedocs.io/en/latest/usage.html#platform-specific-notes

**Comment by Aragonite** [comment] 2017-11-06 01:58
This raises the question about if Electrum should maintain compatibility with OS that are not even supported by their own creators.  

For example, the end of Microsoft Mainstream support for Windows 7 was January 2015.   Although, Microsoft will maintain the Extended support for Windows 7 until 2020 (mostly security updates - no bug fixes).   For MacOS, El Capitan (10.11) reached the no-support status from Apple last month (with only security update until next fall - 2018).   

We have seen issues recently with both of those two operating systems.  I guess it is up to the devs generosity to spend time fixing compatibility issues related to obsolete Operating Systems.

**Comment by Golddouble** [comment] 2017-11-06 08:17
Same issue here on Windows 7 Starter 32 bit with this version of Ethereum:
https://download.electrum.org/3.0/electrum-3.0.0-setup.exe
I made an update from Version 2.9.2

What can I do to, bring it to work? Can I downgrade to Version 2.9.3? Does this work without losing anything? Thank you.

**Comment by Xayaan** [comment] 2017-11-07 09:13
I was able to reproduce the same issue, Error loading python DLL on Windows 8.1 x64

**Comment by pdario** [comment] 2017-11-07 09:21
Fixed for me with v3.0.1!

**Comment by ecdsa** [comment] 2017-11-07 11:09
closing this. I added a note on the website, for machines that need a windows update.

**Closed** 2017-11-07 11:09 UTC

**Comment by RattitudeMining** [comment] 2017-11-07 20:58
Update worked for me also, 3.0.1 on a pair of  Windows 7 SP1 x64

Note: There is an x64 as we as a x86 version, take care to download the correct version of the Windows Update though are unsure if it makes a difference.

**Comment by sangaman** [comment] 2018-01-07 00:58
Old issue, but just thought I'd add that I got the same error with 3.0.4 on Windows Vista and installing KB2999226 did the trick. So if anyone is trying to run Electrum on a really old Windows machine they have hope.

**Comment by Pathogenius** [comment] 2019-01-18 09:43
I start electrum after install onto clean Win7 x64, first error electrum throws is it can't find:

"api-ms-win-crt-runtime-l1-1-0.dll"

I learn this is part of "vcredist_x64.exe", so I try to install that, but the installer for it throws an error about certificates and wont install. Obviously this machine wont be going online to update certificates, so I manually copy the api file into electrum folder, then electrum throws the error regarding python36.dll

I decide to forget about trying to run cold wallet, and just go ahead and download electrum on another online machine. Windows smartscreen blocks the download. Good times...
